### ISSUE TITLE
when I run make, give this error

### ISSUE THREAD

**Issue by fayeshine** [tqdm/tqdm#100]
rm -f .coverage  # coverage erase
nosetests tqdm --with-coverage --cover-package=tqdm --cover-erase --cover-min-percentage=80 --ignore-files="tests_perf\.py" -d -v
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
tests_pandas.test_pandas ... ok
tests_pandas.test_pandas_leave ... ok
Test time interval format ... ok
Test statistics and progress bar formatting ... ok
Test SI unit prefixes ... ok
tests_tqdm.test_all_defaults ... ok                                                                                                              
Test csv iterator ... ok
Test output to arbitrary file-like objects ... ok
Test `leave=True` always prints info about the last iteration ... ok
Test trange ... ok
Test mininterval ... ok
Test maxinterval ... ok
Test miniters ... ok
Test purely dynamic miniters ... ok
Test large mininterval ... ok
Test smoothed dynamic miniters ... ok
Test smoothed dynamic miniters with mininterval ... ok
Test disable ... ok
Test SI unit prefix ... ok
Test ascii/unicode bar ... ok
Test manual creation and updates ... ok
Test manual creation and closure ... ok
Test exponential weighted average smoothing ... ok
Test nested progress bars ... ok
0it [00:00, ?it/s]okatting ... 
Test unpause ... FAIL
Hello: 0it [00:00, ?it/s]ok
Test internal GUI properties ... ok
Test version string ... ok

======================================================================
FAIL: Test unpause
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/HWJ/anaconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/HWJ/pkgs/tqdm/tqdm/tests/tests_tqdm.py", line 734, in test_unpause
    assert abs(r_before - r_after) < 1  # TODO: replace equal when DiscreteTimer
AssertionError: 
>>  assert abs(91.41 - 87.61) < 1  # TODO: replace equal when DiscreteTimer
    

----------------------------------------------------------------------
Ran 29 tests in 2.318s

FAILED (failures=1)
make[1]: *** [testcoverage] Error 1
make: *** [alltests] Error 2

**Comment by lrq3000** [comment]
This is normal, it's because this test is a timing test, and the current unit test does not use a virtualized timer, so depending on your computer resources and performance, the test may fail sometimes.

This will be fixed by #60.

**Comment by casperdcl** [comment]
I'd be worried if you get this error *every* time you run the test...

**Comment by lrq3000** [comment]
It's possible s/he gets this error every time if the temporal resolution of
its OS is not high enough (at least the implementation of time.time). But
anyway this shouldn't happen, and it doesn't with the virtual timer in the
PR above.

2016-01-05 18:16 GMT+01:00 Casper da Costa-Luis <notifications@github.com>:

**Comment by fayeshine** [comment]
@lrq3000 @casperdcl  
Yes, every time I run the test
what do you mean "temporal resolution of its OS"?
OS X 10.11 el captain, python 2.7.11

**Comment by lrq3000** [comment]
Ok thank you for the feedback. I don't know much about Mac OSX and its temporal resolution, but I guess that it's different enough from Windows and Linux (the OSes we run our tests against) so that you have these fails everytime.

By temporal resolution, I mean that each OS has a different way to manage time, sometimes with a finer grain and sometimes coarser (eg, some OSes can only report a difference of 0.01s reliably, while others can report up to 0.00001s, and so on). And thus, tests using timing comparison may give different results.

This is currently being fixed in a PR which replaces real time by a virtual timer that we fully control.

**Comment by nabijaczleweli** [comment]
You could test OSX on Travis, you know

**Comment by lrq3000** [comment]
@nabijaczleweli No I didn't know, thank's for notifying! We'll definitely be looking into this solution. In the past, I tried to support AppVeyor to unit test on Windows automatically, but it was really too much of a burden to setup and maintain correctly :/

**Comment by nabijaczleweli** [comment]
Yeah, headless Windows is (almost) literally Hitler

**Comment by casperdcl** [comment]
will reopen if anyone reports #60 did not manage to fix this
