### ISSUE TITLE
[QUESTION] Npm-friendly?

### ISSUE THREAD

**Issue by ThisIsACoolBoy** [tqdm/tqdm#1009]
Is this npm friendly? Etc: *downloads node.js*
console: npm init
console: npm install tqdm

**Comment by casperdcl** [comment]
This a a Python library; installable via pip or conda. For use as a CLI app it's also installable via snap or docker. https://github.com/tqdm/tqdm/#installation

**Comment by casperdcl** [comment]
Ports to other languages are listed at https://tqdm.github.io/ports/ but I can't speak about their features.

**Comment by ThisIsACoolBoy** [comment]
Thanks for the response.
