### ISSUE TITLE
low efficiency

### ISSUE THREAD

**Issue by fayeshine** [tqdm/tqdm#101]
When I run the example,
for i in trange(1000):
    sleep(0.01)

it seems only 88 iters per second, a decreasing of 12% performance is noticed

**Comment by lrq3000** [comment]
This should not happen normally, on my comp it's ~99it/s. What is your OS system and terminal?

**Comment by casperdcl** [comment]
Even the 99.5 it less than expected because `sleep` isn't very accurate. But 88 is excessive.

**Comment by fayeshine** [comment]
@lrq3000 @casperdcl 
macbook air os x 10.11 el captain,
terminal is mac os default terminal
python 2.7.11 (from anaconda 2.4.1)

**Comment by lrq3000** [comment]
Unfortunately, I think none of our devs use Mac OSX, so it will be hard to debug this issue until we have someone owning this OS.

**Comment by abzcoding** [comment]
@lrq3000 
it is happening in my laptop too
macbook pro osx 10.11 el captain,
python 3.5.0b4
tqdm Version: 3.6.0
<img width="782" alt="screen shot 2016-01-09 at 11 17 50 pm" src="https://cloud.githubusercontent.com/assets/10992695/12218024/899732fa-b727-11e5-9931-957f6e81fb53.png">

**Comment by abzcoding** [comment]
@lrq3000  i think the problem is not in tqdm
please take a look at the following picture
<img width="743" alt="screen shot 2016-01-09 at 11 26 14 pm" src="https://cloud.githubusercontent.com/assets/10992695/12218052/7c309178-b728-11e5-90dc-988ecc46fd69.png">

**Comment by abzcoding** [comment]
the problem is definitely not yours 
<img width="695" alt="screen shot 2016-01-09 at 11 39 57 pm" src="https://cloud.githubusercontent.com/assets/10992695/12218097/61cd1e6c-b72a-11e5-87b2-a92b7ca80279.png">
![pycallgraph](https://cloud.githubusercontent.com/assets/10992695/12218101/6cad6c42-b72a-11e5-863d-a1ce15bd43ac.png)
(10/11.560 = 0.8650519031) === 86.5%

**Comment by casperdcl** [comment]
Yes, sorry, this is what I meant... The `sleep` function is not reliable. This isn't something we can fix. In fact, `tqdm` has just correctly drawn to your attention how broken `sleep` is on your particular setup!

**Comment by lrq3000** [comment]
@abzcoding Thank you for your tests and for resolving this mysterious case :) We could maybe implement a test in `tests_perf.py` to safeguard against this kind of issue.
