### ISSUE TITLE
cli: add `--tee` and `bar_format={line}`

### ISSUE THREAD

**Issue by Piping** [tqdm/tqdm#1013]
Hi,

When I use `tqdm` cli version, I found it is pretty hard to print user input so that I can have effects similar to apt progress bar.

Usage:
```bash
echo -e 'A\nB\nC' | tqdm --bar_format="{input}\n{l_bar}{bar}{r_bar}"
```
should show
```
A
B
C
[Progress:  ===========> 100%]
```

**Comment by casperdcl** [comment]
srry don't understand what you mean

**Comment by Piping** [comment]
@casperdcl update the description. But the main idea is to have the cli version do `tqdm.write()`.

**Comment by casperdcl** [comment]
ah you mean replacing `some_cmd | tqdm > some_cmd.log` with `some_cmd | tqdm | tee some_cmd.log`...

I don't think `bash` by default separates stdin and stdout. The only way I see is to have `tqdm` itself have a `tee` mode: `some_cmd | tqdm --tee > some_cmd.log` which would actually output to both stdout (`stdout.write`) and stderr (`tqdm.write`).

**Comment by Piping** [comment]
@casperdcl  that option can work.
Current output of tqdm is the following:
```
3it [00:00, 42509.84it/s]
A
B
C
```
I want the progress bar can be updated at the bottom right after cmd output.
Currently I have to resolve to python version to do `tqdm.write`. `--bar_format` can take an extra variable{input}  as well.

**Comment by casperdcl** [comment]
just added `--tee` - you can try `pip install -U 'git+https://github.com/tqdm/tqdm@cli-tee#egg=tqdm'`

**Comment by Piping** [comment]
@casperdcl works for me. Thanks for your promptly help!

**Comment by casperdcl** [comment]
sure - will be in the next release
