### ISSUE TITLE
Progress bar always rendered in Google Colab/Jupyter Notebook

### ISSUE THREAD

**Issue by EugenHotaj** [tqdm/tqdm#1015]
On the terminal, it is possible to disable the progress bar by not specifying `"{bar}"` in `bar_format`. For example `bar_format="{l_bar}{r_bar}"` will render the left and right sides of the bar, but not the actual progress bar itself.

On Google Colab/Jupyter Notebook, the bar will always render on the left side, even when disabled. My guess is that this happens because an `IProgress` is [always created in `status_printer` ](https://github.com/tqdm/tqdm/blob/master/tqdm/notebook.py#L100-L114). A simple fix might be to create a component for the description instead of implicitly using `IProgress` and set the `IProgress` component to invisible if no `"{bar}:` is given, e.g.:

```python
# in status_printer
desc = HTML()
pbar = IProgres(...)
ptext = HTM()
container = HBOX(children=[desc, pbar, ptext])
...

# in display
desc, pbar, ptext = self.container.children
...
if we_dont_want_the_bar:
  pbar.closer()  # or pbar.visible = False
...
```

- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [x] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```
  Google colab
  4.41.1 3.6.9 (default, Apr 18 2020, 01:56:04)
  [GCC 8.4.0] linux
  ```

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=
  [StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

**Comment by casperdcl** [comment]
The pbar is still displayed for "status" purposes

https://github.com/tqdm/tqdm/blob/faaa81ddd856625dbacf0040bff73bc0aa48c6a6/tqdm/notebook.py#L102-L105

which means it'll still turn red upon keyboard interrupt etc.

Maybe should make it shorter though when used in this mode.
