### ISSUE TITLE
Minimal-printing progress bar?

### ISSUE THREAD

**Issue by indigoviolet** [tqdm/tqdm#1020]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [x] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
4.48.2 3.8.1 (default, Apr 21 2020, 04:55:19) 
[GCC 7.5.0] linux
 ```
  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=
  [StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

```
This is perhaps an unusual scenario, but I use Jupyter notebooks via an Emacs library (ein). Cell outputs in that context behave mostly as expected, but there is a feature where the output buffer switches to a "See more"-style collapsed mode after it exceeds a certain (configurable) size. 

There is an unfortunate interaction between how progress bars work (clearing themselves and printing again to update) and how the output size of these buffers is counted: the output size counts all the previous "versions" of the progress bar, ie. it monotonically increases even though visually, the old version is replaced by the new one.  This means that the output buffers are more likely to switch to the collapsed "See more" mode if they contain a progress bar. 

One fix might be to use the progress bar in the most minimal mode possible: for example, I don't actually care about the visual progress _bar_: an in-place spinner + the "2/10" or "50%" text would be sufficient. But I haven't been able to figure out how to put `tqdm` into that sort of minimal form.

Thanks for your work on this library, and any pointers you can share!

**Comment by casperdcl** [comment]
Sounds like you mean

`tqdm(..., bar_format="{percentage:3.0f} {n_fmt}/{total_fmt}{unit}")`

or similar.

See 
https://github.com/tqdm/tqdm#custom-integration if you want to change the defaults.

**Comment by indigoviolet** [comment]
Thanks, that's helpful. I also found the `mininterval` and `maxinterval` settings helpful to tweak how often tqdm printed.
