### ISSUE TITLE
Query about pull requests

### ISSUE THREAD

**Issue by MinusRF** [tqdm/tqdm#1024]
Greetings, We ( group of 11 members ) have a software development lab in which we require to work as a team and contribute to a live open source project. We need to report instructor with our progress every week, so if our codes clear your tests will you accept our pull requests ?

**Comment by casperdcl** [comment]
Not sure I follow. If you're asking if this is a maintained repo, yes. Yes it is.

Echoing https://github.com/twbs/bootstrap/discussions/31528#discussioncomment-55338 - the purpose of PRs is to add/fix features rather than passing tests.

Both PRs and Issues are always welcome.
