### ISSUE TITLE
Visual output bug after retry.

### ISSUE THREAD

**Issue by mikhail-akimov** [tqdm/tqdm#1026]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable: 

4.42.0 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:43:08) [MSC v.1926 32 bit (Intel)] win32

When an exception occurs while iterating over the tqdmobject and the attempt is retried (for example, by the retry module), the progress bar display starts to disperse.

for example:

```
from retry import retry
import tqdm

@retry()
def test():
    iterator = tqdm.tqdm(range(100000000))
    for f in iterator:
        if f > 100000000 / 4:
            raise ValueError()


test()
```

Each time the function is restarted, the position value (tqdm.pos) is incremented by 1. And as a result, the conclusion completely breaks down.

I found a solution - when initializing an object, specify **position=0**. But it seems to me that many may encounter a similar error.

**Comment by casperdcl** [comment]
Fixed by [tqdm>=4.45.0](https://tqdm.github.io/releases/#v4450-2020-04-02)
