### ISSUE TITLE
run make fail on linux

### ISSUE THREAD

**Issue by fayeshine** [tqdm/tqdm#103]
make
make[1]: Entering directory '/home/wenjian/pkgs/tqdm'
rm -f .coverage  # coverage erase
nosetests tqdm --with-coverage --cover-package=tqdm --cover-erase --cover-min-percentage=80 --ignore-files="tests_perf\.py" -d -v
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
tests_pandas.test_pandas ... ok
tests_pandas.test_pandas_leave ... ok
Test time interval format ... ok
Test statistics and progress bar formatting ... ok
Test SI unit prefixes ... ok
tests_tqdm.test_all_defaults ... ok                                             
Test csv iterator ... ok
Test output to arbitrary file-like objects ... ok
Test `leave=True` always prints info about the last iteration ... ok
Test trange ... ok
Test mininterval ... ok
Test maxinterval ... ok
Test miniters ... ok
Test purely dynamic miniters ... ok
Test large mininterval ... ok
Test smoothed dynamic miniters ... ok
Test smoothed dynamic miniters with mininterval ... ok
Test disable ... ok
Test SI unit prefix ... ok
Test ascii/unicode bar ... ok
Test manual creation and updates ... ok
Test manual creation and closure ... ok
Test exponential weighted average smoothing ... ok
Test nested progress bars ... ok
0it [00:00, ?it/s]okatting ... 
Test unpause ... ok
Hello: 0it [00:00, ?it/s]ok
Test internal GUI properties ... ok
Test version string ... ok

----------------------------------------------------------------------
Ran 29 tests in 1.000s

OK
make[1]: Leaving directory '/home/wenjian/pkgs/tqdm'
make[1]: Entering directory '/home/wenjian/pkgs/tqdm'
nosetests tqdm/tests/tests_perf.py -d -v
Test overhead of iteration based tqdm ... FAIL
Test overhead of manual tqdm ... FAIL

======================================================================
FAIL: Test overhead of iteration based tqdm
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/wenjian/pkgs/tqdm/tqdm/tests/tests_perf.py", line 58, in test_iter_overhead
    (total, time_tqdm, total, time_bench))
AssertionError: trange(1e+06): 0.539649, range(1e+06): 0.023868

======================================================================
FAIL: Test overhead of manual tqdm
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/wenjian/pkgs/tqdm/tqdm/tests/tests_perf.py", line 85, in test_manual_overhead
    (total, time_tqdm, total, time_bench))
AssertionError: tqdm(1e+06): 0.670235, range(1e+06): 0.023699

----------------------------------------------------------------------
Ran 2 tests in 1.267s

FAILED (failures=2)
Makefile:64: recipe for target 'testperf' failed
make[1]: *** [testperf] Error 1
make[1]: Leaving directory '/home/wenjian/pkgs/tqdm'
Makefile:34: recipe for target 'alltests' failed
make: *** [alltests] Error 2

**Comment by lrq3000** [comment]
Similarly to #100, should be fixed by #60.

**Comment by casperdcl** [comment]
Will reopen if anyone reports #60 not managing to fix this
