### ISSUE TITLE
Having tqdm do nothing with a flag

### ISSUE THREAD

**Issue by jerabaul29** [tqdm/tqdm#1030]
This is an improvement request, if not the behavior is already implemented (I checked the readme and could not find help on this topic, but if I missed something, apologies, and can you show me where I could find doc / example of the feature?).

I quite often end up writing code like this:

```python
use_tqdm = True # here True, but may change to False next time

if use_tqdm:
    wrapper = tqdm.tqdm
else:
    def nop(it, *a, **k):
        return it
    wrapper = nop

for i in wrapper(range(10)):
    do_something(i)
```

Is there a way to / can a feature be done so that one can instead do the following, in which case tqdm does nothing (and it would do something without the last arg:

```python
for i in tqdm.tqdm(range(10), do_nothing=True):
    do_something(i)
```

**Comment by casperdcl** [comment]
`disable=True`

https://github.com/tqdm/tqdm#documentation
