### ISSUE TITLE
[JupyterLab] tqdm.auto visual output bug 4.49.0

### ISSUE THREAD

**Issue by vfdev-5** [tqdm/tqdm#1031]
Visual output bug since the new 4.49.0 release with jupyter lab:

```python
from tqdm.auto import tqdm
import tqdm as t
print(t.__version__)
import time

pbar = tqdm(
    total=None, 
    leave=False, 
    bar_format="{desc}[{n_fmt}/{total_fmt}] {percentage:3.0f}%|{bar}{postfix} [{elapsed}<{remaining}]", 
    initial=1,
    desc="Iterations"
)

for _ in range(10):
    time.sleep(0.5)
    pbar.update(1)    
    
pbar.close()
```
gives

<img width="745" alt="Screen Shot 2020-09-13 at 21 06 20" src="https://user-images.githubusercontent.com/2459423/93026409-17567480-f606-11ea-8536-1532b0be3521.png">

When I remove `bar_format` visual output looks better.

- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [ ] I have visited the [source website], and in particular
  read the [known issues]
- [ ] I have searched through the [issue tracker] for duplicates
- [ ] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```
> 4.49.0 3.7.7 (default, Mar 23 2020, 22:36:06) 
> [GCC 7.3.0] linux

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=
[StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

**Comment by casperdcl** [comment]
Can you confirm this is also the case with `tqdm==4.48.2`?

I think `tqdm==4.48.0` has the desired behaviour.

In all versions this should work though:

```diff
 import time

 pbar = tqdm(
-     total=None,
+     total=10,
     leave=False,
     bar_format="{desc}[{n_fmt}/{total_fmt}] {percentage:3.0f}%|{bar}{postfix} [{elapsed}<{remaining}]",
```

**Comment by casperdcl** [comment]
@vfdev-5 lemme know if #1032 fixes your issue.

**Comment by vfdev-5** [comment]
@casperdcl thanks for working on the issue ! Yes, you are right the behaviour I'd like is the one with `tqdm<=4.48.0`.

I agree that if total is set, visual output is OK.

#1032 makes the visual output same as if I use 4.49.0 and remove `bar_format`. Ultimately, desired visual output is like the one with `tqdm<=4.48.0`.
