### ISSUE TITLE
causing job died when stderr closed in the middle

### ISSUE THREAD

**Issue by holymonson** [tqdm/tqdm#1033]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
> 4.48.2 3.8.5 | packaged by conda-forge | (default, Aug 29 2020, 01:18:42)
[Clang 10.0.1 ] darwin

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=
[StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

---

Steps to reproduce:
1. Run a long job in background and disowned, `python somejob.py &!`. tqdm works fine producing progress bar
2. Exit that shell, the job will die too.
3. However, if running the job with stderr redirtected, `python somejob.py 2>/dev/null &!`, it will keep running even the shell exited.

I guess when the shell exits, `stderr` will change/close, tqdm failed to write to that file descriptor as before and raise exception. 

What I expected is, tqdm should keep silent if no file to write and never disturb the main job.

**Comment by casperdcl** [comment]
Hmm one solution to this would be to pass in a custom file to tqdm. Something like (`tqdm(..., file=IgnoreWriteErrors(sys.stderr))`)

**Comment by holymonson** [comment]
`logging` won't raise `IOError` in the same situation, IMHO, `tqdm` should behave the same too, unless user explicitly ask (via a parameter maybe).

**Comment by casperdcl** [comment]
I don't understand at all what you mean.

```python
import logging, time
logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)
while True:
    log.info("hello")
    time.sleep(1)
```

This program:

1. `python somejob.py &!` works fine producing `hello` messages
2. Exit that shell, the job will die too.
3. However, if running the job with `stderr` redirected, `python somejob.py 2>/dev/null &!`, it will keep running even the shell exited.

Clearly expected behaviour and nothing to do with `tqdm`.

**Comment by holymonson** [comment]
> 2. Exit that shell; the job will die too.

Not exactly, using your test code above, the job __won't die__ when the shell exits. You can check `ps` to find it still running in background  (though you can't see its output), or add `print('hello', file=open('test.output', 'a'))` to see its continuous output.

But the code below __will cause the job dead__ when the shell exits.
```python
import tqdm, time
for i in tqdm.tqdm(range(100)):
    print('hello', file=open('test.output', 'a'))
    time.sleep(1)
```

**Comment by casperdcl** [comment]
> > 1. Exit that shell; the job will die too.
> 
> Not exactly, using your test code above, the job **won't die** when the shell exits. You can check `ps` to find it still running in background (though you can't see its output)

Can't reproduce this (running on Ubuntu). Maybe your system (mac) is different?

**Comment by holymonson** [comment]
I can reproduce it on ubuntu 16.04 and macos, zsh and bash, python3. Can you try below again?
1. Open a new shell, run `python test.py &!`.
```python
# test.py
import logging, time
for i in range(100):
    logging.warn(f"hello {i}")
    print(f"hello {i}", file=open("test.output", "a"))
    time.sleep(1)
```
2. Open another shell, run `tail -f test.output`, it should continuously output.
3. Exit the first shell, the output in the second shell should continue.

**Comment by casperdcl** [comment]
>     3. Exit the first shell, the output in the second shell should continue.

Nope; doesn't continue for me.

**Comment by holymonson** [comment]
Strange, I have tried on 3 systems and they all show the disowned job run in background. 

It seems `bash` don't support tailing`&!` to run a disowned job like `zsh`, it's in background but not disowned.  Would you please add Step 1.5, run builtin command `disown` before exiting the shell?

**Comment by casperdcl** [comment]
right got it

**Comment by casperdcl** [comment]
could you try #1033 (`pip install -U 'git+https://github.com/tqdm/tqdm@closed-write-errors#egg=tqdm'`) and see if this fixes your issue?

**Comment by holymonson** [comment]
Confirm that branch `closed-write-errors` fixed this issue.
