### ISSUE TITLE
TqdmDeprecationWarning vs "no attribute 'notebook'"

### ISSUE THREAD

**Issue by dnhkng** [tqdm/tqdm#1034]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [X ] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [ ] I have visited the [source website], and in particular
  read the [known issues]
- [x ] I have searched through the [issue tracker] for duplicates
- [x ] I have mentioned version numbers, operating system and environment

In Juptyer notebook, I can import and use TQDM. 

However, on the first use, i can either use: 
- `tqdm.tqdm_notebook(***)`
- in which case I get the warning: "Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`"

Or I can directly use:
 - `tqdm.notebook.tqdm(***)`
- in which case I get the error: "AttributeError: module 'tqdm' has no attribute 'notebook'"

Only after running the command "`tqdm.tqdm_notebook(***)`" does the 'tqdm.notebook' attribute appear!

[Example screen capture](https://postimg.cc/N9yxqmgy)

**Comment by casperdcl** [comment]
Sounds like you need to update to the latest version (e.g. `pip install -U tqdm`) & restart your jupyter kernel.

**Comment by casperdcl** [comment]
Sounds like you need to update to the latest version (e.g. `pip install -U tqdm`) & restart your jupyter kernel.

**Comment by casperdcl** [comment]
Ah no wait saw your screenshot.

You need to `import tqdm.notebook`.

Really it's best to just do `from tqdm.auto import tqdm`
