### ISSUE TITLE
bar_format option does not exist?

### ISSUE THREAD

**Issue by yutkin** [tqdm/tqdm#104]
In docs there is option `bar_format` but module from PyPy has not it:
```
pbar = tqdm(total=post_count, bar_format='{l_bar}{bar}| {n_fmt}/{total_fmt}'
TypeError: __init__() got an unexpected keyword argument 'bar_format'
```

**Comment by lrq3000** [comment]
The documentation on Github reflects the features of the git archive. The `bar_format` option was not yet pushed to the pypy repository, but you can grab the git archive by clicking on this link:

https://github.com/tqdm/tqdm/archive/master.zip

**Comment by yutkin** [comment]
@lrq3000 Yes, thank you. Would you tell me when it will pushed to the PyPy repository?

**Comment by lrq3000** [comment]
We have a few other Pull Requests hanging out there, so after they are
reviewed and merged in a few days, we will probably push to pypy.

2016-01-08 20:46 GMT+01:00 Dmitry Yutkin <notifications@github.com>:
