### ISSUE TITLE
[Feature Request] Estimated Completion Time/Date for Long-Running Processes

### ISSUE THREAD

**Issue by MrLukeKR** [tqdm/tqdm#1051]
As someone who runs a lot of long-running machine learning training tasks, I think it would be helpful, as well as having an X hours/minutes/seconds remaining display, having the estimated time that the task will complete from this point, e.g. 12:00:00PM 21/02/21

- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [x] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [ ] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=
[StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

**Comment by dbdean** [comment]
This would be awesome. I've been missing this for a long time.

**Comment by MrLukeKR** [comment]
I wouldn't mind developing it myself if I have a look into the codename and can get assigned to the issue :)
