### ISSUE TITLE
Time measurement not working with luigi's dynamic dependencies

### ISSUE THREAD

**Issue by LinqLover** [tqdm/tqdm#1067]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [x] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```
  4.50.2 3.6.9 (default, Oct  8 2020, 12:12:24) 
  [GCC 8.4.0] linux
  ```

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=
[StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

---

I just realized that tqdm does not measure the time correctly during running a dynamic dependency in the [luigi](https://github.com/spotify/luigi) framework. I have no idea on which end the error occurs, but it would be great if you could take a look at it, maybe there's something wrong with the way tqdm measures time?

See spotify/luigi#3015 for the full bug report.

**Comment by casperdcl** [comment]
looks like a bug, replied https://github.com/spotify/luigi/issues/3015#issuecomment-721992638

happy to re-open if there's an issue.
