### ISSUE TITLE
Proposal: option for making tqdm quiet until some time has passed

### ISSUE THREAD

**Issue by Witiko** [tqdm/tqdm#1069]
Long-running operations waste time. Therefore, it's a common pattern to cache their results, so that they finish instantly the next time we run them. In the first case, tqdm is useful, since it tells us how many episodes of a Netflix series we will be able to binge-watch before the operation has run its course. In the second case, tqdm only clutters the terminal. Therefore, it would be useful to have a parameter that makes tqdm wait a bit before it displays the progress bar. This way, the progress bar would only be shown for long-running operations. The `leave=False` parameter is a step in the right direction, but it goes too far and erases useful information about the total time of long operations.

**Comment by casperdcl** [comment]
solution proposed in #836 but would be great if you could give feedback there about interface (use `disable` or a new kwarg such as `delay`/`waituntil`): https://github.com/tqdm/tqdm/pull/836#discussion_r398094407
