### ISSUE TITLE
Round number in format rate_noinv

### ISSUE THREAD

**Issue by datnguyen20007** [tqdm/tqdm#1078]
When I try to use tqdm.notebook.tqdm
pbar = tqdm(total=num_train, bar_format='{n_fmt}/{total_fmt} files, {rate_noinv} items/sec')

It shows the display problems:
1. The progress bar still displays on the left side
2. {rate_noinv} variable need to round to 02 decimals.
Example: 88.53514394600354 items/sec

Thank you developers for your good tool.

**Comment by casperdcl** [comment]
`{rate_noinv:.2f}`

**Comment by datnguyen20007** [comment]
Thank you so much.

**Comment by casperdcl** [comment]
> 1. The progress bar still displays on the left side

It's not really a progress bar in this mode - it's more like a status indicator (blue/green/red for running/complete/error)

**Comment by datnguyen20007** [comment]
Sir, thank you very much.
How can we turn off this status indicator, keep text progress only ?
