### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by casperdcl** [tqdm/tqdm#108]
Add a changelog or similar (from #77)

**Comment by lrq3000** [comment]
Interestingly, I found [this](https://allmychanges.com/p/python/tqdm/), which means that Github's Releases notes are parseable (via webscraping or Github's API). So the changelog effort should go towards making it available/accessible from PyPi.

**Comment by casperdcl** [comment]
@lrq3000 good find. I was going to write my own scraper for the github release page. Probably best if we just add the link as @jcea suggested (but to the website you found instead of github).

**Comment by casperdcl** [comment]
Fixed by #118
