### ISSUE TITLE
Updating tqdm's description/postfix while respecting mininterval

### ISSUE THREAD

**Issue by willisk** [tqdm/tqdm#1086]
categories:
    + [x] visual output bug

I'm trying to use set_postfix to give updated information during an update of the bar progress and without forcing a refresh to respect the refresh rate set in mininterval.

```python
import tqdm
import sys

print(tqdm.__version__, sys.version, sys.platform, flush=True)

from tqdm import tqdm
from time import sleep


with tqdm(range(10)) as pbar:
    for _ in pbar:
        for i in range(100):
            sleep(0.03)
            pbar.set_postfix(batch=i, refresh=False)
            pbar.update(0)
```

This works as expected before the first real update of the progress bar.

```
4.52.0 3.8.6 (default, Oct 27 2020, 08:58:03) 
[Clang 10.0.0 (clang-1000.11.45.5)] darwin
  0%|          | 0/10 [00:13<?, ?it/s, batch=42]
```

After an update of the progress bar, batch sits at 99 and doesn't change.

```
 40%|████      | 4/10 [00:13<00:19,  3.26s/it, batch=99]
```

**Comment by casperdcl** [comment]
the `postfix` and `description` are by design not intended to be updated multiple times in one iteration, so the internal optimisation (which kicks in after the first iteration) kicks in an only updates `postfix` only at the end of each iteration (so it's always 99).

Sounds like you may want:

```
from tqdm import trange
for _ in trange(10):
    for i in trange(100, desc="batch", leave=False):
        sleep(0.03)
```

**Comment by willisk** [comment]
Thanks for clarifying. I guess two progress bars are the way to go then.
Sadly, there seems to be a bug in Jupyter VSCode where two progress bars will create new lines.
Guess I'll have to give up on this.

**Comment by casperdcl** [comment]
You could also do

```python
epochs = 100
batches = 10

for b in trange(
    epochs * batches, unit_scale=0.1, unit="epoch",
    bar_format="{l_bar}{bar}|{n:.1f}/{total_fmt} [{elapsed}<{remaining}, {rate_fmt}{postfix}]"):
    i = b % batches  # batch num
    # epoch = b // batches
    sleep(0.03)
```

**Comment by willisk** [comment]
Thanks, I will use this approach. Closing this issue then..
