### ISSUE TITLE
add flag to suppress ` from pandas import Panel` warning.

### ISSUE THREAD

**Issue by SebastianoX** [tqdm/tqdm#1094]
Please add flag to suppress the pandas Panel warning:
```
/home/.../lib/python3.7/site-packages/tqdm/std.py:699: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel
```

This repeats itself all over the place, when tqdm is called from within a framework that iterates over a page that imports tqdm under the hood!

Also making tqdm pandas or third party libraries agnostic would be good. This would relieve some heavy duty from developers.

**Comment by SebastianoX** [comment]
(this issue is related to https://github.com/tqdm/tqdm/issues/824 but it is not looking into the same solution)

**Comment by sandrotosi** [comment]
this also makes the tests fail after the introduction of `-W=error` flag to pytest

**Comment by casperdcl** [comment]
`-W=error` isn't causing any failures for me. In any case `pandas>1.2.0` doesn't cause this error anyway (https://github.com/pandas-dev/pandas/pull/37983). Now that it's fixed, I'm ok with adding an extra suppression just for those still using older versions.

**Comment by sandrotosi** [comment]
in debian we still have 1.1.5, that's why -w=error cases the failures

**Comment by casperdcl** [comment]
Warning will disappear using either `tqdm>=4.57.0` (#1127) or `pandas>=1.2.0`.

**Comment by sandrotosi** [comment]
cool, i'll upgrade to 4.57.0 then!
