### ISSUE TITLE
multiple lines when printing into a file from console

### ISSUE THREAD

**Issue by jajupmochi** [tqdm/tqdm#1100]
- [x] I have marked all applicable categories:
    + [x] visual output bug
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

tqdm.__version__ = 4.45.0 
sys.version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
sys.platform = linux
python version = 3.6.9

I have a file `tqdm_writing.py` with the following code:
```
from tqdm import tqdm
from time import sleep
import os
import sys

save_dir = 'outputs/'
os.makedirs(save_dir, exist_ok=True)

for x in tqdm(range(0, 10), file=sys.stdout, position=0, leave=True):
    sleep(0.25)
```

When I run in Ubuntu console with:
```
python3 tqdm_writing.py >> tqdm.txt
```

The contents in the file `tqdm.txt` are multiple lines:
```
  0%|          | 0/10 [00:00<?, ?it/s]
 10%|█         | 1/10 [00:00<00:02,  3.99it/s]
 20%|██        | 2/10 [00:00<00:02,  3.99it/s]
 30%|███       | 3/10 [00:00<00:01,  3.99it/s]
 40%|████      | 4/10 [00:01<00:01,  3.99it/s]
 50%|█████     | 5/10 [00:01<00:01,  3.99it/s]
 60%|██████    | 6/10 [00:01<00:01,  3.99it/s]
 70%|███████   | 7/10 [00:01<00:00,  3.98it/s]
 80%|████████  | 8/10 [00:02<00:00,  3.99it/s]
 90%|█████████ | 9/10 [00:02<00:00,  3.99it/s]
100%|██████████| 10/10 [00:02<00:00,  3.99it/s]
100%|██████████| 10/10 [00:02<00:00,  3.98it/s]
```

However, I expect one line:
```
100%|██████████| 10/10 [00:02<00:00,  3.98it/s]
```

What did I do wrong? Thanks.

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=
[StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

**Comment by almson** [comment]
That is how the console works. Applications print a stream of bytes. They can't go back and delete them, they can only print backspace characters or other terminal commands. Your terminal renders the backspace characters/commands and it looks like a single line is being updated. Your text editor does not render them and shows the entire stream.

The solutions are: 
  - ask your text editor to render differently
  - don't use tqdm
  - set miniter and/or mininterval so high that tqdm only prints once at the end

**Comment by casperdcl** [comment]
`cat tqdm.txt` to display

**Comment by jajupmochi** [comment]
Thanks. I am now using `miniters` and `mininterval`:
```
from tqdm import tqdm
import math

def get_iters(iterable, desc=None, file=None, length=None, verbose=True, **kwargs):
	if verbose:
		if 'miniters' not in kwargs:
			if length is None:
				try:
					kwargs['miniters'] = math.ceil(len(iterable) / 100)
				except TypeError:
					raise
					kwargs['miniters'] = 100
			else:
				kwargs['miniters'] = math.ceil(length / 100)
		if 'maxinterval' not in kwargs:
			kwargs['maxinterval'] = 600
		return tqdm(iterable, desc=desc, file=file, **kwargs)
	else:
		return iterable
```

 I will try `cat tqdm.txt`.
