### ISSUE TITLE
EMA implementation not correct for initial iterations

### ISSUE THREAD

**Issue by almson** [tqdm/tqdm#1101]
The current exponential moving average implementation is "naive" and is not correct for the initial iterations. The first value has a disproportionate influence, which makes the result diverge from the true average. The correct implementation initializes with 0 and divides the result by `1 - factor**step`. I'll skip the proof.

Here is a class that I use:

```
class EMA:
    beta: float
    ema: float
    step: int

    def __init__ (self, beta: float):
        self.beta = beta
        self.ema = 0
        self.step = 0

    def append(self, value: float):
        self.ema = self.beta * self.ema + (1 - self.beta) * value
        self.step += 1

    def get(self):
        return self.ema / (1 - self.beta ** self.step) if self.step > 0 else 'N/A'
```

**Comment by casperdcl** [comment]
hmm... in your class, is that division to compensate for the fact that you start with `ema = 0`? `tqdm`'s implementation does not insert an initial `ema = 0`.

**Comment by almson** [comment]
It's not to compensate for starting with `ema=0`, it's that you have to both start with `ema=0` and do the division. This way, the result is close to a true mean. If you start with `ema=value` and smoothing is 0.01 then the first value will have a disproportionate weight for the first 100 results.

**Comment by almson** [comment]
Here is an example. Say you have first 4 values = `[10, 1, 1, 1]` and smoothing is 0.01. With current implementation the result is 9.7. With the proposed implementation the result is 3.24. True mean is 3.25.

**Comment by casperdcl** [comment]
Ah you mean a correction factor for early iterations as outlined in https://en.wikipedia.org/wiki/Moving_average#Approximating_the_EMA_with_a_limited_number_of_terms

Sure, can do.

**Comment by almson** [comment]
Thanks! Yeah, exactly, the idea is to divide by (1-"weight omitted by stopping after k terms").

The implementation isn't correct because it's using `self.n` instead of `step` (ie, number of calls to ema). The two are equal when update(1) is called but not otherwise.

**Comment by casperdcl** [comment]
> Here is an example. Say you have first 4 values = `[10, 1, 1, 1]` and smoothing is 0.01. With current implementation the result is 9.7. With the proposed implementation the result is 3.24. True mean is 3.25.

PS. I get 3.22 with the proposed implementation (not 3.24).

**Comment by almson** [comment]
You're right it should be 3.2162.

`python -c "print(((((0*0.99+10*0.01)*0.99+1*0.01)*0.99+1*0.01)*0.99+1*0.01)/(1-0.99**4))"`

**Comment by casperdcl** [comment]
P.S. as an easter egg you can do `from tqdm.std import EMA` if you'd like to avoid redefining an `EMA` class for use elsewhere... slightly cleaner syntax.

```python
from tqdm.std import EMA

ema = EMA()
for update in [10, 1, 1, 1]:
    print(ema(update))
print(ema())
```

https://github.com/tqdm/tqdm/blob/822ca363f0b819d571d1683747c51f099bcbf31a/tqdm/std.py#L216-L244
