### ISSUE TITLE
Add support for updating the description (based on an initial callable)

### ISSUE THREAD

**Issue by kevinmarsh** [tqdm/tqdm#1110]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [x] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [ ] I have mentioned version numbers, operating system and
  environment, where applicable

---

A common pattern I find myself using is to use `set_description` to give me a bit more in progress detail. So in this simple example I want to see in real time when new even numbers have been found:

```python
from time import sleep
from tqdm import tqdm

def is_even(number):
    sleep(2)
    return number % 2 == 0

def find_even_numbers(numbers):
    even_numbers = []
    pbar = tqdm(numbers, desc=f"{len(even_numbers)} found")
    for number in pbar:
        if is_even(number):
            even_numbers.append(number)
            pbar.set_description(f"{len(even_numbers)} found")
    return even_numbers


find_even_numbers([1, 2, 3, 4, 5])
```
![2021-01-05 14:11:04](https://user-images.githubusercontent.com/1423728/103705698-5cf5cf00-4f60-11eb-8378-0980042fa56f.png)
![2021-01-05 14:11:23](https://user-images.githubusercontent.com/1423728/103705708-61ba8300-4f60-11eb-8056-1558defbe0e9.png)

The caveat is that I want the description set when tqdm is initalized (so the prefix doesn't magically appear the first time `is_even` is true) and when it needs updating, but I also want to keep my code DRY. The current description is pretty simple, but imagine there's more data I'm wanting to keep updated.

I could DRY it up by encapsulating the description in a function:
```python
even_numbers = []
def get_description():
    return f"{len(even_numbers)} found"
```
and then using that in `pbar = tqdm(numbers, desc=get_description())` and `pbar.set_description(get_description())` but I feel like a nicer API would be to be able to call `pbar.update_description()` on a callable description function intialized on `pbar`.

If you think this is a sensible improvement then I can put together a PR for [a relatively simple change](https://github.com/kevinmarsh/tqdm/commit/5e0c02076182b3cc308027b8d7a8023b4d4dcd70#diff-705b1f138d56c394e86e887dc6b2ac8e6d7655b74415b122089636f4b28195c2R1382) to implement this, but just wanted some feedback in case there were alternatives I hadn't considered or concerns about adding another way to update the description (in addition to `set_description` and `set_description_str`).

**Comment by Michael1015198808** [comment]
You may implement this by creating a subclass of `tqdm` like

```Python3
import tqdm

class my_tqdm(tqdm.std.tqdm):
    def __init__(self, *args, func = None, **kwargs):
        self.__desc_func = func
        super(my_tqdm, self).__init__(*args, **kwargs)

    def display(self, *args, **kwargs):
        if self.__desc_func:
            self.desc = self.__desc_func()
        super(my_tqdm, self).display(*args, **kwargs)
```

An example of using this class

```Python3
ans = 0
def l():
    return "%d found" % ans

for i in my_tqdm(range(10000), func = l):
    if i % 7 == 0:
        ans += 1
```

For simplicity, `my_tqdm` here accept a function without argument. If you need to pass some arguments, you may modify the `__init__` of `my_tqdm`, or try using closure to wrap the function into a new one without arguments.

And, calling your function every loop may be time-consuming. If you can tolerate a little out-sync, you can override `refresh` instead.

Using two leading underscores in `__desc_func` is to make it invisible to its superclass. (to avoid collisions!)

**Comment by kevinmarsh** [comment]
Thanks for the response @Michael1015198808

I was more gauging to see if there was interest in adding this functionality into `tqdm` itself, so I think I'll close this issue as "not interested at this time"
