### ISSUE TITLE
ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by tdegeus** [tqdm/tqdm#1117]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

With the latest `tqdm` on conda-forge I'm getting:

```
import tqdm
  File "/home/tdegeus/miniconda3/envs/code_velocity_s6g1/lib/python3.8/site-packages/tqdm/__init__.py", line 3, in <module>
    from .cli import main  # TODO: remove in v5.0.0
ValueError: source code string cannot contain null bytes
```

The version:

```
tqdm                      4.56.0             pyhd8ed1ab_0    conda-forge
```

(on Linux).

Everything works fine when downgrading to `tqdm-4.55.2`. Strangely my Linux CI is not failing, which presumable uses the same package.

**Comment by tdegeus** [comment]
Indeed, even in a different environment:
```
less /home/tdegeus/miniconda3/envs/stable/lib/python3.8/site-packages/tqdm/cli.py
"/home/tdegeus/miniconda3/envs/stable/lib/python3.8/site-packages/tqdm/cli.py" may be a binary file.  See it anyway?
```

**Comment by maresb** [comment]
Curiously I just ran into the same error on a CI run [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=566316&view=logs&jobId=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00), and found this by googling the error. I'm not sure if there's any connection.

**Comment by maresb** [comment]
And in my case it went away after restarting. Must have been cosmic rays. :laughing:

**Comment by casperdcl** [comment]
Hmm, can't reproduce this 🤔

```
tqdm ((v4.56.0))$ file tqdm/cli.py
tqdm/cli.py: Python script, ASCII text executable
```

Happy to reopen & investigate further if still an issue

**Comment by tdegeus** [comment]
Haven't encountered it recently. I'm assuming it went away in some update.
