### ISSUE TITLE
TqdmWarning: clamping frac to range [0, 1].  How to prevent this ?

### ISSUE THREAD

**Issue by JamesZBL** [tqdm/tqdm#1118]
``tqdm`` sometimes show this warning, and I wonder how to prevent this:

```
/Library/Python/3.7/site-packages/tqdm/std.py:535: TqdmWarning: clamping frac to range [0, 1]██████████████████████████▊| 99.84615384615518/100 [1:51:16<00:02, 15.16s/it]
```

This is my demo:

```python
   pbar2 = trange(100)
   pbar2.set_description("blabla")

   pbar2.reset()

        for t in range(0, a):

            for k in b.keys():
                run_task(e, f, g)

            time.sleep(c)
            pbar2.update(100.0 / d)

   pbar2.reset()

```

**Comment by casperdcl** [comment]
> `100.0 / d`

is a fraction so due to rouding error isn't perfectly accurate. This means the final `update` is trying to take the total beyond 100% which you are being warned about.

You can always use `warnings` to `'ignore'` the `TqdmWarning`.

**Comment by JamesZBL** [comment]
Thank you. @casperdcl
