### ISSUE TITLE
Binder demo doesn't work

### ISSUE THREAD

**Issue by lrzpellegrini** [tqdm/tqdm#1119]
- [X] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [X] I have visited the [source website], and in particular
  read the [known issues]
- [X] I have searched through the [issue tracker] for duplicates
- [X] I have mentioned version numbers, operating system and
  environment, where applicable

The Binder demo doesn't seem to work. I'm reaching Binder from the link in the README (https://mybinder.org/v2/gh/tqdm/tqdm/master?filepath=DEMO.ipynb).

Here is the error trace from Binder:

```
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2dockerj_cys6ji'...
HEAD is now at c58fc25 bump version, merge pull request #1112 from tqdm/devel
Using DockerBuildPack builder
Step 1/4 : FROM python:3.7-alpine
 ---> 72e4ef8abf8e
Step 2/4 : COPY dist/*.whl .
COPY failed: no source files were specified
```

The error applies to the `c58fc25` commit (as reported in the trace).

**Comment by casperdcl** [comment]
fixed version for now (until #1113 is merged): https://mybinder.org/v2/gh/tqdm/tqdm/devel?filepath=DEMO.ipynb
