### ISSUE TITLE
tqdm.tk: tk.py for tqdm ,more one Tk() in code

### ISSUE THREAD

**Issue by lxj361** [tqdm/tqdm#1129]
![image](https://user-images.githubusercontent.com/77576275/108718099-0b79c180-7559-11eb-812b-263f0f192485.png)

![image](https://user-images.githubusercontent.com/77576275/108718160-1f252800-7559-11eb-948a-eca6c75cc9cd.png)
from tqdm.tk import trange, tqdm
from random import random, randint
from time import sleep
win=Tk()
win.withdraw()
# with tqdm(tk_parent=win,total=10,desc='site_num',bar_format='{l_bar}{bar}|{n_fmt}/{total_fmt}| {rate_fmt} {postfix}',ncols=80) as s_bar:
p_bar=tqdm(tk_parent=win,total=100,desc='First Pbar',ncols=80,nrows=0,bar_format='{l_bar}{bar}|{n_fmt}/{total_fmt}| {rate_fmt} {postfix}')
t_bar=tqdm(tk_parent=win,total=100,desc='secnod',ncols=80,nrows=5)

for j in trange(100):
    p_bar.update(n=1)
    t_bar.update(n=1)
    # s_bar.update(n=1)
    sleep(2)
    # s_bar.update()
    p_bar.refresh()
    t_bar.refresh()
[StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

**Comment by lxj361** [comment]
sorry

**Comment by casperdcl** [comment]
probably remove `withdraw()`?

**Comment by lxj361** [comment]
> probably remove `withdraw()`?

U're right

**Comment by lxj361** [comment]
more question: how make the bar_win dispaly when clicked the button'test'; 
Not display when I clicked the button ,it display utill the program end
  
![image](https://user-images.githubusercontent.com/77576275/108797706-c8eece00-75c6-11eb-8d00-91f0dd390f7f.png)

![Uploading image.png…]()
