### ISSUE TITLE
support for initial_epoch in keras TqdmCallback

### ISSUE THREAD

**Issue by fabiocarrara** [tqdm/tqdm#1138]
- [x] I have marked all applicable categories:
  - [ ]  exception-raising bug
  - [ ]  visual output bug
  - [ ]  documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand StackOverflow#tqdm is more appropriate)
  - [x]  new feature request
- [x]  I have visited the source website, and in particular read the known issues
- [x]  I have searched through the issue tracker for duplicates
- [x]  I have mentioned version numbers, operating system and evnironment, where applicable:

version 4.59.0, Google Colab

Would love the keras TqdmCallback to support  `initial_epochs ` in keras .fit() call to correctly initialize the starting point of the progress bar when resuming training.

Passing the initial epoch using `initial` kwarg does not seem to work, as it is not considered in `on_train_begin()`.

https://github.com/tqdm/tqdm/blob/bcce20f771a16cb8e4ac5cc5b2307374a2c0e535/tqdm/keras.py#L69-L73

Colab Gist reproducing the problem:
https://colab.research.google.com/gist/fabiocarrara/3f81bed4bc735291205b1b42fd5c1567/untitled1.ipynb

**Comment by javoweb** [comment]
Hi @casperdcl, are you working on this? I want to contribute to this fix.

**Comment by casperdcl** [comment]
Oh sure go ahead; I wasn't going to look at this for another couple of weeks
