### ISSUE TITLE
cannot install from source package tqdm-4.61.0.tar.gz

### ISSUE THREAD

**Issue by CnBDM-Su** [tqdm/tqdm#1192]
Because of my offline environment, I installed the tqdm with source package of pypi.
But after I "pip install tqdm-4.61.1.tar.gz", I got Successfully built UNKNOWN instead of tqdm, how can i fix it.
THANKS

**Comment by casperdcl** [comment]
You mean you basically do this?

```bash
pip download --no-binary ":all:" tqdm
pip install tqdm-*.tar.gz
```

In which case...

- could you just `pip download tqdm` instead (to get `*.whl`)
- or could you upgrade `pip`? It's probably an old version (what does `pip --version` say?)

**Comment by casperdcl** [comment]
closing for now, happy to reopen if still an issue
