### ISSUE TITLE
tqdm.notebook not rendering

### ISSUE THREAD

**Issue by simonm3** [tqdm/tqdm#1194]
I have an issue where tqdm works fine but tqdm.notebook shows unformatted (the standard tqdm) progress bar and does not update at all. I have tried it in a virtual env with pip installing only jupyter and tqdm.

Perhaps there is a clash with some other package. Be pleased if anyone can tell me how to fix.

**Comment by casperdcl** [comment]
did you follow https://ipywidgets.readthedocs.io/en/stable/user_install.html?

**Comment by simonm3** [comment]
yes.

this was a while ago and it seems to work now....I guess an incompatibility
somewhere. Suggest close if nobody else had this issue.
