### ISSUE TITLE
support pandas==1.3.0

### ISSUE THREAD

**Issue by casperdcl** [tqdm/tqdm#1199]
https://github.com/pandas-dev/pandas/issues/42356

```python
AttributeError: 'DataFrame' object has no attribute '_is_builtin_func'
```

need to ~check what the internal pandas replacement API call is~ migrate to `pandas.core.common.is_builtin_func`.

**Comment by alex-calderwood** [comment]
Nope. I am getting it with both pandas 1.3 and pandas 1.25 and tqdm 4.61.2 and tqdm 4.62.2
