### ISSUE TITLE
License clarification: MIT and/or Creative Commons?

### ISSUE THREAD

**Issue by EdwardBetts** [tqdm/tqdm#121]
I'm interested in clarifying the license for tqdm. The README says that the license is MIT, but the LICENSE includes this exception:

Exceptions or notable authors are listed below in reverse chronological order:

* [CC-BY-SA-4.0] 2015-2016 Casper da Costa-Luis [casperdcl](https://github.com/casperdcl)

  [CC-BY-SA-4.0]: http://creativecommons.org/licenses/by-sa/4.0/

Does this mean that some parts of the project are MIT, but any commits from casperdcl are CC-BY-SA-4.0 or does it mean the whole thing is MIT but commits by casperdcl are also available with the Creative Commons license?

**Comment by casperdcl** [comment]
Ah sorry if this wasn't clear. It means commits attributed to @casperdcl are released under cc-by-sa-4.0, google asserts copyright specifically for #96 (released under the MIT license)... all other contributors implicitly assert copyright and release under the MIT licence. I guess the README should be updated with a note that multiple licences are involved...

**Comment by EdwardBetts** [comment]
I think it would be useful to document which parts of the project are MIT and which are cc-by-sa-4.0

The license for any change to a Creative Commons part must also be cc-by-sa-4.0 because of the ShareAlike requirement.

**Comment by casperdcl** [comment]
Pretty much every function in every file has lines which fall under the CC licence (about 2/3 of all lines). It's inextricable from tqdm in general. If you need an MIT-only version you could checkout v1.0.0

**Comment by richardotis** [comment]
If the project includes CC-SA code then I don't think you can distribute it using the MIT license because of the "ShareAlike" requirement. This library looks really neat but I've been hesitating to use it in public code because of the license confusion, so I'm hoping you can clear it up soon.

**Comment by casperdcl** [comment]
We're considering converting the CC licence to GPLv3+ or similar... would you be happier with that?

**Comment by EdwardBetts** [comment]
GPLv3+ sounds good to me. I think the GPL is a better fit for software than Creative Commons.

**Comment by richardotis** [comment]
MIT or another BSD-style license is my preference since that's what the entire scientific Python stack uses but, if you really want to require source code redistribution, I'd prefer LGPL so that the redistribution requirement would be limited to this library.

**Comment by lrq3000** [comment]
I think LGPL can be a good option. See Creative Commons summary here:
https://web.archive.org/web/20100323130420/http://creativecommons.org/licenses/LGPL/2.1/

What do you think about it Casper?

2016-02-08 15:25 GMT+01:00 Richard Otis <notifications@github.com>:

**Comment by casperdcl** [comment]
Well I've opened #124 interestingly the gnu people don't recommend Lgpl because they think enough things are already under it and we should be pushing now for truly free (gpl) software.

**Comment by lrq3000** [comment]
Yes Casper you're right, I've read all about this issue a long time ago
when I investigated opensource licences. But I think that's more a matter
of activism than fairness : putting a library under LGPL forces others to
redistribute changes to the library, and I think that's fair ; while GPL
forces users to put their _whole_ software under the same licence, with a
viral effect, which can be unfair.

Indeed, I think it's more fair to leave users with the freedom to use
whatever licence they want for the softwares they write as long as it's
unrelated to our library. Also, I'd prefer closed source projects to use
our libraries than using their usual badly written progress bars ;)

2016-02-09 22:39 GMT+01:00 Casper da Costa-Luis <notifications@github.com>:

**Comment by casperdcl** [comment]
Yes, which is why I went for LGPL in the end. Thanks everyone for the feedback in this transition.

**Comment by casperdcl** [comment]
closed by #124 - will reopen upon request

**Comment by lrq3000** [comment]
> Pretty much every function in every file has lines which fall under the CC licence (about 2/3 of all lines). It's inextricable from tqdm in general. If you need an MIT-only version you could checkout v1.0.0

BTW this is false, all versions before [this commit](https://github.com/tqdm/tqdm/commit/b7669dfe004b3622d0cfd92c8fb59912d196ea22) are under MIT License, it's not just v1.0.0.
