### ISSUE TITLE
VS Code now support ipywidgets

### ISSUE THREAD

**Issue by gordonwatts** [tqdm/tqdm#1213]
- [ ] I have marked all applicable categories:
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [x] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:

Recent versions of `vscode` support `ipywidgets`. It could be that the `autonotebook` code that was introduced in [this PR](https://github.com/tqdm/tqdm/pull/751) now can be reverted. I note that comments on the end of that indicate there should be a new issue, but I didn't spot it.

If the authors feel comfortable with this idea, I can do the work to submit a PR.

**Comment by casperdcl** [comment]
Ah yes was also mentioned in https://github.com/tqdm/tqdm/pull/751#issuecomment-739453132. Happy to accept a PR if you can find out the minimum version supported!

**Comment by gordonwatts** [comment]
Ok. I think the tricky part will actually be knowing what version of VS CODE is running inside the notebook. I'll hunt around and see if I can find something.

**Comment by aldanor** [comment]
Any updates on that? Given the time that has passed, can we just remove that `VSCODE_PID` check?

Whichever the case, one the following will hold true for any user:
1. `autonotebook` in the latest tqdm doesn't work properly with newer version of vscode (where "new" = over half a year now)
2. `autonotebook` in the latest tqdm doesn't work properly in older versions of vscode

Given that (2) will dwindle over time and vscode tends to keep itself updated, can we just remove that single line from `autonotebook.py`?

**Comment by gordonwatts** [comment]
Sorry - I would say yes. I guess it has been working well for me recently, so I'd stopped paying attention to this!

**Comment by casperdcl** [comment]
fixed by #1309
