### ISSUE TITLE
Memory leak in `tqdm_notebook`

### ISSUE THREAD

**Issue by rfriel** [tqdm/tqdm#1216]
In some cases, using the `tqdm_notebook` class to iterate through an object multiple times will accumulate copies of the object in memory.

This causes the user to run out of memory when, for example, using `tqdm_notebook` to iterate through a large dataset once per epoch in neural net training.

The root cause is the reference cycle created on [this line](https://github.com/tqdm/tqdm/blob/8a66f6e35d753f58dbed4425ab2fb91641bef715/tqdm/notebook.py#L240).

I have written a full walkthrough in this [Colab notebook](https://colab.research.google.com/drive/1PE9qkY4weO5p8c2UdyRkhYxN2q8Li3ti?usp=sharing).  I recommend reading the notebook, as it shows the memory issue directly using `tracemalloc`, but I'll reproduce the examples here.

#### Versions:

- the problem exists in 4.59.0 (my local version) and 4.62.0 (latest)
- the problem does not exist in 4.41.1 (default version on Colab)

#### Related issues:

The only issue I could find with a memory leak was #746 with pytorch's `DataLoader`.  However, that issue involved non-notebook tqdm.

(It's worth nothing, though, that I first experienced the issue when using `DataLoader`.)

### Minimal example

(uses numpy to create a large array quickly)

In the loop below, one copy of `y`'s memory cost is added per loop iteration.  For example, the loop will crash a standard Colab runtime (~12GB memory).

```python
from copy import deepcopy
import numpy as np
from tqdm.notebook import tqdm

y = np.ones((80000, 3000))

def loop_fn(y_):
    # deepcopy ensures we allocate new memory in each function call
    # (which should be released when the function returns)
    y2 = deepcopy(y_)
    for _ in tqdm(y2):
        pass

for i in range(10):
    loop_fn(y)
```

### Ruling out causes besides `tqdm_notebook`

The issue does not occur if the import above is replaced with `from tqdm import tqdm`.

The issue does not occur if we replace `loop_fn` with 

```python
def loop_fn(y_):
    y2 = deepcopy(y_)
```

so merely copying the array (without tqdm) is fine.

### Root cause in `tqdm_notebook`

The root cause is [the line](https://github.com/tqdm/tqdm/blob/8a66f6e35d753f58dbed4425ab2fb91641bef715/tqdm/notebook.py#L240) 

```python
self.container.pbar = self
```

which creates a reference cycle between `self` and `self.container`.

Thus, the garbage collector cannot collect a `tqdm_notebook` instance via reference counting.  So, for example, the instance does not get collected immediately upon leaving a function like `loop_fn` above.

This prevents garbage collection of its `iterable` attribute (set to `y2` above).

To see that this is the problem, observe that this does _not_ leak memory:

```python
def loop_fn_fixed(y_):
    y2 = deepcopy(y_)
    iterable = tqdm_notebook(y2)
    for __ in iterable:
        pass
    del iterable.container.pbar  # fix!

for i in range(10):
    loop_fn_fixed(y)
```

while an identical `loop_fn_fixed` without the last line does loop memory.

---

- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] visual output bug
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by casperdcl** [comment]
Can you try with [`devel`](https://github.com/tqdm/tqdm/commit/8c35d42) (`pip install "git+https://github.com/tqdm/tqdm@devel#egg=tqdm"`)?

**Comment by rfriel** [comment]
> Can you try with [`devel`](https://github.com/tqdm/tqdm/commit/8c35d42) (`pip install "git+https://github.com/tqdm/tqdm@devel#egg=tqdm"`)?

I tried it and it no longer leaks.  Thanks!

**Comment by LucaMarconato** [comment]
`tqdm` is giving me a memory leak when iterating a torch data loader. I am not using `enumerate`. I'm on CPU with `num_workers = 10`. I am operating in a `.py` file, not on `.ipynb` file.
The bug appears both using `tqdm` from `tqdm.auto` and `tqdm` from `tqdm`.

My code looks like this:
```
from tqdm.auto import tqdm

for data in tqdm(loader, desc="my desc"):
    pass
```

These are the versions of the packages I am using (output from `conda list`):
```
tqdm                      4.63.0                   pypi_0    pypi
pytorch                   1.10.2          py3.8_cuda10.2_cudnn7.6.5_0    pytorch
```
