### ISSUE TITLE
Too wide progress bar in Jupyter notebooks

### ISSUE THREAD

**Issue by robert-lieck** [tqdm/tqdm#1269]
The progress bar is too wide in Jupyter notebooks (includes a linebreak). This seems to be a relatively recent issue as I have not encountered it before. The problem does not occur when calling ipython from the terminal.

Code to reproduce:
```python
from tqdm import tqdm
for i in tqdm(range(100)):
    pass
```
![image](https://user-images.githubusercontent.com/16177217/139810289-878b77a5-3786-4788-b8c7-86b0d25ef0de.png)

tqdm 4.62.3
python 3.9.7
ipykernel           6.5.0
ipython             7.29.0
ipython-genutils    0.2.0
ipywidgets          7.6.5
jupyter             1.0.0
jupyter-client      7.0.6
jupyter-console     6.4.0
jupyter-core        4.9.1
jupyterlab-pygments 0.1.2
jupyterlab-widgets  1.0.2

- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by WhoTHU** [comment]
Haha, I have a similar problem recently met. But on the contrary, the bar is too narrow in Jupyter，
![image](https://user-images.githubusercontent.com/20219437/140293145-2c2deac2-edcf-48ab-88e8-f96c433bdd0e.png)

when I use bar_format='{l_bar}{bar:40}{r_bar}' it becomes this
![image](https://user-images.githubusercontent.com/20219437/140293499-49ef713e-c5f5-430b-9c28-5d9f17a02e80.png)

The bar only displays a part of the whole bar. These two problems may be related.

**Comment by chengs** [comment]
![image](https://user-images.githubusercontent.com/824529/141955753-d9ba16dc-2222-479b-8e40-3cbf1ad60cfd.png)
Use `tqdm.notebook` ?

**Comment by robert-lieck** [comment]
In the minimal example that I provided, using `tqdm.notebook` would indeed be a solution. But I am using `tqdm` in a library that may or may not be used in a notebook. Having to manually set parameters or specific implementations to obtain an appropriately formatted progress bar defeats the main purpose of the entire `tqdm` library.

**Comment by casperdcl** [comment]
```python
from tqdm.autonotebook import tqdm
# or to suppress the warning:
from tqdm.auto import tqdm
```

**Comment by robert-lieck** [comment]
Oh, this is great, many thanks – and sorry I missed out on that. I guess this will become my new default import statement for `tqdm` 😄
