### ISSUE TITLE
Python 2.6 UnicodeEncodeError

### ISSUE THREAD

**Issue by arusahni** [tqdm/tqdm#127]
Running 3.8.0 from PyPi on RHEL6 w/Python 2.6.6, this code:

``` python
from tqdm import tqdm
from time import sleep
for num in tqdm(range(20)):
    sleep(1)
```

results in the following output/traceback:

```
0%|                                                             | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/proj/venv/lib/python2.6/site-packages/tqdm/_tqdm.py", line 483, in __iter__
    1 / avg_time if avg_time else None, bar_format))
  File "/opt/proj/venv/lib/python2.6/site-packages/tqdm/_tqdm.py", line 95, in print_status
    fp.write('\r' + s + (' ' * max(last_printed_len[0] - len_s, 0)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-16: ordinal not in range(128)
```

**Comment by casperdcl** [comment]
Could you try with the latest version from here (github)? We'll push to pypi once you can confirm it's fixed here...

**Comment by arusahni** [comment]
v4.1.0 from the head of the master branch works as expected.

**Comment by casperdcl** [comment]
Whew. That's good. It took a bit of work to fix... we'll push the update soon.

**Comment by dyno** [comment]
still hit this problem on 2.6 with the code in master branch.

**Comment by lrq3000** [comment]
Um...  That's weird since the 2.6 unit test passes fine. Can you provide a sample code or is it the same as provided above?

**Comment by bwbeach** [comment]
Running on a Mac with Python 2.6.9 (installed with macports), I'm still seeing this problem:

```
(p26)stone:~ brianb$ tqdm --version
4.9.0
(p26)stone:~ brianb$ python
Python 2.6.9 (unknown, Mar  7 2016, 10:48:33) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tqdm import tqdm
>>> from time import sleep
>>> for num in tqdm(range(20)): sleep(1)
... 
  0%|                                                                                                          | 0/20 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/brianb/p26/lib/python2.6/site-packages/tqdm/_tqdm.py", line 835, in __iter__
    1 / avg_time if avg_time else None, bar_format))
  File "/Users/brianb/p26/lib/python2.6/site-packages/tqdm/_tqdm.py", line 195, in print_status
    fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
  File "/Users/brianb/p26/lib/python2.6/site-packages/tqdm/_tqdm.py", line 188, in fp_write
    fp.write(_unicode(s))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-10: ordinal not in range(128)
>>> ^D
(p26)stone:~ brianb$ echo $LANG
en_US.UTF-8
```

**Comment by casperdcl** [comment]
does the problem disappear with v4.1.0 @bwbeach @dyno as it did with @arusahni ?

**Comment by dyno** [comment]
yes. v.4.1.0 works. it looks like it switch to ascii=True there. @casperdcl

**Comment by casperdcl** [comment]
Thanks @dyno. Since I can't replicate your issue it would help me greatly if you could find out which version breaks: v4.2.0 v4.3.0 v4.4.0 v4.4.1 v4.4.2 v4.4.3 v4.5.0 v4.5.2 v4.6.0 v4.6.1 v4.6.2 v4.7.0 v4.7.1 v4.7.2 v4.7.3 v4.7.4 v4.7.5 v4.7.6 v4.8.0 v4.8.1 v4.8.2 v4.8.3 v4.8.4 v4.9.0

To make this easy, you could create two files:

In `testunicode.py`:
``` python
from tqdm import tqdm
from time import sleep
try:
    for num in tqdm(range(20)):
        sleep(1)
except UnicodeEncodeError:
    print (tqdm.__version__ + " is broken")
```

In testunicode.sh:
``` sh
#!/bin/bash
for v in v4.2.0 v4.3.0 v4.4.0 v4.4.1 v4.4.2 v4.4.3 v4.5.0 v4.5.2 v4.6.0 v4.6.1 v4.6.2 v4.7.0 v4.7.1 v4.7.2 v4.7.3 v4.7.4 v4.7.5 v4.7.6 v4.8.0 v4.8.1 v4.8.2 v4.8.3 v4.8.4 v4.9.0; do
  pip install -U "tqdm==$v"
  python testunicode.py
```

Then simply run:
``` sh
$ chmod +x testunicode.sh
$ ./testunicode.sh
```

**Comment by dyno** [comment]
i used the github branch tags,
v4.2.0 is good. 
v4.3.0 is broken.

**Comment by casperdcl** [comment]
Thanks @dyno. This is quite annoying. Do you know of any method you can use to tell that `sys.stderr` does not support unicode on your machine? Trying to write unicode and catching the exception is not a great solution.

**Comment by dyno** [comment]
https://wiki.python.org/moin/PrintFails
the solution at the end of this page works for me - meaning it actually prints the correct utf-8 progress bar. 

```
import sys, codecs, locale
sys.stdout = codecs.getwriter(locale.getpreferredencoding())(sys.stdout)
sys.stderr = codecs.getwriter(locale.getpreferredencoding())(sys.stderr)

import tqdm
from time import sleep
try:
    for _ in tqdm.tqdm(range(20)):
        sleep(1)
except UnicodeEncodeError:
    print (tqdm.__version__ + " is broken")

```

**Comment by ryaku711** [comment]
i am having a similar issue. I'm running on a linux system. Basically the # symbol is not showing up. When i try to use unicode i get a lot of odd characters and instead of a nice bar, it will start to scroll down the screen.

UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-7: ordinal not in range(128)

symbol i get is ˆâ–ˆâ–ˆâ–ˆâ–ˆ

**Comment by casperdcl** [comment]
Hi @ryaku711. You could use `ascii=True` (that is, `tqdm(..., ascii=True, ...)`) to force use of `#` instead of unicode. Hopefully this will be fixed by #314

**Comment by chengs** [comment]
@casperdcl this can be closed, IMHO

**Comment by casperdcl** [comment]
because EOL of py2.6? or has the issue been fixed?
