### ISSUE TITLE
ValueError: n (0) cannot be less than 1

### ISSUE THREAD

**Issue by SantiagoONE** [tqdm/tqdm#128]
I had this error with the sample called "tqdm_wget.py":

![deepinscreenshot20160220203524](https://cloud.githubusercontent.com/assets/8689272/13200342/840a36d8-d811-11e5-89c5-fe8d4378fc93.png)

**Comment by casperdcl** [comment]
Hi @SantiagoONE ... this is a feature we added in #111 - is this error reproducible? It implies `urllib` is calling `tqdm` with negative values (e.g. it's reporting that 3 bytes have downloaded in total after reporting 4 bytes have downloaded).

I can't quite remember @lrq3000 but did you mention something about this?

**Comment by nabijaczleweli** [comment]
Or, rather, it means, that it didn't manage to download anything (in the 
screenshot, n is 0)

**Comment by casperdcl** [comment]
Oh I see. This was fixed in v4.1.0 (not on pypi yet) let me know if that works for you...

**Comment by casperdcl** [comment]
Will reopen upon request if this is still an issue
