### ISSUE TITLE
Blank lines of nested progress bar in VSCode + ipynb

### ISSUE THREAD

**Issue by Joilence** [tqdm/tqdm#1287]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```
4.62.3 3.8.2 (default, Mar 25 2020, 11:22:43) 
[Clang 4.0.1 (tags/RELEASE_401/final)] darwin
VSCode 1.63.2, macOS 12.1 (M1).

Unable to correctly display nested progress bar in VSCode + .ipynb, always leaves a blank line when a sub-loop is finished.

I'm aware that in the known issue it is mentioned that tdqm require support for moving cursors up to the previous line which, for e.g., consoles of PyCharm does not support, but it does not mention VSCode. I'm not sure if VSCode has the same lack of support.

Code:

```python
import tqdm, sys
# from tqdm.auto import tqdm # this does not work to detect notebook env
import time
import sys
from tqdm.notebook import tqdm
for _ in tqdm(range(5)):
    for _ in tqdm(range(20), leave=False):
        for _ in tqdm(range(50), leave=False):
            # do something, e.g. sleep
            time.sleep(0.01)
```
<img width="634" alt="CleanShot 2022-01-10 at 01 18 48@2x" src="https://user-images.githubusercontent.com/14588641/148707208-4e7629f4-b5a0-498a-b2a1-a83631879f21.png">

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by dyspr0sium** [comment]
The same issue with blank newlines for nested loops occurs in .ipynbs opened in `jupyter lab`. The same .ipynb opened in `jupyter notebook` does not display this issue.

**Comment by aldanor** [comment]
Wonder if there's any news/thoughts on this? Just encountered this as well in vscode which is pretty sad. Looks like there's some div containers generated that don't/can't get properly removed?

**Comment by aldanor** [comment]
https://user-images.githubusercontent.com/2418513/158709499-9201e00d-3982-48cc-99c6-8343f913f621.mp4

**Comment by casperdcl** [comment]
This has been reported before (originally at #433) - the real problem is upstream https://github.com/jupyterlab/jupyterlab/issues/7354 (bot auto-closed, should be re-opened) and https://github.com/jupyter-widgets/ipywidgets/issues/1845.
