### ISSUE TITLE
Progress bar with logging and ftplib

### ISSUE THREAD

**Issue by kierun** [tqdm/tqdm#129]
I have a script that downloads a number of files via `ftplib`.  I have some logging that can be printed to the console. And, of course, I am using `tqdm`.  However, I get the following output:

```
INFO     [Install (install:114)] Downloading all 3 package(s).
INFO     [Source (source:266)] Downloading ook-1.2.3-el7-x64.tar.xz
ook-1.2.3-el7-x64.tar.xz:   0%|                     | 0.00/29.0 [00:00<?, ?it/s]
INFO     [Source (source:266)] Downloading eek-4.5.6-el7-x64.tar.xz
eek-4.5.6-el7-x64.tar.xz:   0%|                    | 0.00/14.8M [00:00<?, ?it/s]
eek-4.5.6-el7-x64.tar.xz:  84%|█████████▏ | 12.4M/14.8M [00:00<00:00, 30.7Mit/s]INFO     [Source (source:266)] Downloading monkey-7.8.9-el7-x64.tar.xz
monkey-7.8.9-el7-x64.tar.xz:   0%|                  | 0.00/29.0 [00:00<?, ?it/s]
INFO     [Mead (mead:245)] Started now (0:00:00.521348).
```
The code that produces the tqdm is like so:

```
with open(local, 'wb') as fd:
    total = ftp.size(item)
    with tqdm(total=total,
              unit_scale=True,
              desc=item,
              miniters=1,
              file=sys.stdout,
              leave=True
              ) as pbar:
        def cb(data):
            pbar.update(len(data))
            fd.write(data)
    ftp.retrbinary('RETR {}'.format(item), cb)
```

Even if I set `leave=False`, I get this:

```
INFO     [Install (install:114)] Downloading all 3 package(s).
INFO     [Source (source:266)] Downloading ook-1.2.3-el7-x64.tar.xz

INFO     [Source (source:266)] Downloading eek-4.5.6-el7-x64.tar.xz
eek-4.5.6-el7-x64.tar.xz:  84%|█████████▏ | 12.4M/14.8M [00:00<00:00, 31.0Mit/s]INFO     [Source (source:266)] Downloading monkey-7.8.9-el7-x64.tar.xz

INFO     [Mead (mead:245)] Started now (0:00:00.518758).
```

Notice the blank lines.

What am I doing wrong here?

Actually, I do not think that ftplib has anything to do with it whatsoever.  ☺

**Comment by lrq3000** [comment]
I'm not sure I understand the issue, but in any case `tqdm` needs to be started after at least one `newline` because it uses a rewriting scheme beginning at the start of the line to refresh the bar progress. If `tqdm` bar is placed at the middle of the line, this won't work.

**Comment by kierun** [comment]
The call to `ftp.retrbinary` was badly intended resulting in the effect.

However, there still is a new line *after* the tqdm finishes.  How do I set it so that it clear (\r`) the line but does not issue a new line?

**Comment by casperdcl** [comment]
pass in `leave=False` as an argument to `tqdm`.

**Comment by kierun** [comment]
Silly me, that worked.

Thank you.
