### ISSUE TITLE
using 8 GPUs in training loop printed a lot of messages while only rank==0 have tqdm bar

### ISSUE THREAD

**Issue by jinfagang** [tqdm/tqdm#1294]
Hi, i have only:

```
if rank == 0:
            bar = tqdm(total=len(loader) * group_size,
                   desc=f'Epoch {epoch}/{total_epochs}'.format(epoch))
```
But, seems all GPUs printed out tqdm messages:

![image](https://user-images.githubusercontent.com/21303438/150277679-50507472-8c87-4e98-a492-524ffef31d38.png)

the order totally messed up.

How to use in under 8 GPUs training?

**Comment by casperdcl** [comment]
Looks more like a [StackOverflow#tqdm](https://stackoverflow.com/questions/tagged/tqdm)-type question
