### ISSUE TITLE
Random duplicated line on multithreaded progress bard update

### ISSUE THREAD

**Issue by joaompinto** [tqdm/tqdm#1305]
- [ X] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [X] visual output bug
- [X ] I have visited the [source website], and in particular
  read the [known issues]
- [ ] I have searched through the [issue tracker] for duplicates
- [ ] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```
4.63.0 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] linux

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=

from tqdm import tqdm
import time
from concurrent.futures import ThreadPoolExecutor, as_completed

layers = [{"size" : 1000}, {"size" : 1000}]

The following code, randomly produces a 3rd line duplicating the content of the previous line:
````python
def download_layer(layer, position):
    total = layer['size']
    with tqdm(total=total, position=position, ascii=True) as pbar:
        for n in range(int(total / 50)):
            time.sleep(0.01)
            pbar.update(50)


with ThreadPoolExecutor(max_workers=len(layers)) as ex:
    futures = []
    for i, layer in enumerate(layers):
        futures.append(ex.submit(download_layer, layer, i))
    for future in as_completed(futures):
        result = future.result()
```

It was tested running python from Windows + WSL2 and the VSCode Terminal.

**Comment by joaompinto** [comment]
![wsl2_bug](https://user-images.githubusercontent.com/1143125/156929897-b0c38fad-6974-47c2-a1ad-41810bff0f0f.PNG)

**Comment by jithu7432** [comment]
![image](https://user-images.githubusercontent.com/76789703/171662275-10d657e1-5063-408d-8fce-a7bd31ee6bae.png)

**Comment by jithu7432** [comment]
Works fine on `fish`, but on `bash` I am having problems.
NB: also tested with `bash --noprofile --norc`

**Comment by mjpieters** [comment]
This is almost certainly the same issue as #1496.

Could you try my PR fix (#1502) for that issue? You can install it in your local virtualenv by using

```
pip install git+https://github.com/tqdm/tqdm.git@refs/pull/1502/merge
```

**Comment by joaompinto** [comment]
Works fine now.
Thanks

**Comment by mjpieters** [comment]
Glad it works! Note that the PR has not yet been merged however; if the PR is accepted and merged, issues like these would be closed automatically (provided I add them to the 'fixes' list, which I do when I get confirmations like this).
