### ISSUE TITLE
tqdm v4 on pypi

### ISSUE THREAD

**Issue by keturn** [tqdm/tqdm#131]
Is there a stable release of tqdm 4.x? The github release tag says "4.0 stable", but pypi still only has 3.8.

**Comment by lianyi** [comment]
+1 for getting tqdm-4.0 and  tqdm-4.2.0 in pypi.

**Comment by lrq3000** [comment]
Just need to tidy things up and the release will be uploaded :) The v4.x branch is a major update because of the new positioning system, we need to make sure everything is stable!
