### ISSUE TITLE
jupyter lab: does not render progressbar

### ISSUE THREAD

**Issue by wookayin** [tqdm/tqdm#1310]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
- [x] I have visited the [source website], and in particular read the [known issues]
- [x]  I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)

  4.63.0       3.9.7 | packaged by conda-forge          darwin
  ```

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=

## Bug

From some point in my environments, I was seeing tqdm.notebook renders like a JSON rather than a HTML widget or progress bar. It happens in a jupyter lab -- jupyter notebook is fine.

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/1009873/159085537-a60c32b4-2944-4734-af3d-c9cb38a4619f.png">

I suspect this is due to some combination of other plugins and extensions, but I cannot easily find why so that's why I file this issue to keep track of my troubleshooting.

## Environment information:

```
tqdm 4.63.0
ipywidgets==8.0.0a
widgetsnbextension==4.0.0rc0

jupyter-client==7.1.2
jupyter-core==4.9.1
jupyter-lsp==1.5.1
jupyter-server==1.13.5
jupyterlab==3.3.2
jupyterlab-lsp==3.10.0
jupyterlab-pygments==0.1.2
jupyterlab-server==2.10.3
jupyterlab-widgets==3.0.0rc0


$ jupyter labextension list
JupyterLab v3.3.2
/Users/wookayin/.miniforge3/share/jupyter/labextensions
        @pyviz/jupyterlab_pyviz v2.1.0 enabled OK (python, pyviz_comms)
        @krassowski/jupyterlab-lsp v3.10.0 enabled OK (python, jupyterlab-lsp)
        @voila-dashboards/jupyterlab-preview v2.1.3 enabled OK (python, voila)
        @jupyter-widgets/jupyterlab-manager v5.0.0-rc.0 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /Users/wookayin/.miniforge3/share/jupyter/lab
```

**Comment by wookayin** [comment]
I found that this is an issue of `ipywidgets>=8.0.0.rc0`. I will report an issue there.

**Comment by casperdcl** [comment]
@wookayin you mean there's some issue under https://github.com/jupyter-widgets/ipywidgets/issues?

**Comment by Hubbitus** [comment]
Sorry, is there some fix or workarounds?

**Comment by A-Telfer** [comment]
downgrading ipywidgets to below <8 didn't work for me

**Comment by wragge** [comment]
Downgrading ipywidgets to 7.7.1 and jupyterlab-widgets to 1.1.1 worked for me.

**Comment by lqhuang** [comment]
> Downgrading ipywidgets to 7.7.1 and jupyterlab-widgets to 1.1.1 worked for me.

Yeah, just limit the version like this at current stage

```
jupyterlab_widgets<2.0.0
ipywidgets<8.0.0
```

**Comment by casperdcl** [comment]
`jupyter notebook` works fine (any version of `ipywidgets` & `tqdm`). I believe you mean `jupyter lab` is broken?

**Comment by casperdcl** [comment]
Does #1361 (`pip install -U "git+https://github.com/tqdm/tqdm.git@fix-jupyterlab#egg=tqdm"`) work for you?

**Comment by i-aki-y** [comment]
> Does https://github.com/tqdm/tqdm/pull/1361 (pip install -U "git+https://github.com/tqdm/tqdm.git@fix-jupyterlab#egg=tqdm") work for you?

Hi @casperdcl , it works for me!
With the following versions:

```
ipywidgets                8.0.1
jupyterlab                3.4.5
jupyterlab-widgets        3.0.2
```

**Comment by lqhuang** [comment]
> `jupyter notebook` works fine (any version of `ipywidgets` & `tqdm`). I believe you mean `jupyter lab` is broken?

Yes, my setup is under the `jupyterlab`. Seems you have solved. Thanks for your efforts!

**Comment by michaelaye** [comment]
pinning ipywidgets to <8 is becoming quite a constraint quickly. would be a pain to say goodbye to tqdm. :(

**Comment by casperdcl** [comment]
Should be fixed now in [tqdm>=4.64.1](https://github.com/tqdm/tqdm/releases/tag/v4.64.1)

**Comment by postrou** [comment]
Still have this issue. 
```
tqdm==4.64.1
ipywidgets==8.0.2
jupyterlab-widgets==3.0.3
```
Rolling back ipywidgets helps.

**Comment by casperdcl** [comment]
Are you sure? those specs work for me. Are you sure you're connecting to the right `(ipy)kernel`?

**Comment by postrou** [comment]
I use VS Code for jupyter notebooks, if it is important. Here is the screenshot

<img width="745" alt="image" src="https://user-images.githubusercontent.com/27743016/188515845-6a4bd92a-5ce5-4c5e-979a-a683410ed8d3.png">

Whenever I run the cell with `trange`, jupyter gives me the following as output
```
info 22:3:17.614: Cell 1 executed with state Success
info 22:3:17.652: Widget Message: WidgetManager: Loading class LayoutModel:@jupyter-widgets/base:2.0.0
info 22:3:17.675: Widget Message: WidgetManager: Loading class ProgressStyleModel:@jupyter-widgets/controls:2.0.0
info 22:3:17.675: Widget Message: WidgetManager: Loading class FloatProgressModel:@jupyter-widgets/controls:2.0.0
info 22:3:17.675: Widget Message: WidgetManager: Loading class LayoutModel:@jupyter-widgets/base:2.0.0
info 22:3:17.680: Widget Message: Waiting for model to be available before rendering it 6cf19fa53cad44fea6d9f91514e87548
info 22:3:17.680: Widget Message: WidgetManager: Loading class HTMLStyleModel:@jupyter-widgets/controls:2.0.0
info 22:3:17.680: Widget Message: WidgetManager: failed, Loading class HTMLStyleModel:@jupyter-widgets/controls:2.0.0
info 22:3:17.680: Widget Message: WidgetManager: failed, Loading class HTMLStyleModel:@jupyter-widgets/controls:2.0.0
error 22:3:17.680: Widget load failure {} {
  className: 'HTMLStyleModel',
  moduleName: '@jupyter-widgets/controls',
  moduleVersion: '2.0.0',
  cdnsUsed: false,
  isOnline: true,
  timedout: false,
  error: '{}'
}
info 22:3:17.681: Widget Message: WidgetManager: Loading class HTMLModel:@jupyter-widgets/controls:2.0.0
info 22:3:17.681: Widget Message: WidgetManager: Loading class LayoutModel:@jupyter-widgets/base:2.0.0
info 22:3:17.691: Widget Message: WidgetManager: Loading class HTMLStyleModel:@jupyter-widgets/controls:2.0.0
info 22:3:17.692: Widget Message: WidgetManager: failed, Loading class HTMLStyleModel:@jupyter-widgets/controls:2.0.0
info 22:3:17.695: Widget Message: WidgetManager: failed, Loading class HTMLStyleModel:@jupyter-widgets/controls:2.0.0
error 22:3:17.695: Widget load failure {} {
  className: 'HTMLStyleModel',
  moduleName: '@jupyter-widgets/controls',
  moduleVersion: '2.0.0',
  cdnsUsed: false,
  isOnline: true,
  timedout: false,
  error: '{}'
}
info 22:3:17.696: Widget Message: WidgetManager: Loading class HTMLModel:@jupyter-widgets/controls:2.0.0
info 22:3:17.697: Widget Message: WidgetManager: Loading class LayoutModel:@jupyter-widgets/base:2.0.0
info 22:3:17.700: Widget Message: WidgetManager: Loading class HBoxModel:@jupyter-widgets/controls:2.0.0
info 22:3:17.705: Widget Message: Received display data message 6cf19fa53cad44fea6d9f91514e87548
info 22:3:17.705: Widget Message: Error: Failed to render widget 6cf19fa53cad44fea6d9f91514e87548, Error: Module @jupyter-widgets/controls, semver range ^2.0.0 is not registered as a widget module
```

**Comment by Jajiko** [comment]
I also have problems with the same configuration as postrou.
```
tqdm==4.64.1
ipywidgets==8.0.2
jupyterlab-widgets==3.0.3
```
For me, nothing is displayed. 
I tested vanilla jupyter, not vscode. 
Can it be a Windows-only problem? A friend did not have problems with these versions on Linux.

**Comment by Jajiko** [comment]
Thanks for the reply. The ASCII version seems to work, but the notebook version does not.
![image](https://user-images.githubusercontent.com/24193411/191477499-9b78945a-7427-411c-ba9d-8c2d859b0acc.png)

What other dependencies could affect it?

**Comment by specter119** [comment]
@Jajiko seems you still use the legacy jupyter notebook.

![image](https://user-images.githubusercontent.com/8768524/191504218-e29f3ac5-626a-47b0-9f95-34048bcc8289.png)

**Comment by morrisalp** [comment]
I'm running in dockerized JupyterLab (v2.3.2). After upgrading to tqdm==4.64.1, notebook display shows this strange behavior:
<img width="371" alt="Screen Shot 2022-11-27 at 21 48 10" src="https://user-images.githubusercontent.com/8263996/204156411-54b00135-d04b-436b-ab29-16fde0942473.png">
with ASCII output and no updates. The ASCII bar works though:
<img width="459" alt="Screen Shot 2022-11-27 at 21 49 02" src="https://user-images.githubusercontent.com/8263996/204156455-22d06287-aa2a-4c04-a5ac-3164e296720f.png">
Relevant versions:
<img width="646" alt="Screen Shot 2022-11-27 at 21 50 22" src="https://user-images.githubusercontent.com/8263996/204156528-b3a3281e-5533-44ea-87d5-9b31984fbec5.png">

**Comment by enzokro** [comment]
> I'm running in dockerized JupyterLab (v2.3.2). After upgrading to tqdm==4.64.1, notebook display shows this strange behavior: <img alt="Screen Shot 2022-11-27 at 21 48 10" width="371" src="https://user-images.githubusercontent.com/8263996/204156411-54b00135-d04b-436b-ab29-16fde0942473.png"> with ASCII output and no updates. The ASCII bar works though: <img alt="Screen Shot 2022-11-27 at 21 49 02" width="459" src="https://user-images.githubusercontent.com/8263996/204156455-22d06287-aa2a-4c04-a5ac-3164e296720f.png"> Relevant versions: <img alt="Screen Shot 2022-11-27 at 21 50 22" width="646" src="https://user-images.githubusercontent.com/8263996/204156528-b3a3281e-5533-44ea-87d5-9b31984fbec5.png">

Seeing the same issue, with the exact same package versions. It still happens even in a brand new environment even with careful re-installs.

Maybe it helps for debugging: but it seems tied to the state of the widgets and/or kernel. That would make sense if the issue is in some ~/.jupyter config or file, so it's more global than a specific env.

I haven't found a good way to "reset" or "rebuild" the widget state. Maybe that points in a promising direction?

**Comment by enzokro** [comment]
Hi all,

Was able to resolve this on my end, I hope it's helpful for others.

Basically, I had been using jupyter notebook for a while and recently switched to lab. There were a few stray notebook extensions, mainly matplotlib and js-widgets, still hanging around. I believe these caused my issues.

I completely uninstalled and removed those notebook extensions. Then, making sure that no server was running, I did a `pip uninstall` and `pip reinstall --upgrade --ignore-installed --force-reinstall` of the following libraries: jupyterlab, jupyterlab_widgets, ipywidgets.

Finally, a `jupyter lab clean` and `jupyter lab build`.

After the three steps above, the widgets are back! This might be more specific to my broken environment than the problem others are having, just posting in case it helps anyone.

**Comment by morrisalp** [comment]
I finally found a solution! Based on the advice of @enzokro, I found that running the following two commands before launching Jupyter Lab makes the widgets appear properly:

```
pip install --upgrade --ignore-installed --force-reinstall jupyterlab_widgets
jupyter lab build
```

I didn't need to do any of the other steps @enzokro mentioned, this is enough to make it work for me.

(see my post above for more info about my environment)

**Comment by PaulKGrimes** [comment]
This is still broken with:
tqdm 4.65.0
ipywidgets 8.0.6
jupyterlab_widgets 3.0.7

**Comment by sebnapi** [comment]
Don't get any output with vanilla jupyter on MacOS:
```
import ipywidgets
import jupyterlab_widgets
import tqdm

print(ipywidgets.__version__, jupyterlab_widgets.__version__, tqdm.__version__)
```
`8.1.0 3.0.8 4.66.1`
