### ISSUE TITLE
PyTorch Multiprocessing Bug

### ISSUE THREAD

**Issue by aakashsur** [tqdm/tqdm#1312]
- [X] I have marked all applicable categories:
    + [X] exception-raising bug
    + [ ] visual output bug
- [X] I have visited the [source website], and in particular
  read the [known issues]
- [X] I have searched through the [issue tracker] for duplicates
- [X] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=

Versions -
tqdm: 4.63.1
python: 3.8.10
system: [GCC 10.2.0] linux

When using tqdm in pytorch, I get the following error when the `num_workers` parameter on torch.utils.data.Dataloader is more than 0: 

```
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fd2e1e6d550>
Traceback (most recent call last):
  File "/mmfs1/home/asur/.virtual/python-3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/mmfs1/home/asur/.virtual/python-3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/mmfs1/sw/contrib/cesg-src/spack/opt/spack/linux-centos8-cascadelake/gcc-10.2.0/python-3.8.10/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
```

This issue has been referenced [here](https://discuss.pytorch.org/t/error-while-multiprocessing-in-dataloader/46845/18) before. While the assertion exception is ignored, it is still raised a number of times, and not always in the same spot, suggesting a race condition. Indeed, as the thread suggests, setting `num_workers` to 0 and avoiding any multiprocessing solves the issue. Additionally, it seems that using `from tqdm.auto import tqdm` is perhaps a culprit, since using `from tqdm import tqdm` also solves the issue oddly enough.

**Comment by casperdcl** [comment]
As per the discussion you linked it doesn't seem it's a `tqdm` issue - looks like there are several no(n)-`tqdm` users who had the same error. The traceback doesn't mention `tqdm` at all :thinking:
