### ISSUE TITLE
add configuration to turn off progress bars

### ISSUE THREAD

**Issue by antonysouthworth-halter** [tqdm/tqdm#1318]
- [ ] I have marked all applicable categories:
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [x] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

```
4.64.0 3.8.13 (default, Apr  1 2022, 11:52:33)
[Clang 12.0.0 (clang-1200.0.32.29)] darwin
```

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=
[StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

Hi,

`tqdm` is very useful during development to understand the progress of your code. However, if this code is deployed somewhere that doesn't have a regular tty, e.g. CI systems or servers, the progress bar could interfere with the regular logging of the application, e.g. for ingestion into systems like AWS CloudWatch, SumoLogic, Spluk or others.

I think it would be nice if `tqdm` could be configured to be a no-op. For example using an environment variable:

```bash
python my-script.py # tqdm progress bar emitted as usual

env TQDM_DISABLE=true python my-script.py # tqdm does nothing
```

**Comment by fromm1990** [comment]
@antonysouthworth-halter wouldn't the `disable` parameter do what you are asking for? https://tqdm.github.io/docs/tqdm/#__init__

**Comment by antonysouthworth-halter** [comment]
@fromm1990 thanks for that! Even after a good hunt I didn't see that one before.

It seems `disable=None` would basically do what I want for a single call to `tqdm()`. The thing there is that it won't work for an entire project (unless I also missed the docs that allow you to set the default value for `disable` globally....).

Still good to know that it's at least kinda possible, just not as convenient as setting an envvar.

**Comment by Raichuu41** [comment]
> @fromm1990 thanks for that! Even after a good hunt I didn't see that one before.
> 
> It seems `disable=None` would basically do what I want for a single call to `tqdm()`. The thing there is that it won't work for an entire project (unless I also missed the docs that allow you to set the default value for `disable` globally....).
> 
> Still good to know that it's at least kinda possible, just not as convenient as setting an envvar.

@antonysouthworth-halter Not sure if you still need it, but a simple solution for you could be to always specify the disable parameter with a environment variable when you initialize a tqdm progress bar. The value for the disable parameter you could still take out from the runtime environment (e.g. Python's built in os module with `os.getenv()`). For default, it can be set to True in an environment file. To display the progress bars globally, you can set the value to False as developer.

It will be pretty much as convenient and as easy to use as your desired feature :)

**Comment by chaoyifei** [comment]
How can i get progress data when disable=True

**Comment by casperdcl** [comment]
Thanks everyone for your patience! Just released [`tqdm==4.66.0`](https://github.com/tqdm/tqdm/releases/tag/v4.66.0) which includes support for env var overrides. I'm using `TQDM_MININTERVAL=5` in most of my CI jobs now :)

**Comment by hughesadam87** [comment]
> @fromm1990 thanks for that! Even after a good hunt I didn't see that one before.
> 
> It seems `disable=None` would basically do what I want for a single call to `tqdm()`. The thing there is that it won't work for an entire project (unless I also missed the docs that allow you to set the default value for `disable` globally....).
> 
> Still good to know that it's at least kinda possible, just not as convenient as setting an envvar.

FWIW - tqdm is a deep depenency in a stack we are using and we aren't explicitly calling it so can't access the `disable=True`, yet it's very spammy.  Why doesn't `export TQDM_DISABLE=1` fix this?

**Comment by 0x26res** [comment]
> Why doesn't export TQDM_DISABLE=1 fix this?

It works for me. Which version of tqdm are you using?
