### ISSUE TITLE
`tqdm` incompatible with ipywidgets v8.0

### ISSUE THREAD

**Issue by redeboer** [tqdm/tqdm#1364]
It seems that `tqdm` is incompatble with the new release of [ipywidgets v8.0](https://ipywidgets.readthedocs.io/en/8.0.1/changelog.html): with that version, the progress bar is rendered as JSON.

### How to reproduce

Using Python 3.8.13:

```shell
python3 -m pip install ipywidgets==8.0.1 jupyterlab==3.4.5 tqdm==4.64.0
```

Then run the following in a Jupyter notebook:

```python
import time
from tqdm.auto import tqdm

for i in tqdm(range(3)):
    time.sleep(1)
```

| `ipywidgets==7.7.2` | `ipywidgets==8.0.1` |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/29308176/188162468-72e73855-6ab6-4a64-8694-9ed7c830bbe9.png)  | ![image](https://user-images.githubusercontent.com/29308176/188160662-c95294ac-6966-4431-82e8-00c733fb7b1f.png) |

**Comment by casperdcl** [comment]
duplicate of #1310; should be fixed soon by #1366 in `tqdm>=4.64.1`
