### ISSUE TITLE
No module named 'docopt'

### ISSUE THREAD

**Issue by horida** [tqdm/tqdm#141]
Looks like the dependency on docopt is missing in 4.4.0

**Comment by casperdcl** [comment]
Wasn't too sure if I should add it since it's only needed for module/CLI
execution.

**Comment by r-darwish** [comment]
@casperdcl that's correct. However, `_main.py` is imported by `__init__.py` so essentially it makes `docopt` a dependency. I suggest not to import `_main.py` by `__init__.py`, as the users of the library probably don't need the CLI.

**Comment by casperdcl** [comment]
Thanks, I didn't realise it was in there.

**Comment by casperdcl** [comment]
I think I've found a way around [dependency hell](https://mail.python.org/pipermail/python-list/2014-November/681597.html) without breaking syntax `from tqdm import main` but allowing `from tqdm import ...` without requiring `docopt`.

An `ImportError` will now be raised only when attempting to run `main` when `docopt` doesn't exist.

**Comment by BoltzmannBrain** [comment]
@casperdcl was this fixed?

**Comment by casperdcl** [comment]
Yes, it's in master and going to be in 4.4.1

**Comment by BoltzmannBrain** [comment]
Great thanks!
