### ISSUE TITLE
Cannot reset if total was initialized as 0 (zero)

### ISSUE THREAD

**Issue by fireattack** [tqdm/tqdm#1433]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable: 4.64.1 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] win32

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=

When a tqdm object is initialized with total=0, there reset(total={a number}) no longer works.

STR:

```py
from tqdm import tqdm
import time


bar = tqdm(total=0)

def upload_chunk(chunk_no, chunks):
    size = 1024*1024*5
    if bar:
        bar.desc = f'chunk {chunk_no + 1}/{chunks}'
        bar.reset(total=size)
    def gen():
        offset = 0
        while True:
            if offset < size:
                update_chunk = 1024*1000
                time.sleep(0.1)
                yield 'a'
                offset += update_chunk
                if bar:
                    bar.update(update_chunk)
            else:
                break
    _ = list(gen())

upload_chunk(0, 100)
bar.close()
print('Done!')
```

**Comment by dargudear** [comment]
`if bar:` is evaluated to false because of following definition
```
    def __bool__(self):
        if self.total is not None:
            return self.total > 0
```
Instead of checking of bool value of bar check ` if bar is not None` in your code.

**Comment by fireattack** [comment]
Wow, thanks! That explains it. 

My bad for not catching that it never actually reaches `bar.reset`.

Again, thanks for the help.
