### ISSUE TITLE
Provide an option about inv_rate

### ISSUE THREAD

**Issue by ppwwyyxx** [tqdm/tqdm#144]
I notice that when rate is less than 1 unit /s, it will display as [number]s /unit.

Sometimes it may not be a good idea: I need to think about what unit it is to know if I'm getting faster or slower. I'd prefer a simple way like 0.7 unit / s.

Could there be an option for this? Thanks.

**Comment by lrq3000** [comment]
We can add this option in custom bar formatting, would that be ok for you?

**Comment by ppwwyyxx** [comment]
Sure! That would be great.

**Comment by lrq3000** [comment]
Ok I implemented it in the [branch inv-option](https://github.com/tqdm/tqdm/tree/inv-option), please try it and tell me if this fits your need. Here is the sample code to generate the bar with not inversed rate:

```
from tqdm import trange
from time import sleep

for i in trange(10, bar_format="{l_bar}{bar}| {n_fmt}/{total_fmt} [{elapsed}<{remaining}, {rate_noinv_fmt}]"):
    sleep(2)
```

**Comment by ppwwyyxx** [comment]
It's really nice! That's what I needed.

**Comment by lrq3000** [comment]
Ok then it will get merged :) Thank you for the feedback!

2016-05-09 17:09 GMT+02:00 Yuxin Wu <notifications@github.com>:
