### ISSUE TITLE
can't upgrade from pip on Ubuntu 12.04.5 LTS x86_64

### ISSUE THREAD

**Issue by markdaly** [tqdm/tqdm#146]
I'm trying to upgrade tqdm and it seems to be downloading the win32 zip file ...is there something wrong with how it is setup on PyPI? [pip.log](https://github.com/tqdm/tqdm/files/215288/pip.log.txt) and output of install:

```bash
sudo pip install tqdm --upgrade
Downloading/unpacking tqdm
  Downloading tqdm-4.4.0.win32.zip (82Kb): 82Kb downloaded
  Running setup.py egg_info for package tqdm
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/home/mdaly/build/tqdm/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/home/mdaly/build/tqdm/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /home/mdaly/.pip/pip.log
```

I was able to install directly from GitHub with this: `pip install -e git+https://github.com/tqdm/tqdm.git@master#egg=tqdm` but wanted to see if there was something else I was doing wrong.

**Comment by casperdcl** [comment]
Odd. Just removed the offending file(s)...can you try now? (after uninstalling first)?

**Comment by markdaly** [comment]
yes, it worked perfectly, thanks!

**Comment by lrq3000** [comment]
This is not normal at all, the win32 build should not be downloaded on a Linux box. I wonder what is the culprit...
