### ISSUE TITLE
tqdm.update(0) causes DivisionByZeroError when using smoothing

### ISSUE THREAD

**Issue by karanlyons** [tqdm/tqdm#148]
Commit 231a9948aa8e6a2f68260514988590b08a00be18 adds a micro optimization that no longer checks that delta_t is non-zero, and this breaks in cases such as:

```python
from tqdm import tqdm

t = tqdm(total=10)
t.update(0)
```

Reverting this commit fixes the error. The reason one may call `t.update(0)` is to force a repaint of the bar in cases like a change in the description. So it instead may be better to have a repaint method that avoids any calculations related to the progress itself, but only deals with actually printing the bar to the terminal.

**Comment by casperdcl** [comment]
Thanks!

**Comment by casperdcl** [comment]
merged #152

**Comment by lrq3000** [comment]
About repainting, there will be a method `tqdm.refresh()` when #150 gets merged.
