### ISSUE TITLE
img.tqdm.ml links broken

### ISSUE THREAD

**Issue by DFEvans** [tqdm/tqdm#1483]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] visual output bug
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [ ] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=

The README contains several image links that point to https://img.tqdm.ml, e.g. the beautiful "walkthrough" animation: https://img.tqdm.ml/tqdm.gif

At the time of writing, this server is not accessible - I can't even find any current DNS records for it.

Has the server been moved to a different address, and the README needs an update?

**Comment by casperdcl** [comment]
Looks like there's a massive problem with the registrar. Fixed in #1491, thanks :)
