### ISSUE TITLE
please include LICENSE file in the PyPI tarball release

### ISSUE THREAD

**Issue by sandrotosi** [tqdm/tqdm#156]
Hello,
it would really help if you could consider adding the LICENSE file in the released tarballs on PyPI; this will clarify the legal positions of the project.

thanks for considering!

Sandro

**Comment by casperdcl** [comment]
Oops, thanks, was spelled differently in the MANIFEST file so wasn't being picked up. Fixed in laters commit on `master` and will be in the next PyPI release
