### ISSUE TITLE
Work with enumerate() / add tqdm_enumerate() function

### ISSUE THREAD

**Issue by olsgaard** [tqdm/tqdm#157]
Since an `enumerate()` iter doesn't have a length, tqdm doesn't work very well with loops over enumerate(), like so:

    for i, s in tqdm(enumerate(list)):
        do_something()

I don't know if it is possible to make the above work. If not, I propose a `tqdm_enumerate()` function, that works just like `tqdm()`, only that for every iteration it yields an integer count on top of its normal yield, so that

    for i, s in tqdm_enumerate(list):
        do_something()

will work as expected.

Something along the lines of below. 

    def tqdm_enumerate(iter):
        i = 0
        for y in tqdm(iter):
            yield i, y
            i += 1

**Comment by casperdcl** [comment]
Good question; remember having the same problem. Wonderful solution you're
going to love:

``` python
for i in enumerate(tqdm(list)):
    # do things
```

**Comment by olsgaard** [comment]
You are absolutely right, I am going to love that solution. I'm closing this issue.

**Comment by casperdcl** [comment]
Yes, surprisingly I added this longer ago than I expected: commits ee6c3ce9 to d877c1df , back before v2.0.0 was released (`__len__()` method)

**Comment by o11c** [comment]
Note that you *can* call `__reduce__` to get the underlying iterable and call `len` or `__length_hint__` on that.

**Comment by rjurney** [comment]
@casperdcl @olsgaard It isn't clear how your solution actually helps?

**Comment by casperdcl** [comment]
`enumerate` hides iterables' `len` so you should wrap with `tqdm` first since `len` will still be available

**Comment by casperdcl** [comment]
Also you can use the recently added `tqdm.contrib.tenumerate`... and check out [FAQs](https://github.com/tqdm/tqdm#faqs)

**Comment by anican** [comment]
@casperdcl many years later but just wanted to say thanks!!

**Comment by noobying** [comment]
thanks a lot!!
