### ISSUE TITLE
Sys.stdout redirection and tqdm.write()

### ISSUE THREAD

**Issue by lrq3000** [tqdm/tqdm#164]
[Here is a code snippet I did](http://stackoverflow.com/a/37243211/1121352) to redirect `sys.stdout` to `tqdm.write()`:

```
from time import sleep

import contextlib
import sys

from tqdm import tqdm

class DummyFile(object):
  file = None
  def __init__(self, file):
    self.file = file

  def write(self, x):
    # Avoid print() second call (useless \n)
    if len(x.rstrip()) > 0:
        tqdm.write(x, file=self.file)

@contextlib.contextmanager
def nostdout():
    save_stdout = sys.stdout
    sys.stdout = DummyFile(sys.stdout)
    yield
    sys.stdout = save_stdout

def blabla():
  print("Foo blabla")

# tqdm call to sys.stdout must be done BEFORE stdout redirection
# and you need to specify sys.stdout, not sys.stderr (default)
for _ in tqdm(range(3), file=sys.stdout):
    with nostdout():
        blabla()
        sleep(.5)

print('Done!')
```

There are two interesting things here:

1. The anti-mixup strategy does not work here: when redirecting sys.stdout (even after calling tqdm), the write method won't be able to recognize sys.stdout.

2. The redirection must necessarily happen AFTER tqdm is instanciated, else the output will be horrible. That's weird. If for example we save sys.stdout into `old_stdout` and then try to first redirect sys.stdout, then `tqdm(range(3), file=old_stdout)`, it will partially work, but `tqdm` won't be able to detect the stdout ncols!

Should we add this example somewhere in tqdm's documentation? Or try to fix ncols detection when stdout redirection (if possible)?

**Comment by casperdcl** [comment]
"fix ncols detection when stdout redirection" I can do easily; might think
about this...

**Comment by lrq3000** [comment]
@casperdcl here is the canonical example code that redirects sys.stdout and then `tqdm` can't detect `ncols` properly anymore:

```
from time import sleep

import contextlib
import sys

from tqdm import tqdm

class DummyFile(object):
  file = None
  def __init__(self, file):
    self.file = file

  def write(self, x):
    # Avoid print() second call (useless \n)
    if len(x.rstrip()) > 0:
        tqdm.write(x, file=self.file)

def blabla():
  print("Foo blabla")

# tqdm call to sys.stdout must be done BEFORE stdout redirection
# and you need to specify sys.stdout, not sys.stderr (default)
old_stdout = sys.stdout
sys.stdout = DummyFile(sys.stdout)
for _ in tqdm(range(3), file=old_stdout):
    blabla()
    sleep(.5)

print('Done!')
```

Result:
```
Foo blabla     | 0/3 [00:00<?, ?it/s]
Foo blabla     | 1/3 [00:03<00:07,  3.51s/it]
Foo blabla#6   | 2/3 [00:07<00:03,  3.51s/it]
100%|##########| 3/3 [00:10<00:00,  3.50s/it]
Done!
```

The bars are way too small! Clearly `ncols` isn't detected properly because of the bar size and because the `tqdm.refresh()` doesn't properly clear the line (because the `ncols` must be set to default 10 or something like that).

**Comment by lrq3000** [comment]
Ok found the culprit, it can be easily fixed by setting `dynamic_ncols=True`, and it's simply because of [this line of code](https://github.com/tqdm/tqdm/blob/000288b33ab3c05d344d2f238bb51398d2fc141c/tqdm/_tqdm.py#L436):

```
        if ((ncols is None) and (file in (sys.stderr, sys.stdout))) or \
                dynamic_ncols:
```

Of course, since the provided `file` is not `sys.stdout/err` but a wrapper, the condition is not met. Not sure how we can fix that automatically, I think we should just put it in the documentation ("if you want to redirect stdout, specify `file=sys.stdout, dynamic_ncols=True` in `tqdm` ... ").

**Comment by lrq3000** [comment]
Added instructions in PR #171. We could maybe program these helper classes and functions directly into `tqdm`, maybe as a module (`tqdm_redirect`?), but for now this will do.

**Comment by nikhilweee** [comment]
+1 for a built in `tqdm_redirect`! Would be much appreciated!
