### ISSUE TITLE
No Panda support outside of groupby()

### ISSUE THREAD

**Issue by Marotte** [tqdm/tqdm#166]
Showing the progress indicator for Panda Dataframe manipulations seems to require first a .groupby(). What about direct apply? Such as:

    tqdm_pandas(tqdm())
    df = pd.DataFrame(np.random.randint(0, 10, (7, 3)))
    df['atimesb'] = df.progress_apply(lambda x: x[0] * x[2], axis=1)
    print df

Today it raises the error:

    AttributeError: 'DataFrame' object has no attribute 'progress_apply'

**Comment by lrq3000** [comment]
Could you please try this version of `tqdm` and report if it works alright for your use cases?

https://github.com/tqdm/tqdm/archive/pandas_apply.zip

**Comment by Marotte** [comment]
It works beautifully!

**Comment by casperdcl** [comment]
great @Marotte, merged

**Comment by lrq3000** [comment]
Great work Casper, and so fast!

2016-05-26 21:29 GMT+02:00 Casper da Costa-Luis <notifications@github.com>:

**Comment by casperdcl** [comment]
hah feel sort of embarrassed by all this pandas stuff #lrq3000 ... I implemented all of it but use none of it.

**Comment by lrq3000** [comment]
Don't worry, I'm sure others will (and are already) put tqdm_pandas to
great uses ;)

2016-05-26 23:39 GMT+02:00 Casper da Costa-Luis <notifications@github.com>:

**Comment by Marotte** [comment]
That would be me ;-)

Thanks a lot for your efforts, Casper. Even more appreciated as you're not even a user of tqdm_pandas yourself.
