### ISSUE TITLE
tqdm does not work with IPython_4.0, Jupyter_1.0, Python_3.5

### ISSUE THREAD

**Issue by ragesz** [tqdm/tqdm#168]
Dear Developers,

I tried the official example, but no status bar and nothing is displayed when I'm running it:
```
from tqdm import tnrange, tqdm_notebook
from time import sleep

for i in tnrange(10, desc='1st loop'):
    for j in tqdm_notebook(range(100), desc='2nd loop'):
        sleep(0.01)
```
Only the ' * ' is present at " In [*] " (on the left-side of the cell) when the above cell is running.
If I run the below example then a "console-like" status bar appears (it is "console-like" in jupyter, because it has pink background, and it is placed right under my cell; so it's not a native jupyter widget):
```
from tqdm import tqdm
from time import sleep

for i in tqdm(range(1000), desc='1st loop'):
    time.sleep(0.01)
```
It is a limitation or a bug or did I something wrong?

Thank you!

**Comment by lrq3000** [comment]
No something is wrong, this should work with IPython v4/Jupyter v1 as this
is the version I used to do my tests. I will take a look this week-end,
thank's for reporting the bug.

2016-05-23 18:23 GMT+02:00 ragesz <notifications@github.com>:

**Comment by lrq3000** [comment]
I just tested with the same setup as you (Py35, Jupyter 1.0), and it works correctly.

Could you please check if you have `ipywidgets` library installed?

**Comment by lrq3000** [comment]
Also make sure that you have `ipywidgets` v4.0 installed and not any superior version, else you will also need to install `widgetsnbextension`.

If this doesn't fix your issue, could you please look in the console after executing the cell containing the `tqdm_notebook` code and copy/paste here the last 10 lines?

**Comment by ragesz** [comment]
Thank you! `widgetsnbextension` solved this problem. I use Anaconda, and it has `ipywidgets` v4.1.0 and no `widgetsnbextension`, so I had to install it.

**Comment by lrq3000** [comment]
Thank you @ragesz for reporting this. I will report the issue to Anaconda, the maintainers probably didn't see that this new package was required for ipywidgets >= 4.1...
