### ISSUE TITLE
Flaky nosetests plugin to auto rerun perf test?

### ISSUE THREAD

**Issue by lrq3000** [tqdm/tqdm#175]
«[Flaky](https://github.com/box/flaky) is a plugin for nose or py.test that automatically reruns flaky tests.

Ideally, tests reliably pass or fail, but sometimes test fixtures must rely on components that aren't 100% reliable. With flaky, instead of removing those tests or marking them to @skip, they can be automatically retried» using the `@flaky` decorator.

We must check if this can be compatible with Travis (ie, if we rerun the test using flaky, is Travis also happy?), but this could solve our perf test issue.

**Comment by casperdcl** [comment]
looks like they use travis so it must work... I was thinking of implementing a much simpler custom decorator which just retries say 3 times on error.

**Comment by lrq3000** [comment]
Ok if you have an idea to implement retries by ourselves, then I follow :)

The advantage with flaky is that we won't have to deal with bugs or whatever, and it's a plugin for nosetest, so it's easy to make it optional on Travis.

**Comment by lrq3000** [comment]
Ok if you have an idea to implement retries by ourselves, then I follow :)

The advantage with flaky is that we won't have to deal with bugs or whatever, and it's a plugin for nosetest, so it's easy to make it optional for users but required on Travis.

**Comment by casperdcl** [comment]
implemented my own version in #179 ... I haven't checked but I'm guessing flaky does the same.

**Comment by casperdcl** [comment]
#179 merged
