### ISSUE TITLE
Not working when single looping over multiple indices.

### ISSUE THREAD

**Issue by fdeugenio** [tqdm/tqdm#185]
If I have a loop with e.g enumerate, or numpy.nditer or numpy.ndenumerate, the bar is not displayed correctly.
I expected tqdm to create a single progress bar.

**Comment by casperdcl** [comment]
Since things like `enumerate` don't expose a length, instead of:

```
for x in tqdm(enumerate(thing)):
```

you need:

```
for x in enumerate(tqdm(thing)):
```

does this solve your issue?

**Comment by fdeugenio** [comment]
Let's say I have:

data = np.empty(81).reshape(9, 9)

If I enter:

for a, b in tqdm(np.ndenumerate(data)):

     time.sleep(0.05)


I would expect a loop over 81 entries of data.

np.ndenumerate(tqdm(thing))

still does not work [but it's true that enumerate(tqdm(thing)) does work]

**Comment by casperdcl** [comment]
fixed and merged into master
