### ISSUE TITLE
tqdm_notebook fails with IPython 3

### ISSUE THREAD

**Issue by QuLogic** [tqdm/tqdm#187]
Running something simple like:
```python
import tqdm
for i in tqdm.tqdm_notebook(range(1000000)):
    i * 2
```
produces this traceback:
```pytb
NameError                                 Traceback (most recent call last)
<ipython-input-6-207cef0f8cd2> in <module>()
      1 import tqdm
----> 2 for i in tqdm.tqdm_notebook(range(1000000)):
      3     i * 2

~/.local/lib/python3.4/site-packages/tqdm/__init__.py in tqdm_notebook(*args, **kwargs)
     17     """See tqdm._tqdm_notebook.tqdm_notebook for full documentation"""
     18     from ._tqdm_notebook import tqdm_notebook as _tqdm_notebook
---> 19     return _tqdm_notebook(*args, **kwargs)
     20 
     21 

~/.local/lib/python3.4/site-packages/tqdm/_tqdm_notebook.py in __init__(self, *args, **kwargs)
    182         # self.sp('', close=True)
    183         # Replace with IPython progress bar display (with correct total)
--> 184         self.sp = self.status_printer(self.fp, self.total, self.desc)
    185         self.desc = None  # trick to place description before the bar
    186 

~/.local/lib/python3.4/site-packages/tqdm/_tqdm_notebook.py in status_printer(file, total, desc)
    103         # Prepare IPython progress bar
    104         if total:
--> 105             pbar = IntProgress(min=0, max=total)
    106         else:  # No total? Show info style bar with no progress tqdm status
    107             pbar = IntProgress(min=0, max=1)

NameError: name 'IntProgress' is not defined
```
using 4.7.4-a581bbd.

The conditional imports seem a bit confused about versions. The [comments in the first block](https://github.com/tqdm/tqdm/blob/master/tqdm/_tqdm_notebook.py#L22-L42) say `ipywidgets` is IPython 4.x, and `IPython.html.widgets` is 3.x/2.x, but the [second block](https://github.com/tqdm/tqdm/blob/master/tqdm/_tqdm_notebook.py#L44-L52) always imports from `ipywidgets`.

**Comment by lrq3000** [comment]
I'll check it out, thank you for reporting the bug. About the import of ipywidgets, it's normal, it's because all imports are aliased to ipywidgets to uniformize the lines of codes after.

**Comment by QuLogic** [comment]
Aliasing does not appear to apply to imports in either Python version:
```python
$ python
Python 2.7.11 (default, Mar 31 2016, 20:46:51) 
[GCC 5.3.1 20151207 (Red Hat 5.3.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import lxml as lx
>>> from lx import etree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named lx
>>> import lxml.etree

$ python3
Python 3.4.3 (default, Mar 31 2016, 20:42:37) 
[GCC 5.3.1 20151207 (Red Hat 5.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lxml as lx
>>> from lx import etree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'lx'
>>> import lxml.etree
```

**Comment by casperdcl** [comment]
that's interesting. Nobody reported issues when I added this. grrr...

**Comment by lrq3000** [comment]
@casperdcl oops sorry no, mea culpa. I tried with IPython v4 (which works because there's no aliasing), but I didn't try with other versions as I was convinced import aliasing would work in Python.

**Comment by casperdcl** [comment]
merged in #190 - though python needs to make up its mind about warnings...

**Comment by philipsd6** [comment]
I'm still getting this error with the latest from master:
```console
$ pip3 list| grep -e jupyter -e ipy -e tqdm
ipykernel (4.5.0)
ipython (5.1.0)
ipython-genutils (0.1.0)
jupyter-client (4.4.0)
jupyter-core (4.2.0)
tqdm (4.8.4, /home/philipsd6/.local/venvs/tqdm/src/tqdm)
```
```python
>>> import sys
>>> import tqdm
>>> sys.version
'3.5.2 (default, Sep 10 2016, 08:21:44) \n[GCC 5.4.0 20160609]'
>>> tqdm.__version__
'4.8.4-bde013b'
>>> for i in tqdm.tqdm_notebook(range(1000000)):
...     i * 2
```
```pytb
Traceback (most recent call last):
  File "<ipython-input-11-bec7d82c3842>", line 1, in <module>
    for i in tqdm.tqdm_notebook(range(1000000)):
  File "/home/philipsd6/.local/venvs/tqdm/src/tqdm/tqdm/__init__.py", line 19, in tqdm_notebook
    return _tqdm_notebook(*args, **kwargs)
  File "/home/philipsd6/.local/venvs/tqdm/src/tqdm/tqdm/_tqdm_notebook.py", line 178, in __init__
    self.sp = self.status_printer(self.fp, self.total, self.desc)
  File "/home/philipsd6/.local/venvs/tqdm/src/tqdm/tqdm/_tqdm_notebook.py", line 96, in status_printer
    pbar = IntProgress(min=0, max=total)
NameError: name 'IntProgress' is not defined
```

**Comment by casperdcl** [comment]
@philipsd6 I received a notification that you commented here but I can't seem to find your comment. Did you delete it?

**Comment by philipsd6** [comment]
Yup, I was being dumb, so I erased the evidence.

**Comment by casperdcl** [comment]
Oh, ok, great! Feel free @philipsd6 and @QuLogic to :+1: [this comment](https://github.com/vinta/awesome-python/pull/662#issue-160805918)!

**Comment by lrq3000** [comment]
Ah good, because I was already looking on how to fix the issue XD

**Comment by philipsd6** [comment]
Just for reference, I have a notebook that creates Jupyter kernels by setting up a new virtualenv, installing ipykernel, and creating the kernel file. All I was missing was to also install ipywidgets in the venv. See? Dumb. ;)

**Comment by stefanv** [comment]
@philipsd6 The error message when `ipywidgets` is missing is pretty obscure :/  `NameError: name 'IntProgress' is not defined`

**Comment by b3by** [comment]
The error seems to still be there with iPython5!

**Comment by balarsen** [comment]
I certainly get this error still 

Software	Version
Python	3.6.1 64bit [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
IPython	5.3.0
OS	Darwin 15.6.0 x86_64 i386 64bit
matplotlib	2.0.0
numpy	1.11.3
xarray	0.9.1
tqdm	4.11.2
Fri Mar 31 16:47:45 2017 MDT

**Comment by vignesh-m** [comment]
The short answer is to install [ipywidgets](https://github.com/jupyter-widgets/ipywidgets)

**Comment by stevenmanton** [comment]
I'm having the same issue. Installing ipywidgets didn't fix it, unfortunately.

**Comment by caidish** [comment]
I'm having the same issue.In my windows desktop,it works well.However,when I run the same code on Ubuntu,it breaks down.

**Comment by davidsmandrade** [comment]
I've installed ipywidgets too and it not working yet. Obs: I'm running on ubuntu. Thanks!

**Comment by andrewzwicky** [comment]
I tried this and got it to work for me.

https://github.com/jupyter-widgets/ipywidgets/issues/541

`jupyter nbextension enable --py --sys-prefix widgetsnbextension`

Using (irrelevant packages omitted):
ipykernel==4.6.1
ipyparallel==6.0.2
ipython==6.0.0
ipython-genutils==0.2.0
ipywidgets==6.0.0
jupyter-client==5.0.1
jupyter-core==4.3.0
nbconvert==5.1.1
nbformat==4.3.0
notebook==5.0.0
tqdm==4.11.2
widgetsnbextension==2.0.0

**Comment by caidish** [comment]
@andrewzwicky Thanks a lot!It really helps.`jupyter nbextension enable --py --sys-prefix widgetsnbextension`

**Comment by stolsvik** [comment]
Not really sure if this helped or not, but after dozens of attempts, I ran both "install" and "enable". It worked afterwards. One should think the enable performed install, but the output of the two commands was at least different. (Do note that this wasn't exactly a scientific experiment, as I probably had changed dozens of parameters of the system by that time..!)

Anyway: `jupyter nbextension install --py --sys-prefix widgetsnbextension`

**Comment by rodrigoruiz** [comment]
I'm still having the same issue when running on Google Colab.

**Comment by chengs** [comment]
@rodrigoruiz ipywidget is not supported by Google Colab. https://github.com/googlecolab/colabtools/issues/60

**Comment by jcorro2** [comment]
I did this to make it work:

> conda install -c conda-forge ipywidgets
> jupyter nbextension enable --py widgetsnbextension
> jupyter labextension install @jupyter-widgets/jupyterlab-manager
> conda install jupyter

The last command is likely to kill your running kernel. If you are training or just trained a large model, I'd suggest you save it to disk before running the last command so you can recover from where you left.
