### ISSUE TITLE
tqdm work with logging

### ISSUE THREAD

**Issue by combecn** [tqdm/tqdm#193]
I tried "Redirecting writing" samples which works great. While I wants to use logging.info() instead of print under python 2.7, it doesn't work.
Is it possible to redirect logging just like redirect print?

Thanks in advance.

**Comment by combecn** [comment]
I found a solution:

create a new logger handler to let tqdm output messages. This works fine when sub task (compute) doesn't output logging info. How to modify when I need sub task (compute) to output logging info?

```
import logging
import multiprocessing
import time
import colorlog
from tqdm import tqdm

class TqdmHandler(logging.StreamHandler):
    def __init__(self):
        logging.StreamHandler.__init__(self)

    def emit(self, record):
        msg = self.format(record)
        tqdm.write(msg)


def compute(i):
    time.sleep(.5)
    return i**2

if __name__ == "__main__":
    logger = colorlog.getLogger("SQUARE")
    logger.setLevel(logging.DEBUG)
    handler = TqdmHandler()
    handler.setFormatter(colorlog.ColoredFormatter(
        '%(log_color)s%(name)s | %(asctime)s | %(levelname)s | %(message)s',
        datefmt='%Y-%d-%d %H:%M:%S',
        log_colors={
            'DEBUG': 'cyan',
            'INFO': 'white',
            'SUCCESS:': 'green',
            'WARNING': 'yellow',
            'ERROR': 'red',
            'CRITICAL': 'red,bg_white'},))

    logger.addHandler(handler)
    pool = multiprocessing.Pool()
    try:
        for square in tqdm(pool.imap_unordered(compute, range(100)), total=100):
            logger.debug(str(square))

    except KeyboardInterrupt:
        logging.warning("got Ctrl+C")
    finally:
        pool.terminate()
        pool.join()
```

**Comment by lrq3000** [comment]
Hello @combecn, thank you for the example code. I just tried it and it works perfectly well on my computer.

Are you using IDLE by any chance? Else, can you please provide details about what Python version you are using and on what platform (Linux, Windows, Mac)? Also, could you provide a screenshot of the buggy output?

**Comment by lrq3000** [comment]
PS: Would you agree that we reuse your example under MPL license as an official example in our library?

**Comment by lrq3000** [comment]
Ok sorry I didn't get what you meant. Indeed there was a bug in `tqdm` preventing the use of `write()` in a subtask because the subtask would be called before `tqdm` gets instanciated! (because the threads are launched before the parent gets to resume).

So, [I fixed the issue in a branch](https://github.com/tqdm/tqdm/archive/no_instances_write_fix.zip), please download and try it.

Here is the code I used:

```
import logging
import multiprocessing
import time
import colorlog
from tqdm import tqdm

class TqdmHandler(logging.StreamHandler):
    def __init__(self):
        logging.StreamHandler.__init__(self)

    def emit(self, record):
        msg = self.format(record)
        tqdm.write(msg)


def compute(i):
    logger = colorlog.getLogger("SQUARE")
    logger.setLevel(logging.DEBUG)
    handler = TqdmHandler()
    handler.setFormatter(colorlog.ColoredFormatter(
        '%(log_color)s%(name)s | %(asctime)s | %(levelname)s | %(message)s',
        datefmt='%Y-%d-%d %H:%M:%S',
        log_colors={
            'DEBUG': 'cyan',
            'INFO': 'white',
            'SUCCESS:': 'green',
            'WARNING': 'yellow',
            'ERROR': 'red',
            'CRITICAL': 'red,bg_white'},))

    logger.addHandler(handler)
    logger.debug("Inside subtask: "+str(i))
    time.sleep(.5)
    return i**2

if __name__ == "__main__":
    pool = multiprocessing.Pool()
    try:
        for square in tqdm(pool.imap_unordered(compute, range(100)), total=100):
            pass

    finally:
        pool.terminate()
        pool.join()
```

But remember that the output will be gibberish at times, because you are printing inside the subtask, and they are running in threads in parallel, so they can output at the same time and thus intermingle. It's probably cleaner if you keep all your logging inside the for loop as in your first example.

**Comment by combecn** [comment]
Hello @lrq3000 , you can use the sample code with MIT. But actually I copied original code from [stackowerflow ](http://stackoverflow.com/questions/32172763/progress-measuring-with-pythons-multiprocessing-pool-and-map-function) and did some modification. Maybe you can ask there for author's permission.

I'll have a try of your fix and report later.

**Comment by combecn** [comment]
Hello @lrq3000 , the code runs smoothly but I still found some issues:
I added leave = True in tqdm function.

1. sometimes there missed a newline between sub task outputs. logging.debug should always starts from a newline. But in tqdm, some  newlines are missing.
2. sometimes the color of progress bar didn't reset to white.
3. the progress bar still didn't behavior like a continue changing bar. it outputted several bars among hundreds of outputs.


```
SQUARE | 2016-18-18 14:16:29 | DEBUG | Inside subtask: 92
SQUARE | 2016-18-18 14:16:29 | DEBUG | Inside subtask: 92
SQUARE | 2016-18-18 14:16:29 | DEBUG | Inside subtask: 92
SQUARE | 2016-18-18 14:16:29 | DEBUG | Inside subtask: 92
QUARE | 2016-18-18 14:16:29 | DEBUG | Inside subtask: 92 90%|###################
#################9    | 90/100 [00:14<00:01,  7.00it/s]
SQUARE | 2016-18-18 14:16:29 | DEBUG | Inside subtask: 93S
QUARE | 2016-18-18 14:16:29 | DEBUG | Inside subtask: 92S
QUARE | 2016-18-18 14:16:29 | DEBUG | Inside subtask: 93S
QUARE | 2016-18-18 14:16:29 | DEBUG | Inside subtask: 92S
QUARE | 2016-18-18 14:16:29 | DEBUG | Inside subtask: 93S
QUARE | 2016-18-18 14:16:29 | DEBUG | Inside subtask: 92S
QUARE | 2016-18-18 14:16:29 | DEBUG | Inside subtask: 93
SQUARE | 2016-18-18 14:16:29 | DEBUG | Inside subtask: 92SQUARE | 2016-18-18 14:
16:29 | DEBUG | Inside subtask: 93

SQUARE | 2016-18-18 14:16:29 | DEBUG | Inside subtask: 92SQUARE | 2016-18-18 14:
16:29 | DEBUG | Inside subtask: 93

SQUARE | 2016-18-18 14:16:29 | DEBUG | Inside subtask: 92SQUARE | 2016-18-18 14:
16:29 | DEBUG | Inside subtask: 93
```

**Comment by combecn** [comment]
Hello @lrq3000 , I accidentally closed this issue, can you reopen it?

**Comment by lrq3000** [comment]
Hello @combecn, yes I reopened the issue, but the 3 issues you described are all due, I think, to the fact that the logging output is done in the threaded subtask. I guess if you just do a `print("\rSome newline")` without any `tqdm` bar anywhere, you will get the same issues.

**Comment by combecn** [comment]
Hello @lrq3000 , I tired without tqdm. You're right. Many thanks to your help.

**Comment by lrq3000** [comment]
Your are welcome @combecn . Be careful with race conditions!

**Comment by lrq3000** [comment]
(Will close this issue when #196 gets merged)
