### ISSUE TITLE
Useage of delim argument

### ISSUE THREAD

**Issue by dr-costas** [tqdm/tqdm#194]
Hi, 

 Itried to do: 

```python
for i in tqdm(range(100), leave=True, ncols=70, desc='Test asdadas', delim='0'):
    sleep(0.1)
```

But I got: 

````python
tqdm/_tqdm.py, line 427, in __init__
    Warning("Unknown argument(s): " + str(kwargs)))
Warning: Unknown argument(s): {'delim': '0'}
````

**Comment by casperdcl** [comment]
delim is only for command line usage, not on python scripts!

**Comment by lrq3000** [comment]
What was your goal when you tried to use `delim`? Was it just to try it out or did you had a particular goal to accomplish in mind?

**Comment by lrq3000** [comment]
Closing it now, but feel free to reopen if you have any question!
