### ISSUE TITLE
Release new version to pypi

### ISSUE THREAD

**Issue by hadim** [tqdm/tqdm#2]
We should release a new version to Pypi once some features are added.

We also need to ask a Pypi administrator the permissions to upload the package to https://pypi.python.org/pypi/tqdm

**Comment by hadim** [comment]
You can follow the discussion with pypi admins here : https://sourceforge.net/p/pypi/support-requests/507/

**Comment by hadim** [comment]
Let's wait some weeks before changing the name of the project.

**Comment by casperdcl** [comment]
I quite liked the current package name. It's short and meaningful (like the implementation!) and has thousands (maybe more?) of users. Maybe worth mentioning on the sourceforge ticket - it's been actively developed and has a bunch of users. Changing the project name would be weird.

**Comment by hadim** [comment]
I agree with you but in my opinion it's very important to have a pypi access.... So let's wait and see what pypi admin say :-)

**Comment by walkerdb** [comment]
The name is short, but it's far from semantic - it's impossible to know what it does just by looking at it. I'd be in favor of changing it. (might be moot anyway due to the pypi situation).

**Comment by hadim** [comment]
If we can keep it, I will be in favor of that because `tqdm` starts to be known. I actually discover it after reading various tutorial on french blog. 

What's the opinion of the others?

**Comment by casperdcl** [comment]
Well I never knew any arabic but I found it cool that it was a nice short
abbreviation for something. It's true that it may be hard to pick up,
though. probar, trackbar, pmeter are all free on pypi.

**Comment by flying-sheep** [comment]
you can see [here](http://sourceforge.net/p/pypi/support-requests/search/?q=status%3Awont-fix+or+status%3Aclosed) that they haven’t closed a support request since may…

**Comment by casperdcl** [comment]
Yeah I actually contacted the main maintenance dev who responded with apologetic expletives, with a promise to attend to things over the weekend... This was over a month ago. I don't know if/when anything will be updated.

**Comment by hadim** [comment]
They are very slow. I remember sometime ago I contacted them via sourceforge for the same kind of request and it took 2-3 months before they take care of it... Pypi support is not well maintened but I guess  it is because it's done only by volunteers... and there is a lot of requests.

My idea was to wait until the end of the summer and wait until september-october. If we still don't have answer, then we switch name.

Are you ok with this ?

**Comment by lrq3000** [comment]
I am ok because the project should be released anyway to PyPi. But I still hope for them to answer the request...

**Comment by hadim** [comment]
Still no answer from PyPi developers... except if someone here know how to reach PyPi admins I think we gonna have to make a choice here...

What do you think guys ?

**Comment by lrq3000** [comment]
I agree, we should change the name of the project. I don't expect the PyPi admins to answer anymore, since the big holidays ended since more than a month, and there's still no even a hint of a reply from them (in addition, I tried to look for a mailing list, and it seems that it's not in use since 2013, so that's really not a good sign).

**Comment by lrq3000** [comment]
If you want to still keep a relationship with tqdm, then we can just make up a name with tqdm + something, this way, google searches on tqdm will still probably be able to reach this project.

**Comment by casperdcl** [comment]
:+1: for something like `pbar-tqdm` as a package name

**Comment by lrq3000** [comment]
pbar for progressbar? Then why not just call it "progressbar-tqdm" ? This would be even better for search engines and more evocative for potential users

**Comment by hadim** [comment]
I think the best way to do it is keep this repo, empty it and put a message in the README saying that the project has been moved to another repo.

If others agree, this is the way I think we should do it : 

- [ ] find a name
- [ ] create the organization
- [ ] create the repo
- [ ] move the code to the new repo
- [ ] move all issues and PR to the new repo (I am sure there is some scripts that can take care of this)
- [ ] and finally we can release it on pypi !!!

**Comment by hadim** [comment]
I don't like xxx-tqdm, I think we should not worry to much about SEO. People will end up here and then follow our message saying we have moved.

**Comment by hadim** [comment]
I really like a short name such as `pbar`

**Comment by hadim** [comment]
I will open a new issue

**Comment by hadim** [comment]
Please see #30.
