### ISSUE TITLE
nest progress bars spams the console on windows

### ISSUE THREAD

**Issue by theiviaxx** [tqdm/tqdm#200]
Using python 2.7.3 x64 on windows 7
From the readme:

    from tqdm import trange
    from time import sleep

    for i in trange(10, desc='1st loop'):
        for j in trange(5, desc='2nd loop', leave=False):
            for k in trange(100, desc='3nd loop'):
                sleep(0.01)

will just print each new thing on a new line:

    1st loop:   0%|                                         | 0/10 [00:00<?, ?it/s]
    2nd loop:   0%|                                          | 0/5 [00:00<?, ?it/s]

    3nd loop:   0%|                                        | 0/100 [00:00<?, ?it/s]

    3nd loop:  11%|###3                          | 11/100 [00:00<00:00, 100.00it/s]

    3nd loop:  22%|######6                       | 22/100 [00:00<00:00, 100.00it/s]

    3nd loop:  33%|#########9                    | 33/100 [00:00<00:00, 100.00it/s]

    3nd loop:  43%|############9                 | 43/100 [00:00<00:00, 100.00it/s]

    3nd loop:  54%|################2             | 54/100 [00:00<00:00, 100.00it/s]

    3nd loop:  64%|###################2          | 64/100 [00:00<00:00, 100.00it/s]

    3nd loop:  75%|######################5       | 75/100 [00:00<00:00, 100.00it/s]

    3nd loop:  86%|#########################8    | 86/100 [00:00<00:00, 100.00it/s]

    3nd loop:  97%|#############################1| 97/100 [00:00<00:00, 100.00it/s]

    3nd loop: 100%|#############################| 100/100 [00:01<00:00, 100.00it/s]
    2nd loop:  20%|######8                           | 1/5 [00:01<00:04,  1.00it/s]

    3nd loop:   0%|                                        | 0/100 [00:00<?, ?it/s]

    3nd loop:  10%|###                           | 10/100 [00:00<00:00, 100.00it/s]

    3nd loop:  21%|######3                       | 21/100 [00:00<00:00, 100.00it/s]

    3nd loop:  31%|#########6                     | 31/100 [00:00<00:00, 99.70it/s]

    3nd loop:  41%|############7                  | 41/100 [00:00<00:00, 99.49it/s]

    3nd loop:  51%|###############8               | 51/100 [00:00<00:00, 99.35it/s]

    3nd loop:  61%|##################9            | 61/100 [00:00<00:00, 99.54it/s]

    3nd loop:  71%|######################         | 71/100 [00:00<00:00, 99.38it/s]

    3nd loop:  81%|#########################1     | 81/100 [00:00<00:00, 99.27it/s]

    3nd loop:  91%|############################2  | 91/100 [00:00<00:00, 99.19it/s]

    3nd loop: 100%|##############################| 100/100 [00:01<00:00, 99.30it/s]
    2nd loop:  40%|#############6                    | 2/5 [00:02<00:03,  1.00s/it]

    3nd loop:   0%|                                        | 0/100 [00:00<?, ?it/s]

    3nd loop:  10%|###                           | 10/100 [00:00<00:00, 100.00it/s]

    3nd loop:  21%|######3                       | 21/100 [00:00<00:00, 100.00it/s]

    3nd loop:  31%|#########6                     | 31/100 [00:00<00:00, 99.70it/s]

Did i miss something or use it incorrectly?

**Comment by lrq3000** [comment]
Hey Brett, did you install the latest version of [colorama](https://github.com/tartley/colorama)?

**Comment by theiviaxx** [comment]
I didn't have colorama at all, after installing colorama, tqdm works as expected.  I guess it wasn't clear that it was required for nested display.
Thanks for the help

**Comment by casperdcl** [comment]
Hi Brett, no worries, I think we're overdue a "known issues" and a "common
issues" section in the readme. Also the words "don't panic" in large,
friendly letters. ;)

**Comment by lrq3000** [comment]
Actually, it's not technically necessary because the nested display still
works (you can see each bar of each level, they are refreshed when they get
updated), but the display is just horrible without colorama (at least on
Windows, it's not necessary on Unix-like platforms).

2016-07-20 21:47 GMT+02:00 Casper da Costa-Luis <notifications@github.com>:

> Hi Brett, no worries, I think we're overdue a "known issues" and a "common
> issues" section in the readme. Also the words "don't panic" in large,
> friendly letters. ;)
>

**Comment by blackgis** [comment]
Still the unexpected behavior exists!! although i got colorama. Is there any other lib i need?

**Comment by lrq3000** [comment]
@blackgis No, other libraries exist but we only use colorama. What OS and Python distribution do you use?

**Comment by lrq3000** [comment]
Also you can try to update to the latest colorama version available on github, this sometimes fix the issues, the colorama team is super responsive and on the edge to fix as issues come along (particularly with newer versions of Windows): https://github.com/tartley/colorama
