### ISSUE TITLE
? for buttons

### ISSUE THREAD

**Issue by CrazyPython** [tqdm/tqdm#204]
Image: http://imgur.com/a/Dv7pb

Spotted on Safari, Mac OS X.

**Comment by lrq3000** [comment]
Yeah I noticed it too since yesterday. The badges are relying on external webservices, so it seems one of those is currently down. We should wait a bit to see if it comes back online, if not, we will try to find an alternative.

**Comment by casperdcl** [comment]
seems fine now. those badges were all pypi ones. would've hoped they could be more reliable.
