### ISSUE TITLE
New string formatting speed issues

### ISSUE THREAD

**Issue by lrq3000** [tqdm/tqdm#21]
Hi there,

I noted that the previous string formatting, like:

    '%5.2f' % (n / elapsed)

Was systematically changed to:

    '{0:5.2f}'.format(float(n) / elapsed)

However, this is about 2x slower than the old string formatting. Is there any reason to keep using the new formatting style?

**Comment by hadim** [comment]
Could you please provide a small banchmark so we can test and compare ?

**Comment by lrq3000** [comment]
Yes, the following in ipython:

    from __future__ import division, absolute_import
    n = 10
    elapsed = 3
    %timeit '{0:5.2f}'.format(n / elapsed)
    %timeit '%5.2f' % (n / elapsed)

Result:

    100000 loops, best of 3: 2.31 µs per loop
    1000000 loops, best of 3: 761 ns per loop

I can try changing in tqdm directly and we could then benchmark it in situ.

**Comment by casperdcl** [comment]
O.o interesting that the new and recommended formatting style is significantly slower. I can confirm a factor of 2 difference on my machine, too. I had originally changed everything without realising - sorry.

In terms of overall performance impact:

```{python}
from tqdm import trange
def test():
  for i in trange(100000):
    a=[1]*100000
%timeit -n1 -r1 test
```

Has no measurable effect. I'm getting ~850ms regardless of whether the new or old formatting conventions are used. Perhaps bytecode-compiled it's more efficient? This is nowhere near the bottleneck. Up to you if you still think it needs changing.

**Comment by casperdcl** [comment]
Further clarification: after some rather more strenuous testing/profiling I can confirm that there is a slight measurable effect. However, the main bottleneck is still calls to `time.time` (I did my best to reduce these with "clever" dynamic values for `miniters`/`mininterval`). An order of magnitude less of a bottleneck is the `format_meter` function.

I don't think it's worth reverting - the current implementation is a lot easier to read and extend. It is recommended formatting after all.

**Comment by lrq3000** [comment]
Ok, good for me, thank you very much for having benchmarked that :)

2015-07-13 12:29 GMT+02:00 Casper da Costa-Luis <notifications@github.com>:
