### ISSUE TITLE
Pandas series.map

### ISSUE THREAD

**Issue by josepablog** [tqdm/tqdm#214]
Hello,

I just learned about this project.  Very cool.   Although this [site](http://jgardiner.co.uk/blog/jupyter_progress_bar) says it is not possible to use TQDM to track the progress of  `map` in a `Series` object, I don't want to give up!

Is there any way of mapping the progress of a mapping operation?

Thanks,
JPG

**Comment by casperdcl** [comment]
very likely possible (haven't looked at site yet). please do let me know of
there are any other pandas things which you've seen other progress output
for but not supported in tqdm yet. it's likely just a matter of two lines
of missing code from me. ;)

**Comment by casperdcl** [comment]
@JamesGardiner, please feel free to comment here (or open a new issue for other suggestions)!

regarding your blog post (liked above) we *do* now support series, dataframes, as well as grouped versions of both - all thanks to someone asking for them. I don't use pandas myself so won't know about any of this stuff until someone such as yourself asks me to look into it! Let's see if I can add map support in the next few minutes...

**Comment by JamesGardiner** [comment]
Thanks for the heads up @casperdcl, and for adding this functionality. I'll make an amendment to the blog to point this out. And if I hit other suggestions, I'll be sure to open an issue.
