### ISSUE TITLE
Interactive docstring in GIF example?

### ISSUE THREAD

**Issue by cfperez** [tqdm/tqdm#216]
@casperdcl Unrelated to tqdm (which is great btw): I really want that interactive docstring display in the shell that is show in the example, but can't find it anywhere. How do you do it?

**Comment by casperdcl** [comment]
`bpython-curses` though `ptpython` might be better for you if you're on
Linux ;)

**Comment by cfperez** [comment]
Thanks!

**Comment by lrq3000** [comment]
Maybe we should add this to the documentation since so many people are displaying a great interest!
