### ISSUE TITLE
Provide a parameter to control rate/inv_rate behaviour

### ISSUE THREAD

**Issue by Abrackadabra** [tqdm/tqdm#218]
It'd be cool to have a consistent way to compare loops with rates both less and greater than 1. Right now if the rate is rarer than once per second, inverse rate is automatically displayed with no way to control this functionality. Something like `bool auto_inverse_rate` will do. Or even `func format_rate` to provide complete control over it.

**Comment by lrq3000** [comment]
Hello @Abrackadabra,

We had a similar request in the past, and so it's already implemented :) You can provide a special argument `rate_noinv_format` to the `bar_format` argument (which allows you to provide a custom template for the `tqdm` bar):

```
from tqdm import trange
from time import sleep

for i in trange(10, bar_format="{l_bar}{bar}| {n_fmt}/{total_fmt} [{elapsed}<{remaining}, {rate_noinv_fmt}]"):
    sleep(2)
```

For more info, please refer to #144. Tell us if this fits your request :)
