### ISSUE TITLE
Completed nested/parallel bars printing when leave=True

### ISSUE THREAD

**Issue by o11c** [tqdm/tqdm#230]
If your program only ever uses a single  `tqdm` instance at a time, then `leave=True` is great - you get a neat history of every bit of progress you've ever made.

However, if you use _multiple_ `tqdm` instances, things don't work so well. Particularly, the remains of old, completed `tqdm` instances will be _below_ the new active ones.

Solution for the simple case: when you create a new `tqdm` instance, clear out all the old rows below it (you do not want to do this earlier, because you _do_ want to display the 100% until the next one is ready). Remember that the creator of the `tqdm` instances does not necessarily _know_ about other pieces of code that create instances, so it has to be done in the library - nobody knows what to `.clear()`

However, this is not all that's needed for more advanced cases where bars may complete in any order - for example, I want to do a current-and-past parallel download presentation like `aptitude` does - essentially, every completed `tqdm` should be moved _above_ all active `tqdm`s (which then need to all be redrawn), and then forgotten.

**Comment by lrq3000** [comment]
Good idea, this can be done. So on `close()` if `leave=True`, the bar should be printed at position 0, then line return, then refresh all other bars. This would incur a big display cost at each bar end compared to current implementation, but the better display is worth it, then it can be done I think.

**Comment by o11c** [comment]
If you use the insert-line (CSI L) and delete-line (CSI M) escapes, you don't actually have to redraw everything ...

(vttest: 11.3.3.11)

**Comment by lrq3000** [comment]
Nice @o11c :

> CSI Pn L: Insert Pn lines before current line, scroll current line down.
> CSI Pn M: Delete Pn lines from current line downward, do not scroll
From [this page](http://webcache.googleusercontent.com/search?q=cache:04lkkfOs_aYJ:courseweb.stthomas.edu/tpsturm/private/notes/qm300/ANSI.html+&cd=1&hl=fr&ct=clnk&gl=us).

But I fear that it won't be supported by all environments. First we need to check if `colorama` supports it, and then we have to ponder whether using more control codes is worth the additional burden. But anyway, it will about the same to support either approach (redraw everything or by using insert-line and delete-line), it's just a few lines of code that will change.

**Comment by lrq3000** [comment]
So to summary, here is what we can do:

* On bar close/completion, if leave=True:
    * move to position 0
    * draw current bar completed display
    * move to next line (this is the new position 0)
    * refresh display of other bars
* if leave=False, do current behavior (just clear the line)

This will work but it violates your proposition that a completed bar should stay in place until another one to replace it is created. This is not possible with current design because `tqdm` removes a bar from the pool as soon as it gets completed.

**Comment by lrq3000** [comment]
@o11c Please tell us if you think the summary is good and could fulfill your proposition. If so, it could be implemented quite fast (if there's no tricky issues I didn't foresee XD).

**Comment by skycaptain** [comment]
@lrq3000: Any news? I'm working on a project that involves nested process bars. Using the following code, I'm getting a very ugly printout:

```python
with tqdm(total=100) as pbar:
    for i in range(10):
        with tqdm(total=100, leave=True) as pbar2:
            for i2 in range(10):
                pbar2.update(10)
        pbar.update(10)
    
print("foo")
```

```sh
100%|██████████████████████████████████████| 100/100 [00:00<00:00, 72315.59it/s]
foo%|████████████████████████████████████| 100/100 [00:00<00:00, 2330168.89it/s]
```

**Comment by casperdcl** [comment]
@skycaptain you could just do: `nested pars = 1; print("\n" * nested_bars)` before you `print("foo")`

**Comment by skycaptain** [comment]
@casperdcl This is what I'm doing for now.

**Comment by casperdcl** [comment]
Not sure if we can do better @skycaptain. @lrq3000 we'd have to change to `leave=None` and then `if leave is None: leave = pos==0`

**Comment by toddlipcon** [comment]
I ran into the same issue and found something like the following works pretty well to clean up the output.

[issue-230.txt](https://github.com/tqdm/tqdm/files/3150965/issue-230.txt)

With your example script modified to leave="output", I get the following output:

100%|██████████| 100/100 [00:00<00:00, 6260155.22it/s]
100%|██████████| 100/100 [00:00<00:00, 6657625.40it/s]
100%|██████████| 100/100 [00:00<00:00, 6657625.40it/s]
100%|██████████| 100/100 [00:00<00:00, 7108989.83it/s]
100%|██████████| 100/100 [00:00<00:00, 7108989.83it/s]
100%|██████████| 100/100 [00:00<00:00, 7108989.83it/s]
100%|██████████| 100/100 [00:00<00:00, 7231558.62it/s]
100%|██████████| 100/100 [00:00<00:00, 7231558.62it/s]
100%|██████████| 100/100 [00:00<00:00, 7626007.27it/s]
100%|██████████| 100/100 [00:00<00:00, 7767229.63it/s]
100%|██████████| 100/100 [00:00<00:00, 32734.75it/s]
foo

which seems preferable
