### ISSUE TITLE
tqdm_auto to auto detect submodule to use depending on frontend

### ISSUE THREAD

**Issue by lrq3000** [tqdm/tqdm#234]
Maybe we can make a `tqdm_auto` submodule which would try to autodetect the frontend env and provide the most appropriate module, eg:
- tqdm_notebook for [IPython notebook](http://stackoverflow.com/questions/15411967/how-can-i-check-if-code-is-executed-in-the-ipython-notebook).
- tqdm_gui for IDEs not supporting `\r` control character such as [IDLE](http://stackoverflow.com/questions/17133769/find-out-if-a-python-script-is-running-in-idle-or-terminal-command-prompt/17135271#17135271) and PyCharm.
- core tqdm for the rest.

The proposition is interesting because it would fix three issues:
- Some users are targetting multiple envs, currently they have to fix this by themselves.
- Some IDEs do not support the required control characters, so there's no way to fix core tqdm display issues. But by providing a `tqdm_auto` wrapper, users could just use that in most instances and get a correctly displayed progress bar.
- With tqdm being more and more included in various libraries, the risk that these libraries get used in various development environment increases and thus the usage of tqdm. In these instances, tqdm should be resilient enough to ensure that it's not the breaking point for a library (it must not prevent the usage of a library in any env).

What do you think about it guys?

**Comment by thehesiod** [comment]
it seems in PyCharm 2016.3.2 using one progressbar works ok, but if you add multiple progress bars it breaks down.  Not sure if this is a bug in PyCharm's terminal or tqdm

**Comment by lrq3000** [comment]
See #372 for auto detection between commandline and notebook (thanks to @flying-sheep!).

**Comment by lrq3000** [comment]
@thehesiod yes that's a known issue of IDLE/PyCharm, we can't do anything about it. Hence why this feature request, it will open a GUI to handle multiple bars in IDLE/PyCharm.

**Comment by flying-sheep** [comment]
another alternative would be to horizontally tile progress bars, so one `\r` still clears everything, or using pager mode in case those limited terminal emulators support clearing the screen or positioning the cursor there.

**Comment by lrq3000** [comment]
Yes but then we would quickly run out of space and the bars will be forced
to have a newline return, so with this technique we would only have max 2/3
simultaneous bars :-/

2017-04-11 15:58 GMT+02:00 Philipp A. <notifications@github.com>:

**Comment by mlubej** [comment]
Hello!

Any news on this? :D

**Comment by flying-sheep** [comment]
there’s no other options besides waiting for intellij to fix their terminal

**Comment by mlubej** [comment]
> there’s no other options besides waiting for intellij to fix their terminal

Sorry, I accidentally deleted the comment.

I did notice, however, the following use of tqdm

```
from tqdm.autonotebook import tqdm
from tqdm.auto import tqdm
````

Both do exactly what is requested. The first one produces a warning in the notebook, while in the second case the warning is suppressed.

Found [here](https://pypi.org/project/tqdm/#ipython-jupyter-integration), just before the next section

**Comment by casperdcl** [comment]
I think this can be closed since `tqdm.autonotebook` will automatically choose between `tqdm.tqdm` and `tqdm.notebook` with a warning. `tqdm.auto` will automatically choose from all backends (for now that's just the above two, another issue can be opened regarding supporting more)

**Comment by StanczakDominik** [comment]
This one can definitely be closed, `tqdm.auto` is absolutely wonderful.
