### ISSUE TITLE
make tqdm a class

### ISSUE THREAD

**Issue by flying-sheep** [tqdm/tqdm#24]
And all parameters fields of that class.

This way, we can do

```py
t = tqdm(foo)
for elem in t:
	do_stuff(elem)
	if condition:
		t.desc = 'floob'
```

**Comment by hadim** [comment]
I'd like the idea. Want to make a PR ?

**Comment by casperdcl** [comment]
Already pulled the code to a branch on this repo and started fixing it. I think it works but I haven't had time to fully test it yet.

**Comment by casperdcl** [comment]
Sorryy i mean see #22

**Comment by casperdcl** [comment]
Ah sorry about this - completely forgot. Going to look into this issue now. The branch I had been working on was https://github.com/tqdm/tqdm/tree/flexibility-tweaks
