### ISSUE TITLE
Abstraction layers + tqdm ports

### ISSUE THREAD

**Issue by CrazyPython** [tqdm/tqdm#241]
*tl;dr* basically we can write tqdm ports using stuff like Jython and R integration

Rewriting tqdm for an entirely new language is hard. But we can port tqdm to e.g. Java and R much more easily with stuff like Jython and R's built in Pythonintegration.

Jython layout:

tqdm python (stripped down without unportable features)
↓
Jython
↓
Small Java tqdm handler to make the API simpler

This may be slower, but it's better than nothing and much easier than rewriting the entirety of tqdm. It also lets us do this:

💻 📈🌏😈

**Comment by lrq3000** [comment]
CrazyPython it's great that you are involved with tqdm, but please try to avoid the creation of too many issues, it's beginning to be more than what we can handle in a reasonable timeframe :/ So please merge information that are on the same subject, like with #235!

**Comment by CrazyPython** [comment]
@lrq3000 Okay, yeah it was getting to that point :/

**Comment by lrq3000** [comment]
Thank's for reposting the info in #235 :)

**Comment by CrazyPython** [comment]
@lrq3000 *Meanwhile on some remote island in the middle of the ocean...*

```
IssueDDoS 1.0 has encountered an error: TooManyRequests. Increasing delay between requests.
```
