### ISSUE TITLE
tqdm wrapper on requests library

### ISSUE THREAD

**Issue by CrazyPython** [tqdm/tqdm#242]
This is a common tqdm usage, might be useful to adapt some code used by others to download stuff with tqdm into tqdm.

**Comment by lrq3000** [comment]
Either monkey-patch or at least add a code snippet in the readme, below the urllib code snippet, would be nice indeed.

**Comment by casperdcl** [comment]
https://stackoverflow.com/questions/15644964/python-progress-bar-and-downloads
