### ISSUE TITLE
Customised step size per iteration

### ISSUE THREAD

**Issue by ferrouswheel** [tqdm/tqdm#265]
When I first used tqdm with `tqdm(range(0,1000,10))` I was half expecting for it to automatically detect that the iterator increases by 10 every iteration, counting from 0 to 1000. Instead it counts to 100.

While it'd be great to infer this from the wrapped iterator, being able to give a hint about the start/end and step size would also work.

**Comment by CrazyPython** [comment]
This functionality already exists.

**Comment by ferrouswheel** [comment]
Ah sorry. I couldn't find it by examples, documentation, or a quick look at
the code. Care to point me in the right direction?

**Comment by CrazyPython** [comment]
@ferrouswheel use the source! it's a fairly obvious keyword variable.

**Comment by CrazyPython** [comment]
manual `.update()` is also supported:

```python
import tqdm
bar = tqdm.tqdm(total=somenumber)
for blah in blahblah:
    bar.update(x)  # x = step amount
```

**Comment by CrazyPython** [comment]
@ferrouswheel `total` should be it

**Comment by ferrouswheel** [comment]
Thanks! I think my confusion is in the wording, "number of expected iterations". Since my iteration count (number of loops) would be different to the total value that tqdm counts up to. I also didn't understanding that I could update tqdm directly with an arbitary value, but that's probably me reading the docs a little too quickly.

**Comment by lrq3000** [comment]
In fact, `trange` bases its automatic calculation of `total` based on what `len()` is returned by `range()`. In your case, the `len`, or the number of loop iterations, is indeed 100 because you have a stepsize of 10 for 1000.

In `trange()`, we could use what is returned by the iterator to update `self.n`, but we still won't be able to know what is the original total since it is not returned by `range()` (only the concrete number of loop iterations is returned by `len(range(0, 1000, 10))`, which is 100, not the total 1000).

**Comment by ferrouswheel** [comment]
@lrq3000 I thought maybe a keyword argument to `trange` might be a nice way to tell it the `total`, and then the update step would be `total/len(range(..)`.

**Comment by CrazyPython** [comment]
@lrq3000 well, you could just parse the arguments passed to trange... I mean they're right there.

**Comment by lrq3000** [comment]
Nope we don't have neither the real total neither the stepsize, that's what
I've been trying to explain. But Joel's suggestion might be feasible, I'll
have a look.

2016-09-13 22:55 GMT+02:00 CrazyPython <notifications@github.com>:

**Comment by CrazyPython** [comment]
@lrq3000 really? it's right damn there...
```
    class trange(tqdm):
        def __init__(*args, **kwargs):
            ...

```

to 

```

    class trange(tqdm):
        def __init__(self, start, arg2, arg3=None):
            if arg3 is None:
                stepsize = 1
                end = arg2
            else:
                stepsize = arg2
                end = arg3

            ...

```

**Comment by lrq3000** [comment]
Ah ok yes you're right CrazyPython, it's just that trange is a simple
wrapper around tqdm, so all calculations are done in tqdm.

Doing calculations inside trange would change quite a few things, such as
inheritance (all submodules inherit from tqdm, not trange, so any
calculation in trange won't be reproduced in submodules).

Maybe we could use mixins as you suggested somewhere to fix this issue,
we'll have to dig into that.

2016-09-14 2:24 GMT+02:00 CrazyPython <notifications@github.com>:

**Comment by CrazyPython** [comment]
@lrq3000 trange can be a MixIn that is instantiable itself. It goes with the philosophy of tqdm: to keep things as simple as possible

**Comment by lrq3000** [comment]
See #273 and tell me if it fulfills your request.

**Comment by CrazyPython** [comment]
Appears so.

**Comment by trianxy** [comment]
This works for me and counts from 1 to 200:
```
for i in tqdm(range(0, 2000, 10), unit_divisor=True):

    pass
```

**Comment by usstq** [comment]
in this case, `tqdm` should be used as a pure `gui` w/o being coupled with `iterable`.

```python
pbar = tqdm(total=1000)
for i0 in range(start, stop, step):
    i1 = min(i0+step, stop)
    pbar.n = i1
    pbar.refresh()
```
