### ISSUE TITLE
Use file=None not file=sys.stderr in the constructor

### ISSUE THREAD

**Issue by DavidEscott** [tqdm/tqdm#275]
This is in the family of def(foo=[]) type issues. Since you have file=sys.stderr in your **init**, I cannot change sys.stderr after importing tqdm and expect it to work correctly.

file=None followed by: file = file or sys.stderr would be preferable.

**Comment by lrq3000** [comment]
You can change after importing, you just have to supply the new sys.stderr as the file argument when you instanciate tqdm.

But indeed it might be better to define None so that sys.stderr gets resolved at instanciation rather than import.

**Comment by DavidEscott** [comment]
I'm aware, it's what I am doing, but it is error prone and requires changes
to the caller who may be a function who doesn't know or care where his
output goes (which is my use case).

Another place this should be done is at tqdm.write for the stdout option.

-----

My use case here is that I ignore SIGHUP so that I can close the terminal
window and not kill the process. But any attempt to print/log out write
will cause a crash.

So I'm injecting a proxy for stdout/stderr that ignores these errors, but
tqdm isn't picking it up.

--------

It might be worth putting a simple proxy for stdout/stderr in tqdm. Often
the streams that tqdm controls are transient and merely for the edification
of the user. I don't care if they get corrupted or are closed. I want the
calculation to continue. In my mind "for x in tqdm(thing)" should never
fail because of an issue in tqdm. It's just decoration for the loop it is
not important to the processing.

**Comment by lrq3000** [comment]
Agreed, thanks @DavidEscott for your feedback.

TODO:
- [ ] Use `file=None` and set default `self.fp=sys.stderr` inside init. Same for `tqdm.write()` (and other methods/submodules?). This will allow users to redirect sys.stderr before instanciating tqdm, without needing to supply the new redirection to tqdm.
- [ ] Check that it doesn't impact the stdout redirection scheme described in the readme.
- [ ] Wrap any writing in `try/except` block (this should not impact performances as the except block will only get evaluated in necessary). The `except` block should still display any error but as a non blocking message (using a new `TqdmErrorMessage() class`?).

**Comment by scopatz** [comment]
For what it is worth, we are seeing this come up as a problem in xonsh, where tqdm effectively does not work. See xonsh/xonsh#2058

**Comment by casperdcl** [comment]
fixed by #293 in [v4.13.0](https://github.com/tqdm/tqdm/releases/tag/v4.13.0)

**Comment by scopatz** [comment]
Thanks @casperdcl!
