### ISSUE TITLE
Specify `tqdm_notebook` bar width

### ISSUE THREAD

**Issue by wmayner** [tqdm/tqdm#276]
Thanks to the maintainers for this incredible tool!

I'm wondering how to specify the width of a progress bar in a Jupyter notebook, since the default is pretty small. The `tqdm_notebook` function doesn't seem to respect the `ncols` or `dynamic_ncols` keyword arguments of `tqdm`. 

Is there a way to do this? If not, then I guess this is a feature request 😸

**Comment by lrq3000** [comment]
Unluckily, no it doesn't seem to be possible with ipywidgets, as there is no argument to specify the width of the progress bar. I guess the progress bar gets resized depending on cell size, thus on screen size, but I'm not sure about that.

If you want this feature you [may try to ask them directly](https://github.com/ipython/ipywidgets/issues/) ;)

**Comment by lrq3000** [comment]
My bad, it seems there's a way to specify the layout using CSS-like arguments (see [here layout.width](http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Styling.html) and [here for autoresize on screen size](http://stackoverflow.com/questions/35880006/automatically-adjust-ipython-widgets-layout)). But it seems [it's not working correctly with the latest ipywidgets](https://github.com/ipython/ipywidgets/issues/773), so I'll try but I won't promise it will work :)

**Comment by wmayner** [comment]
Awesome, thanks for looking into it!

**Comment by lrq3000** [comment]
Please try #292 on your setup, but on mine it doesn't work yet...

**Comment by chengs** [comment]
It works, but there is a bug on style. I will fix it.

**Comment by chengs** [comment]
Once #292 is merged, this issue will be resolved.

**Comment by soerendip** [comment]
Can anybody post a working example with the progress bar, please?

**Comment by wookayin** [comment]
@soerendip For me, the following worked:
```
from tqdm.notebook import tqdm
tqdm(range(10), ncols='100%')  # or '100px', 100 (in px)
```

Seems ncols is used for CSS property width. Non-integer values will be rejected by non-notebook tqdm.

**Comment by casperdcl** [comment]
@chengs
