### ISSUE TITLE
Adding extra information

### ISSUE THREAD

**Issue by Dapid** [tqdm/tqdm#277]
It would be nice if I could add some information to the mere progress. Example:

```
26576/32000 [=======================>......] - ETA: 87s - loss: 0.5678
```

Where loss is something being computed inside the loop. In this case, I am using `pbar.update` as a callback of a minimisation algorithm, and I would like to have some feedback.

**Comment by lrq3000** [comment]
Hey David,

There was already the same request a few weeks ago and a PR you can test
and give feedback on.

I can't link here because I'm writing on a phone.

Please test it and tell us if it fits your needs :)

**Comment by CrazyPython** [comment]
@lrq3000 ...is that French?

**Comment by lrq3000** [comment]
What do you mean?

**Comment by Dapid** [comment]
Sorry, I cannot find the PR. Whenever you are able, can you link it here?

**Comment by Naihonn** [comment]
Totally off-topic but to satisfy your hunger for knowledge yes, **a écrit** really means **he/she wrote** in French.

**Comment by lrq3000** [comment]
@Dapid it's PR #270 and previous issue #266.

@CrazyPython ah yes it's french, it's because I replied by mail and my mailbox is in french :)
