### ISSUE TITLE
Allow bar_format without total

### ISSUE THREAD

**Issue by pjvandehaar** [tqdm/tqdm#282]
Thanks for `tqdm`!  It's a wonderful tool.

In order to use `bar_format`, `total` must be used.  I want to be able to do this without `total=int(1e100)`:

```
import tqdm, time
slow_iter = (time.sleep(1e-4) or i for i in range(int(1e5)))
with tqdm.tqdm(slow_iter, total=int(1e100), bar_format='Found {n:7} files') as prog_iter:
     for i in prog_iter:
          if i % int(1e4) == 0:
               prog_iter.write('Woohoo,{:6} files!'.format(i))
```

**Comment by lrq3000** [comment]
Yes this will be implemented by #223 (I know it's a bit obscure, sorry about that, there are a lot of things in this PR). But thank you for your PR, we will merge it with #223.
