### ISSUE TITLE
Questions on SO: pipe

### ISSUE THREAD

**Issue by lrq3000** [tqdm/tqdm#287]
* http://unix.stackexchange.com/questions/2577/how-can-i-move-files-and-view-the-progress-e-g-with-a-progress-bar
* http://unix.stackexchange.com/questions/1537/measure-pipe-throughput-in-the-shell/1539#1539

The best alternative to tqdm pipe: https://github.com/Xfennec/progress

From its readme:
```
How does it work?

It simply scans /proc for interesting commands, and then looks at directories fd and fdinfo to find opened files and seek positions, and reports status for the largest file.

It's very light, and compatible with virtually any command.
```

But it depends on ncurses and works only on Linux.

**Comment by casperdcl** [comment]
Hello world. I'm sort of back (i.e. might have time to look at tqdm again). I've answered http://unix.stackexchange.com/questions/1537/measure-pipe-throughput-in-the-shell/316217
... we could try re-implementing the process monitoring things that UNIX has, but it won't be windows compatible.

**Comment by lrq3000** [comment]
Hey Casper, good to see you back :)

I see no issue in implementing a platform specific additional feature as long as it doesn't prevent the main feature, tqdm pipe, from being used on Windows. Also, if you use psutils for process monitoring, it might also work on Windows if psutils for windows are installed, so we might potentially find a way later on to port this kind of platform-specific code.

Also you come back at the right time: I was going to work on merging tqdm PRs this week-end, starting tomorrow, because I won't be able to get back to tqdm for a few weeks at least after this week-end. If you can check the PRs (tagged to-review), that would be great!

My plan was to first merge the bugfix PRs, or PRs adding small features to the core. Then release a new minor version of tqdm with these fixes. Then merge the new modular architecture, and then merge submodules PRs (after being rebased on the new modular architecture). Then we can release a new major version of tqdm. What do you think about it? I think it's the cleanest way to move to the new architecture, even if I will lose some time rebasing every submodules.

**Comment by lrq3000** [comment]
@casperdcl I saw you enabled reviews on this repo (or was it enabled automatically?), so I can't merge in my own PRs anymore (which is a good thing, I don't want to disable it).

If you want to have a quick look at the things you have to review, you can [use this](https://github.com/tqdm/tqdm/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3Ato-review%20%20-label%3Asubmodule). When you will have reviewed these PRs (except the monitoring thread, it's not urgent and can be done later), I will implement the new submodules architecture #198 and then we can offer Dask support #279 and [other submodules](https://github.com/tqdm/tqdm/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20label%3Asubmodule) in the standard pypi release in a safe manner.

**Comment by casperdcl** [comment]
Nice, thanks Stephen.
