### ISSUE TITLE
Change tqdm project name

### ISSUE THREAD

**Issue by hadim** [tqdm/tqdm#30]
I think the best way to do it is keep this repo, empty it and put a message in the README saying that the project has been moved to another repo.

If others agree, this is the way I think we should do it : 

- [ ] find a name
- [ ] rename the organization
- [ ] rename the repo
- [ ] tag a version on git (v1.0 ???)
- [ ] create a new account on pypi
- [ ] share password with @lrq3000, @casperdcl, @kmike  and @hadim
- [ ] and finally we can release it on pypi !!!

PS: for the pypi release I would like us to register a new account on pypi with project name as login and a password (shared by mail) to avoid any issue if someone disapear.

**Comment by hadim** [comment]
Name proposed are : 

- pbar
- pbar-tqdm
- progressbar
- progressbar-tqdm

I vote for pbar !

**Comment by casperdcl** [comment]
from 18 June, #2 : 
> Well I never knew any arabic but I found it cool that it was a nice short abbreviation for something.
> It's true that it may be hard to pick up, though. probar, trackbar, pmeter are all free on pypi.

**Comment by hadim** [comment]
I also like probar

**Comment by casperdcl** [comment]
I had checked and `Pbar` was taken so I thought `pbar` wasn't too great an idea... even though it is also my favourite

**Comment by lrq3000** [comment]
You can also just rename the repo, when people try to access the previous name, they will automatically be redirected to the new repo (I did it on one of my projects, and I still use the old git address to do my pull and push). Dunno if you can do the same with the organization name though.

**Comment by hadim** [comment]
Ok good to know, we can try that.

**Comment by lrq3000** [comment]
Some other names (not taken on Pypi):
- tinybar
- fastbar
- fastprogress
- fastmeter
- simplebar

**Comment by hadim** [comment]
I like simplebar

**Comment by hadim** [comment]
@lrq3000 @casperdcl are you ok for simplebar ?

@casperdcl do you want to take care of the transition ? I can take care of it if you're busy.

**Comment by lrq3000** [comment]
I like simplebar yes, that's also my main preference. In second position, I like tinybar and progressbar-tqdm.
BTW thank's for the invitation @hadim :)

**Comment by lrq3000** [comment]
Note that there are some python scripts called "simplebar.py" over the internet. Nothing officially released somewhere though.

**Comment by hadim** [comment]
Right I already saw this kind of script but I think we can deal with that cuz simplebar will become mainstream soon :-D

**Comment by lrq3000** [comment]
Lol I hope so too :)

**Comment by hadim** [comment]
@casperdcl @kmike any thought ?

**Comment by kmike** [comment]
I'd love to see something no longer than 4 chars because when you're writing code like this:
```
for item in awesome_progress_bar(iter_data(...)):
    # ...
```
it is very easy to hit 80 columns limit.

**Comment by kmike** [comment]
This is stupid, but a short name was always one of the tqdm advantages :)

**Comment by hadim** [comment]
I agree with that, simplebar was a good compromise to me. Other short names to propose ?

- simbar 
- spbar

**Comment by hadim** [comment]
I like simbar

**Comment by kmike** [comment]
what about `lll`?

**Comment by hadim** [comment]
Hum... I am not a huge fan of that.

**Comment by kmike** [comment]
another option is simply to do `from tqdm2 import tqdm`

**Comment by hadim** [comment]
If we don't agree on a name `tqdm2` could do the job but I am sure we can find a cool, short, not taken name that everyone will love :-)

**Comment by hadim** [comment]
What about ppb (for PythonProgressBar) ?

**Comment by hadim** [comment]
Or ppg (for PythonProGress) ?

**Comment by kmike** [comment]
there are at least pdb and pbr well-known existing packages, ppb and ppg may look siminal.

rpg? (real progressbar)

**Comment by hadim** [comment]
Hum rpg is confusing with the totally unrelated but still a lot of used on internet Role Playing Game

**Comment by hadim** [comment]
tpb (The ProgressBar)

**Comment by kmike** [comment]
yes, that's the point - people will remember rpg better than pdb :)

**Comment by hadim** [comment]
Hum, I could agree on rpg. Do you like tpb ?

**Comment by hadim** [comment]
mpb (My ProgressBar)

**Comment by hadim** [comment]
@casperdcl @lrq3000 any preferences for the name ?

**Comment by casperdcl** [comment]
having fun guys? how about... `rap` ? (yes, 'tis free on pypi)

**Comment by casperdcl** [comment]
i.e. sell it like a short n sweet (w)rapper for iterators?

**Comment by kmike** [comment]
Well, all these 3-4 letter names look usable, but they are not easily memorizable. I can imagine myself wondering "mbp, mdp, mpb, what was the name of a nice progress bar I've seen on reddit? damn, i'd just install 'progressbar' from pypi" 

I'm not sure lll is a good idea, but it is provoking and kind of resembles a progress bar; rpg or rap are real words so people can recall the name later. I like rap, but I'm sure for some people it has negative sentiment and they won't use the progress bar just because it is named rap. The same applies to lll name though :)

**Comment by casperdcl** [comment]
Yeah. I actually like all music *except* rap. Which I don't classify as music (it's just poetry made deliberately bad because the guy who wrote it is afraid of being labelled homosexual)

**Comment by hadim** [comment]
I also like rap but @kmike comment on it could hapen I think. 

I don't think people will install a package cuz of its name but because they found the github or pypi page and then just copy paste the pip command for install, then read the doc and integrate the thing on their project.

**Comment by casperdcl** [comment]
back to the point... i think a word that is both short and meaningful is a must. things like `tinybar` may be the best compromise... argh dilemmas.

**Comment by lrq3000** [comment]
@kmike: what kind of advantage a short name brings? I mean, if it's for coding, you can just do an alias `import tqdm-new-name as t`. And for searching, it depends: a shortened name is unique, but it's harder to remember and to guess what it is about for new users.

**Comment by hadim** [comment]
Ok for `tinybar`, it's meaningfull, short and overall it highlights the strength of this project which is tiny overhead !

**Comment by kmike** [comment]
pub? it is like bar
also, `bistro` which is also somewhat like bar. 'bistro' means 'fast' in Russian. But it is 5 letters haha

**Comment by hadim** [comment]
Ahahah we will never agree on one name !!

I also like bistro (but the org name on github is taken)

**Comment by hadim** [comment]
and pub is taken on pypi

**Comment by lrq3000** [comment]
My point of view: I disagree with all shortened names, for the reasons I said above. In addition, an explicit name is more pythonic (explicit is better than implicit). In addition, I am strongly against names that are still in use, even if it's in an unrelated domain: it will make the module VERY hard to find, and very unexplicit to users (what will they think when they first see a module named "rpg" or "rap"? That's it's about roleplaying games or music...).

**Comment by lrq3000** [comment]
My point is: let's not shoot our feet here. I always felt that one reason for TQDM not reaching a wide public was in part because of its unevocative name, so since we have the opportunity to change the name, and we all want the new project to reach a wide audience, let's try to find something better than such a mysterious acronym (even if I have grown to really like this acronym, but that's not the point here).

**Comment by hadim** [comment]
tinybar ?

**Comment by lrq3000** [comment]
I prefer tinybar. I can also go with bistro but I find it less evocative, but if you guys want to go by an original, "yahoo"-like name, I can agree with that.

**Comment by kmike** [comment]
@lrq3000 there is a value in having a standard import name in source code which you don't have to override. When you see `t(mydata)` you have to go to the imports to find out what is it, it is also less greppable. 

A good point about googleability. From this point of view tqdm2 looks the best IMHO. 1000+ github stars show tqdm did reach a wide public.

All these [tiny,easy,simple,super,sweet,fast]bars look the same for me :) They have the same problem as mbp/mdp/mbd: "do i want tiny progress bar or easy progress bar or what?" That's just an opinion, of couse.

**Comment by casperdcl** [comment]
Considerations:

- relevance to purpose (progressbar wrapper for iterators)
- brevity
- understandability (`bistro` and `tqdm` not great for non-Russian/Arabic speakers)
- distinguishability (no confusion with other similar names)

All-in-all I vote for `rap` so far. Maybe will think of something else by tomorrow...

**Comment by casperdcl** [comment]
If we mention `tqdm` in our docs and have this old repo link autoredirect I don't think getting old users over should be too difficult...

**Comment by hadim** [comment]
`bistro` also mean pub in french (this is why I like it :-)). But as I said the org on github is taken...

I am still in favor of `tinybar`.

`bistro` would be my second choice.

**Comment by kmike** [comment]
my favourite so far is tqdm2

**Comment by casperdcl** [comment]
Hate the fact that `eta` was taken last year. The things that all my colleagues like about this is the speed and accuracy of stats...

**Comment by lrq3000** [comment]
@kmike my bad, I didn't check recently how many stars the tqdm project had!

I agree about tqdm2 and the similarity between all *bar names.

Choosing a name is not such an easy task :)

**Comment by hadim** [comment]
But it's important that we all agree on it ! Two of us are in favor of `tqdm2` and I still don't like `rap`. So @casperdcl unless you are in favor of `tinybar` we can agree on `tqdm2` ?

**Comment by lrq3000** [comment]
Let's just say our order of preference for the names, we can decide later:
1- tinybar or simplebar
2- bistro
3- tqdm2

**Comment by hadim** [comment]
Ok.

1- tinybar
2- bistro
3- tqdm2
4- simplebar

**Comment by kmike** [comment]
+1 to let things settle down :)

1. lll 
2. tqdm2
3. wait for pypi admins or @noamraph 
4. i'm not against other names if you agree on them

**Comment by lrq3000** [comment]
@kmike about 4, it would be better if you could tell the ones you prefer the best at least :)

**Comment by casperdcl** [comment]
Erm... `rate` is available on pypi?

--

**Comment by kmike** [comment]
I'm fine with fastbar,tinybar,rpg,bistro,rap, in order of preference. I like bistro and rap less because there can be negative feelings towards them.

rate sounds good, +1 to it.

**Comment by hadim** [comment]
Well I also like rate :-)

**Comment by casperdcl** [comment]
K's I'll look at this tomorrow.

--

**Comment by lrq3000** [comment]
rate +1 too, if it's available, it could be great

**Comment by kmike** [comment]
The only 2 downsides of 'rate' i can think of are 1) it is more likely to be in conflict with user variables; 2) github org is not available. But still, the name is great and I prefer it to all other names we've discussed.

**Comment by hadim** [comment]
Oh great catch for the conflict with user variables... I use rate a lot of... I downvote for it :-(

**Comment by casperdcl** [comment]
ratify? berate? barp, waitbar (like matlab), prostrate?

**Comment by hadim** [comment]
I like ratify, waitbar and berate byr order of preferences. I don't like prostrate.

**Comment by lrq3000** [comment]
Same as @hadim for the order of pref, and I also don't like prostrate for probably the same reasons :p But I would suggest rateify instead of ratify (sounds like we're rat-ifying something instead of rate-ifying something).

**Comment by hadim** [comment]
ratify is shorter :-)

**Comment by lrq3000** [comment]
lol, ok as you want, one letter isn't a big deal anyway :)

**Comment by casperdcl** [comment]
What's the advantage(s) of changing the organisation name? If we change it then the old links will only auto-redirect if nobody else claims 'tqdm' as a user/org name.

**Comment by hadim** [comment]
I guess we don't have to change the name of the project guys :-)

See https://sourceforge.net/p/pypi/support-requests/507/

So I created a new account for Pypi with the login "tqdm". I also created a new gmail adress (needed for pypi account) which is python.tqdm@gmail.com. I will email you the password soon.

Hope it's fine for everyone !

**Comment by hadim** [comment]
See #33 ?

**Comment by lrq3000** [comment]
Wow amazing timing lol
