### ISSUE TITLE
known-issues

### ISSUE THREAD

**Issue by casperdcl** [tqdm/tqdm#309]
Discussion continued from issues listed below. The appropriate section would be https://github.com/tqdm/tqdm/#help, possibly in a sub-section "known issues" shall we make a list here for now?

Lack of carriage return and/or up control characters:
- PyCharm #307 #208 #203 
- IDLE #191 
- ConEmu #254

Abstraction:
- zip #256 (fix by replacing `tqdm(zip(a, b))` with `zip(tqdm(a), b)` or even `zip(tqdm(a), tqdm(b))`)
- enumerate #157 (incl. numpy versions. `len` is hidden. fix by replacing `tqdm(enumerate(a))` with `enumerate(tqdm(a))`)

**Comment by lrq3000** [comment]
Yes good idea, we can later move it either to the readme or the wiki.

2016-11-13 13:13 GMT+01:00 Casper da Costa-Luis <notifications@github.com>:
