### ISSUE TITLE
[Question] "semi nested" progress meter?

### ISSUE THREAD

**Issue by jasmainak** [tqdm/tqdm#312]
I have a silly question and I hope this is the right place to ask it :) Please let me know if I should ask somewhere else. I am trying the following code:

```py
from tqdm import trange
from time import sleep

for i in trange(10, desc='1st loop', leave=True):
    for j in trange(100, desc='2nd loop', leave=False):
        sleep(0.01)
    for k in trange(100, desc='3nd loop', leave=False):
        sleep(0.01)
```

and this gives me:

![output1](https://cloud.githubusercontent.com/assets/15852194/20362738/e55ea162-ac3c-11e6-88a8-effe402c5d60.png)

The progress bar for the second loop and the third loop keep overwriting each other. What I was hoping to achieve is actually to have them on two different lines. So, something like this:

![output2](https://cloud.githubusercontent.com/assets/15852194/20362884/4fada7f2-ac3d-11e6-89cc-f19b45ea7365.png)

so that they do not disappear until the first loop finishes. Is this somehow possible? I tried various combinations of `leave=True` and `leave=False` but nothing seemed to work. I also tried putting an empty `print('')` statement but it seemed to affect the 1st loop ...

Many thanks!
ps: @lrq3000 did we met at the CRCNS conference? ;)

**Comment by lrq3000** [comment]
Hey Mainak,

Yes we met at the CRCNS! Lol I did not expect to see you here but nice to see you :) I plan to send you a mail but I'm overloaded with work, but soon!

About your question, yes that's absolutely the right place :) And indeed, the current "auto nested management" (unofficial name) can only support one loop per nesting level.

If you have more complicated scheme like yours, you can define your own positional scheme (what we call "absolute positioning") using the `position=id` argument, where `id` starts from 1. With your example, it would be something like this:

```python
from tqdm import trange
from time import sleep

for i in trange(10, desc='1st loop', leave=True, position=1):
    for j in trange(100, desc='2nd loop', leave=True, position=2):
        sleep(0.01)
    for k in trange(100, desc='3nd loop', leave=True, position=3):
        sleep(0.01)
```

Note also the `leave=True` for all bars, this does not impact the positioning, it just ensures the bar stays displayed until it gets replaced by a new one (when the `i` bar increases).

Hope this helps, feel free to tell us if you have any other question (or feedback) :)

PS: Out of curiosity, for what project are you using tqdm for? An EEG script? ;)

**Comment by jasmainak** [comment]
Haha, yes I didn't expect to be using `tqdm` when I met you but I had definitely heard good things about the project already. This is brilliant stuff! I didn't _really_ expect that there would actually be a way to do it ... because I was thinking you can use `'\r'` to get to the beginning of the line, but how would you go between lines? Now, I have to read the code :)

I am actually thinking of using this for [controlling the `verbosity` level](https://github.com/autoreject/autoreject/pull/14) in my repo for cleaning EEG data automatically (because people trying to use it are complaining that it's too talkative ...). We already talked about the project at the CRCNS poster :) Looking forward to your email!

**Comment by lrq3000** [comment]
Ah nice! I'm glad you found `tqdm` useful :) And nice use of `position`, we never thought about that, so we might add this as an example case :)

About the verbosity, I like applications that are verbose because it's easier to debug if something goes wrong (and also to track progress), but yeah for most people a progress bar is what they usually prefer ;) But please keep the extended verbosity, I'll use it for sure! (I always run into bugs...).

About how we do it, we just use a special "up" character that allows us to backtrack to previous lines :) It works on all platforms (on Windows thanks to the colorama library which extends the windows console control characters with Unix ones, except if you use tqdm_notebook then you don't need colorama of course). The relevant (and pretty simple) code is [here](https://github.com/tqdm/tqdm/blob/master/tqdm/_tqdm.py#L1039-L1040) and [here](https://github.com/tqdm/tqdm/blob/master/tqdm/_utils.py#L127-L128) :)

**Comment by lrq3000** [comment]
(advertisement mode) And if you like `tqdm`, please [add a like here](https://github.com/vinta/awesome-python/pull/662) so that we can get listed as an [awesome Python library](https://github.com/vinta/awesome-python) ;)

**Comment by jasmainak** [comment]
You have my vote now for the awesome Python library list! It seems to me a no-brainer that `tqdm` should be there :)

Of course, I hope the change isn't at the cost of debug-ability. I will let you complain on the github issues page if you don't like something or if the algorithm doesn't work on your data. It's research code turned into a library, so it's far from perfect (and always evolving) ... but I'm always nice to people who complain :) Adding that use case as an example in `tqdm` sounds really cool.

Ha, I didn't know there was a special character to backtrack to previous lines. That does make sense. Keep up all the good work!

**Comment by casperdcl** [comment]
Thanks Stephen for handling this issue. I noticed you've also started pushing the awesome-python inclusion, which is also appreciated. There's probably going to be more references to issues on the pr than actual votes.

**Comment by jasmainak** [comment]
hey @lrq3000 @casperdcl it seems that the behavior of [this code](https://github.com/tqdm/tqdm/issues/312#issuecomment-261098464) has changed since we last discussed this. Is there a way to get the old behavior that one was getting in `tqdm == 4.9.0`? Changing the second two loops to `leave=False` helps but doesn't quite give the same output. Thanks a lot!
