### ISSUE TITLE
Ugly logo

### ISSUE THREAD

**Issue by CrazyPython** [tqdm/tqdm#315]
This sounds rude but...

The logo is quite ugly. Ways to improve:

 - Choose better colors (https://material.google.com/style/color.html)
  - e.g. #2196F3 + #FFC107
 - Don't use gradients or reflections
 - Remove 3D

I could imagine a flat 2D version of this looking very nice.

**Comment by casperdcl** [comment]
Well it would be great if you could design a logo that you'd prefer. I was aiming for either animated pixelart or 3D...

**Comment by casperdcl** [comment]
![logo](https://cloud.githubusercontent.com/assets/10780059/20651130/ed9a025c-b4d6-11e6-8b7b-6bf8fcfaabd7.gif)

**Comment by lrq3000** [comment]
Ohhh I like this one a lot more, it is visually brighter and more vivid,
and the animation feels slower (the previous one felt a bit too frantic to
be honest).

I am still not sure if we should have an animated logo. I guess you want to
convey the dynamicity and speed of tqdm by an animation, but animations
might be a bit too distracting in our case.

But in any case, this logo is way better than the previous one, if we keep
an animated logo it's this one.

An idea: why not try a middle ground about the animation: let the animation
stay on one frame for a few second, then do the animation, and loop like
this. This way, the logo would be static most of the time, but with the
nice candy-effect that every once in a while it does the animation.
Something like 2 or 3 seconds would be good I think. What do you think
about it?

Thanks Casper for working on enhancing the logo!

2016-11-27 20:23 GMT+01:00 Casper da Costa-Luis <notifications@github.com>:

**Comment by casperdcl** [comment]
![logo](https://cloud.githubusercontent.com/assets/10780059/20689829/23570654-b5bf-11e6-8bc9-5d79a78e217f.gif)

**Comment by CrazyPython** [comment]
@casperdcl 

- Slower animation
- Is the gradient on the center dot necessary in the first image?
- Do a rendering with Black + White, maybe?
- #3F51B5 (indigo 500) + #FFEE58 (yellow 400), maybe try #009688 (teal 500)

**Comment by lrq3000** [comment]
I like this one a LOT Casper! I validate, it can be published like this!

@CrazyPython: The gradient shouldn't be too slow, I think it's perfect like
this (since it's stopping a moment, even if the animation is quick it's not
frantic). About the black and white, I prefer a colored logo :-/. I find
the gradient and the whole animation nice.

About the change of colors, I don't know, maybe we can try to see :) I
guess the order is outer + inner + dot, right?

2016-11-29 0:59 GMT+01:00 CrazyPython <notifications@github.com>:

**Comment by casperdcl** [comment]
4![logo-4](https://cloud.githubusercontent.com/assets/10780059/20690584/5e7a3194-b5c3-11e6-85ac-c4f012e54966.gif) - 2196F3 FFC107 2196F3 (above)
5![logo-5](https://cloud.githubusercontent.com/assets/10780059/20700582/08dbae1e-b606-11e6-948f-9b0a821cc09b.gif) - 3F51B5 FFEE58 009688
6![logo-6](https://cloud.githubusercontent.com/assets/10780059/20700332/9fa53da8-b604-11e6-94cb-4cff82a97eab.gif) - 2196F3 FFEE58 3F51B5
7![logo-7](https://cloud.githubusercontent.com/assets/10780059/20700334/a2e6444e-b604-11e6-9bb2-e99c01dea874.gif) - 3F51B5 FFEE58 2196F3
8![logo-n8](https://cloud.githubusercontent.com/assets/10780059/20700774/2bb47d7a-b607-11e6-9664-bd64bb1ebb79.gif) - 2196F3 FFC107 009688

All 12 combos (I am not going to upload em all):
(2196F3|3F51B5) (FFC107|FFEE58) (2196F3|009688|3F51B5)

**Comment by lrq3000** [comment]
I prefer 4, the one above, the one I already liked :) I think 2 colors are perfect, and the colors chosen are on the spot, to me it really looks professional. You did a great job Casper! :+1:

**Comment by lrq3000** [comment]
Al the other ones (except 8) have a "washed out" effect, the colors aren't as vivid (or they don't mix well together, I don't know, I'm no graphist ;) ). The 8th one could also fit but I think 2 colors is better than 1, I hence prefer 4 (and it looks nicer to me but that's subjective).

**Comment by lrq3000** [comment]
But really Casper you did a great job, you see how it's hard to design a logo, everyone has an opinion but noone is really precise, because we don't really know what would "feel" better lol...

But here I am convinced this is way better than before, the stop-and-animation with vivid color design is perfect!

**Comment by lrq3000** [comment]
Also, at last we won't have a logo that looks like a wifi tag on the entry door of a fast-food ;)

**Comment by CrazyPython** [comment]
Any ideas for a better static image? The current org logo should stay in my opinion.

**Comment by lrq3000** [comment]
No problem for a static one, we can use 4 but stuck to the initial frame.
That's also why I like it :) It will be as nice printed statically as
displayed in a web browser (with the added twist of a small animation).

2016-11-29 18:07 GMT+01:00 CrazyPython <notifications@github.com>:

**Comment by casperdcl** [comment]
I see a lot of +1s there. I agree that FFEE58 (similar to current org logo) looks too washed out next to more vivid colours. The current org logo (0, [above](https://github.com/tqdm/tqdm/issues/315#issuecomment-263423857)) could stay, I don't mind.

Your second preference @lrq3000 (8) has three colours, your first preference (4) has two. From what I understand you may want to see this:

9 ![logo-9](https://cloud.githubusercontent.com/assets/10780059/20744357/78f424b0-b6d3-11e6-8285-2848fe903b7d.gif) - 3F51B5 FFC107 3F51B5
4 ![logo-4](https://cloud.githubusercontent.com/assets/10780059/20690584/5e7a3194-b5c3-11e6-85ac-c4f012e54966.gif) - 2196F3 FFC107 2196F3

**Comment by casperdcl** [comment]
counting in hex, there's also
A ![logo-a](https://cloud.githubusercontent.com/assets/10780059/20770617/39d5b468-b73e-11e6-9b0d-4764a8d4ee9e.gif) 3F51B5 FFC107 2196F3

**Comment by lrq3000** [comment]
9 is nice :) but I still prefer 4! the colors are vivid, I think it's the
best. If we want to be perfectionists, someone should try to print it to
see if printers can render the colors correctly (not perfectly of course,
but maybe the blue is too bright to be printed...). If printers cannot
render the vivid colors, maybe we will have to use a blue color a little
less vivid, a bit in the middle of 4 and 9.

2016-11-30 21:48 GMT+01:00 Casper da Costa-Luis <notifications@github.com>:

**Comment by casperdcl** [comment]
the org logo https://avatars3.githubusercontent.com/u/12731565?v=3&s=200 is now also a high-res (400x400) version of https://github.com/tqdm/tqdm/blob/master/logo.png (100x100) which is a static version of https://github.com/tqdm/tqdm/blob/master/images/logo.gif

**Comment by casperdcl** [comment]
ah looks like pypy3 on travis is having issues. says verison of python is unsupported (3.2.*) even though it should be 3.5.2... https://travis-ci.org/tqdm/tqdm/builds/180960117

**Comment by casperdcl** [comment]
failing build related to https://github.com/travis-ci/travis-ci/issues/6727
