### ISSUE TITLE
Moving the GUI into an inheriting object

### ISSUE THREAD

**Issue by lrq3000** [tqdm/tqdm#32]
I just gave a thought on how the GUI could be moved to its own module. As I said in another comment, I think it would be better to modularize the GUI logic, keeping it separated from the console logic, as to avoid potential conflicts (ie, if we update the console code, it could break the GUI, or the other way around), for ease of maintenance and more robustness.

I thought of two ways to do that:

1- move the GUI into its own module (eg, _tqdmgui.py) and in its own class, that would inherit from the _tqdm.tqdm() class. This would give something like this:

```
from ._tqdm import tqdm

class tqdmgui(tqdm):

    def __init__(self, **kwargs):
                     
        tqdm.__init__(self, **kwargs)
        self.sp = None
        # Gui logic here in addition to tqdm.__init__()
    
    def __iter__(self):
        # Gui logic here that overrides __iter__()
    
    def update(self, n=1):
        # Gui logic that overrides update()

    def close(self):
        # Gui logic that overrides close()
```

This would totally modularize the code, but there would be a bit of redundancy and it wouldn't be possible to use `tqdm(..., gui=True)` anymore to use the GUI, you'd have to do `tqdmgui(...)`.

2- if we want to keep the `gui` argument inside the main tqdm() class, we can move the GUI management to a class or function that would replace StatusPrinter. For example, we could replace in tqdm() class the direct calls to format_meter() or StatusPrinter by a class property that would point to the correct functions/objects to use:

```
class tqdm(object):
    def __init__(self, iterable=None, desc=None, total=None, leave=False,
                 file=sys.stderr, ncols=None, mininterval=0.1,
                 miniters=None, ascii=None, disable=False,
                 unit='it', unit_scale=False, gui=False):

        # Initialization code here...
        
        if not gui:
            self.sp = StatusPrinter(self.file)
            self.sp_call = lambda *args, **kwargs: self.sp(format_meter(*args, **kwargs))
            # etc.
        else:
            self.sp = GUIPrinter()
            self.sp_call = self.sp_gui.gui_format_meter
```

Then in the code, to call, you'd have to replace `self.sp(format_meter(...))` by `self.sp_call(...)`.

However, I'm not sure that this latter option can be realized. @casperdcl, could you tell me if the GUI would have all the necessary info to work if it is supplied the [arguments of the format_meter() function](https://github.com/tqdm/tqdm/blob/master/tqdm/_tqdm.py#L72)?

3- I just thought we can also mix both 1 and 2: we can change self.sp in the inherited tqdmgui class to call a specifically designed StatusPrinter-like object.

----------

What do you think guys? Would you like the GUI to be modularized? If yes, what option would you prefer? (you can also propose other options)

**Comment by casperdcl** [comment]
I had already thought of the second option (modifying sp, reverting it to a class and putting gui syntax there). This I think would be the best practice but wouldn't really make a difference to lines of code or potential errors.

Definitely no problem with console stuff being broken in future, though, since we have ~100% coverage for all that!

**Comment by lrq3000** [comment]
Ah yes indeed if there's 100% coverage it's ok about broken things, but still modularizing would be cool for maintenance (and it would be easier to add other GUI wrappers like QT, wx, etc.).

What do you think Casper? Do you want to keep the `gui` argument or is it ok to move to its own class? Are you ok if I give it a try?

**Comment by lrq3000** [comment]
OK I gave it a try. Solution 1 works with no or an insignificant overhead in terms of performance, solution 2 has quite a hit on performances, and solution 3 (mixing both solutions) is even worse.

Here are my attempts:
https://github.com/lrq3000/tqdm/pull/1/files

- _tqdmgui.py implements solution 1 only and is quite good,
- _tqdm2.py implements solution 2
- _tqdmgui2.py implements solution 3

**Comment by casperdcl** [comment]
cloased by #53
