### ISSUE TITLE
'tqdm' object has no attribute 'pos'

### ISSUE THREAD

**Issue by jimanvlad** [tqdm/tqdm#323]
Hi,

I sometimes get this error, with no clear explanation. I wrapped my iterator with tqdm and every now and then, after a few iterations, it comes up with this AttributeError: 'tqdm' object has no attribute 'pos'

Redacted trace below. Any ideas?

```
\\<inbox>\Inbox\Reports\GFH: 0emails [00:00, ?emails/s]
   File "P:\TS Projects\Python\python3\Lib\threading.py", line 911, in _bootstrap_inner
     self.run()
   File "P:\TS Projects\Python\python3\Lib\threading.py", line 859, in run
     self._target(*self._args, **self._kwargs)
   File "P:\TS Projects\Document Classification\dataExtractor.py", line 111, in startExtractionThread
     extractor.run("emails", inbox, outlook)
   File "P:\TS Projects\Document Classification\dataExtractor.py", line 90, in run
     self.extract_data(mainfolder, restriction, db, collection)
   File "P:\TS Projects\Document Classification\dataExtractor.py", line 79, in extract_data
     walk_folders(folder)
   File "P:\TS Projects\Document Classification\dataExtractor.py", line 78, in walk_folders
     walk_folders(flds)
   File "P:\TS Projects\Document Classification\dataExtractor.py", line 78, in walk_folders
     walk_folders(flds)
   File "P:\TS Projects\Document Classification\dataExtractor.py", line 36, in walk_folders
     for msg in self.iterator:
   File "P:\TS Projects\Python\venv3\lib\site-packages\tqdm-4.10.0-py3.4.egg\tqdm\_tqdm.py", line 883, in __iter__
     self.close()
   File "P:\TS Projects\Python\venv3\lib\site-packages\tqdm-4.10.0-py3.4.egg\tqdm\_tqdm.py", line 984, in close
     self._decr_instances(self)
   File "P:\TS Projects\Python\venv3\lib\site-packages\tqdm-4.10.0-py3.4.egg\tqdm\_tqdm.py", line 398, in _decr_instances
     if inst.pos > instance.pos:
 AttributeError: 'tqdm' object has no attribute 'pos'
```

**Comment by jimanvlad** [comment]
@casperdcl Any idea on this one?

**Comment by lrq3000** [comment]
From the traceback it seems you are using tqdm in a thread. Support for
threading and multiprocessing is still in the works, ill give it another
shot in the next few days.

2016-12-16 13:00 GMT+01:00 Vlad Jiman <notifications@github.com>:

**Comment by jimanvlad** [comment]
It is indeed in a thread. I spawn an instance for each email inbox that I want to extract data from.

**Comment by casperdcl** [comment]
Thanks @lrq3000. @jimanvlad I didn't implement tqdm's internal monitor thread - @lrq3000 should be able to assist you better.

**Comment by lrq3000** [comment]
Casper it doesnt seem like its coming from the monitoring thread but rather
the instances count at closing, so this directly pertains to tqdm core
internals, but im not surprised as tqdm is not thread safe yet. If I can
patch the monitoring thread, we should be able to translate the same
changes to other parts (hopefully).

2016-12-16 15:01 GMT+01:00 Casper da Costa-Luis <notifications@github.com>:

**Comment by jimanvlad** [comment]
I sometimes get this as well fi it helps:

 Exception in thread Thread-4:
 Traceback (most recent call last):
   File "P:\TS Projects\Python\python3\Lib\threading.py", line 911, in _bootstrap_inner
     self.run()
   File "P:\TS Projects\Python\venv3\lib\site-packages\tqdm-4.10.0-py3.4.egg\tqdm\_tqdm.py", line 105, in run
     if instance.miniters > 1 and \
 AttributeError: 'tqdm' object has no attribute 'miniters'

**Comment by lrq3000** [comment]
This comes from the monitoring thread. My guess is that a tqdm instance is
instanciated at the same time as another (the last) instance gets closed,
so at the beginning of tqdm instance creation everything is ok, but by the
time it reaches the two lines of codes where it has to access other
instances, everything changed, and thus we get an error. But that's just a
guess, we'll have to look more into this issue.

2016-12-16 19:19 GMT+01:00 Vlad Jiman <notifications@github.com>:

**Comment by casperdcl** [comment]
"The monitor thread may be disabled application-wide by setting `tqdm.tqdm.monitor_interval = 0` before instantiation of any `tqdm` bar." Perhaps this will at least make the error disappear in your case?

**Comment by jimanvlad** [comment]
tqdm.tqdm.monitor_interval = 0 didn't help at all. Same error.

**Comment by gwerbin** [comment]
I'm seeing this error as well, inside a custom Django management command. I didn't even know Django commands were threaded, but I'm getting the exact same `miniters` exception. Anything else that might help debug?

**Comment by lrq3000** [comment]
Thanks Greg and Vlad, but you can't do anything more, we just need to
implement thread-safety :) I will give it a try soon, next week maximum.
But no guarantee it will be solved, this is a really tricky issue :/

2016-12-21 0:57 GMT+01:00 Greg Werbin <notifications@github.com>:

**Comment by TPeterW** [comment]
I have the same problem here, I'm using [joblib](https://github.com/joblib/joblib) to run a library called [tsfresh](https://github.com/blue-yonder/tsfresh) that uses tqdm, and this error pops up from time to time and on different computers.

**Comment by lrq3000** [comment]
Working on it!

**Comment by lrq3000** [comment]
@Everyone, please try #329 and tell me if this fixes your issues ([direct download link here](https://github.com/tqdm/tqdm/archive/parallel-print-fix2.zip)).

**Comment by Andarius** [comment]
Hey @lrq3000, I tried the fix on linux, but it didn't work (Ubuntu 16.04, python 3.5)

**Comment by lrq3000** [comment]
Did you try the sample code (ie, providing a lock from parent) on the PR?

**Comment by Andarius** [comment]
Sorry for the late answer. The sample of code works. However if I tried it with `threading.Thread` instead and it failed (by passing the lock to the threads)

**Comment by lrq3000** [comment]
Thank you for thee feedback!

About using threading, did you also changed the lock to import Lock from
threading, instead of multiprocessing?

**Comment by Andarius** [comment]
My bad, it works actually fine :) I was running it with the wrong environment...
This code works perfectly !

```
from tqdm import tqdm
from threading import Thread, Lock
from time import sleep


def progresser(n):         
    text = "bar{}".format(n)
    for i in tqdm(range(5000), desc=text, position=n, leave=True):
        sleep(0.001)

def run_listener(write_lock, thread_nb):
	tqdm.set_lock(write_lock)
	progresser(thread_nb)

def main(nb_threads=10):
	write_lock = Lock()
	for i in range(0, nb_threads):
	    t = Thread(target=run_listener, args=(write_lock, i))
	    t.start()

if __name__ == '__main__':
	main()
```

**Comment by mlissner** [comment]
I think I have an example of this that doesn't use threading:

```
with open('/tmp/out.csv', 'w') as f:
    w = csv.writer(f)
    for row in tqdm.tqdm(list(Thing.objects.values_list())):
        w.writerow(row)
```

It's possible Django uses threads, but I've never seen any hints that it does in the past.

**Comment by koppa** [comment]
I observed the same error and using no threading (except pandas & seaborn for internal computations).


```
Traceback (most recent call last):                                                                                   | 0/56 [00:00<?, ?it/s]
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/armasuisse/virtualenv/lib/python3.5/site-packages/tqdm/_tqdm.py", line 109, in run
    if instance.miniters > 1 and \
AttributeError: 'tqdm' object has no attribute 'miniters'

```

**Comment by GriceTurrble** [comment]
I only just started using tqdm to monitor data migration progress in Django, and I have seen the same error as @koppa , saying "no attribute 'miniters'". This is when I'm running about 4 million objects and just using the `desc` option.

It seems to appear completely at random, but it also appears to run normally anyway. No real adverse effects, just an error. Weird stuff.

**Comment by guillochon** [comment]
Also getting this issue, no threading.

**Comment by leobuskin** [comment]
Confirm an issue w/o threading

**Comment by leobuskin** [comment]
tqdm 4.19.4, we're still experiencing this issues with Celery (gevent) :boom:

**Comment by oak-tree** [comment]
I'm downloading file with multithreading via 
```
pool = multiprocessing.pool.ThreadPool()
pool.apply_async(self.process_file,(args))
```

I sometimes gets the following error:

## Error log
>   File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
>     raise self._value
> AttributeError: 'tqdm' object has no attribute 'pos'
> Exception AttributeError: "'tqdm' object has no attribute 'pos'" in <object repr() failed> ignored
> Exception AttributeError: "'tqdm' object has no attribute 'pos'" in <object repr() failed> ignored
> Exception AttributeError: "'tqdm' object has no attribute 'pos'" in <object repr() failed> ignored
> @training2:^Cgit/cropper/scripts$
> @training2:~/git/cropper/scripts$ python

## Version
> Python 2.7.12 (default, Nov 19 2016, 06:48:10)
> [GCC 5.4.0 20160609] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import tqdm
> >>> tqdm.__version__
> '4.19.5'
> >>>


any workaround?

**Comment by william-silversmith** [comment]
Bump. Submitted a PR with a possible fix. :)

**Comment by casperdcl** [comment]
Just to be clear, this is a synchronisation issue. Despite some of the comments saying "without threading" the traces invariably show threading libraries. Django uses threads.

**Comment by william-silversmith** [comment]
I agree. There might be a higher level of synchronization that's missing but the proximal cause of crashing is that cls._instances is being filled up in `__new__` and some of them get to `__init__` before the others. The ones that haven't been initialized don't have `pos` defined, so `_get_free_pos` dies when iterating through them. 

Maybe the results will be ultimately incorrect, but the crash goes away if you define pos in `__new__` before the `instance` variable is added to `cls._instances`.

**Comment by william-silversmith** [comment]
I'm ambivalent vis a vis resolving the crash, both methods will work. However, adding checks to _get_free_pos necessarily slow it down vs. making sure that all attributes are pre-defined. Also, I think it's pretty sensible to initialize a new tqdm position to 0. From a code maintainability perspective, simply adding checks leaves any new code that accesses cls._instances vulnerable to the same bug. Predefining pos eliminates the issue for future code. However, it still leaves other attributes accessed in `__init__` vulnerable to this bug.

The real problem is the fact that uninitialized instances are already added to `cls._instances`. Maybe that should be done after `__init__` is completed or partway through rather than in `__new__`?

**Comment by jacktrades** [comment]
I just started using `tqdm` yesterday in a Django project (so far it's great, thanks!), and have the latest version `tqdm.__version__ == '4.23.1'`.  I initially ran into this issue with a queryset that had a rather large `prefetch_related` set.  I thought that had something to do with it, but it turns out that any sufficiently large queryset triggers this error for me.

Here's the code I'm using:

```python
accomplishments = Accomplishment.objects.filter(...)
for accomplishment in tqdm.tqdm(accomplishments):
    # ...
```

And the traceback I'm getting

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/nick/.virtualenvs/schools/lib/python2.7/site-packages/tqdm/_monitor.py", line 87, in run
    if instances != self.tqdm_cls._instances:  # pragma: nocover
  File "/Users/nick/.virtualenvs/schools/bin/../lib/python2.7/_weakrefset.py", line 177, in __ne__
    opposite = self.__eq__(other)
  File "/Users/nick/.virtualenvs/schools/bin/../lib/python2.7/_weakrefset.py", line 174, in __eq__
    return self.data == set(ref(item) for item in other)
  File "/Users/nick/.virtualenvs/schools/lib/python2.7/site-packages/tqdm/_tqdm.py", line 896, in __eq__
    return abs(self.pos) == abs(other.pos)
AttributeError: 'tqdm' object has no attribute 'pos'
```

It looks like "sufficiently large" is somewhere between 117,000 (does not cause the error) and 127,000 (causes the error), at least for the data/models I'm using.

**Comment by j6mes** [comment]
Hey, I've just installed 4.23.3 and am still having an error with multi-threading that manifests itself with a trace similar to what other people have posted:

Removing the parallel map and using the vanilla single-threaded `map` function that is built-in in python fixes this issue.

```
Traceback (most recent call last):
  File "src/scripts/retrieval/ets/process_ets.py", line 67, in <module>
    for line in p.imap_unordered(lambda line: process_line(method,line),lines):
  File "/home/james/anaconda3/envs/fever/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
  File "/home/james/anaconda3/envs/fever/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "src/scripts/retrieval/ets/process_ets.py", line 67, in <lambda>
    for line in p.imap_unordered(lambda line: process_line(method,line),lines):
  File "src/scripts/retrieval/ets/process_ets.py", line 20, in process_line
    sents = method.get_sentences_for_claim(line["claim"])
  File "/data/fev_nlp1/Shared/ets/fever-ets/src/retrieval/ets/da.py", line 103, in get_sentences_for_claim
    scores = self.rank(claim_text, lines)
  File "/data/fev_nlp1/Shared/ets/fever-ets/src/retrieval/ets/da.py", line 65, in rank
    predictions = self.model.forward_on_instances(insts,cuda_device=self.cuda_device)
  File "/home/james/anaconda3/envs/fever/lib/python3.6/site-packages/allennlp/models/model.py", line 143, in forward_on_instances
    dataset.index_instances(self.vocab)
  File "/home/james/anaconda3/envs/fever/lib/python3.6/site-packages/allennlp/data/dataset.py", line 58, in index_instances
    for instance in tqdm.tqdm(self.instances):
  File "/home/james/anaconda3/envs/fever/lib/python3.6/site-packages/tqdm/_tqdm.py", line 987, in __iter__
    self.close()
  File "/home/james/anaconda3/envs/fever/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1084, in close
    self._decr_instances(self)
  File "/home/james/anaconda3/envs/fever/lib/python3.6/site-packages/tqdm/_tqdm.py", line 446, in _decr_instances
    if inst.pos > abs(instance.pos):
AttributeError: 'tqdm' object has no attribute 'pos'
terminate called without an active exception
Aborted (core dumped) 
```

**Comment by carlthome** [comment]
Same here. Running `tqdm.tnrange` inside a parallel `tf.data` pipeline leads to `AttributeError: 'tqdm_notebook' object has no attribute 'pos'` _sometimes_. Race conditions?

**Comment by GilJ** [comment]
I don't think anyone posted an example yet, but I have one here.

Running on `4.23.4`.

The idea is to have 1 general progress bar, and a progress bar per batch of work.

Without the `position` argument in the `fib_wrapper` call, it doesn't have this exception (`AttributeError: 'tqdm' object has no attribute 'pos'`). Can provide more details on request.

```python
from multiprocessing.pool import Pool

import tqdm
import multiprocessing


def fib(n):
    if n > 1:
        return fib(n-1) + fib(n-2)
    else:
        return 1


def fib_wrapper(n, i):
    current_process = multiprocessing.current_process()
    for _ in tqdm.tqdm(range(n), position=current_process._identity):
        fib(i)


def test(i):
    pool = Pool()
    overall_progressbar = tqdm.tqdm(total=i, desc='Overall', position=0)

    def callback(result):
        overall_progressbar.update()

    for i in range(i):
        pool.apply_async(fib_wrapper, args=(10, 31), callback=callback)

    pool.close()
    pool.join()


if __name__ == '__main__':
    test(100)
```

**Comment by liu904905023** [comment]
update the tqdm,everything is  ok.

**Comment by notnami** [comment]
Can we confirm that the latest version of tqdm doesn't show this issue?

**Comment by ngibsonn** [comment]
I can confirm it's still an issue:

ception in thread 192.168.1.105: on 192.168.1.103: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  1.40it/s]
Traceback (most recent call last):on 192.168.1.104: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.42it/s]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner██████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.41it/s]
    self.run()buntu-18.04 clients on 192.168.1.106: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  1.42it/s]
  File "./LoadGen.py", line 129, in run                                                                                                                                               | 0/1 [00:00<?, ?it/s]
    StopClients(self.r_path, self.user, self.name, x, self.threadID)                                                                                                                  | 0/1 [00:00<?, ?it/s]
  File "./LoadGen.py", line 233, in StopClients
    for i in t:
  File "/Library/Python/2.7/site-packages/tqdm-4.24.0-py2.7.egg/tqdm/_tqdm.py", line 991, in __iter__
    self.close()
  File "/Library/Python/2.7/site-packages/tqdm-4.24.0-py2.7.egg/tqdm/_tqdm.py", line 1088, in close
    self._decr_instances(self)
  File "/Library/Python/2.7/site-packages/tqdm-4.24.0-py2.7.egg/tqdm/_tqdm.py", line 446, in _decr_instances
    if inst.pos > abs(instance.pos):
AttributeError: 'tqdm' object has no attribute 'pos'

**Comment by ngibsonn** [comment]
Is there any chance this will be fixed eventually?

Thank you

**Comment by Mitmischer** [comment]
I also get this error sometimes, but it's hard to reproduce it. I will attach a minimum sample as soon as I find one.

**Comment by casperdcl** [comment]
@ngibsonn you're using `v4.24.0`. Does updating to the latest version fix your problem?

**Comment by vpuhoff** [comment]
To avoid this problem, specify the line number in the position parameter when calling tqdm. The easiest way to get it if you get it from threading.current_thread ().name
get something like this
rownum = int (threading.current_thread().name.replace ('Thread -'))
for x in tqdm(range (100), position=rownum):
   dowork()
thus, each thread will be assigned a line according to the thread number. The only downside if the streams are proliferating continuously can be a problem.

**Comment by casperdcl** [comment]
happy to reopen if this is still an issue for `tqdm>=4.29.0`

**Comment by fake-name** [comment]
I'm definitely still seeing it on `tqdm-4.30.0`. I just upgraded to 4.31.0, let's see if it's still there.

**Comment by casperdcl** [comment]
Thanks @fake-name can you post a traceback? 4.31.0 should not make any difference over 4.30.0 for this issue

**Comment by fake-name** [comment]
```
  File "runScheduler.py", line 93, in doCall
    self._doCall()
  File "runScheduler.py", line 110, in _doCall
    instance._go()
  File "/media/Storage/Scripts/ReadableWebProxy/WebMirror/TimedTriggers/TriggerBase.py", line 44, in _go
    self.go()
  File "/media/Storage/Scripts/ReadableWebProxy/WebMirror/TimedTriggers/RollingRewalkTriggers.py", line 175, in go
    self.retrigger_other()
  File "/media/Storage/Scripts/ReadableWebProxy/WebMirror/TimedTriggers/RollingRewalkTriggers.py", line 124, in retrigger_other
    for chunk in pbar:
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 991, in __iter__
    self.close()
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 1088, in close
    self._decr_instances(self)
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 446, in _decr_instances
    if inst.pos > abs(instance.pos):
AttributeError: 'tqdm' object has no attribute 'pos'

```

```
durr@rwpscrape /m/S/ReadableWebProxy> cat /usr/local/lib/python3.5/dist-packages/tqdm/_version.py  | grep version_info
version_info = 4, 31, 0
```

**Comment by casperdcl** [comment]
this makes no sense...


```bash
tqdm (master)$ git checkout v4.30.0
tqdm ((v4.31.0))$ grep inst.pos tqdm/_tqdm.py -n
484:        positions = set(abs(inst.pos) for inst in cls._instances
505:                    if hasattr(inst, "pos") and inst.pos > abs(instance.pos):
506:                        inst.pos -= 1
```

how did you install `tqdm`? maybe try uninstalling and reinstalling?

**Comment by casperdcl** [comment]
perhaps your traceback is from a venv, while your `cat | grep version_info` is from your system?

**Comment by fake-name** [comment]
I'm not using venvs, but it could be a stale pyc file.

**Comment by casperdcl** [comment]
I'm going to cross my fingers, hope that's it, and re-close this issue :)

**Comment by fake-name** [comment]
lol, ok. 

I can't check now, but I should be able to once I get home.

**Comment by fake-name** [comment]
OK, yeah, the errors I was seeing include line numbers that are literal empty lines in the source, so it was something somewhere caching something.

I managed to do multiple updates of multiple packages, and somehow some of the updated packages weren't rebuilt. I deleted all the pyc files and it appears to be loading the new version now.
