### ISSUE TITLE
 AttributeError: 'tqdm' object has no attribute 'total'

### ISSUE THREAD

**Issue by jimanvlad** [tqdm/tqdm#324]
Setting the disabled flag to True seems to get rid of the "total" property. Why is that? 

Apart from https://github.com/tqdm/tqdm/issues/323, everything works fine when disable=False.

```
self.iterator = tqdm(folder.Items.Restrict(restriction),unit="emails", desc=folder.FolderPath, position=self.tqdmpos, **disable=True**)

 Exception in thread Thread-7:
 Traceback (most recent call last):
   File "P:\TS Projects\Python\python3\Lib\threading.py", line 911, in _bootstrap_inner
     self.run()
   File "P:\TS Projects\Python\python3\Lib\threading.py", line 859, in run
     self._target(*self._args, **self._kwargs)
   File "P:\TS Projects\Document Classification\dataExtractor.py", line 111, in startExtractionThread
     extractor.run("emails", inbox, outlook)
   File "P:\TS Projects\Document Classification\dataExtractor.py", line 90, in run
     self.extract_data(mainfolder, restriction, db, collection)
   File "P:\TS Projects\Document Classification\dataExtractor.py", line 79, in extract_data
     walk_folders(folder)
   File "P:\TS Projects\Document Classification\dataExtractor.py", line 40, in walk_folders
     self.progressbar.max = self.iterator.total
 AttributeError: 'tqdm' object has no attribute 'total'
```

**Comment by casperdcl** [comment]
In `P:\TS Projects\Document Classification\dataExtractor.py`, line 40 you should really use:

``` python
self.progressbar.max = getattr(self.iterator, "total", -1)
```

or similar if you know `self.iterator` will sometimes be disabled.

**Comment by jimanvlad** [comment]
Hi,

thanks for the reply. However, I'm still not clear as to why that attribute doesn't exist when disable=True. I thought the disable just hid the console output. If I use getattr(self.iterator, "total", -1) and getattr(self.iterator, "n", -1) to update my progress bar, it will never update because both total and n will always be -1.

**Comment by casperdcl** [comment]
No, `disable` actually avoids instantiating most of the `tqdm` class (for optimisation purposes).

It would help if we understood your use case. From your code it appears you have your own progress bar, but want to use tqdm along with it somehow.

**Comment by jimanvlad** [comment]
I use tqdm for a couple of reasons:
1. I work a lot out of the console for debugging, so sometimes I need the visual output there
2. tqdm wraps everything up nicely and calculates all I need (n, total, iteration speed etc.)

I was basically looking for a way to just disable the output to console (as I use a number of threads, together with other print statements and it gets a bit noisy).

**Comment by casperdcl** [comment]
ok so you could do `tqdm(..., file=StringIO())`

**Comment by jimanvlad** [comment]
That works!

However, the file= argument isn't documented on the main page as far as I can tell.

**Comment by casperdcl** [comment]
You're welcome! It's the fifth documented argument: https://github.com/tqdm/tqdm#parameters

please :+1: this link: [vinta/awesome-python/pull/662](https://github.com/vinta/awesome-python/pull/662#issue-160805918) if you love tqdm.
