### ISSUE TITLE
Release a new version for tqdm

### ISSUE THREAD

**Issue by hadim** [tqdm/tqdm#33]
- [x] choose a version number
- [x] since we have a mail, add it to README (python.tqdm@gmail.com) ?
- [x] tag it on git
- [x] release it on pypi

Who want to take care of this ?

PS: we still need to wait pypi admin to move tqdm to our pypi account. See https://sourceforge.net/p/pypi/support-requests/507/

**Comment by hadim** [comment]
Since pypi tqdm version is 1.0, I am in favor releasing a 2.0 version then I think we should follow the standard version number called semver (http://semver.org/).

**Comment by casperdcl** [comment]
Yup, I like v2.0 too. Would've been 4.3.1a by now if we'd had access from the start xD

**Comment by lrq3000** [comment]
I agree with v2.0 and semantic versioning.

While we're at it, we can also set the version in a specific VERSION file and then we can use tools like [this one](https://github.com/peritus/bumpversion) or [this one](https://pypi.python.org/pypi/semantic_version/2.4.2) to automatically update the version.

I can take care of uploading to pypi, I've done it recently with another project, it's easy using [twine](https://pypi.python.org/pypi/twine).

**Comment by hadim** [comment]
Fine for me but please find a place in the project (`CONTRIBUTE` ?) to write the procedure you used to release the version which imply tagging and upload to pypi.

Before doing it I would like to have the agreement of @kmike

**Comment by lrq3000** [comment]
Ok I will first prepare everything for pypi uploading and ask you to check if everything's ok before uploading.

**Comment by hadim** [comment]
Ok you can still make a PR waiting for @kmike

**Comment by casperdcl** [comment]
Fine for twine, but don't like the idea of a separate version file and use of another utility... Seems like an unnecessary dependency.

**Comment by hadim** [comment]
The version number usually go to `tqdm/_version.py` and it is stored with something like that `__version__ = 2.0-dev` and then called in `tqdm/__init__.py`.

Just my opinion, I am really not complicated if you want to do something else...

**Comment by lrq3000** [comment]
@casperdcl using another utility is just optional, it's just to automate, but you can of course edit the version number by hand.

@hadim this is also another possibility, in the end it's the same. If you prefer that I will create tqdm/_version.py instead of VERSION.

**Comment by lrq3000** [comment]
Should I add us all to the list of authors on Pypi?

**Comment by kmike** [comment]
Hey, it's good news! 

regarding `_version.py`: it is fine as soon as we don't import it from setup.py. Importing the package being installed from setup.py may cause all kind of problems because setup.py may be called before the package is installed.

For Scrapy and ScrapingHub projects we're using https://github.com/peritus/bumpversion; releases are uploaded to pypi by Travis (using twine), after a release tag is added to git repo. For my own projects I'm just uploading wheels/sdists from a local machine. Both approaches sound fine.

**Comment by lrq3000** [comment]
@kmike arg I didn't know about the issue of importing the version into setup.py. Is this what you are talking about?

https://github.com/lrq3000/tqdm/commit/e572e9baa13011da6d7ec133bcd50990ca1adc2e#diff-2eeaed663bd0d25b7e608891384b7298R8

I have seen this usage in a lot of python libraries. Are you sure it will produce an issue? (so far, I tried to install with one of the builds I've done and it seems to work ok). What would you advise then to automatically update the version in the setup.py?

**Comment by lrq3000** [comment]
About the authors list, should I do this:

```
author='Noam Yorav-Raphael, Casper da Costa-Luis, Hadrien Mary, Mikhail Korobov, Ivan Ivanov, Stephen Larroque',
```

Or just this:

```
author='tqdm project'
```
?

**Comment by kmike** [comment]
@lrq3000 it may or may not cause problems, it depends on many things. For example, if a module has dependencies, and they end up being imported after package import, then installation will fail because dependencies are not installed yet (setup.py is called several times during the istallation - to get version/dependency information and then to install the package). It may work, but it is more robust to avoid it and do something similar to https://github.com/mitsuhiko/flask/blob/1ac4156016a578fdf439ac69bc39b9c6687ea9f9/setup.py#L50 instead.

**Comment by kmike** [comment]
+1 to 2.0 version

I think we should keep Noam Yorav-Raphael noamraph@gmail.com as author and add 'tqdm developers' as maintainers. PyPI shows maintainer contacts by default.

IMHO it is good to have CONTRIBUTING formatted to 80 columns - this way it will always be readable (e.g. in console with git diff).

@lrq3000 could you please open a PR? It is easier to comment on changes inline.

**Comment by kmike** [comment]
What did happen with 1.0 release? It looks README is from an updated version (`00:34<00:10, 222.22 it/s`), but the sdist is from original tqdm.

**Comment by hadim** [comment]
I am fine with @kmike for the authors related stuffs.

I change yesterday the pypi readme but we can still change it.

About `_version.py`, from my experience it should not be imported in `setup.py` but parsed (see here https://github.com/vispy/vispy/blob/master/setup.py#L51 for example).

The nice thing to have `__version__` variable is that you can show tqdm version from your code (usefull for debugging).

You should open a PR, it will be easier to discuss on code directly.

**Comment by lrq3000** [comment]
Ok I open a PR then, but I'm not finished yet. See #34.
