### ISSUE TITLE
Request for python 3.6 compatibility

### ISSUE THREAD

**Issue by ruxi** [tqdm/tqdm#333]
What's needed to get python 3.6 compatibility? Update to the setup.py?

 Currently, getting this error when trying to install by conda

```
    UnsatisfiableError: The following specifications were found to be in conflict:
  - progressbar2 -> python 2.7*|3.4*|3.5*
  - python 3.6*
   Use "conda info <package>" to see the dependencies for each package.
```

**Comment by lrq3000** [comment]
But I'm talking about source install, for conda we will need to update by
ourselves

**Comment by ruxi** [comment]
Oh, sorry. I had the same message for tqdm. Was trying both packages independently. Will try the source install as well

**Comment by ruxi** [comment]
Just tried a local install via setup.py. Worked fine

Seems like the issue is with conda

**Comment by ruxi** [comment]
Okay, tried again. Works with pip & source install, just not with conda. So, that's fine. Thanks!

```
(py36) user $ ~/git/gist/test $ conda env update
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ....


UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - tqdm -> python 2.7*|3.4*|3.5*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by lrq3000** [comment]
Thanks for the report, it should also work with conda so we're going to
have a look!

**Comment by timtobey** [comment]
I get  the same error with 3,2

**Comment by casperdcl** [comment]
what, something about `progressbar2`? `tqdm` does not have any dependencies. I don't know why or how `conda` would say there are dependencies.
