### ISSUE TITLE
Progress bar disappears during long iterations

### ISSUE THREAD

**Issue by abw333** [tqdm/tqdm#334]
I am using Python 3.6 and tqdm 4.10.0.

My code looks like:
```
with multiprocessing.Pool() as pool:
    for input, output in zip(tqdm.tqdm(args_list, smoothing=0),
                             pool.imap(function, args_list)):
        ...                                                                                                                                                 
```

Iterations are fairly short (~15 iterations/s), with a few exceptions that may last much longer (~60s/iteration). Whenever I hit these longer iterations, the progress bar will disappear until the iteration completes. Is this expected?

EDIT: I don't expect that multiprocessing is causing this issue, but I haven't verified this, so I left it in the code sample above, just in case.

**Comment by lrq3000** [comment]
`tqdm` is not yet parallel safe, please try #329 and please report if this fixes your issue!

Indeed, your issue seems very similar to what is reported in another ticket: https://github.com/tqdm/tqdm/issues/285#issuecomment-271105145
