### ISSUE TITLE
some tests aren't "stable" enough?

### ISSUE THREAD

**Issue by yarikoptic** [tqdm/tqdm#335]
- [ ] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#help
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

Hi,
while building backports of 4.10.0 release for NeuroDebian  I have noted that on some releases build failed due to some tests failing.  And it seems that some (e.g. the `OSError: 1 `tqdm` instances still in existence POST-test` which I searched for) would fail in some runs but not always.  Here is e.g. two runs (Debian unstable sid env):
```shell
/tmp/buildd/tqdm-4.10.0# nosetests3 build/lib/tqdm/
Test CLI delims: 1000it [00:00, 343148.49it/s]
Test CLI pipes: 1.00Kit [00:00, 701Kit/s]
Test CLI errors: 0it [00:00, ?it/s]

Error:
Usage:
  tqdm [--help | options]

Error:
Usage:
  tqdm [--help | options]

Error:
Usage:
  tqdm [--help | options]
Test default kwargs ... ...............................S.....
======================================================================
ERROR: Test overhead of manual tqdm vs simple progress bar (hard)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 277, in tearDown
    try_run(self.test, names)
  File "/usr/lib/python3/dist-packages/nose/util.py", line 471, in try_run
    return func()
  File "/build/tqdm-4.10.0/build/lib/tqdm/tests/tests_tqdm.py", line 117, in posttest
    "{0} `tqdm` instances still in existence POST-test".format(n))
OSError: 1 `tqdm` instances still in existence POST-test

======================================================================
FAIL: Test overhead of iteration based tqdm vs simple progress bar (hard)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/tqdm-4.10.0/build/lib/tqdm/tests/tests_perf.py", line 294, in test_iter_overhead_simplebar_hard
    assert(time_tqdm() < 2 * time_bench())
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/build/tqdm-4.10.0/build/lib/tqdm/tests/tests_perf.py", line 74, in test_inner
    fn()
  File "/build/tqdm-4.10.0/build/lib/tqdm/tests/tests_perf.py", line 297, in test_iter_overhead_simplebar_hard
    (total, time_tqdm(), total, time_bench()))
AssertionError: trange(10000): 0.144787, simple_progress(10000): 0.070839

======================================================================
FAIL: Test overhead of manual tqdm vs simple progress bar (hard)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/tqdm-4.10.0/build/lib/tqdm/tests/tests_perf.py", line 327, in test_manual_overhead_simplebar_hard
    assert(time_tqdm() < 2 * time_bench())
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/build/tqdm-4.10.0/build/lib/tqdm/tests/tests_perf.py", line 74, in test_inner
    fn()
  File "/build/tqdm-4.10.0/build/lib/tqdm/tests/tests_perf.py", line 330, in test_manual_overhead_simplebar_hard
    (total, time_tqdm(), total, time_bench()))
AssertionError: tqdm(10000): 0.165010, simple_progress(10000): 0.069812

----------------------------------------------------------------------
Ran 52 tests in 8.985s

FAILED (SKIP=6, errors=1, failures=2)
```
```shell
/tmp/buildd/tqdm-4.10.0# nosetests3 build/lib/tqdm/
Test CLI delims: 1000it [00:00, 485395.67it/s]
Test CLI pipes: 1.00Kit [00:00, 1.02Mit/s]
Test CLI errors: 0it [00:00, ?it/s]

Error:
Usage:
  tqdm [--help | options]

Error:
Usage:
  tqdm [--help | options]

Error:
Usage:
  tqdm [--help | options]
Test default kwargs ... ...............................S.....
======================================================================
FAIL: Test overhead of iteration based tqdm vs simple progress bar (hard)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/tqdm-4.10.0/build/lib/tqdm/tests/tests_perf.py", line 294, in test_iter_overhead_simplebar_hard
    assert(time_tqdm() < 2 * time_bench())
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/build/tqdm-4.10.0/build/lib/tqdm/tests/tests_perf.py", line 74, in test_inner
    fn()
  File "/build/tqdm-4.10.0/build/lib/tqdm/tests/tests_perf.py", line 297, in test_iter_overhead_simplebar_hard
    (total, time_tqdm(), total, time_bench()))
AssertionError: trange(10000): 0.126044, simple_progress(10000): 0.062638

----------------------------------------------------------------------
Ran 52 tests in 7.609s

FAILED (SKIP=6, failures=1)

```

**Comment by lrq3000** [comment]
Ah, it's been a long time since we've seen those errors.

Yes, these tests are unstable by nature, because they are performance tests, so they depend on your machine. We tried to make them as independent from the environment as possible, but it's not possible to do a performance test that is totally independent from everything else.

Also, can I ask you if you ran these tests while having closed every other CPU consuming process (like Skype, Chrome, whatever)? If that's not the case, can you try to run the test again several times with as many other processes closed as possible?

**Comment by yarikoptic** [comment]
thanks! those tests failed while building the package on a server, which is used for other purposes as well, so can't guarantee it not being busy with other tasks.  I wonder if it might be worth tagging those tests with e.g. "performance" (ref: http://nose.readthedocs.io/en/latest/plugins/attrib.html) so package maintainers could exclude those tests at once while running tests during pkg build time?

**Comment by yarikoptic** [comment]
FWIW -- not sure yet what interactions are but it is not just a server being busy, since it isn't, but tests still tend to fail from time to time.  May be for some of them at least it might work to get some helper decorator which would run them up to 5 times until any run succeeds, and if none -- then fail (something like we have in good old pymvpa: https://github.com/PyMVPA/PyMVPA/blob/master/mvpa2/testing/tools.py#L387).  just an idea

**Comment by casperdcl** [comment]
the performance tests are already abstracted into their own file (see tqdm/tests/tests_perf.py). You can easily run all tests from that folder excluding that file.

**Comment by casperdcl** [comment]
we also retry 3 times

**Comment by casperdcl** [comment]
to be even more explicit:

```sh
# run all tests in tox
tqdm$ python setup.py make test
# run all tests with nose for the current python version
tqdm$ python setup.py make testnose
# skip perf tests with nose
tqdm$ python setup.py make testcoverage
```

**Comment by casperdcl** [comment]
Closing this for now, happy to reopen of there are any more issues or suggestions.

**Comment by yarikoptic** [comment]
thank you @casperdcl  for all the information !

**Comment by casperdcl** [comment]
You're welcome @yarikoptic. Was annoying to sort out back when we did. Glad we didn't have to look into it all over again. You can check out https://tqdm.github.io/tqdm/ to see performance of `tqdm` over the (commit) ages... He hover at worst-case empty loops being ~5x quicker when not wrapped with `tqdm`.

**Comment by yarikoptic** [comment]
Thanks for the link to ASV reports!!!  We really should setup some benchmarking for our projects (datalad, etc) but never got to it since I wasn't sure if I should continue trying to extend/fix up vbench (did setup for numpy awhile back: http://yarikoptic.github.io/numpy-vbench/ ).  Should really look into ASV.  Cheers.
