### ISSUE TITLE
set_description does not update correctly for notebook

### ISSUE THREAD

**Issue by postelrich** [tqdm/tqdm#345]
I am using `tqdm_notebook` and trying to update the description. Instead of updating the initial description, it leaves the original description and sticks the new one between `{bar}` and `{r_bar}`.

I am using it in a more manual manner like:

```
from time import sleep
from tqdm import tqdm_notebook

with tqdm_notebook(total=100, miniters=1, mininterval=0, desc="start") as pbar:
    sleep(1) # do stuff
    pbar.set_description("doing stuff")
    pbar.update(10)
    sleep(2)
    pbar.set_description("more stuff")
    pbar.update(20)
    sleep(1)
    pbar.set_description("refresh")
    pbar.refresh()
```

After first update:
```
start: |||| doing stuff: 10% 10/100 [00:01<00:09, 9.82it/s]
```

After second update:
```
start: ||||||| more stuff: 30% 30/100 [00:03<00:07, 9.89it/s]
```

After refresh (adds a second text bar):
<img width="821" alt="screen shot 2017-02-09 at 2 43 56 pm" src="https://cloud.githubusercontent.com/assets/3619876/22800091/36b99d2e-eed6-11e6-9c03-618f9c37dc2d.png">

**Comment by ConX** [comment]
Same happens to me. I believe the _refresh()_ isn't implemented for the tqdm_notebook.

**Comment by postelrich** [comment]
I was able to solve this by setting `file=open(os.devnull, 'w')`. The refresh function calls the write to file: https://github.com/tqdm/tqdm/blob/master/tqdm/_tqdm.py#L1112
