### ISSUE TITLE
AttributeError: 'tqdm' object has no attribute 'total'

### ISSUE THREAD

**Issue by postelrich** [tqdm/tqdm#346]
I am using tqdm in a manual manner where I'm making use of some of the attributes to do updates.  If I set it to disable, it throws the error.  

```
from tqdm import tqdm

with tqdm(total=100, disable=True) as pbar:
    pbar.total

---------------------------------------------------------
AttributeError          Traceback (most recent call last)
<ipython-input-2-3015d755e0b2> in <module>()
      1 with tqdm(range(100), disable=True) as pbar:
----> 2     pbar.total
      3

AttributeError: 'tqdm' object has no attribute 'total'
```

Looks like the disable case needs to set more defaults. Also notice it for `n`

```
with tqdm(total=100, disable=True) as pbar:
    pbar.n

---------------------------------------------------------
AttributeError          Traceback (most recent call last)
<ipython-input-3-e9efa165606e> in <module>()
      1 with tqdm(range(100), disable=True) as pbar:
----> 2     pbar.n
      3

AttributeError: 'tqdm' object has no attribute 'n'
```

**Comment by casperdcl** [comment]
you clearly pass in `100` (as in `range(100)`) so should be using that hard-coded value in your loops instead of `tqdm.total` (or define a new variable `myTotal = 100`) and use that everywhere.

**Comment by casperdcl** [comment]
we definitely will not be able to add `n` when disabled.

**Comment by postelrich** [comment]
@casperdcl I corrected my example, still throws an error. If these attributes don't exist on disable, how can the disable feature work? I would expect to be able to use tqdm the same with/without it disabled, similar to disabling logging.

I was able to get it working by subclassing tqdm and setting those attributes to 0 on init.

**Comment by casperdcl** [comment]
By explanation, you are never meant to read `pbar.total` or `pbar.n` regardless of whether disabled is true or false. Neither attribute is part of the public API (well, `total` is a write-only attribute of the public API)

**Comment by casperdcl** [comment]
Functions (such as `update()` and `close()`) which are in the API will always work correctly. Hope this helps.

**Comment by lrq3000** [comment]
Yes the idea of tqdm is to offload the logic to manage a progress bar, so
users are not expected to directly access internal attributes (nor any
attribute in fact), only methods.

The only case where accessing attributes might be useful is when you want
to manage the display (eg, in your own GUI) of the progress bar, but for
that case we have a PR #223 in the works where you can provide a callback.

2017-02-14 23:04 GMT+01:00 Casper da Costa-Luis <notifications@github.com>:

**Comment by postelrich** [comment]
My use case is I am manually controlling the progress bar via `update`.  Through my use case, it may not always end at exactly 100% after the code executes, so I have a little check after execution to update it with the remainder by doing `pbar.update(pbar.total - pbar.n)`.

**Comment by casperdcl** [comment]
closing for now. Perhaps we should consider prefixing underscores on all of our variables that are intended to be private/protected.
