### ISSUE TITLE
Don't append ":  " to description string automatically

### ISSUE THREAD

**Issue by w1th0utnam3** [tqdm/tqdm#347]
In my opinion the `": "` which is automatically appended to the description string should be part of the format string, not of the description string. The reason is that the colon is only sensible in the front of the bar but you can move the description anywhere using the `bar_format` kwarg. Having a colon at any other position does not look nice.

Initially my motivation for this request was to display some additional variables, like `set_postfix` allows but with a custom format for numbers. So I tried using `set_description` for this which appends the `": "`. The alternative that I currently use is to convert all `dict` entries to `str` with the respective format. Nevertheless I think it would be sensible to remove the mentioned characters from the description.

This was already mentioned in [a comment](https://github.com/tqdm/tqdm/issues/343#issuecomment-277293329) on issue #343. Relevant [line of code](https://github.com/tqdm/tqdm/blob/master/tqdm/_tqdm.py#L706).

Additional remark: `postfix` is not mentioned in the `bar_format` docstring and in the github README as a variable for the format string.

**Comment by casperdcl** [comment]
Going to close this in favour of continuing discussion in #362
