### ISSUE TITLE
Bar is not drawn on Python 3 if .write() is used too soon

### ISSUE THREAD

**Issue by hynek** [tqdm/tqdm#348]
Consider the following program:

```python
import time

from tqdm import tqdm

with tqdm(range(5)) as bar:
    for i in bar:
        bar.write(str(i))
        time.sleep(1)
```

On Python 2.7, it does exactly what you’d expect.

On Python 3 (at least 3.5 and 3.6), the bar is not drawn until it’s closed.

If you move the `bar.write()` *behind* the `time.sleep(1)`, it works on Python 3 too.

Some kind of race condition?

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#help
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by lrq3000** [comment]
I think this is related to PR #331. Still have to fix some issues, but if
you can try it and tell us if it fixes the issue (or not), it would be
great :)

2017-02-14 16:41 GMT+01:00 Hynek Schlawack <notifications@github.com>:

**Comment by hynek** [comment]
It does indeed!

**Comment by ifly6** [comment]
I've got this problem running tqdm 4.29.1
