### ISSUE TITLE
Getting avg_time from tqdm

### ISSUE THREAD

**Issue by elbamos** [tqdm/tqdm#349]
Is there a reason `tqdm.__iter__()` doesn't update `self.avg_time` the way that `tqdm_update()` does?  

Compare https://github.com/tqdm/tqdm/blob/master/tqdm/_tqdm.py#L851 with https://github.com/tqdm/tqdm/blob/master/tqdm/_tqdm.py#L942

The issue is, I'd like to find get the average time from the `tqdm` object after I finish iterating through it. 

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#help
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by casperdcl** [comment]
grr they should be the same. Hard to keep this in sync (we duplicate code for performance reasons)

**Comment by elbamos** [comment]
So, are you going to go with `self.avg_time` or `avg_time`?  (My vote is `self.avg_time`.)  Anyway, looking forward to the fix, thanks!

**Comment by casperdcl** [comment]
Ah I see, `__iter__()` and `update()` are indeed synchronised, but `__iter__()` caches variables locally for speed optimisation purposes.

**Comment by casperdcl** [comment]
> The issue is, I'd like to find get the average time from the tqdm object after I finish iterating through it.

To do this, we could if you like add an extra line to `close()` to add/update `self.avg_time`
