### ISSUE TITLE
Missing total for DataFrame.progress_apply

### ISSUE THREAD

**Issue by kpj** [tqdm/tqdm#351]
Hello,

I am using tqdm version `4.11.2` and pandas version `0.19.2`.
When I try the minimal example
```python
import pandas as pd
from tqdm import tqdm

tqdm.pandas()
df = pd.DataFrame({1:[1], 2:[2], 3:[3]})
foo = df.progress_apply(lambda x: x+1)
```
the output is
```bash
4it [00:00, 2616.13it/s]
```
instead of a progressbar counting up to 4.

Am I missing something? I took a short [peek](https://github.com/tqdm/tqdm/blob/master/tqdm/_tqdm.py#L506) at the code, but `total` *seems* to be set correctly, so I am not sure what exactly is going on.

#299 seems to be a similar issue, but focuses on a different problem, I think.

**Comment by cancan101** [comment]
For some reason the total is set for Series but not for DataFrames. See: https://github.com/tqdm/tqdm/blob/ed6e0b4414e104caecc1bddbdec68001781c4ef3/tqdm/_tqdm.py#L511-L512:
```python
total = len(df) if isinstance(df, Series) else df.size // len(df)
```
where: `df.size // len(df)==1`

**Comment by cancan101** [comment]
I think the issue is whether the apply is along axis 0 or axis 1.

**Comment by kpj** [comment]
Perfect, it seems to work now.
Thanks a lot!

**Comment by casperdcl** [comment]
Great. Note to self: we should probably add a unit test to prevent against future regressions

**Comment by casperdcl** [comment]
think unit tests are now in #524
