### ISSUE TITLE
Binary unit prefixes with unit_scale

### ISSUE THREAD

**Issue by tobbez** [tqdm/tqdm#354]
When working with files and transfer rates it's usually more appropriate to use [binary unit prefixes](https://en.wikipedia.org/wiki/Binary_prefix) (`Ki` = 1024, `Mi` = 1024² etc.).

Currently there doesn't seem to be a way of doing that at all.

**Comment by casperdcl** [comment]
you can now use `unit_divisor=1024`, and if you want also `unit="iB"`

**Comment by tobbez** [comment]
Thanks!

**Comment by casperdcl** [comment]
Ah should also note as per docs `unit_divisor` is ignored when `unit_scale=False`

**Comment by sammko** [comment]
Using `unit="iB"` is not a solution, as if the speed goes down low enough, it will be shown without a prefix, just as iB, which is wrong.
