### ISSUE TITLE
Truncate infinite generators

### ISSUE THREAD

**Issue by williamsmj** [tqdm/tqdm#355]
I'd like to sample from an infinite generator. I am currently doing something like this, which seems extremely ugly:
```    
gen = itertools.count()
counts = []
for i in trange(N):
    counts.append(next(gen))
```
(in reality `gen` is a more interesting generator, but the point is it is infinite/has no `len()`). 

I'd love for this to work, but the generator is infinite, and is not truncated regardless of the `total=N` setting the scale of the tqdm progress bar.
```
counts = list(tqdm(gen, total=N))
```
Is there a reason this doesn't work? Would a PR to make it work be considered?

Or is there a better option? This is the best I could come up with:
```
counts = [x for x, _ in zip(gen, tqdm(range(N)))]
```

The following works, in the sense that `counts` is correct, and I get a correctly scaled progress bar, but it's not a lot less verbose than the `for` loop:
```
counts = list(tqdm(itertools.islice(gen, N), total=N))
```

The following gives me correct `counts`, but an `islice` object has no `len()`, so the progress bar has no scale/countdown.
```
counts = list(tqdm(itertools.islice(gen, N)))
```

**Comment by casperdcl** [comment]
Thanks @williamsmj this is the same issue as listed in https://github.com/tqdm/tqdm/#faq-and-known-issues with `zip` and `enumerate`. The "fix" is to do as you suggested, `[x for x, _ in zip(gen, tqdm(range(N)))]` or `list(tqdm(itertools.islice(gen, N), total=N))` since we cannot fix itertools (where the real problem lies)

**Comment by williamsmj** [comment]
I totally understand if you want `tqdm` to always be the identity function with some side effects, but if on the other hand you agree that
```
counts = list(tqdm(gen, total=N))
```
should work, something like this would get it done:
```
In [1]: def tqdm2(gen, total=None, *args, **kwargs):
   ...:     return tqdm.tqdm(itertools.islice(gen, kwargs.get('total', None)), *args, **kwargs)
   ...:
   ...:

In [2]: for i in tqdm2(itertools.count(), total=5):
   ...:     pass
100%|██████████████████████████████████████████████████| 5/5 [00:00<00:00, 142663.40it/s]
```
It's just syntactic sugar, but it does solve the problem.

I'm sure I'm missing edge cases, but even though the problem lies in the fact that an `islice` doesn't have a `__len__`, it is solvable by `tqdm`.
