### ISSUE TITLE
Scrolling behavior in jupyter notebook

### ISSUE THREAD

**Issue by braingineer** [tqdm/tqdm#358]
I can't find any github issues on this (sorry if I missed it).

![image](http://i.imgur.com/JlKFbbT.png)

Why would it scroll like this?

**Comment by ncullen93** [comment]
Also happens in jupyter console

**Comment by braingineer** [comment]
I've gotten a minimum working example now. brand new environment and everything:

```
import tqdm
import time


def runone(n, position=0, bar=None):
    if bar is None:
        bar = tqdm.tqdm(total=n, position=position)
    for _ in range(n):
        bar.update(1)
        time.sleep(0.01)
        yield

        
x = [runone(100, i) for i in range(3)]
for _ in range(100):
    for bar in x:
        next(bar)
```

**Comment by casperdcl** [comment]
yes, see #375... you need `tqdm_notebook`

**Comment by braingineer** [comment]
Thanks for reply.

@casperdcl  --- so the stance is that tqdm does not work for notebooks, period?

there is a bug, atm, w/ tqdm_notebok & jupyter lab (#394)

Best,
Brian

**Comment by casperdcl** [comment]
Yes, and we're not sure what exactly the bug is... seems to ne an upstream issue.

**Comment by braingineer** [comment]
Ok, just good to know :)

And that was my intuition for it as well. It always seemed to be something mysterious about how jupyter was rendering things in notebooks.

**Comment by casperdcl** [comment]
related: #443
