### ISSUE TITLE
tqdm_notebook sometimes creating 'Widget Javascript not detected.' rather than progress bar

### ISSUE THREAD

**Issue by nathanielatom** [tqdm/tqdm#360]
When using
```
from tqdm import tnrange, tqdm_notebook
from time import sleep

for i in tnrange(10, desc='1st loop'):
    for j in tqdm_notebook(xrange(100), desc='2nd loop'):
        sleep(0.01)
```
in the notebook, I get expected results about half the time. The other ~half of the time I get
```
[IPKernelApp] WARNING | Widget Javascript not detected.  It may not be installed or enabled properly.
```
 instead of a progress bar. Occurrences seem totally random from what I can tell.

I have run  `jupyter nbextension enable --py --sys-prefix widgetsnbextension`
and it spits out
```
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
```
but the issue persists.

Version info (all installed with conda):

python: 3.6
jupyter: 1.0.0
notebook: 4.4.1
ipywidgets: 6.0.0
tqdm: 4.11.2

**Comment by nykh** [comment]
I can confirm this

python 3.6.1
jupyter 1.0.0
notebook: 4.4.1
ipywidgets: 6.0.0
tqdm: 4.11.2

**Comment by ghego** [comment]
I can confirm this too:

python 3.6.2
jupyter 1.0.0
notebook 5.0.0
ipywidgets 6.0.0
tqdm 4.15.0

**Comment by Jessime** [comment]
I'm getting the same thing.

python 3.6.2
jupyter 1.0.0
notebook 5.0.0
ipywidgets 6.0.0
tqdm 4.15.0

`jupyter nbextension enable --py widgetsnbextension` does not seem to work for me.

**Comment by JBorrow** [comment]
Using ```jupyter nbextension enable --py widgetsnbextension``` worked for me.

**Comment by jeansoula** [comment]
I'm using: 
python 3.6
jupyter 1.0.0
notebook 5.0.0
ipywidgets 6.0.0
tqdm 4.15.0

And I did : `jupyter nbextension enable --py widgetsnbextension`

Then : `jupyter notebook` and finally  `restart the kernel` but I still got the same issue `Widget Javascript not detected.  It may not be installed or enabled properly.`

**Comment by Jessime** [comment]
Upgrading to `ipywidgets 7.0.0` seems to have cleared up the issue for me.

**Comment by JBorrow** [comment]
Could some of the people above who had issues please ensure that they have updated to 7.0.0 and check if it is working now?

**Comment by tsbertalan** [comment]
Cautiously, I'll say that I think this might have fixed it for me. I'll
report again after a week of usage.

**Comment by tsbertalan** [comment]
After a bit more than a week, I haven't felt the need to complain about
this, so I guess its fixed.

**Comment by lrq3000** [comment]
Yes this is an old issue with ipywidgets, glad to know they finally fixed it in the latest release :-) Thanks for the report!
