### ISSUE TITLE
Can i force a newline each refresh?

### ISSUE THREAD

**Issue by jhmenke** [tqdm/tqdm#361]
I have an application which runs from a multiprocessing.pool.
Currently, each thread in the pool uses a tqdm progress bar and overwrites the others. In this scenario i would like for each progress bar update to be shown in a new line, so that my console scrolls through the updates from each thread.

Is this doable with the current tqdm version?

**Comment by casperdcl** [comment]
Yes, see #329 and #291

**Comment by casperdcl** [comment]
Essentially each thread has an index which is used to position its bar on the correct line

**Comment by jhmenke** [comment]
Thanks! I searched for multiprocessing, but only among the open issues.

**Comment by casperdcl** [comment]
You're welcome!
