### ISSUE TITLE
notebook progress bar not closing

### ISSUE THREAD

**Issue by postelrich** [tqdm/tqdm#369]
Using ipython 4, I noticed that if I set `leave=False` for `tqdm_notebook` that they would remain after completion.  Looking into it further it seems that `ipywidget.HBox` has no `visible` attribute as used here: https://github.com/tqdm/tqdm/blob/master/tqdm/_tqdm_notebook.py#L146. What seems to be a good alternative is `HBox().close()`

**Comment by casperdcl** [comment]
duplicate of #352
