### ISSUE TITLE
Jupyter Notebook 5 support

### ISSUE THREAD

**Issue by Evfro** [tqdm/tqdm#371]
Currently, upgrading to the newest version of [Jupyter Notebook 5.0](http://jupyter-notebook.readthedocs.io/en/latest/changelog.html#notebook-version-5-0) breaks `tqdm_notebook` functionality. Would be nice to have a workaround or full solution for this.

Thanks!

**Comment by lrq3000** [comment]
Yes an upgrade will be done in June (or before if someone else tackles the
problem before me).

2017-04-09 11:12 GMT+02:00 Evgeny Frolov <notifications@github.com>:

**Comment by andrewzwicky** [comment]
I've been seeing #187 personally, so I'd like to take a look at this.  Have you worked on this so far?  If not, can you point me in the likeliest direction?

**Comment by TiesdeKok** [comment]
Yesterday I figured to code up a pull request to fix this as I use TQDM in my notebooks all the time, however, after updating: `jupyter`, `ipython`, `tqdm`, and `ipywidgets` it seems to work again. 

Can someone verify whether updating everything also works for them?

My gut feeling is that the code of tqdm notebook is fine, but that something changed with the way that `ipywidgets` works for `jupyter notebook 5`. Can someone that hasn't updated ipywidgets (and for which tqdm notebook doesn't work with Jupyter 5) try to see whether `ipywidgets` works? 

You can test it by running the code below, it should display a slider. 

```
from ipywidgets import IntSlider  
IntSlider()
```

**Comment by Evfro** [comment]
@TiesdeKok can you specify what version of ipywidgets should be considered as "not upgraded"? Currently I have v. '4.1.1' and it works in my Jupyter Notebook (I see a slider and can move it).

**Comment by TiesdeKok** [comment]
@Evfro I don't recall what version of ipywidgets I used to be honest. Does TQDM notebook work for you as well (with Jupyter Notebook version 5)?

It would be valuable to know whether you are able to use ipywidgets 4.1.1. but not TQDM notebook with Jupyter Notebook 5.

**Comment by Evfro** [comment]
@TiesdeKok strangely enough, now I cannot reproduce the problem. I'm not sure, whether I had ipywidgets 4.1.1 when I upgraded to Jupyter Notebook 5 first time. To summarize, I definitely did not upgrade anything when downgraded notebook to v. 4.4.1 (due to the issue). Now, when I upgraded notebook once again, it seems that tqdm is working.

**Comment by TiesdeKok** [comment]
@Evfro that is strange indeed, at least it is working now :smile:. My situation is similar, I thought the upgrading solved it, but given your case it might very well be something else that made it work again all of a sudden. Maybe the act of importing and using ipywidgets directly fixes the problem somehow?

**Comment by Evfro** [comment]
@TiesdeKok
> Maybe the act of importing and using ipywidgets directly fixes the problem somehow
I have checked that now. Even without ipywidgets import it works. :)

Would be interesting to see is whether it has something to do with the conflict within tqdm itself. What I mean is maybe tqdm breaks when notebook already has a "cached" progress bar, created in v.4 notebook and then you try to use it after the notebook upgrade without clearing the "cache". I call it cache, but probably it's something else, related to how tqdm operates with notebook. I just haven't looked into tqdm internals yet.

**Comment by cphyc** [comment]
Is it working now?

**Comment by Evfro** [comment]
@cphyc it works fine. However, if you still have issues with it after upgrading `jupyter notebook`, what I've found to be a solid workaround is to first uninstall `ipywidgets` and then reinstall it again. You may also have to additionally run `jupyter nbextension enable --py --sys-prefix widgetsnbextension`. Be sure to use `conda` if you installed jupyter with it. Or, if you have installed it with `pip`, then you should use `pip` for `ipywidgets` as well.

**Comment by maxim-lian** [comment]
Can this now be closed?

**Comment by chengs** [comment]
i think this problem is resolved
