### ISSUE TITLE
Automatic selection of backend (terminal or notebook)

### ISSUE THREAD

**Issue by flying-sheep** [tqdm/tqdm#372]
Hi, I’m the author of [smart-progress](https://github.com/flying-sheep/smart-progress), and wonder if you’d be interested in implementing its functionality here.

The detection basically happens [here](https://github.com/flying-sheep/smart-progress/blob/1091a0a9cc2d7a6304f992d13cb718d5150a64c6/smart_progress.py#L12-L21). I don’t use the notebook backend if:

1. `IPython.get_ipython` or `ipywidgets.FloatProgress` can’t be imported (then we can’t use it, duh), or
2. `get_ipython()` returns `None` (then we’re in a terminal), or
3. its return value isn’t an instance of `ZMQInteractiveShell` * (then we’re in `jupyter console`)

It’s a bit hackish, but maybe it would be useful for functions that can be used either from the notebook or the terminal.

---
*dunno why in the code i compared the class name instead of using `isinstance`; i should have commented that

**Comment by lrq3000** [comment]
Yes! Thank you very much, it will become part of #234!

**Comment by flying-sheep** [comment]
oh, cool. sorry for re-filing this, but i searched the issues! maybe i forgot to also search the PRs.

**Comment by lrq3000** [comment]
No problem, don't be sorry! You don't need to search if you offer code XD

2017-04-11 15:55 GMT+02:00 Philipp A. <notifications@github.com>:
