### ISSUE TITLE
Avoid use of setcheckinterval and/or setswitchinterval

### ISSUE THREAD

**Issue by maartenbreddels** [tqdm/tqdm#376]
Hi,

I noticed that using version 4.11.2 with my own multithreading caused [vaex](https://github.com/maartenbreddels/vaex) to slow down alot. I [found the issue](https://github.com/tqdm/tqdm/compare/v4.11.1...v4.11.2) to be the call to [setswitchinterval](https://docs.python.org/3/library/sys.html#sys.setswitchinterval) instead of [setcheckinterval](https://docs.python.org/3/library/sys.html#sys.setcheckinterval), which has different semantics. 
 * setcheckinterval takes as argument the # of instruction after which to do a context switch
 * setswitchinterval takes as argument the number of seconds after which to do a context switch, which is now set to 100. So it only does it after more than a minute!

Also, it affects the whole Python interpreter, isn't it better not to change this? And remove [this line](https://github.com/tqdm/tqdm/blob/a379e330d013cf5f7cec8e9460d1d5e03b543444/tqdm/_tqdm.py#L67) alltogether?

Relevent issues's PR's: #326 #319 

Thanks.

**Comment by lrq3000** [comment]
This line can be removed altogether, just needs to make sure it's set in
the unit test to avoid concurrency issues.

2017-05-01 10:45 GMT-04:00 Casper da Costa-Luis <notifications@github.com>:

**Comment by casperdcl** [comment]
Nice, thanks @lrq3000. Could you make a PR?

**Comment by maartenbreddels** [comment]
Maybe I haven't stressed it enough, but that line causes **all multithreaded** code in Python3+ to fail. I'm happy to do a PR to remove that line, but i'm not sure what is needed for the unit test.

**Comment by casperdcl** [comment]
ah. right. let's upgrade the priority

**Comment by casperdcl** [comment]
ah. right. let's upgrade the priority

**Comment by casperdcl** [comment]
Sorry this took so long :)
