### ISSUE TITLE
Not an issue, just some modifications I made for myself that I find useful

### ISSUE THREAD

**Issue by blaz62746** [tqdm/tqdm#379]
Hi,
first of all I really appreciate your work and this python module is just awesome.
However, I didn't like some little things so I modified them to suit me.
Here I post a modified .py file that suits me better and I would really like to see this changes in newer updates so that I don't need to change them for myself each time I update tqdm module. It's just a suggestion. Just change extension from .txt to .py.

Thanks.
[_tqdm.txt](https://github.com/tqdm/tqdm/files/980883/_tqdm.txt)

**Comment by casperdcl** [comment]
closed by #381
