### ISSUE TITLE
Ada ifo

### ISSUE THREAD

**Issue by budwons** [tqdm/tqdm#380]
- [ ] I have visited the [source website], and in particular
  read the [known issues]
- [ ] I have searched through the [issue tracker] for duplicates

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#help
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by casperdcl** [comment]
@budwons did you mean to open an issue here? If so, not sure what the issue is.

Thanks

**Comment by budwons** [comment]
Sorry. That was an error.
I did not mean to open an issue.
Best,
Bud
