### ISSUE TITLE
AttributeError: 'tqdm' object has no attribute 'fp'

### ISSUE THREAD

**Issue by fvisin** [tqdm/tqdm#383]
I am using my own stream handler as suggested in [[1]](https://github.com/tqdm/tqdm/issues/193#issuecomment-233212170) to use tqdm with a logger.

```python
class TqdmHandler(logging.StreamHandler):
    def __init__(self):
        logging.StreamHandler.__init__(self)

    def emit(self, record):
        msg = self.format(record)
        tqdm.write(msg)
```

The code crashes in some cases with "AttributeError: 'tqdm' object has no attribute ' when the `tqdm.write(msg)` command is issued. The culprit of the error is [here](https://github.com/tqdm/tqdm/blob/e18f20497b4253e21174d4114b22559db3f612ec/tqdm/_tqdm.py#L433): one of the elements in `_instances` has no attribute `fp`. 

From what I can tell an instance object with no `fp` attribute is created by the `__new__` method. Could it be the problem?

**Comment by MPagel** [comment]
maybe...
        for inst in getattr(cls, '_instances', []):
            # Clear instance if in the target output file
            # or if write output + tqdm output are both either
            # sys.stdout or sys.stderr (because both are mixed in terminal)
            inst_fp = getattr(inst,'fp',None)
            if inst_fp is not None and (inst_fp == fp or all(f in (sys.stdout, sys.stderr)
                                    for f in (fp, inst_fp))):
                inst.clear()
inst_cleared.append(inst)

Could even change the conditional to `if (inst_fp is not None and inst_fp == fp) or all(f in (sys.stdout, sys.stderr) for f in (fp, inst_fp))):` or eliminate the parentheses entirely as OOP doesn't matter (`or all(f in (sys.stdout, sys.stderr) for f in (fp, None))` should always be false

**Comment by duckythescientist** [comment]
This looks like a race condition, and I'm worried that there is also a deadlock issue. 

Here is a minimized test case:

```python
#!/usr/bin/env python3

import threading

from tqdm import tqdm


def race_write():
    while True:
        tqdm.write("spam")


def race_pbar():
    while True:
        for i in tqdm(range(2)):
            pass


t_write = threading.Thread(target=race_write)
t_pbar = threading.Thread(target=race_pbar)

t_write.start()
t_pbar.start()
```

Output (non-deterministic):
```
spam
spam
spam
spam
spam
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "tqdm_race.py", line 10, in race_write
    tqdm.write("spam")
  File "/usr/local/lib/python3.5/dist-packages/tqdm-4.19.2-py3.5.egg/tqdm/_tqdm.py", line 497, in write
    with cls.external_write_mode(file=file, nolock=nolock):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tqdm-4.19.2-py3.5.egg/tqdm/_tqdm.py", line 519, in external_write_mode
    if inst.fp == fp or all(
AttributeError: 'tqdm' object has no attribute 'fp'
```

**Comment by casperdcl** [comment]
I suppose the problem is that `inst` exists in `cls._instances` but is in the process of being deleted so `inst.fp` doesn't exist?

**Comment by duckythescientist** [comment]
I think it's during instantiation. `__new__` will make the class and add it to `cls._instances`, but because it hasn't had `__init__` called on it yet, it doesn't have the `.fp` attribute. I'm currently working on a fix. The band-aid that I posted above works in my test case, and it passes the unittests, but it's not as elegant as I would hope. I've also fixed the issue by acquiring the lock at the beginning of `__new__` and releasing it at the end of `__init__` (and also removing other lock/unlock statements in those methods). However, when testing this, the unittest for `TMonitor` hangs.

**Comment by casperdcl** [comment]
Could the current version's approach (vis. #493) help?

**Comment by casperdcl** [comment]
Is this still a thing with `tqdm>=4.21.0`?

**Comment by fvisin** [comment]
It's been some time since I last used that code, but I don't recall having errors the last times I executed it. It's probably solved, I will close the issue. Thanks!

**Comment by duckythescientist** [comment]
It's still an issue on 4.21.0. I just checked with my code.

**Comment by casperdcl** [comment]
thought so, thanks.
