### ISSUE TITLE
Nested Trees?

### ISSUE THREAD

**Issue by dstufft** [tqdm/tqdm#384]
I see how to handle nested progress bars, but I wonder if it's possible to have nested trees? If not is that something you could see yourself adding? This is sort of like what was asked in https://github.com/tqdm/tqdm/issues/312 except you want the ability to have multiple progress bars going at once. 

You can see an example of this at https://github.com/hfaran/progressive/.

**Comment by casperdcl** [comment]
you could make things tree-like...

```python
from tqdm import trange
from time import sleep


for i in trange(9, desc=' '):
    for j in trange(i, desc=' ' * 5):
        for k in trange(j, desc=' ' * 9):
            sleep(0.1)
print('\n')
```

```
 : 100%|█████████████████████████████| 9/9 [00:08<00:00,  1.69s/it]     : 100%|█████████████████████████| 8/8 [00:02<00:00,  2.03it/s]         : 100%|█████████████████████| 7/7 [00:00<00:00,  9.95it/s]
```

**Comment by dstufft** [comment]
If I'm not mistaken, while that displays as a tree, it only really allows you to advance the inner most progress bar doesn't it? One of the goals here is to have the inner most bars operate entirely independently of each other and they can be progressing in parallel (in say worker threads or something).

**Comment by casperdcl** [comment]
See #329, #285... Not tested and haven't added multithreading here but you get the idea:

```python
from tqdm import tqdm, trange
from time import sleep

a1 = tqdm(total=2, desc="a1", position=0)
b1 = tqdm(total=2, desc="  b1", position=1)
c1 = trange(9, desc="    c1", position=2)
c2 = trange(9, desc="    c2", position=3)
b2 = trange(9, desc="  b2", position=4)

def do(inner, outer):
    for i in inner:
        sleep(0.1)
    outer.update()

def do_b1():
    do(c1, b1)
    do(c2, b1)
    a1.update()

def do_b2():
    for i in b2:
        sleep(0.1)
    a1.update()

def do_a1():
    do_b1()
    do_b2()

do_a1()
print('\n' * 3)
```

**Comment by casperdcl** [comment]
closing as assumed solved. Happy to re-open if there are any more suggestions.
