### ISSUE TITLE
Update graphic

### ISSUE THREAD

**Issue by casperdcl** [tqdm/tqdm#39]
Update the gif animation (see redundant #38)

**Comment by lrq3000** [comment]
Yes that would be a good thing. As soon as someone upload the new gif animation, I will update the pypi page too :)

**Comment by lrq3000** [comment]
I tried to use Dreampie to recreate the gif anim with unicode smooth progress bar, but on Windows there's a bug, Dreampie doesn't support full unicode :S But I can make a demo in an IPython Notebook. Would that be OK?

**Comment by casperdcl** [comment]
A gif of some sort would have to replace what's up already. Doesn't have to be dreampie. A screen capture utility might be enough...

**Comment by lrq3000** [comment]
Yes I know we don't need dreampie but it was designed to have extended unicode support, but in fact it's limited on Windows, so I can't use the smooth bar inside a console, I can only do so inside an IPython Notebook. Would that be ok or would you prefer a screen capture of a console?

**Comment by casperdcl** [comment]
will also need to fix broken links (CONTRIBUTIONS, LICENCE) on pypi

**Comment by lrq3000** [comment]
@casperdcl fixed links: https://github.com/tqdm/tqdm/commit/3c5707e1b39f5558d72e2f33ad84b908331bea30

I will push to pypi when the makefile branch will be merged (I'm lazy to type all the commands manually :p)

**Comment by casperdcl** [comment]
Can you build and push to pypi @lrq3000 ? Thx.

**Comment by lrq3000** [comment]
Yes, I'm reviewing the changes right now and I'll update pypi in a few minutes.

**Comment by lrq3000** [comment]
Ok done, v2.2.3 is on PyPi :) BTW, I optimized the gif animation to set a fixed delay between each frame (else the animation could be too speedy on some browsers or gif viewers such as IrfanView) and to reduce file size. I also removed it from the builds so that the pypi download is reduced from ~700KB to 30KB!

**Comment by casperdcl** [comment]
Nice work. Don't know why it was in the build in the first place...

**Comment by lrq3000** [comment]
It was my fault, sorry, I thought it was a good idea :S But the previous gif was only 61 KB! But I guess it was possible to have such a tiny animation because the bar update wasn't smooth so there aren't as many frames as in the new animation.

**Comment by casperdcl** [comment]
Erm. Was a spacing bug in the makefile... could you push the fixed version? What utils did you use to optimise the gif, btw?

**Comment by lrq3000** [comment]
Oops sorry, that's the last command I have added at the last moment to fix an issue (ie, to force update MANIFEST.in). I have just released the latest version on PyPi and on Github.

About the gif animation, I have manually removed useless frames using GIMP :)

**Comment by lrq3000** [comment]
BTW, there is also a great gif compressor tool here:

https://github.com/pornel/giflossy

Usable online here:

http://ezgif.com/optimize

But it also reduces the quality so I avoided using it in the end.

**Comment by casperdcl** [comment]
Hah, I tried command-line optimisation and compression but never editing individual frames in gimp :)
