### ISSUE TITLE
How to not display ETA and rate

### ISSUE THREAD

**Issue by notuxius** [tqdm/tqdm#40]
how to disable viewing of ETA and it/s in progressbar for more minimal output

**Comment by lrq3000** [comment]
It's not currently possible to disable the ETA nor it/s, but you can resize the progress bar by using the `ncols` argument.

**Comment by lrq3000** [comment]
But if you really want to do that, and don't mind getting "hacky", you can manually edit these lines to remove what you don't want:

https://github.com/tqdm/tqdm/blob/master/tqdm/_tqdm.py#L135-L136

**Comment by casperdcl** [comment]
We could add arguments to disable eta, it/s if requested by enough other people. In the mean time, define your own format_meter function based on the comment above....

**Comment by lrq3000** [comment]
Just an idea: we could just add one parameter which would be a list of parameters to show. If none, then it would default to show all parameters.

**Comment by lrq3000** [comment]
Another way would be to directly let the user define the template of the bar, like they did here with the `format_str` argument:

https://github.com/aplavin/ipy-progressbar/blob/ipy2/ipy_progressbar/terminal_bar.py#L13

```
format_str='%(title)s: %(percent)3d%% [%(bar)s] %(current)d/%(max)d [%(elapsed).1f s] [eta %(eta_avg).0f+-%(eta_stddev).0f s]',
```

**Comment by casperdcl** [comment]
:+1: to the custom format (even though it will negatively affect speed)

**Comment by lrq3000** [comment]
Yes but the speed decrease will only appear if the user sets a custom
format, else the default format will be used so there won't be any
noticeable effect on speed (apart from the infinitesimal decrease due to
the added if statement ;) ).

2015-12-19 1:16 GMT+01:00 Casper da Costa-Luis <notifications@github.com>:

**Comment by casperdcl** [comment]
ok. all done (with custom format string)

**Comment by PyTis** [comment]
I am very confused.  Judging by reading all of this, you guys have since added in bar_format as an option.
Judging by the documentation,... l_bar='{desc}: {percentage:3.0f}%|'
So when I specify "for i in tqdm.tqdm(range(int(9e6)), ncols=0, bar_format='{l_bar}', postfix=None): pass"
I should only get the percentage, however, I am getting all output, minus the "bar" itself, which is controlled by ncols.  Can someone please help?

 79% 7141647/9000000 [00:03<00:00, 2126903.64it/s]

**Comment by casperdcl** [comment]
@PyTis that'a because you used `ncols=0`. From the documentation:


> ncols  : int, optional
>     The width of the entire output message. If specified,
>     dynamically resizes the progressbar to stay within this bound.
>     If unspecified, attempts to use environment width. The
>     fallback is a meter width of 10 and no limit for the counter and
>     statistics. **If 0, will not print any meter (only stats).**

I think you can drop the `ncols` argument in your case.

**Comment by PyTis** [comment]
_You were right!  Thank you so very much._  

**Now, my output is just a percentage, as desired, with one caveat, that I could "live" with, but would much prefer to do without.  The percentage is followed by a pipe ("|").**  

_Do you know how I can get rid of that?_

Last but not least question, though you need not answer this if you don't want to, I am sure I can figure it out on my own, but what is the "lightest" version of what I am using this for, that I can "export?"  I would rather just a single file to pull and add to my code base (proper copyright of original author left in place of course).  It would make packaging my project much easier, as it would remove the dependency.

If there isn't such a thing, well if it isn't easy I mean, then perhaps that should be a suggestion to the authors, to package a "light" percentage only version, or at least one where all of the code is,... what is the word I am looking for,... "simplified?"  "condensed?"... no,..  AH!  "Minified!"

**Comment by PyTis** [comment]
P.S.  I have "Watched" and "Stared" this project, I love it, I think it is a great, and very useful library!  Thank you very much.

I have some down time right now, and I am working on turning my 150+ personal scripts into useful, documented libraries myself.  They are all done, and working, but need "cleaned," and prepped for release.

**Comment by casperdcl** [comment]
@PyTis

> The percentage is followed by a pipe ("|").
>
> Do you know how I can get rid of that?

simply directly use `bar_format='{desc}: {percentage:3.0f}%'`

> what is the "lightest" version of what I am using this for, that I can "export?"
> [...] "simplified?" "condensed?"... no,.. AH! "Minified!"

Probably just `tqdm/*.py`: specifically, `_tqdm.py`, `_utils.py` and an edited `__init__.py`. See  https://github.com/conda/conda/tree/master/conda/_vendor/tqdm and future plans at https://github.com/tqdm/tqdm/pull/198#issuecomment-394184136

> I have some down time right now, and I am working on turning my 150+ personal scripts into useful, documented libraries myself. They are all done, and working, but need "cleaned," and prepped for release.

I can help with this and have done the same with some of my scripts - do you have any links to your current code?

**Comment by brando90** [comment]
I hate be a complainer to a library that seems to be so well mantained and used but the default setting are confusing. The ETA is shown (I presume) by a less than or equal:
```
  0%|          | 0/10 [00:00<?, ?it/s]i=0
 10%|█         | 1/10 [00:05<00:45,  5.00s/it]i=1
 20%|██        | 2/10 [00:10<00:40,  5.00s/it]i=2
 30%|███       | 3/10 [00:15<00:35,  5.00s/it]i=3
 40%|████      | 4/10 [00:20<00:30,  5.00s/it]i=4
 50%|█████     | 5/10 [00:25<00:25,  5.00s/it]i=5
 60%|██████    | 6/10 [00:30<00:20,  5.00s/it]i=6
```

I assume `00:05<00:45` means that 0.05 seconds have passed but the estimation is to take 0.45. Right?

Code:
```
#%%

from tqdm import tqdm
import time

for i in tqdm(range(10)):
    # time.sleep(0.1)
    time.sleep(5)
    print(f'{i=}')
```

**Comment by casperdcl** [comment]
`00:05<00:45` means 5 seconds have elapsed and a further (estimated) 45 remain. `<` is used as an ASCII arrow really rather than a less than sign.

**Comment by brando90** [comment]
> `00:05<00:45` means 5 seconds have elapsed and a further (estimated) 45 remain. `<` is used as an ASCII arrow really rather than a less than sign.
SO 
```
Extracting : six-1.16.0-pyhd3eb1b0_1.conda:   0%|          | 1/433 [05:18<38:15:04, 318.76s/it]
```
means 38 hours remaining?!

**Comment by matanox** [comment]
I guess it would be nice to have more examples on how to modify the progress bar line, in particular reducing the detail level that `35/121 [00:04<00:08, 10.63it/s]` is to just `35/121`, reducing and adding a la `35/121 segments`.
