### ISSUE TITLE
The canonical multiprocessing example displays only a single bar

### ISSUE THREAD

**Issue by mojones** [tqdm/tqdm#407]
I'm trying to use `tqdm` to monitor multiple FTP downloads using `ftplib`. Browsing around the documentation led me to this "canonical" example:

```
from time import sleep
from tqdm import tqdm
from multiprocessing import Pool, freeze_support

def progresser(n):
    text = "progresser #{}".format(n)
    for i in tqdm(range(5000), desc=text, position=n):
        sleep(0.001)

if __name__ == '__main__':
    freeze_support()  # for Windows support
    L = list(range(10))
    Pool(len(L)).map(progresser, L)
```

but on my system (Ubuntu 14.04, Python 3.4.3, tqdm 4.14.0) I get a mixture of empty lines, non-updating progress bars, and a single updating progress bar at the bottom:

![selection_035](https://user-images.githubusercontent.com/893512/27547700-b3b3687c-5a8e-11e7-8714-4d70933afbc2.png)

If I watch the bottom progress bar carefully I can see that the name occasionally changes, so I think that the progress bars are being drawn on top of one another. I've searched the issues and the closest thing I can find is this:

https://github.com/tqdm/tqdm/issues/285

but I don't think it's the same problem, as that issue reported multiple updating progress bars visible and I am only seeing one (the screenshots are very different). Let me know if I can provide any other info - I really want to use `tqdm` for this project but am out of depth when it comes to trying to figure out what's wrong.

**Comment by casperdcl** [comment]
This is annoying. It works fine on py27... There is indeed something weird with py3. Have you seen #329?

**Comment by mojones** [comment]
I did have a look at #329, but quickly reached the limit of my understanding when looking at the code examples :-). Entertainingly, when I run the canonical code under Python 2 on my system, I get a different result, though still not quite what is expected:

![selection_036](https://user-images.githubusercontent.com/893512/27558319-f1355e0a-5ab4-11e7-9034-ac7443c4d5c8.png)

Which seems to me like the progress bars are still overwriting each other, just in a different pattern.

**Comment by NoAnyLove** [comment]
The initialization of tdqm, update method and close method are not thread-safe. I searchd the issue, and found that pull#291 is trying to solve the parallelism output, but that code is not in current release, nor in master branch. You can use your own synchronization mechanism to solve this problem.

Besides, the progressbar at position 0 will have an extra line return appended when close it, as @lrq3000 mentioned in issue #329. An easy workaround is, starting from 1. I think it would be better to have an optinal parameter to determine this behavior.

A sample code 

```python
from multiprocessing.pool import ThreadPool
import time
import threading
from tqdm import tqdm


def demo(lock, position, total):
    text = "progresser #{}".format(position)
    with lock:
        progress = tqdm(
            total=total,
            position=position,
            desc=text,
        )
    for _ in range(0, total, 5):
        with lock:
            progress.update(5)
        time.sleep(0.1)
    with lock:
        progress.close()


pool = ThreadPool(5)
tasks = range(50)
lock = threading.Lock()
for i, url in enumerate(tasks, 1):
    pool.apply_async(demo, args=(lock, i, 100))
pool.close()
pool.join()
```

![screenshot](https://user-images.githubusercontent.com/1233483/29389305-5354c3f8-82b7-11e7-8946-a84e7e9085d3.png)

**Comment by casperdcl** [comment]
Thanks for this. I recall writing pretty much exactly this snippet ages ago but it must be lost in another issue somewhere.

**Comment by casperdcl** [comment]
Ah yes of course good ol' #329

**Comment by casperdcl** [comment]
Could you check out the updated branch at #329, and verify it works with:

```python
from multiprocessing.pool import ThreadPool
import time
import threading
from tqdm import tqdm


def demo(position, total):
    text = "progresser #{}".format(position)
    progress = tqdm(
        total=total,
        position=position,
        desc=text,
    )
    for _ in range(0, total, 5):
        progress.update(5)
        time.sleep(0.1)
    progress.close()


pool = ThreadPool(5)
tasks = range(50)
for i, url in enumerate(tasks, 1):
    pool.apply_async(demo, args=(i, 100))
pool.close()
pool.join()
```

**Comment by Guo-Zhang** [comment]
It still does not work on my Mac.
<img width="570" alt="image" src="https://user-images.githubusercontent.com/13083271/47271649-254a0a80-d541-11e8-9dea-8513112ba75b.png">

**Comment by celinew1221** [comment]
multiprocessing library updates Pool to class, I used this, but there's still bug:

```
from multiprocessing import Pool, Lock
import time
from tqdm import tqdm
lock = Lock()

def demo(position):
    text = "progresser #{}".format(position)
    total = 100
    with lock:
        progress = tqdm(total=total, position=position, desc=text)
    for _ in range(0, total, 5):
        with lock:
            progress.update(5)
        time.sleep(0.1)
    with lock:
        progress.close()

args = []
for i in range(50):
    args.append((i,))

with Pool(processes=5) as pool:
    pool.starmap(demo, args)
```
![image](https://user-images.githubusercontent.com/10788062/57945449-eb0ed480-78a7-11e9-9999-67004757eec5.png)

**Comment by pronkinnikita** [comment]
```python
from fastprogress import progress_bar
from multiprocessing import Pool


def process(n: int) -> int:
    return n ** 2

numbers = [1, 2, 3, 4]

with Pool(4) as p:
    res = p.map(process, progress_bar(numbers))
```

**Comment by casperdcl** [comment]
@pronkinnikita are you saying that if you replace `from fastprogress import progress_bar` with `from tqdm.auto import tqdm as progress_bar` your code stops working properly?

**Comment by pronkinnikita** [comment]
> @pronkinnikita are you saying that if you replace `from fastprogress import progress_bar` with `from tqdm.auto import tqdm as progress_bar` your code stops working properly?

Sorry, updated comment, now it seems fine. Nope, i think is works the same way with vanila tqdm.

**Comment by Vampire-Vx** [comment]
still have bug on canonical multiprocessing example...

**Comment by casperdcl** [comment]
are you sure the current version of https://github.com/tqdm/tqdm#nested-progress-bars doesn't run out-of-the box for you?

**Comment by aktiver** [comment]
@NoAnyLove great solution! how does one add a custom function to executed while TDDM tracks the functions execution process?

**Comment by raszpl** [comment]
Does this work correctly now? 
test case from https://github.com/tqdm/tqdm/issues/407#issuecomment-322932800 limited to 5 bars produces

when running:

> D:\_code>test.py
> 
> progresser #1:  20%|█████████████▏                                                    | 20/100 [00:00<00:01, 61.36it/s]
> progresser #2:  20%|█████████████▏                                                    | 20/100 [00:00<00:01, 61.92it/s]
> progresser #3:  20%|█████████████▏                                                    | 20/100 [00:00<00:01, 61.80it/s]
> progresser #4:  20%|█████████████▏                                                    | 20/100 [00:00<00:01, 61.48it/s]
> progresser #5:  20%|█████████████▏                                                    | 20/100 [00:00<00:01, 62.18it/s]
> 

but then when if finishes result is:

> D:\_code>test.py
> progresser #3: 100%|█████████████████████████████████████████████████████████████████| 100/100 [00:02<00:00, 49.34it/s]
> progresser #2: 100%|█████████████████████████████████████████████████████████████████| 100/100 [00:02<00:00, 49.31it/s]
> progresser #4: 100%|█████████████████████████████████████████████████████████████████| 100/100 [00:02<00:00, 49.31it/s]
> progresser #1: 100%|█████████████████████████████████████████████████████████████████| 100/100 [00:02<00:00, 49.27it/s]
> progresser #5: 100%|█████████████████████████████████████████████████████████████████| 100/100 [00:02<00:00, 49.23it/s]
> progresser #5: 100%|█████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 49.65it/s]

Whole thing shifts up one line, order randomizes and progresser #5 gets doubled. Gets even crazier if I set different Totals per invocation: 

when trying 
```
from multiprocessing.pool import ThreadPool
import time
import threading
from tqdm import tqdm


def demo(lock, position, total):
    text = "progresser #{}".format(position)
    with lock:
        progress = tqdm(
            total=total,
            position=position,
            desc=text,
        )
    for _ in range(0, total, position):
        with lock:
            progress.update(5)
        time.sleep(0.1)
    with lock:
        progress.close()


pool = ThreadPool(5)
tasks = range(5)
lock = threading.Lock()
for i, url in enumerate(tasks, 1):
    pool.apply_async(demo, args=(lock, i, i*100))
pool.close()
pool.join()
```

 I get 

> D:\_code>test.py
> progresser #1: 500it [00:10, 49.26it/s]
> progresser #3: 500it [00:10, 49.26it/s]
> progresser #5: 100%|█████████████████████████████████████████████████████████████████| 500/500 [00:10<00:00, 49.24it/s]
> progresser #2: 500it [00:10, 49.24it/s]
> progresser #4: 500it [00:10, 49.23it/s]
> progresser #5: 100%|█████████████████████████████████████████████████████████████████| 500/500 [00:10<00:00, 49.20it/s]
> D:\_code\disk mfm\sigrok-mfm\ci>

6 total bars, 4 of them went all the way to 500%

What am I doing wrong?
