### ISSUE TITLE
tqdm and dynamic set_postfix : set_postfix() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by apiszcz** [tqdm/tqdm#408]
This documented dynamic example is what I'm interested in using wrt set_postfix, However i have a  iterator from a zip function. So, I'm getting error about passing in 'self' when this is tried.

```
for x,y,z in tqdm(zip(items1,items2,items3)):
  tqdm.set_postfix(str='test')

Produces: set_postfix() missing 1 required positional argument: 'self'

No error with the following, ALSO no set_postfix fields shown
tqdm.set_postfix(self=tqdm,str='h')
```

Related
https://stackoverflow.com/questions/41171191/tqdm-progressbar-and-zip-built-in-do-not-work-together

**Comment by casperdcl** [comment]
I guess you closed this as you realised `zip` is not the issue here (though it also needs fixing). You need an instance to call `set_postfix()`:


```
with tqdm(items1) as t:
  for x,y,z in zip(t,items2,items3)):
    t.set_postfix(str='test')
```
