### ISSUE TITLE
Will tqdm support python `dictionary.items()`?

### ISSUE THREAD

**Issue by elcolie** [tqdm/tqdm#413]
I have read the example and docs.
`tqdm` is very great. Do you have any plan to implement `dictionary.items()` feature?
Will tqdm support python `dictionary.items()`?

**Comment by casperdcl** [comment]
Could you give a short example of what you mean?

**Comment by elcolie** [comment]
Python3.6.1
```python
for k,v in tqdm(my_dict.items()):
     pass
```

**Comment by casperdcl** [comment]
This works in py2.7. I haven't tested in py3.6 but presumably it should also be fine. Can anyone else confirm this issue?

**Comment by elcolie** [comment]
Sorry. I just minimize my case to smallest. I confirm it works in python3
I will ask another question.

```python
def test_tqdm():
    for i in range(1, 100001):
        my_dict = {
            str(i): str(i*i*i)
        }
    for k, v in tqdm(my_dict.items()):
        pass

if __name__ == "__main__":
    test_tqdm()

$ python experiments.py
100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29537.35it/s]
```
