### ISSUE TITLE
Why do I see multiple progress bars in one loop?

### ISSUE THREAD

**Issue by STDupont** [tqdm/tqdm#416]
Hi, 

I use PyCharm 2017.1.3 and see 2-3 progress bars (they appear-disappear all time, most of time I see 2 bars) during 1 loop running. I run simple downloading code of 1 file. Didn't find any similar cases here, so sorry if I missed them. 
Do you have any ideas of what could be the reason?

![question](https://user-images.githubusercontent.com/30659337/28876378-a9298320-77a1-11e7-925f-57d505e5807d.jpg)

**Comment by casperdcl** [comment]
See #307 #208 #203

**Comment by casperdcl** [comment]
Also https://github.com/tqdm/tqdm#faq-and-known-issues
