### ISSUE TITLE
Function tqdm_notebook has no attribute 'pandas' (Jupyter)

### ISSUE THREAD

**Issue by sortafreel** [tqdm/tqdm#419]
Don't really understand is it a mistake or just my local problem, still have some issues with using tqdm progress bars with _progress_apply_ in Jupyter.

**First try:**
```
from tqdm import tqdm
tqdm_notebook.pandas(desc="Example Desc")
keywords_df['keyword'] = keywords_df['keywird'].progress_apply(lambda x: x.replace('*',''))
```
**Output** (without any bars)**:**
`AttributeError: 'function' object has no attribute 'pandas'`

**Second try:**
```
from tqdm import tqdm
tqdm_notebook().pandas(desc="Example Desc")
keywords_df['keyword'] = keywords_df['keywird'].progress_apply(lambda x: x.replace('*',''))
```
**Output:**
Two bars (need one). First bar is empty (0it [00:00, ?it/s]), second is OK.

Any ideas how to change _progress_apply_ text and display bar without empty initialization bar? :)

**Comment by sortafreel** [comment]
Documentation (https://github.com/tqdm/tqdm) says I can just use tqdm_notebook, but it's not working for me :)
```
# Register `pandas.progress_apply` and `pandas.Series.map_apply` with `tqdm`
# (can use `tqdm_gui`, `tqdm_notebook`, optional kwargs, etc.)
tqdm.pandas(desc="my bar!")
```

**Comment by casperdcl** [comment]
notebook support is still in a (late) beta stage. The API might change slightly when we release `tqdm v5` but for now you probably need

```python
from tqdm._tqdm_notebook import tqdm_notebook

tqdm_notebook.pandas(...
```

**Comment by sortafreel** [comment]
Yup, it works great. You saved my day, thanks!

**Comment by javadnoorb** [comment]
@casperdcl that solution didn't work for me with tqdm 4.19.5. Trying the following in Jupyter notebook:

```
import numpy as np
import pandas as pd
from tqdm._tqdm_notebook import tqdm_notebook

df = pd.DataFrame(np.random.rand(10000),columns=['rand'])
tqdm_notebook.pandas('PROGRESS>>>')
df['result'] = df['rand'].progress_apply(lambda x:x**x)
```

leads to just one line saying "A Jupyter Widget" and no progress bar.

**Comment by casperdcl** [comment]
`tqdm_notebook.pandas('PROGRESS>>>')`? You probably need `tqdm_notebook.pandas(desc='PROGRESS>>>')`

**Comment by javadnoorb** [comment]
Still the same. Here's a screenshot of what I last tried:

![image](https://user-images.githubusercontent.com/26352146/37499001-e2ac1c1e-2897-11e8-8909-6413cac6dfb8.png)

**Comment by javadnoorb** [comment]
I just noticed that this seems to be an issue on that specific machine (which is on Google Cloud). Running it locally on my laptop works perfectly, and the graphics are actually very nice:

![image](https://user-images.githubusercontent.com/26352146/37499472-41420656-289a-11e8-8b79-8c55c2dfc460.png)

Not sure why this is the case. But I think I have a corrupted nbextensions on that Google machine, and I'm suspicious that may be the reason.

**Comment by javadnoorb** [comment]
I uninstalled and reinstalled nbextensions and installed ipywidgets afterwards. That fixed it.

**Comment by casperdcl** [comment]
nice, thanks @javadnoorb

**Comment by javadnoorb** [comment]
thanks for the reply @casperdcl
