### ISSUE TITLE
[Feature/wishlist] Negative update?

### ISSUE THREAD

**Issue by cdluminate** [tqdm/tqdm#432]
I went through the document and didn't find a way to roll the tdqm progress bar back. Trying to update the progress bar with a negative value just end up with an error.

```
In [31]: bar.update(-1)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-31-707a754749a6> in <module>()
----> 1 bar.update(-1)

/usr/lib/python3/dist-packages/tqdm/_tqdm.py in update(self, n)
    925 
    926         if n < 0:
--> 927             raise ValueError("n ({0}) cannot be negative".format(n))
    928         self.n += n
    929 

ValueError: n (-1) cannot be negative
```

Actually I intended to print the machine learning model accuracy `(\in [0,1])` with a progress bar library,
and the accuracy value while training is NOT monotonously increasing. Is there any workaround?

Thanks.

**Comment by casperdcl** [comment]
You have a couple of options.

1. have the bar be number of epochs or iteration number (monotonically increasing) and use `set_postfix` to add accuracy info

```python
from tqdm import tqdm
...
n = 1000
with tqdm(total=n) as t:
    def callback(classifier):
        t.update()
        t.set_postfix(acc=classifier.history[-1]['accuracy'])

    c = Classifier(..., max_epochs=n, on_epoch_finished=callback)
    c.fit(...)
```

2. manually set `n` and `refresh()`

```python
from tqdm import tqdm
...
with tqdm(total=100) as t:
    def callback(classifier):
        t.n = int(classifier.history[-1]['accuracy'] * 100)
        t.refresh()

    c = Classifier(..., on_epoch_finished=callback)
    c.fit(...)
```

**Comment by casperdcl** [comment]
in the second case you'd probably want to use the `bar_format` argument for `tqdm` since the ETA stats probably won't be useful.

**Comment by casperdcl** [comment]
@CDLuminate does this answer your question?

**Comment by casperdcl** [comment]
also see #374

**Comment by casperdcl** [comment]
We could allow negative updates and make it so that `refresh()` is automatically called in such cases, but this would add an overhead and perhaps make it easier to write buggy code. Right now `tqdm` will throw an exception of you have a negative update for something you expect to be monotonically increasing.

**Comment by CDLuminate** [comment]
@casperdcl Thank you for you answer. I'll try it out tonight. :-)
