### ISSUE TITLE
Question regarding bash for loop

### ISSUE THREAD

**Issue by tomers** [tqdm/tqdm#436]
I manage to run tqdm properly in bash, however I could not find a way to use it without a pipe, e.g. in a bash for loop:

```
for i in $(seq 0 1023); do
    tqdm # some parameters
    do_something
done
```
Any help would be appreciated

**Comment by casperdcl** [comment]
```bash
for i in $(seq 0 1023 | tqdm --total 1024); do
  do_something
done
```

**Comment by tomers** [comment]
Thank you very much!

**Comment by tomers** [comment]
The first suggestion is not good, since tqdm is filled entirely before processing completed. Please try the following example:

```
for i in $(seq 0 1023 | tqdm --total 1024); do
  sleep 1
done
```

**Comment by tomers** [comment]
I want to run the loop and capture output to a file. The other suggestion does not seem to work well. Please try:

```
#!/usr/bin/env bash

for i in $(seq 0 9); do
  sleep 1
  seq 1000 1999
done | tqdm --total 10 > out.txt
```

**Comment by casperdcl** [comment]
Yes, the second should work better,

> Assuming `do_something` has no output

If you do want stdout in your loop then you'd need

```python
#!/usr/bin/env bash

rm out.txt
for i in $(seq 0 9); do
  sleep 1
  seq 1000 1999 >> out.txt
done | tqdm --total 10
```

or count the output with eg `tqdm --total 1010`

**Comment by tomers** [comment]
Thanks @casperdcl, but unfortunately, this solution still doesn't work.

https://asciinema.org/a/4Wh71E8xpIIVGzF46dCjQTsry

**Comment by casperdcl** [comment]
missing the `echo $i` in the loop to let `tqdm` know which iteration you're at.

**Comment by casperdcl** [comment]
If you still have issues, #359 might be related

**Comment by tomers** [comment]
Still does not work as would be expected by the average user :-(

https://asciinema.org/a/UIlC8GgWmK257Ugxa0OfOdgHz

**Comment by casperdcl** [comment]
edited again now that I've actually run it... was missing `>> /dev/null`

**Comment by tomers** [comment]
Thanks! This code works:

```bash
#!/usr/bin/env bash

rm -f out.txt
for i in $(seq 0 9); do
  sleep 1
  echo $i
  seq 0 999 >> out.txt
done | tqdm --total 10 >> /dev/null
```

Thank you for making `tqdm`. It is a great utility! :-)

**Comment by casperdcl** [comment]
Great. But as I said, it's nicer if you know how many lines you expect and count all of them.

```bash
for i in $(seq 0 9); do
  sleep 1
  seq 1000 1999
done | tqdm --total 10000 > out.txt
```
