### ISSUE TITLE
tqdm.n not set when disabled

### ISSUE THREAD

**Issue by lichray** [tqdm/tqdm#438]
With `tqdm(disable=True)`, updating the progress bar causes
```
*** AttributeError: 'tqdm' object has no attribute 'n'
```
`self.n` should be initialized to `initial` before detecting `disable`, otherwise it's inconvenient to produce a mock object for the progress bar.

**Comment by casperdcl** [comment]
```python
from tqdm import tqdm

with tqdm(total=9, disable=True) as t:
    for x in range(9):
        t.update()
```

works for me

**Comment by casperdcl** [comment]
Oh are you referring to doing something like `t.n += 30` instead of `t.update(30)`? In that case, I'd call this a feature-not-a-bug since normally you shouldn't be accessing `n` directly.

**Comment by casperdcl** [comment]
Happy to reopen if I've misunderstood

**Comment by lichray** [comment]
???
I mean this
```
def cb(monitor):
    p.update(monitor.bytes_read - p.n)
```
It works for enabled tqdm, but not for disabled, and it's a normal usage.

Please reopen.

**Comment by casperdcl** [comment]
```python
def cb(monitor):
    p.update(monitor.bytes_read - getattr(p, 'n', 0))
```
... which is easy to do since you'd have to manually have other custom code, presumably `p.disable = self.disable` somewhere

**Comment by lichray** [comment]
I can of course workaround it, but is there any drawback for just setting `self.n` earlier?  Isn't making public members non-optional a good practice from a type system's point of view?

**Comment by casperdcl** [comment]
yes, but we never wanted `n` as public as such. Of course, in python, everything is public.

**Comment by lichray** [comment]
I don't know what do you mean of "as such" -- I copied your code from README:
```py
self.update(b * bsize - self.n) # will also set self.n = b * bsize
```
so it should work, but it doesn't when the program is piped to non-terminal, so it's a bug.

**Comment by casperdcl** [comment]
Hmm. Well I suppose it's minor to add the memory overhead of initialising `n` even when disabled.
