### ISSUE TITLE
Disabling stats

### ISSUE THREAD

**Issue by skinless8** [tqdm/tqdm#444]
Is there a way to suppress some of the statistics?

For example, if this is the normal view:
50%|████████████            | 2/4 [00:00<00:00, 4.06it/s]

I just want to show
50%|████████████            | 2/4

**Comment by casperdcl** [comment]
yes,

```python
tqdm(..., bar_format="{l_bar}{bar}|{n_fmt}/{total_fmt}")
```

**Comment by skinless8** [comment]
Thank you!

**Comment by casperdcl** [comment]
I'd actually recommend

```python
tqdm(..., bar_format="{l_bar}{bar}|{n_fmt}/{total_fmt}{postfix}")
```

just incase you want to use the `set_postfix`(`_str`) function
