### ISSUE TITLE
Colored Progress Bars

### ISSUE THREAD

**Issue by rafpyprog** [tqdm/tqdm#450]
With a few tweaks in the code I managed to add a color argument to tqdm.

![newgif1](https://user-images.githubusercontent.com/17583740/30978247-5925ad1e-a450-11e7-9f05-7ea07a46413b.gif)

Is this already an implemented feature ? Anyone likes it ?

**Comment by casperdcl** [comment]
colours seem a bit distracting. If you do want them:

```python
from tqdm import trange
from colorama import Fore


for i in trange(int(7e7),
                bar_format="{l_bar}%s{bar}%s{r_bar}" % (Fore.BLUE, Fore.RESET)):
    pass

 38%|█▌  | 26736903/70000000 [00:55<01:28, 486344.28it/s]
```

**Comment by Ehsan1997** [comment]
Both above mentioned methods are not working with notebook, any idea on why?

**Comment by casperdcl** [comment]
notebooks (`tqdm.notebook.tqdm`) are different. They don't appear to support colour

https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#IntProgress

**Comment by casperdcl** [comment]
Right... should be possible: https://github.com/jupyter-widgets/ipywidgets/issues/2982#issuecomment-699653659

```python
from tqdm.notebook import tqdm, trange

with trange(int(1e7)) as pbar:
    pbar.container.children[-2].style.bar_color = '#ffff00'  # or 'yellow'
    for i in pbar:
        pass
```
