### ISSUE TITLE
Wrong output in Windows console

### ISSUE THREAD

**Issue by vuki** [tqdm/tqdm#454]
Standard Windows 10 console (cmd.exe). Python 3.6.2. Test code:

```
import tqdm
import time

for i in tqdm.trange(10):
    time.sleep(0.1)
```
 Output: 
![clipboard01](https://user-images.githubusercontent.com/3974855/31056859-1f1f3730-a6d9-11e7-9300-41f89d02a298.png)

Is this expected? I'm sure it worked correctly in some older version.

**Comment by casperdcl** [comment]
which version of `tqdm` are you using?

**Comment by vuki** [comment]
tqdm==4.18.0

**Comment by casperdcl** [comment]
interesting. so windows is imcorrectly reporting the terminal width when you mess with fonts and scaling. you could always use `trange(..., ncols=75)` or whatever to fix the width

**Comment by vuki** [comment]
Setting `ncols` does not help. The progress bar is shorter but the text still wraps if the number of iterations is sufficiently large. Interestingly, I see the cursor positioned beyond the line (see screenshot) and it moves further with each iteration, eventually skipping to a new line.
![image](https://user-images.githubusercontent.com/3974855/31194196-aad12832-a946-11e7-91d2-41c0d0f86a8e.png)

Progress bar works fine with `ascii=True`. There is obviously an error with unicode characters in Windows console.

**Comment by casperdcl** [comment]
is this fixed if you install `tqdm` from the current `devel` branch?

**Comment by vuki** [comment]
Unicode support for Windows console was added in python 3.6. So it should work for me. Maybe the number of characters going backwards when updating the bar is calculated incorrectly? It's strange that the result depends on the font size. BTW, I believe that Unicode characters *are* widechars.

**Comment by casperdcl** [comment]
well, the true widths of many unicode chars are not wide, which some environments don't seem to understand

**Comment by IceflowRE** [comment]
I cant confirm the experience above inside the windows comand line. But i have this problems when i use the PyCharm console.

---

I only have problems with mutlithreading support, like i already mentioned in #329.

I get this output with unicode:
```
D:\Iceflower\programming\tqdm>python test.py
#0, est. 2.50s: 100%|█████████████████████████████████████████████████████████████| 5000/5000 [00:05<00:00, 840.30it/s]
#1, est. 1.70s:  99%|███████████████████████████████████████████████████████████? | 4936/5000 [00:05<00:00, 838.44it/s]
#1, est. 1.70s: 100%|█████████████████████████████████████████████████████████████| 5000/5000 [00:05<00:00, 838.20it/s]
#2, est. 1.20s: 100%|█████████████████████████████████████████████████████████████| 5000/5000 [00:05<00:00, 836.62it/s]
#3, est. 1.00s: 100%|█████████████████████████████████████████████████████████████| 5000/5000 [00:06<00:00, 833.22it/s]
#4, est. 0.83s: 100%|█████████████████████████████████████████████████████████████| 5000/5000 [00:06<00:00, 823.69it/s]
#5, est. 0.71s: 100%|█████████████████████████████████████████████████████████████| 5000/5000 [00:06<00:00, 830.42it/s]
#6, est. 0.62s: 100%|█████████████████████████████████████████████████████████████| 5000/5000 [00:06<00:00, 821.60it/s]
#7, est. 0.56s: 100%|█████████████████████████████████████████████████████████████| 5000/5000 [00:06<00:00, 816.37it/s]
#8, est. 0.50s: 100%|█████████████████████████████████████████████████████████████| 5000/5000 [00:06<00:00, 823.41it/s]
D:\Iceflower\programming\tqdm>
```

and this with `ascii=True`

```
D:\Iceflower\programming\tqdm>python test.py
#0, est. 2.50s: 100%|###########################################| 5000/5000 [00:05<00:00, 853.46it/s]
#1, est. 1.70s:  98%|##########################################2| 4917/5000 [00:05<00:00, 847.49it/s]
#1, est. 1.70s: 100%|###########################################| 5000/5000 [00:05<00:00, 848.74it/s]
#2, est. 1.20s: 100%|###########################################| 5000/5000 [00:05<00:00, 849.17it/s]
#3, est. 1.00s: 100%|###########################################| 5000/5000 [00:05<00:00, 844.14it/s]
#4, est. 0.83s: 100%|###########################################| 5000/5000 [00:05<00:00, 844.86it/s]
#5, est. 0.71s: 100%|###########################################| 5000/5000 [00:05<00:00, 841.36it/s]
#6, est. 0.62s: 100%|###########################################| 5000/5000 [00:05<00:00, 842.14it/s]
#7, est. 0.56s: 100%|###########################################| 5000/5000 [00:05<00:00, 842.64it/s]
#8, est. 0.50s: 100%|###########################################| 5000/5000 [00:05<00:00, 839.17it/s]
D:\Iceflower\programming\tqdm>
```

**Comment by Raymondlx** [comment]
Hey guys, thanks for your answers. 
I tried with setting `ascii = True`, then it works well on my windows.

**Comment by gmonkman** [comment]
On windows 10 development in PTVS, python dos console output looks as follows with simple range. Notice the odd \uXXXX chars at the end. This also causes status on each newline unless ncols reduced:
```
for x in tqdm(range(10000)):
        sleep(0.001)
```
![capture](https://user-images.githubusercontent.com/15924596/38055253-16c3b2f8-32d1-11e8-91e1-a4dacc7a23d0.JPG)

**Comment by casperdcl** [comment]
That's partial unicode support. You can probably fix it with `tqdm(..., ascii=True)`

**Comment by casperdcl** [comment]
@IceflowRE your PyCharm issue is mentioned in https://github.com/tqdm/tqdm#faq-and-known-issues

**Comment by casperdcl** [comment]
Might add to the FAQs that environments which lie about unicode support will also have problems without `ascii=True`

**Comment by gmonkman** [comment]
ta, yup, tried ascii=True after follow an earlier comment thread and did the trick.

**Comment by Feynt** [comment]
I can confirm this issue occurs on a Raspberry Pi when using the defaults.  Usually the bar flows as normal, but occasionally on both Windows (terminal emulator for zsh/ubuntu image) and Raspbian Buster it will show a standard replacement character (�) and skip a line.  The character may show up in a random location along the progress bar, not at the end.

ascii=True resolves the issue, but I kind of dig the smooth bar when it works.  Oddly it works most of the time, it's only once in a while that it happens.  Particularly for tracking the download of a larger file.  Terminal font shows as Monospace Regular according to LXTerminal in Raspbian Buster, and DejaVu Sans Mono for Powerline in mintty 3.0.0 running terminal emulation for WSL on Win10.

**Comment by Garve** [comment]
Still persists on Windows 10 terminal for me, also with ascii=True. Python 3.8.0, tqdm version 4.39.0.

**Comment by bobshih** [comment]
Hi,
Currently, I use tqdm in PuTTy.
The output progress bar is broken.
There are many new lines, like the image below.
Does any have idea to solve it?
Thanks in advance.
![image](https://user-images.githubusercontent.com/15016623/92215897-11ef8080-eec8-11ea-9dcc-cb250b720f38.png)

below is the locale setting.
![image](https://user-images.githubusercontent.com/15016623/92215951-2a5f9b00-eec8-11ea-86f5-8a3efa0e8a68.png)

**Comment by RawFisher** [comment]
> Hi,
> Currently, I use tqdm in PuTTy in windows 10.
> But the putty is connected to a linux server.
> The output progress bar is broken.
> There are many new lines, like the image below.
> Does any have idea to solve it?
> Thanks in advance.
> ![image](https://user-images.githubusercontent.com/15016623/92215897-11ef8080-eec8-11ea-9dcc-cb250b720f38.png)
> 
> below is the locale setting.
> ![image](https://user-images.githubusercontent.com/15016623/92215951-2a5f9b00-eec8-11ea-86f5-8a3efa0e8a68.png)
> 
> The version of tqdm I used is 4.48.2

![image](https://user-images.githubusercontent.com/26201819/105332785-f33c1d00-5c0f-11eb-8145-0d768928212e.png)
Do not tick this option
It works for me

**Comment by MacwinWin** [comment]
'ascii=True' still not work for me. But though the code below, the symptoms can be relieved a little.

```python3
import time
from tqdm import tqdm

with tqdm(total=3, desc='level_1', position=0, leave=False) as pbar:
    for i in tqdm(range(3)):
        for j in tqdm(range(5), desc='level_2', position=0, leave=True):
            time.sleep(0.1)
        pbar.update()
```
![3](https://user-images.githubusercontent.com/2640539/123225682-86ea8000-d505-11eb-8a65-027d946e2354.gif)

**Comment by casperdcl** [comment]
@MacwinWin sounds like you're missing `colorama` #1139 which should become automatic next release #1180

**Comment by MacwinWin** [comment]
@casperdcl  Thanks a lot.
![1](https://user-images.githubusercontent.com/2640539/123497651-46a01480-d661-11eb-97af-e681258da8ad.gif)

**Comment by LikeToAccess** [comment]
![image](https://user-images.githubusercontent.com/37591675/152960229-a208272c-3f8d-46d8-9117-7420a06032bd.png)
![image](https://user-images.githubusercontent.com/37591675/152960660-e93955e5-136d-4187-b8f9-cf365a9f9a26.png)
```python
# this is my tqdm function
for row in tqdm(file, total=file_line_count(file_path)):
```

There is still a small question mark/empty rectangle symbol appearing for me in the Windows Command Prompt and Windows Powershell.

This is running on Windows Server 2022 Datacenter 21H2 using Python 3.10.2 and tqdm-4.62.3.

**Comment by 1454147447** [comment]
Everytime I restart Terminal multiplexing like tmux or screen,many lines of tqdm will appear on the screen
![QQ图片20221006134224](https://user-images.githubusercontent.com/66127207/194223818-66eb4735-8e3c-4316-bab5-4778ac594d32.png)

**Comment by deseven** [comment]
If this is a known issue that even mentioned in the readme, why `ascii` is still `True` by default on Windows?
