### ISSUE TITLE
Example code snippet does not work as expected

### ISSUE THREAD

**Issue by danieldeutsch** [tqdm/tqdm#455]
I don't think this code snippet from the documentation works as expected. The progress bar only shows up after the loop is complete. (I added the time delay to highlight the problem)

```python
pbar = tqdm(["a", "b", "c", "d"])
for char in pbar:
    pbar.set_description("Processing %s" % char)
    time.sleep(1)
```

- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by chengs** [comment]
Eh, it works on Python 3.6 on my mac.
Can you give more information on this issue?

**Comment by casperdcl** [comment]
@danieldeutsch which version of `tqdm` are you using?

**Comment by danieldeutsch** [comment]
I was using 4.18.0 and python 3.5.2 on Ubuntu 16.04. It now works with version 4.19.4

**Comment by casperdcl** [comment]
Ok great, I thought it should be fixed now. We're finally getting close to [v5](https://github.com/tqdm/tqdm/milestone/8) and [awesomeness](https://github.com/vinta/awesome-python/pull/662#issue-160805918)!
