### ISSUE TITLE
`tqdm_notebook` fails with non-integer update.

### ISSUE THREAD

**Issue by tsbertalan** [tqdm/tqdm#456]
In a Jupyter notebook, if I do
```
import tqdm, time
pbar = tqdm.tqdm(total=10)
for k in range(10):
    pbar.update(.1)
    time.sleep(.1)
```
I get a bar with no problems, but
```
import tqdm, time
pbar = tqdm.tqdm_notebook(total=10)
for k in range(100):
    pbar.update(.1)
    time.sleep(.1)
```
fails with `ValueError: invalid literal for int() with base 10: '0.2'`. This worked until quite recently.

**Comment by casperdcl** [comment]
Could you post more traceback (including line of code in the tqdn library) and the version of tqdm you are using?

**Comment by tsbertalan** [comment]
Sure; a notebook displaying the problem and the saved output are [here](https://www.dropbox.com/sh/qqg80erofljcni5/AACy69N_1LtWeq4wxC5s2NgFa?dl=0).

The traceback itself is below:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-87a6f5d1d306> in <module>()
      2 pbar = tqdm.tqdm_notebook(total=10)
      3 for k in range(100):
----> 4     pbar.update(.1)
      5     time.sleep(.1)

~/venv3/lib/python3.5/site-packages/tqdm/_tqdm_notebook.py in update(self, *args, **kwargs)
    205             # as the interrupt will most likely happen on another statement
    206             self.sp(bar_style='danger')
--> 207             raise exc
    208 
    209     def close(self, *args, **kwargs):

~/venv3/lib/python3.5/site-packages/tqdm/_tqdm_notebook.py in update(self, *args, **kwargs)
    200     def update(self, *args, **kwargs):
    201         try:
--> 202             super(tqdm_notebook, self).update(*args, **kwargs)
    203         except Exception as exc:
    204             # cannot catch KeyboardInterrupt when using manual tqdm

~/venv3/lib/python3.5/site-packages/tqdm/_tqdm.py in update(self, n)
   1081 
   1082                     # Print bar update
-> 1083                     self.sp(self.__repr__())
   1084 
   1085                     if self.pos:

~/venv3/lib/python3.5/site-packages/tqdm/_tqdm_notebook.py in print_status(s, close, bar_style)
    122                     # Check that n can be found in s (else n > total)
    123                     if npos >= 0:
--> 124                         n = int(s[:npos])  # get n from string
    125                         s = s[npos + 3:]  # remove from string
    126 

ValueError: invalid literal for int() with base 10: '0.2'
```

**Comment by chengs** [comment]
@casperdcl Can you assign this to me? I've used tqdm for over a year. now it's time to contribute back.

**Comment by chengs** [comment]
tqdm_notebook is using IntProgress. Is any special reason for this? Why don't change to FloatProgress?

**Comment by casperdcl** [comment]
sure, happy to accept a PR. Is `IntProgress` more widely compatible than `FloatProgress`?

**Comment by chengs** [comment]
The simplest solution is to let tqdm_notebook not support decimal progress and convert decimal progress to int (e.g. *int(float(n))*). Nevertheless, tqdm support decimal progress in terminal. So this will make different behaviors between tqdm and tqdm_notebook.

Or we use FloatProgress instead of IntProgress.  Though FloatProgress exists since quite old Ipython version (2.X). I can't test the compatibility of FloatProgress because I don't have such an old ipython.

**Comment by casperdcl** [comment]
> So decimal progress support in tqdm is also incomplete.

What do you mean by this? What would the desired output be fo ryou to call it "complete?"

**Comment by chengs** [comment]
@casperdcl I mean that the tqdm has a minor problem in displaying decimal progress in the terminal, which shall be fixed.

For instance, 
```
10%|▉         | 0.9999999999999999/10 [00:00<00:09,  1.01s/it]
```

In the above case, the complete output will be 
```
9.9%|▉         | 0.99/10 [00:00<00:09,  1.01s/it]
```
or
```
10%|▉         | 1/10 [00:00<00:09,  1.01s/it]
```

**Comment by casperdcl** [comment]
you could replace `{n_fmt}` with `{n:.3g}` or similar:

```python
tqdm(...,
     bar_format="{l_bar}{bar}| {n:.3g}/{total_fmt} [{elapsed}<{remaining}, {rate_fmt}{postfix}]")
```

**Comment by chengs** [comment]
@casperdcl I have a fix on this issue. But it needs more tests, since the changing from IntProgress to FloatProgress is major and critical. We need to validate it on the past versions of ipython-notebook. It works on the lastest jupyter notebook.

**Comment by chengs** [comment]
@casperdcl I have updated my pull request.

**Comment by david-zwicker** [comment]
I also ran into this problem and couldn't find a workaround for `tqdm_notebook` to show float values. The workaround proposed by @casperdcl to replace `{n}` by `{n:.3g}` does not work anymore and raises the following errors:

```
/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/_tqdm_notebook.py in print_status(s, close, bar_style, desc)
    151                     # Check that n can be found in s (else n > total)
    152                     if npos >= 0:
--> 153                         n = int(s[:npos])  # get n from string
    154                         s = s[npos + 3:]  # remove from string
    155 

ValueError: invalid literal for int() with base 10: '0.2'
```

Clearly, `tqdm_notebook` was only designed to work with integers, but I don't see a good reason for the explicit cast to integers on line 153 mentioned above.

This occurred for tqdm version 4.29.1

**Comment by chengs** [comment]
#471 can fix this, but it is still under review.

**Comment by david-zwicker** [comment]
It looks as if this pull-request is hanging because of two simple PEP8 style violations. Is this the only thing that is missing or are there more pending items?

**Comment by casperdcl** [comment]
dropped off my radar, back on it :)

**Comment by david-zwicker** [comment]
Is there any update on this feature? Is there any way in which I could help? I'd really like to use this feature in one of my projects.

**Comment by casperdcl** [comment]
is this still an issue? seems to work fine for me now...

```python
import tqdm, time
pbar = tqdm.tqdm_notebook(total=10)
for k in range(100):
    pbar.update(.1)
    time.sleep(.1)
```

**Comment by david-zwicker** [comment]
Indeed, the progress bar is now displayed correctly. Thanks for fixing this!

**Comment by casperdcl** [comment]
ok closing for now, happy to re-open if still an issue

**Comment by narfanar** [comment]
The widget-based progress bar does not update fractionally.

Example:
![image](https://user-images.githubusercontent.com/5769148/64260560-5fd74e80-cf2b-11e9-950c-772ab0a110ba.png)

Points:
* Precision in the numerical progress is too high (not limited, AFAICT).
* The visual progress bar updates only on integer progress. changes (not sure whether it truncates or rounds).
