### ISSUE TITLE
No output on Python3

### ISSUE THREAD

**Issue by ericfrederich** [tqdm/tqdm#459]
On both Python 3.5 and 3.6 on Ubuntu I get no output from this script.

If I swap the order of `nothing` and `pb.set_description` then it magically works.

```python
#!/usr/bin/env python

from tqdm import tqdm

# didn't want to use time.sleep to ensure nothing was happening there; this is a real busy loop
def nothing(x):
    for i in range(x):
        for j in range(x):
            for k in range(x):
                pass


def main():
    with tqdm(list(range(100))) as pb:
        for thing in pb:
            pb.set_description('%-15s' % thing)
            nothing(300)


if __name__ == '__main__':
    main()
```

**Comment by casperdcl** [comment]
which version of `tqdm` are you using?

**Comment by ericfrederich** [comment]
`tqdm==4.19.1.post1`

**Comment by ericfrederich** [comment]
I did a `git bisect` and found 8c03307b7661406f2f2141ee94da8127c9761aed to be the offending commit
This script worked before that, but not after.

I just did this on Windows Python 3.6

**Comment by casperdcl** [comment]
Ah sorry just realised, now that I've run your code. This is expected behaviour. You're refreshing the bar too often (`set_description()` by default forces a refresh, see #317).

you need to let `tqdm` determine when to `refresh`:

````python
pb.set_description('%-15s' % thing, refresh=False)
````

The reason given in #317 for the change is that people usually want to force a refresh when setting pre/postfixes. If enough people think otherwise, we could change back to defaulting to `refresh=False`.

**Comment by casperdcl** [comment]
btw, your code could be a bit cleaner with `trange`:

```python
from tqdm import trange

# didn't want to use time.sleep to ensure nothing was happening there; this is a real busy loop
def nothing(x):
    for i in range(x):
        for j in range(x):
            for k in range(x):
                pass


def main():
    with trange(100) as pb:
        for thing in pb:
            pb.set_description('%-15s' % thing, refresh=False)
            nothing(300)


if __name__ == '__main__':
    main()
```

**Comment by MPagel** [comment]
> Ah sorry just realised, now that I've run your code. This is expected behaviour. You're refreshing the bar too often (set_description() by default forces a refresh, see #317).
> 
> you need to let tqdm determine when to refresh:
> 
> pb.set_description('%-15s' % thing, refresh=False)

If this was the explanation, he would still get output, it would just be "laggy" in that the display was hit with very frequent print requests. But not getting output at all suggests a deeper issue.

**Comment by casperdcl** [comment]
oh expletives. yes. argh. could you try the `devel` branch?

**Comment by MPagel** [comment]
apologies. I need my main script to run for a few days uninterrupted. I was down for a few days for non-tqdm reasons and I'm not sure how to replicate the problems I was having without just running my convoluted multithreaded production code. As 4.17.1 is stable for my purposes, I'll continue with that for a while.
