### ISSUE TITLE
Pip Install Fails for 4.19.1.post1

### ISSUE THREAD

**Issue by utkonos** [tqdm/tqdm#460]
The new version, 4.19.1.post1, fails to install using pip on python 3.6.2. This is on macOS and using homebrew python. The previous version installed just fine.

Here is the error output:

https://pastebin.com/v1kzb5aP

**Comment by casperdcl** [comment]
looks like you don't have a man directory? perhaps `brew install man` or similar? Not a Mac user so can't really comment

**Comment by casperdcl** [comment]
See here: https://stackoverflow.com/questions/22753738/pip-install-matplotlib-error-error-usr-local-man-man1-nosetests-1-permission#28359258

**Comment by utkonos** [comment]
Yes, it is because the man directory is missing, and /usr/local is owned by root:wheel. Thanks!

The answer is to create a /usr/local/man directory and then change its ownership to admin:admin (or whatever the name of your homebrew admin account is, but the group will still be admin).

BTW: The suggestion in that stackoverflow answer is very bad and insecure. If the answer to a question is to chmod 777 something, that answer is almost always automatically wrong.

**Comment by casperdcl** [comment]
yes, I saw that but let it go since it's only the local manuals being changed to world-writable in the SO suggestion, which is nowhere near as bad as, say, world-writable `lib` or `bin`

**Comment by jesstelford** [comment]
For future googlers:

```
sudo mkdir -p /usr/local/man
sudo chown -R "$USER:admin" /usr/local/man
```

**Comment by hugovk** [comment]
For future googlers, if you get `illegal user name` from chown (because `$USER:a` evaluates to pwd + username):

```sh
sudo mkdir -p /usr/local/man
sudo chown -R "${USER}:admin" /usr/local/man
```
