### ISSUE TITLE
deadlock between TMonitor.run and tqdm.__del__

### ISSUE THREAD

**Issue by mgraczyk** [tqdm/tqdm#469]
tqdm version: 4.19.2
python version: 2.7.14
platform: macOS 10.12.6

There is a deadlock in the call to `TMonitor.run` that can be triggered by the following execution. Below, the monitor thread's execution is prefixed with `T`, while the main thread is prefixed with `M`. Line numbers refer to [this commit](https://github.com/tqdm/tqdm/blob/533b89125b8ac3905e4f8bd864a033200391366e/tqdm/_tqdm.py).

```
1. T@123: Call to Tmonitor.run, runs until with self.tqdm_cls.get_lock()
2. T@137: Lock acquired using tqdm_cls.get_lock()
3. T@140: next() called on tqdm_cls._instances
4. T@886: __del__ called for a tqdm instance via WeakSet
5. T@1106: _decr_instances called on tqdm instance being closed
6. T@474: T attemps to aquire the lock that it already holds. Waits for release that never comes.
7. M@919: Main thread tries to use a tqdm instance.
8. M@969: Main thread tries to acquire lock held by T, hangs forever.
```

I don't think it is wise to try to acquire a non-reentrant lock in `__del__`.  It seems like this could be solved by using reentrant locks everywhere. Is there any reason to use `multiprocessing.Lock` instead of `multiprocessing.RLock` (also `threading.RLock`)?

**Comment by mgraczyk** [comment]
My workaround is to disable the monitor thread by calling `tqdm.tqdm.monitor_interval = 0` before using tqdm.

**Comment by llazzaro** [comment]
Hi,
I'm having the same issue.

**Comment by chengs** [comment]
@casperdcl about this problem caused by lock, how about letting TMonitor release the locks when it exits?

Precisely, TMonitor should ask for new MP and TP locks when it is created and release them when it is destroyed. Maybe can solve this problem.

**Comment by joelgrus** [comment]
we are running into what I think is this same issue on the latest version (unfortunately, I don't have a minimal reproduction).

basically, we are doing `tqdm.tqdm(some_generator())`, and if the generator throws an exception, `_decr_instances` hangs.

setting `monitor_interval = 0` prevents the bad behavior, so we did that as a workaround (but I don't 100% understand what the consequences of that are)
