### ISSUE TITLE
tqdm_notebook leave=False Leaves Whitespace Behind

### ISSUE THREAD

**Issue by utkonos** [tqdm/tqdm#479]
python 3.6.3

ipykernel (4.6.1)
ipython (6.2.1)
jupyter (1.0.0)
jupyter-client (5.1.0)
jupyter-console (5.2.0)
jupyter-core (4.4.0)
tqdm (4.19.4)

All installed by pip3 on macOS 10.13.1 and Chrome 62.0.3202.94 (Official Build) (64-bit)

I am seeing extra spaces added on redrawing nested progress meters. The inner meters slowly creep farther from the top bar. Here is a quick script that demonstrates the problem:

```
import tqdm

address_space = set()

for i in tqdm.tqdm_notebook(range(256), desc='First Octet'):
    for j in tqdm.tqdm_notebook(range(256), desc='Second Octet', leave=False):
        for k in range(256):
            for l in range(256):
                address_space.add('{}.{}.{}.{}'.format(i, j, k, l))
```

If you substitute the third and fourth nested `range(256)` with more tqdm, the problem is even more obvious.

I have attached an animated GIF of the problem.

![tqdm](https://user-images.githubusercontent.com/2775739/32856204-1d18f03c-ca12-11e7-8f43-f831b381ec69.gif)

**Comment by casperdcl** [comment]
wait this is #433

**Comment by gorogm** [comment]
Appears also with Windows, appears also in Firefox.

**Comment by joooeey** [comment]
This still happens on `v4.62.3` on Linux Mint 20.1 and Firefox 90.0.2.

**Comment by poldpold** [comment]
> This still happens on `v4.62.3` on Linux Mint 20.1 and Firefox 90.0.2.

Same on Chrome `90.0.4430.212` and Red Hat 8.4.

**Comment by thefrol** [comment]
Still on Firefox 94.0 on Ubuntu 18.04

**Comment by JRitmeester** [comment]
Still on Chrome `100.0.4896.127` on Windows 10. Will this ever get fixed?

**Comment by tommedema** [comment]
After much trial and error this is the only workaround that worked for me in JupyterLab:

```python
from IPython.core.display import HTML

# See https://github.com/bstriner/keras-tqdm/issues/21#issuecomment-443019223
display(HTML("""
    <style>
        .jp-OutputArea-child:has(.jp-OutputArea-prompt:empty) {
              padding: 0 !important;
        }
    </style>
"""))
```

**Comment by gersonjferreira** [comment]
it does not work on vscode

**Comment by utkonos** [comment]
@gersonjferreira I would open a new issue. The issue that I reported is fixed.

**Comment by thariq-nugrohotomo** [comment]
TqdmCallback for Keras doesn't have this issue.
