### ISSUE TITLE
Hide progress bar if iterating on empty list

### ISSUE THREAD

**Issue by eseiver** [tqdm/tqdm#486]
I have tqdm in for loops where the list may or may not be populated.
```
for x in tqdm(lst):
   y(x)
```
If `lst` is empty, when I run it on the command line it prints
`0it [00:00, ?it/s]`

Is there a parameter for suppressing this output? like:
`for x in tqdm(lst, hide_empty=True):`

In the meantime I've added an extra if statement, which I'd prefer not to do:
```
if lst:
    for x in tqdm(lst):
       y(x)
else:
    pass
```

**Comment by casperdcl** [comment]
```python
for x in tqdm(lst, disable=len(lst)==0):
    y(x)
```

**Comment by eseiver** [comment]
Thanks!

**Comment by casperdcl** [comment]
No problem. We don't include this by default as iterating an empty list is often a bug which tqdm explicitly informs you of.
