### ISSUE TITLE
progress_apply reports wrong total count

### ISSUE THREAD

**Issue by joders** [tqdm/tqdm#489]
I created a minimal replicating example:

import pandas as pd
from tqdm import tqdm 
tqdm.pandas()
df=pd.DataFrame({'a':np.random.randint(2,5,size=100),'a':np.random.randint(2,9,size=100)})
gb = df.groupby('a')
print("group count: " + str(len(gb)))
gb.progress_apply(lambda x:x)

group count: 7
100%|█████████████████████████████████████████████| 8/**8** [00:00<00:00, 1834.28it/s]

I did not find an open issue for this.

The relevant line in _tqdm.py is 

614:    `total += 1 # pandas calls update once too many`

https://github.com/tqdm/tqdm/blob/69ca16d6a8eae58737ebdaf7368090aab97dcb97/tqdm/_tqdm.py#L614

Python 3.6.1
pandas==0.20.3
tqdm==4.19.5

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by joders** [comment]
I think the problem might be that pandas is actually performing len(gb)+1 operations when you invoke apply on a group with len(gb) items. From the docs:

> In the current implementation apply calls func twice on the
    first group to decide whether it can take a fast or slow code
    path. This can lead to unexpected behavior if func has
    side-effects, as they will take effect twice for the first
    group.

**Comment by casperdcl** [comment]
yes, it's an upstream `pandas` issue, but if the display really annoys you, you could try:

```python
tqdm.pandas(unit_scale=len(gb)/(len(gb)+1.0))
```

**Comment by joders** [comment]
dealt with issue now by printing for the user:

15 items to be processed (needs 16 operations)

**Comment by chengs** [comment]
once #524 is merge, this will be fixed

**Comment by chengs** [comment]
Since #524 is merge, this can be closed. @casperdcl

**Comment by casperdcl** [comment]
@joders please try with `tqdm>4.20.0` happy to reopen if it doesn't work for you
