### ISSUE TITLE
unexpected new lines when using tqdm 

### ISSUE THREAD

**Issue by HaiyongJiang** [tqdm/tqdm#491]
When I used the tqdm, I got some unexpected newlines like: 
Training xx, epoch 1... 
Training xx, epoch 2...
Training xx, epoch 3...

Training xx, epoch 4...
Training xx, epoch 5...

Do you know what's the potential error in my program? The configuration of tqdm are "tqdm(iterator, total=100, leave=True, position=1, desc="XXX", miniters=1)".
 Thank you.

**Comment by casperdcl** [comment]
You seem to be printing information each epoch, which has nothing to do with `tqdm`. You could try replacing `tqdm(iterator, ...)` with just `iterator` to confirm that you still get the same output

**Comment by casperdcl** [comment]
closing since no response. Further information on work-arounds: https://github.com/tqdm/tqdm#redirecting-writing
