### ISSUE TITLE
ImportError: No module named 'tqdm'

### ISSUE THREAD

**Issue by lasmahei** [tqdm/tqdm#497]
When I try to install it on Ubuntu (16.04 LTS), Python 2.7, I keep getting:
ImportError: No module named 'tqdm'

It should be installed correctly:
pip install tqdm
Requirement already satisfied: tqdm in /usr/local/lib/python2.7/dist-packages
What am I doing wrong?
Thanks for your help.

**Comment by casperdcl** [comment]
You must have mismatched `pip` and `python`...

perhaps try `python -m pip install tqdm` and then `python -c 'import tqdm'`

**Comment by ypkkhatri** [comment]
I'm facing same issue:
```
myproject
    |
    +---> venv                    (where all the dependencies installed)
    +---> main.py
    +---> requirements.txt
    +---> workers
            |
            +---> __init__.py
            +---> worker1.py
            +---> worker2.py
```
I'm trying to access `from tqdm import tqdm` in worker1.py it throws an error:
`ModuleNotFoundError: No module named 'tqdm'`

How can I resolve this?

thanks

**Comment by casperdcl** [comment]
As I said before, you should really make sure the python interpreter you're using has `tqdm` installed. It looks like you're using a `virtualenv` so simply installing `tqdm`n(or anything else) for your system python won't do anything. It needs to be installed in your `venv`

**Comment by ypkkhatri** [comment]
@casperdcl Yes you right I'm using virtual environment, and `tqdm` is installed in `venv` but still throws an error

**Comment by casperdcl** [comment]
no, the error is not from `tqdm`. It is not installed in your environment. Before `import tqdm` you should run:

```python
import sys
print(sys.version, sys.platform, sys.executable)
```

**Comment by knageswara78** [comment]
In Anaconda, steps to install the package.

1. Navigate to ‘Environments” and Search for your package. 
2. That package will be displayed and click on Apply. 

Now the package is installed and it can be used right away.

Please share your feedback.

**Comment by bionicles** [comment]
i know i have it installed because when i run "python" in terminal, i can import tqdm, however when i run a script like python make-dataset.py it fails to import. why would import fail only in scripts but not in REPL?

**Comment by casperdcl** [comment]
Your repl and scripts/workers must have different envs.

Try running

```python
import sys
print(sys.executable)
```

**before** `import`ing `tqdm` in both your repl and scripts (and in each of your workers). the paths should match.

**Comment by cmeier303** [comment]
trying to install `conda install -c conda-forge python-graphviz` but it is returning an error ModuleNotFoundError: No module named 'conda._vendor.tqdm._tqdm

`conda install -c conda-forge tqdm` returns the same error.  

I found the package:  AppData\Local\Continuum\anaconda3\pkgs\tqdm-4.31.1-py37_1 and clicking on it as knageswara78 suggests does nothing other than a terminal pops and closes rapidly.  Not sure how to fix.

**Comment by casperdcl** [comment]
That's a conda issue, not tqdm. Looks like your conda installation is broken.

**Comment by samysa-kr** [comment]
> As I said before, you should really make sure the python interpreter you're using has `tqdm` installed. It looks like you're using a `virtualenv` so simply installing `tqdm` (or anything else) for your system python won't do anything. It needs to be installed in your `venv`

Weirdly enough my issue was solved by installing tqdm globally in my system. Your comment gave me the idea to try, since another library had already been sorted the same way.

I executed

**Comment by nbhanoo** [comment]
i solved the problem using pip install tqdm inside virtual environment
