### ISSUE TITLE
switch README to ReStructuredText from Markdown

### ISSUE THREAD

**Issue by kmike** [tqdm/tqdm#5]
pypi only renders rst nicely, so it is better to have README.rst instead of README.md.

**Comment by hadim** [comment]
hum... yeah I know that but I really prefer to keep Markdown because it's much more cleaner than .rst. And nowdays more people read the README from github than from pypi so I don't think it's going to be a problem.

**Comment by hadim** [comment]
And according to this https://bitbucket.org/pypa/pypi/issue/148/support-markdown-for-readmes, Markdown should be allowed in the future.

**Comment by hadim** [comment]
Well in fact it's already the fact to next pypi website : https://warehouse.python.org/project/request/

**Comment by kmike** [comment]
ok :)
