### ISSUE TITLE
Crash on Windows: OSError: raw write() returned invalid length

### ISSUE THREAD

**Issue by karlphillip** [tqdm/tqdm#505]
[This problem](https://stackoverflow.com/q/48371993/176769) happens when alternating between opened windows on Windows 10 (Python 3.4.4, tqdm 4.19.5):

```
Traceback (most recent call last):
  File "tqdmTest.py", line 5, in <module>
    for i in tqdm(range(counter)):
  File "C:\Users\brcod\AppData\Roaming\Python\Python34\site-packages\tqdm\_tqdm.py", line 979, in __iter__
    sp(self.__repr__())
  File "C:\Users\brcod\AppData\Roaming\Python\Python34\site-packages\tqdm\_tqdm.py", line 241, in print_status
    fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
  File "C:\Users\brcod\AppData\Roaming\Python\Python34\site-packages\tqdm\_tqdm.py", line 234, in fp_write
    fp.write(_unicode(s))
OSError: raw write() returned invalid length 306 (should have been between 0 and 153)
```

Sometimes a left-mouse click accidentally selects a few characters on the window while the progress bar is working and then a right-click (or even a key press) will activate the crash.

You can reproduce the problem on _cmd.exe_ or _Powershell_ with this simple application:
```
from tqdm import *
import time

counter = 1000
for i in tqdm(range(counter)):
     time.sleep(.01)
```

Can anyone share a little bit more info on why this happens and if this even tqdm's fault? Is there any workaround for this problem?

**Comment by karlphillip** [comment]
Right now [I am handling this situation](https://stackoverflow.com/a/48374209/176769) like this:

```
from tqdm import *
import time

maxCount = 1000
pbar = tqdm(total = maxCount)

for i in range(maxCount):
     i += 1

     try:
          pbar.update(i - pbar.n)
     except OSError as e:
          pass

     time.sleep(.01)

pbar.close()
```

But I wonder if there is a better way...

**Comment by casperdcl** [comment]
Doesn't sound like a `tqdm` issue. You could try:

```python
import time
import sys

maxCount = 1000

for i in range(maxCount+1):
    sys.stderr.write("\r%4d" % i)
    time.sleep(.01)
```

if that still crashes it can't be `tqdm`.

**Comment by karlphillip** [comment]
Running your code doesn't cause a crash. 

However, I can confirm that the problem happens when [**QuickEdit Mode**](https://imgur.com/a/466iC) is enabled in the properties of the cmd.exe window.

**Comment by casperdcl** [comment]
hmm. what about putting `sys.stderr.write(unicode("\r%4d" % i))` in my example? Really hoping that crashes (implying it's completely a windows issue). Otherwise it might be both `tqdm` and windows.

**Comment by casperdcl** [comment]
ah fun times. Sorry but not sure what we can do.
