### ISSUE TITLE
Automatically choose between tqdm and  tqdm_notebook

### ISSUE THREAD

**Issue by nthiery** [tqdm/tqdm#508]
Use case: writing a module that can be used from either the command line or the notebook

Desired feature: have some wrapper on top of tqdm that detects whether the code is running in a notebook or not, and automatically chooses between tqdm or tqdm_notebook; same for trange and tnrange.

(btw: kudos for tqdm; it's super useful for tracking lengthy computations!)

**Comment by casperdcl** [comment]
duplicate of #443

**Comment by nthiery** [comment]
> duplicate of [1]#443

Thanks for making the connection; #443 had slipped through my keyword
search.

**Comment by casperdcl** [comment]
no problem, feel free to volunteer an opinion there!
