### ISSUE TITLE
Put the tqdm position at the end of terminal

### ISSUE THREAD

**Issue by hildogjr** [tqdm/tqdm#514]
There is some way to force the tqdm position at the end of the terminal?
I will exemplify my desire with a video that shows this in the `apt` command: https://www.youtube.com/watch?v=9jNcjdQxEV8 3min42seconds.

This is nice to I use the process and log messages at the same time.

**Comment by chengs** [comment]
Not quite understand. But I think this *bar_format* parameters is what you need. Please check tqdm document. 

> bar_format : str, optional
Specify a custom bar string formatting. May impact performance. [default: ‘{l_bar}{bar}{r_bar}’], where l_bar=’{desc}: {percentage:3.0f}%|’ and r_bar=’| {n_fmt}/{total_fmt} [{elapsed}<{remaining}, ‘ ‘{rate_fmt}{postfix}]’ Possible vars: l_bar, bar, r_bar, n, n_fmt, total, total_fmt, percentage, rate, rate_fmt, rate_noinv, rate_noinv_fmt, rate_inv, rate_inv_fmt, elapsed, remaining, desc, postfix. Note that a trailing “: ” is automatically removed after {desc} if the latter is empty.

**Comment by casperdcl** [comment]
> use the process and log messages at the same time

I think you're referring to `tqdm.tqdm.write`.

```python
from tqdm import tqdm, trange
for x in trange(10):
  tqdm.write("hello")  # print("hello")
```

You can also integrate this with `logging`:

https://github.com/tqdm/tqdm/issues/313#issuecomment-346819396
