### ISSUE TITLE
ceLogic ID

### ISSUE THREAD

**Issue by brandonleon** [tqdm/tqdm#516]
- [ ] I have visited the [source website], and in particular
  read the [known issues]
- [ ] I have searched through the [issue tracker] for duplicates
- [ ] I have mentioned version numbers, operating system and
  environment, where applicable

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by casperdcl** [comment]
@brandonleon ?

**Comment by brandonleon** [comment]
Sorry, this was a mistake please close it out.
