### ISSUE TITLE
Bar doesn't display when on dict.iteritems()

### ISSUE THREAD

**Issue by DJSiddharthVader** [tqdm/tqdm#517]
OS: Ubuntu 12.04.5 LTS
tqdm version: 4.11.2

I have mydict.iteritems() nested inside of another loop, so it looks like 

```
for x in tqdm(outerloop, desc='files', position=0):
    for key, value in tqdm(mydict.iteritems(), desc='IDs in file', position=1):
            do stuff
            ....

print '\nFinished Cleaning Data'
```

The progress bar for the tqdm on mydict.iteritems() doesnt show up, only the iterations rate. This works when I just iterate over mydict.keys(), getting the right progress bars displaying, but not on mydict.iteritems()
![screenshot from 2018-03-01 11-08-14](https://user-images.githubusercontent.com/18082579/36855243-f079a08a-1d40-11e8-80c7-109ec0cad42a.png)

**Comment by casperdcl** [comment]
Iterators with no `len` (i.e. `len(mydict.iteritems())` fails) cannot provide `tqdm` with a total. You need:

```python
tqdm(mydict.iteritems(), total=len(mydict), ...
```
