### ISSUE TITLE
tqdm_notebook finishes with a new line

### ISSUE THREAD

**Issue by chengs** [tqdm/tqdm#519]
![screen shot 2018-03-05 at 11 02 03 am](https://user-images.githubusercontent.com/824529/36969872-f96a78f8-2066-11e8-80af-e02c853e03f9.png)

**Comment by chengs** [comment]
I would like to know if someone can reproduce this problem.
Perhaps it only happens on me.

**Comment by casperdcl** [comment]
possible duplicate of #433

**Comment by chengs** [comment]
@casperdcl yes, it is duplicate of #433, and is an upstream problem. I will close this. let's wait for ipython fix.
