### ISSUE TITLE
When using with while loop always tqdm starts at 0

### ISSUE THREAD

**Issue by innjoshka** [tqdm/tqdm#525]
I need to use while loop , progressing bar with not at 0 element but always tqdm shows me counter and bar from 0s even it counts from i=50 in my case. So, bar has to start at 50 and be at 50% filled progressing bar. Please try my snappet of code that I've attached below and you'll see that it works incorrectly. 

```
i = 50
pbar = tqdm(total=100)
while i <= 100:
    pbar.update(1)
    i +=1
pbar.close()
```

**Comment by casperdcl** [comment]
`tqdm(total=100, initial=i)`

**Comment by casperdcl** [comment]
also, consider instead:

```
from tqdm import trange
from time import sleep


for i in trange(50, 100):
    sleep(0.05)
```
