### ISSUE TITLE
Seemingly random deadlock in long processes

### ISSUE THREAD

**Issue by flyingdutchman** [tqdm/tqdm#528]
Hello !

While using tqdm i sometimes run into a deadlock. I just press Ctrl+C or Ctrl+Z and the porgram continues normally.

I then used this tool each time I ran my program : 

``` python
from hanging_threads import start_monitoring
monitoring_thread = start_monitoring()

```

And once in a while I run into this deadlock. And when this happens I press Ctrl+Z and get the following output :

``` console
---------           Thread 7592 hangs            ----------
        File "C:\Program Files (x86)\Python36-32\lib\threading.py", line 884, in _bootstrap
                self._bootstrap_inner()
        File "C:\Program Files (x86)\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
                self.run()
        File "C:\Program Files (x86)\Python36-32\lib\site-packages\tqdm\_monitor.py", line 60, in run
                with self.tqdm_cls.get_lock():
        File "C:\Program Files (x86)\Python36-32\lib\site-packages\tqdm\_tqdm.py", line 90, in __enter__
                self.acquire()
        File "C:\Program Files (x86)\Python36-32\lib\site-packages\tqdm\_tqdm.py", line 83, in acquire
                lock.acquire()
```

I'd like to give more information but it is all I have at the moment. I have no idea how to debug these kind of situation. If you give me some instructions I'll be glad to help !

**Comment by casperdcl** [comment]
this trace just shows waiting for acquisition of a lock. Does your program have the ability to show a trace of what already acquired that lock? Currently there's no proof that this is a deadlock...

**Comment by flyingdutchman** [comment]
I can't seem to be able to reproduce the issue in a controlled environnement...

I'll work out a way and create a new issue when I have more details !

Sorry for the bother

**Comment by casperdcl** [comment]
ok thanks. It may be a bug in your program.

**Comment by veegee** [comment]
I have this _exact_ same issue, and my program is single threaded, and not using any locks. I think this is a bug in tqdm.

**Comment by chengs** [comment]
@veegee It's really wired and hard to locate the problem. Could you show your code? I understand perhaps it needs a bit of luck to reproduce the bug, but even such codes will help.

**Comment by black-puppydog** [comment]
I also have this problem, running code based off this one:
https://github.com/leongatys/PytorchNeuralStyleTransfer

The notebook itself doesn't use threading or locks, but I guess pytorch has a fair bit of that...

**Comment by koriakin** [comment]
I have traced this down to a pypy bug (https://bitbucket.org/pypy/pypy/issues/2953/deadlock), see https://gist.github.com/koriakin/97bba413a87bd8f13f6d8d0b84382644 for the reduced testcase.

**Comment by Mehechiger** [comment]
> I have traced this down to a pypy bug (https://bitbucket.org/pypy/pypy/issues/2953/deadlock), see https://gist.github.com/koriakin/97bba413a87bd8f13f6d8d0b84382644 for the reduced testcase.

I have the same issue but It occurs only with pypy+tqdm, abandon either seems to solve the pb, but ... don't wanna do that....

**Comment by koriakin** [comment]
The fix has now been merged to upstream pypy (see https://bitbucket.org/pypy/pypy/issues/2953/deadlock), does anyone have time to try with a nightly build?

**Comment by koriakin** [comment]
Also, this is a duplicate of #627 (assuming the original reporter was also on pypy, which seems likely).

**Comment by casperdcl** [comment]
thanks @koriakin
