### ISSUE TITLE
4.19.7 and 4.19.8 have no release notes

### ISSUE THREAD

**Issue by benjaoming** [tqdm/tqdm#529]
Hi friends,

I noticed that the past two releases are merges of the `devel` branch, but contain no release notes. It's kind of hard to figure out what they are about?

Also, the change log service in use isn't configured correctly: https://allmychanges.com/p/python/tqdm/

Thanks for a great project!

Ben

**Comment by casperdcl** [comment]
btw I just added https://github.com/tqdm/tqdm/wiki/Releases using the github API, but it's only the last 30 releases. Will add release notes for >=4.19.7 soon. It's all related to the monitor thread (#527/#522/#493)

**Comment by benjaoming** [comment]
Thanks @casperdcl for the clarification, will look into whether we need to upgrade then :)

**Comment by casperdcl** [comment]
done (https://github.com/tqdm/tqdm/releases/)

**Comment by benjaoming** [comment]
Thanks for fixing! :)
