### ISSUE TITLE
Support for tqdm progress bars for "rolling" windows in Pandas

### ISSUE THREAD

**Issue by vgoklani** [tqdm/tqdm#530]
Hello - would it be possible to support rolling windows in Pandas when using tqdm?

df['apply_field'] = df['field'].rolling(30).progress_apply(decompose)

will raise this:

AttributeError: 'Rolling' object has no attribute 'progress_apply'

**Comment by chengs** [comment]
Let me do some investigation on it.

**Comment by chengs** [comment]
unfortunately, there is no elegant way to add progress_apply

**Comment by casperdcl** [comment]
`total=None` seems good to me until someone bothers to implement something better

**Comment by chengs** [comment]
ok then. Working on it.

**Comment by chengs** [comment]
@vgoklani so, due to the discussion above, I am sorry but so far it's only possible to add a progress_bar without percentage XXX/XXX.

**Comment by casperdcl** [comment]
8b0bdc6 will allow you to manually specify a `total`, though.
