### ISSUE TITLE
Possibly bug when running with Itertools product?

### ISSUE THREAD

**Issue by v2thegreat** [tqdm/tqdm#536]
Hey, I tried to use the following code and it did not include the progress bar:

```
from tqdm import tqdm
from itertools import product

for a,b,c in tqdm(product(rn, rn, rn)):
    if a+b+c == 1000:
        l.append((a,b,c))
```
This is how the code runs: 

![screenshot 17](https://user-images.githubusercontent.com/22357311/38711262-afefd11a-3e92-11e8-8dbc-51e73d6658c3.png)

Any help on what's going on?

**Comment by casperdcl** [comment]
unfortunately due to things like `itertools.product` not providing a length (see https://github.com/tqdm/tqdm#faq-and-known-issues) `tqdm` has no way of ascertaining the total. You could do `product(tqdm(rn), rn, rn)` instead, or:

```python
with tqdm(total=len(rn)**3) as t:
    for a, b, c in product(rn, repeat=3):
        l.append((a,b,c))
        t.update()
```
