### ISSUE TITLE
'tqdm' object has no attribute 'total' when using 'disable' and multiprocessing 'Pool'

### ISSUE THREAD

**Issue by NOhs** [tqdm/tqdm#539]
The following MWE shows how to get the error message described in the title:

```python
from tqdm import tqdm
from multiprocessing import Pool

def f(arg):
    pass

if __name__ == '__main__':
    pool = Pool()
    list(tqdm(pool.imap(f, range(100)), disable=True))
```

- tqdm Version: 4.22.0
- python 3.6.0
- Win64

It works, when the `disable=True` is removed or set to `False`. But it should also work for the disabled case I would guess.

**Comment by casperdcl** [comment]
confirmed on linux py35
