### ISSUE TITLE
Windows 10 bug

### ISSUE THREAD

**Issue by iperov** [tqdm/tqdm#556]
code used:
`for s in tqdm( RAWS, desc="Loading" ):`

Windows 10 behaviour:
<img width="681" alt="1" src="https://user-images.githubusercontent.com/8076202/40266760-e9202fa2-5b61-11e8-8528-e9a71534783c.png">

Windows 10 has NO customizations, no font changed, no scale, etc. Just installed clean Windows 10, updated to last version, and launch python.

Windows 7:
![cmd_2018-05-19_12-41-42](https://user-images.githubusercontent.com/8076202/40266768-fa055360-5b61-11e8-83e4-d20e810e9b9b.jpg)

```
print(tqdm.__version__, sys.version, sys.platform)
4.23.3 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] win32
```

**Comment by casperdcl** [comment]
Thanks, will have to check this on a windows 10 machine again. You can use `ascii=True` to fix this for now (probably).

**Comment by ligz08** [comment]
I'm experiencing the same issue on a Windows 10 machine (in both cmd and PowerShell).
Using `ascii=True` does solve it. 

My environment:
```
>>> print(tqdm.__version__, sys.version, sys.platform)
4.23.3 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] win32
```

**Comment by iperov** [comment]
@casperdcl can you add func to set ascii=True globally by default?

**Comment by casperdcl** [comment]
we might do `ascii=IS_NIX` if enough people want it. I prefer letting people consciously notice how bad Windows has been about unicode support.

**Comment by iperov** [comment]
how about global default setting ?

**Comment by casperdcl** [comment]
Oh I think I know what you mean. As in just for your code without having to constantly write `ascii=True`?

```python
from tqdm import tqdm as core_tqdm

class tqdm(core_tqdm):
    def __init__(*args, **kwargs):
        kwargs.setdefault("ascii", True)
        super(tqdm, self).__init__(*args, **kwargs)
```

**Comment by casperdcl** [comment]
btw I tried win10 (powershell as well as Anaconda Prompt and cmd) - can't reproduce the bug.

**Comment by ligz08** [comment]
Could it have to do with the April 2018 Windows update (v.1900)?

**Comment by iperov** [comment]
but Chinese Windows 10 still buggy
![7-3 1](https://user-images.githubusercontent.com/8076202/51171873-6bf29b00-18cb-11e9-9d49-daa3624969a5.jpg)

**Comment by iperov** [comment]
![4-1 1](https://user-images.githubusercontent.com/8076202/51172495-c8a28580-18cc-11e9-8a3f-e5cc27a4a4dd.jpg)

**Comment by casperdcl** [comment]
vis. https://github.com/tqdm/tqdm/issues/662#issuecomment-457292595  #556, #200, #499, #454, #307...
