### ISSUE TITLE
Newlines left behind with tqdm_notebook when leave=False

### ISSUE THREAD

**Issue by kotoroshinoto** [tqdm/tqdm#560]
The outer loop is still where it belongs, but the inner loops keep adding more and more whitespace to the gap
for completeness: tqdm version is 4.23.0, notebook version is 5.4.1, ipywidgets is 7.1.2, ipykernel: 4.8.2
![newlines](https://user-images.githubusercontent.com/1337560/40493984-ce225836-5f41-11e8-82c7-43202dc8f1f4.PNG)

**Comment by casperdcl** [comment]
dupe of #433, #550
