### ISSUE TITLE
smoothing not working

### ISSUE THREAD

**Issue by simonm3** [tqdm/tqdm#566]
The smoothing function does not work. Both the examples below show same result in a notebook. 50% 5/10 [00:15<00:15, 3.01s/it]

I think problem is in tqdm.py where it sets "avg_time=self.avg_time". Then around line 943 sets avg_time but never uses this variable nor assigns it back to self.avg_time.

```
from tqdm import tqdm_notebook as tqdm
from time import sleep
for x in tqdm(range(10), smoothing=0):
    if x==0:
        sleep(10)
    sleep(1)
    if x==5:
        break
```

```
from tqdm import tqdm_notebook as tqdm
from time import sleep
for x in tqdm(range(10), smoothing=1):
    if x==0:
        sleep(10)
    sleep(1)
    if x==5:
        break
```

**Comment by chengs** [comment]
does it work on normal tqdm? (not tqdm_notebook)

**Comment by chengs** [comment]
@simonm3 Yes, you're right! This is definitely a bug. Both tqdm and tqdm_notebook do not work.
And your suggestion is likely to be the way to fix it.
