### ISSUE TITLE
Changing (reducing) width of console window causes newlines at progress bar update

### ISSUE THREAD

**Issue by Tom-Evers** [tqdm/tqdm#568]
Default behavior of a 'new' progress bar is to conform to the width of the console.
![image](https://user-images.githubusercontent.com/10848631/41764460-797be190-7601-11e8-8acc-4573e1a48dd2.png)

But when that width changes before the loop is completed (in other words, before 100%), it causes a newline _inside_ the tqdm output, causing some undesirable behavior:
Updates to the bar (and information) no longer change the original instance, but create another instance on the next line.
![image](https://user-images.githubusercontent.com/10848631/41764587-e677c84a-7601-11e8-9694-5fc120fbcedc.png)

**Comment by casperdcl** [comment]
`tqdm(..., dynamic_ncols=True)`
