### ISSUE TITLE
Deadlock with a value referencing a tqdm instance

### ISSUE THREAD

**Issue by kamo-naoyuki** [tqdm/tqdm#571]
- [x] I have visited the [source website], and in particular read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and environment

```
OS: CentOS Linux release 7.3.1611 (Core) 
tqdm: 4.23.4
python: 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 18:21:58) 
```
I'm sorry if you've already known this  issue, or it is in the specification, because it's too easy to reproduce...

```python
import tqdm
ite = tqdm.tqdm(range(10))
raise RuntimeError
```

This code causes a deadlock.　Of course, the following is o.k.

```python
import tqdm
for i in tqdm.tqdm(range(10)):
    raise RuntimeError
```

**Comment by casperdcl** [comment]
possibly related: #548 #445 #528 #469

**Comment by yakirwin** [comment]
Couldn't reproduce on python v2.7.12, tqdm v4.23.3:
V yakirw$ python bla.py
  0%|                                                                                                                                    | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):
  File "bla.py", line 3, in <module>
    raise RuntimeError
RuntimeError
Exception KeyError: KeyError(<weakref at 0x7f7a682ee0a8; to 'tqdm' at 0x7f7a66fb9490>,) in <bound method tqdm.__del__ of   0%|                                                                                                                                    | 0/10 [00:00<?, ?it/s]> ignored

**Comment by casperdcl** [comment]
Might be a python 3 issue?

**Comment by kamo-naoyuki** [comment]
I got the minimum reproducing, but I don't understand why it happens. Python3's bug?

(Named tqdm.py)
```python
from threading import Event, Thread
class TMonitor(Thread):
    def __init__(self):
        Thread.__init__(self)
        self.daemon = True
        self.was_killed = Event()
        self.start()

    def exit(self):
        self.was_killed.set()
        self.join()

    def run(self):
        # Blocking here
        self.was_killed.wait(1)
        # Cannot reach

class tqdm:
    def __init__(self):
        self.monitor = TMonitor()

    def __del__(self):
        self.monitor.exit()
```
```python
from tqdm import tqdm
a = tqdm()
raise RuntimeError
```

**Comment by casperdcl** [comment]
I can confirm

```python
from tqdm import tqdm
a = tqdm()
raise RuntimeError
```

hangs when run in `python3`. I just pushed https://github.com/tqdm/tqdm/commit/858b0b4e058c7f10fdc5518255912a7bd0a350a7 which seems to fix this. Thanks @kamo-naoyuki
