### ISSUE TITLE
Can't evaluate tqdm as a boolean if disable is True

### ISSUE THREAD

**Issue by CharlesB2** [tqdm/tqdm#574]
If I convert a tqdm object to boolean to test for existence, I get an AttributeError if it was created with `disable=True`. Instead I would expect it to evaluate to False.

```
In [3]: pbar = tqdm(disable=False, total=100)
  0%|                                                                              | 0/100 [00:00<?, ?it/s]
In [4]: bool(pbar)
Out[4]: True

In [5]: pbar = tqdm(disable=True, total=100)

In [6]: bool(pbar)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-da3b9c36e33c> in <module>()
----> 1 bool(pbar)

~/prog/vopu/lib/python3.5/site-packages/tqdm/_tqdm.py in __len__(self)
    867 
    868     def __len__(self):
--> 869         return self.total if self.iterable is None else \
    870             (self.iterable.shape[0] if hasattr(self.iterable, "shape")
    871              else len(self.iterable) if hasattr(self.iterable, "__len__")

AttributeError: 'tqdm' object has no attribute 'total'
In [7]: print(tqdm.__version__, sys.version, sys.platform)
4.23.4 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] linux
```

- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by casperdcl** [comment]
I wonder if `False` should be the expected behaviour, though. Consider:

```python
from tqdm import tqdm

a = range(9)
bool(a)  # True

b = []
bool(b)  # False

ta = tqdm(a)
bool(ta)  # True

tb = tqdm(b)
bool(tb)  # False

tad = tqdm(a, disable=True)
bool(tad)  # True

ttd = tqdm(total=9, disable=True)
bool(ttd)  # shouldn't this also be True?
```

**Comment by CharlesB2** [comment]
Indeed, last one should be True. But then maybe a bit of documentation should be added because one could expect a visabled tqdm object to be False :-)

**Comment by chengs** [comment]
IMHO, this last two cases, ttb should be always False. As @CharlesB2 said, I am the one who will expect disabled tqdm to be False...
```
tad = tqdm(a, disable=True)
bool(tad)  # True

ttd = tqdm(total=9, disable=True)
bool(ttd)  # shouldn't this also be True?
```

**Comment by casperdcl** [comment]
But `tqdm` is made to be a transparent wrapper around an iterable, and thus in *all* cases, `func(a)` should have exactly the same behaviour as `func(tqdm(a))`, excluding the side-effect of having a progress bar.

**Comment by chengs** [comment]
@casperdcl if this is your design choice, then I think the commit is fine.
