### ISSUE TITLE
How to show read two big file simultaneously?

### ISSUE THREAD

**Issue by trimQiu** [tqdm/tqdm#575]
Hi,
   When I parser many big files, I want to use tqdm to show how many had parsed. So, I write this in read one file:
```python
with open(filename,'rb') as f:	
    t=len(["" for line in open(filename,'rb')])
    pbar=tqdm(total=t)	
    for line in f:
        pbar.update(1)
        ........
```
And use multiprocessing.Process to read two files simultaneously.
```pyton
p1=Process(target=run,args=(filename,'run.json',))
p2=Process(target=run,args=('F:\\MTBF\T91\\7d6b3f0c\\Debug_Log_T91\\Log_2018_0706_082447\\main_log','run1.json',))
p1.start()
p2.start()
p1.join()
p2.join()
```
Run this script, it can show two processbar, but it is ONLY flush the second processbar, tow process's information all flushed into the second processbar. How can I fix it?

Result of `print(tqdm.__version__,sys.version,sys.platform)`: "4.23.4 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] win32"

**Comment by chengs** [comment]
Use the ``position`` attributes. See README.md
You can change the function ``progresser`` in the following code

```python
from time import sleep
from tqdm import trange, tqdm
from multiprocessing import Pool, freeze_support, RLock

L = list(range(9))

def progresser(n):
    interval = 0.001 / (n + 2)
    total = 5000
    text = "#{}, est. {:<04.2}s".format(n, interval * total)
    for i in trange(total, desc=text, position=n):
        sleep(interval)

if __name__ == '__main__':
    freeze_support()  # for Windows support
    p = Pool(len(L),
             # again, for Windows support
             initializer=tqdm.set_lock, initargs=(RLock(),))
    p.map(progresser, L)
    print("\n" * (len(L) - 2))
```

**Comment by chengs** [comment]
@casperdcl  I closed this as I guess @trimQiu just is not familiar with the usage.
