### ISSUE TITLE
Wrong rounding for hundreds

### ISSUE THREAD

**Issue by sizmailov** [tqdm/tqdm#579]
https://github.com/tqdm/tqdm/blob/19cd7d735a235177b7f8a4413391226c4aac0c8d/tqdm/_tqdm.py#L144-L149

Format for hundreds is `'{0:3.0f}'`, so numbers greater than 999.5 would be printed as `1000`. This leads to trembling.

The right condition should be ` if abs(num) < 999.5: `

**Comment by casperdcl** [comment]
Thanks! would you like to submit a PR, or are you happy for us to fix this in the next release?

**Comment by sizmailov** [comment]
Sure. I also reordered comparisons to reduce number of operations.
