### ISSUE TITLE
Windows+Spyder: why there's new row for every loop, not a single-line progress bar?

### ISSUE THREAD

**Issue by wqs1006** [tqdm/tqdm#580]
I'm using Anaconda Spyder on Windows and my code is like:
`for i in tqdm(range(len(data))):`
when I first run this, it's one-line displayed like:

  1%|          | 2329/208006 [01:08<1:40:26, 34.13it/s]

and this is what I want, but for the second time I run the code, it becomes:

0%|          | 0/208006 [00:00<?, ?it/s]
  0%|          | 4/208006 [00:00<1:44:48, 33.08it/s]
  0%|          | 8/208006 [00:00<1:45:40, 32.81it/s]
  0%|          | 12/208006 [00:00<1:43:04, 33.63it/s]
  0%|          | 16/208006 [00:00<1:42:51, 33.70it/s]
  0%|          | 20/208006 [00:00<1:41:40, 34.09it/s]
  0%|          | 24/208006 [00:00<1:41:11, 34.26it/s]
  0%|          | 28/208006 [00:00<1:40:13, 34.59it/s]
  0%|          | 32/208006 [00:00<1:40:34, 34.47it/s]
  0%|          | 36/208006 [00:01<1:40:40, 34.43it/s]
  0%|          | 40/208006 [00:01<1:40:48, 34.38it/s]
  0%|          | 44/208006 [00:01<1:43:03, 33.63it/s]
  0%|          | 48/208006 [00:01<1:47:27, 32.25it/s]
  0%|          | 51/208006 [00:01<1:48:03, 32.07it/s]
  0%|          | 55/208006 [00:01<1:47:56, 32.11it/s]

and for the third time, it goes like:
0%|          | 0/208006 [00:00<?, ?it/s]

  0%|          | 4/208006 [00:00<1:39:36, 34.80it/s]

  0%|          | 8/208006 [00:00<1:38:44, 35.11it/s]

  0%|          | 12/208006 [00:00<1:45:05, 32.99it/s]

  0%|          | 16/208006 [00:00<1:46:06, 32.67it/s]

  0%|          | 20/208006 [00:00<1:44:06, 33.30it/s]

  0%|          | 24/208006 [00:00<1:44:30, 33.17it/s]

  0%|          | 27/208006 [00:00<1:45:58, 32.71it/s]

I'm really confused, I have read some of the uploaded issues, but there is none about the IDE 'Spyder', can anyone tell me how to do with it?
Thanks a lot!

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by casperdcl** [comment]
this looks like your earlier progress bars were terminated early so didn't `close` properly, meaning subsequent progress bars are trying to be "nested," which must not be supported by Spyder, see #512

If you're expecting to `Ctrl+C` you may need something like:

```python
try:
    with tqdm(...) as t:
        for i in t:
            ...
except KeyboardInterrupt:
    t.close()
    raise
t.close()
```

**Comment by wqs1006** [comment]
Thanks for the immediate reply !

**Comment by casperdcl** [comment]
If it works for you now, please close the issue.

**Comment by shmilydy** [comment]
My friend,I also met the same problem, but trying what you said did not work. Do you have any other ways?

**Comment by shmilydy** [comment]
sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())
from tqdm import tqdm
import pylab 
xmax = 3
fs = []
frames = []
np_samples = []
n_batches_viz = 10
viz_every = params['viz_every']
try:
    with tqdm(range(params['max_iter'])) as t:
        for i in t:
            f, _, _ = sess.run([[loss, unrolled_loss], g_train_op, d_train_op])
            fs.append(f)
            if i % viz_every == 0:
                np_samples.append(np.vstack([sess.run(samples) for _ in range(n_batches_viz)]))
                xx, yy = sess.run([samples, groundtruth])
                xx = xx/255
                yy = yy/255
                plt.figure()
                for i in range(1,64):
                    plt.subplot(8,16,i)
                    plt.imshow(xx[i-1])
                    plt.subplot(8,16,i+64)
                    plt.imshow(yy[i-1])
                    plt.xticks([])
                    plt.yticks([])
            plt.show()
            plt.axis('off')
            if generate_movie:
                frames.append(mplfig_to_npimage(fig))
                show()
except KeyboardInterrupt:
    t.close()
    raise
t.close()
........................................................................
above is my code

**Comment by casperdcl** [comment]
problem is indentation (I see yove opened #809 and #810)

**Comment by shmilydy** [comment]
This is because I copied the text directly. I have another question. The correct procedure is in question 810.
