### ISSUE TITLE
Fixed width left and right of progress bar

### ISSUE THREAD

**Issue by danijar** [tqdm/tqdm#585]
I use multiple progress bar after another and would like their bars to line up. The text left and right to the bars is different because each bar has its own description and throughput number. Is this possible? Note that I'm not talking about the existing dynamic width feature, which is orthogonal as it applies to the width of the whole line. Instead, I'd like the text left and right to the bar to be padded to fixed width, and the bar itself to fill up the remaining space of the line.

**Comment by casperdcl** [comment]
Use `bar_format`, e.g. for left-aligned `desc` of width 5:

```python
from tqdm import trange
for _ in trange(int(1e6), desc="foo", bar_format="{desc:<5}{percentage:3.0f}%|{bar}{r_bar}"):
    pass
```

**Comment by jeking3** [comment]
How does this ensure the bar width remains constant?

**Comment by casperdcl** [comment]
better version now in https://github.com/tqdm/tqdm#description-and-additional-stats

e.g.

```python
bar_format="{l_bar}{bar:10}{r_bar}{bar:-10b}"
```
