### ISSUE TITLE
[suggest] provide a simple version in v5

### ISSUE THREAD

**Issue by chengs** [tqdm/tqdm#610]
Since some critical errors are reported, which are all related to TMonitor, global thread, or global tqdm.__instances set.

Perhaps, it is better to provide a simple version (maybe ``tqdm.simple.tqdm`` and ``tqdm.simple.trange``), without the intergration of the functions above.  It will look like just a wrapper of an iterator.
```
class tqdmSimple():
    def __init___():
        self.iters = iters
        #only this, nothing else
        #no Tmonitor
        #no cls.__instances.

    def __iter__(self):
        for obj in self.iters:
            yield ....
            [print progress]
```

Indeed, it will not have some good features such as auto refresh, but it won't cause complicated errors). And then, tqdm with all features can be constructed on the basis of the simple version. 

For instance, the ``simple_progress`` in the test cases.

**Comment by casperdcl** [comment]
yes, I was planning on this. Probably can just close this issue and add a comment in #198
