### ISSUE TITLE
PyTorch TQDM conflict

### ISSUE THREAD

**Issue by PetrochukM** [tqdm/tqdm#611]
``DataLoader`` when interacting with ``DistributedDataParallel`` and ``tqdm==4.26.0`` causes semaphores to leak.

PyTorch issue: https://github.com/pytorch/pytorch/issues/9985#issuecomment-421502889

Any ideas on resolving this? 

```python
from torch import multiprocessing

# DEPENDANCY: This is required for ``DistributedDataParallel``
# https://pytorch.org/docs/stable/nn.html?highlight=distributeddataparallel#torch.nn.parallel.DistributedDataParallel
try:
    multiprocessing.set_start_method('spawn')
except RuntimeError:
    pass

# DEPENDANCY: This is required for ``from tqdm import tqdm``
# https://github.com/tqdm/tqdm/blob/96d8a3c3642474144f53f74331ef2172d1c39496/tqdm/_tqdm.py#L74
mp_lock = multiprocessing.RLock()

import torch
from torch.utils.data import DataLoader

if __name__ == '__main__':
    data_iterator = torch.utils.data.DataLoader([torch.tensor(i) for i in range(10)], num_workers=4)
    for batch in data_iterator:
        pass
```
```
/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
```

**Comment by chengs** [comment]
python2？

**Comment by PetrochukM** [comment]
Uhhh, Why did you comment out 
```
# try:
#     multiprocessing.set_start_method('spawn')
# except RuntimeError:
#     pass
```
and why did you remove
```
if __name__ == '__main__':
```
This example is reproducible on a CPU...

**Comment by chengs** [comment]
@PetrochukM 
Yes, now I reproduce the error.
Then I find comment the line of mp_lock can fix it.
Why you need RLock?

**Comment by PetrochukM** [comment]
@chengs 

It'd be nice if you were a bit more thoughtful before relying on this thread:
- Please don't change the code and then claim you can't reproduce.
- Please don't ask me questions that are clearly answered in the original post.

Originally, I commented that:
```
# DEPENDANCY: This is required for ``from tqdm import tqdm``
# https://github.com/tqdm/tqdm/blob/96d8a3c3642474144f53f74331ef2172d1c39496/tqdm/_tqdm.py#L74
```

Sorry if that's not clear enough. If you run ``from tqdm import tqdm`` it runs this line of code ``mp_lock = multiprocessing.RLock()`` [Source](https://github.com/tqdm/tqdm/blob/96d8a3c3642474144f53f74331ef2172d1c39496/tqdm/_tqdm.py#L74)

**Comment by chengs** [comment]
@PetrochukM 

Check this 
https://docs.python.org/3/library/multiprocessing.html#multiprocessing.set_start_method

It says:
> multiprocessing.set_start_method(method)
Set the method which should be used to start child processes. method can be 'fork', 'spawn' or 'forkserver'.
> Note that this should be called at most once, and it should be protected inside the if __name__ == '__main__' clause of the main module.

**Comment by chengs** [comment]
@casperdcl Maybe it's better to add a known issue about the conflict bettwen ``RLock`` and ``set_start_method('spawn')``.

**Comment by chengs** [comment]
@casperdcl @mjstevens777 @PetrochukM Eh, you're right. tqdm use RLock as global var. this way is not very good. On linux/mac it only works well when multiprocessing start as "fork". There should be a better way to use this.

**Comment by pencoa** [comment]
Code:
```
    training_generator = data.DataLoader(training_set, **params)
    for s in tqdm(enumerate(training_generator)):
        print(s.size())
```
Output:
```
Traceback (most recent call last):
  File "/home/penzm/BiSET/DataLoader/rankdata.py", line 57, in <module>
    for s in tqdm(enumerate(training_generator)):
TypeError: 'module' object is not callable
```

version info
```
tqdm                      4.32.2                     py_0
pytorch                   1.1.0           py3.6_cuda9.0.176_cudnn7.5.1_0    pytorch
```

**Comment by mjstevens777** [comment]
Did you do `from tqdm import tqdm`? Just doing `import tqdm` will not work
