### ISSUE TITLE
Allow to turn off tqdm via environment variables

### ISSUE THREAD

**Issue by faroit** [tqdm/tqdm#612]
often I use the same code on my local dev machine and a cluster node. To not mess up the log files I normally turn off tqdm. While this is a simple change in the python code, I think it would actually be more convenient to let tqdm check for environment variables and thereby add some level of system level control over tqdm.

e.g. `TQDM=disabled python run.py` could quickly disable tqdm in any script. 
This should be easy to implement using `os.environ.get()`. I can compile a PR if you like this proposal

- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates

**Comment by faroit** [comment]
thats a quick solution. I would still like the suggestions in #614

**Comment by casperdcl** [comment]
Thanks for your patience! Just released [`tqdm==4.66.0`](https://github.com/tqdm/tqdm/releases/tag/v4.66.0) which includes support for env var overrides. I'm using `TQDM_MININTERVAL=5` in most of my CI jobs now :)

**Comment by jamesbraza** [comment]
For those coming across this issue, the tl;dr on env var overrides (e.g. `TQDM_MININTERVAL`) works is:

1. https://github.com/tqdm/tqdm/pull/1491 added `utils.envwrap`, which decorates functions to pull keyword argument overrides from the environment variables matching a prefix ([docs](https://tqdm.github.io/docs/tqdm.utils/#envwrap))
2. `envwrap` decorates the main `tqdm` with the prefix `TQDM_` (amongst other places): https://github.com/tqdm/tqdm/blob/v4.66.2/tqdm/std.py#L951-L960

So to apply this knowledge:

1. Go to the [docs for `tqdm`](https://tqdm.github.io/docs/tqdm/#tqdm-objects)
2. Look up the desired argument name (e.g. `mininterval`, `disable`)
3. Match a keyword argument to your environment variable (e.g. `mininterval` --> `TQDM_MININTERVAL`)

**Comment by timeleft--** [comment]
And just to be clear: `TQDM_DISABLE=1` does disable TQDM like the issue author originally requested.

**Comment by carlfischerjba** [comment]
> And just to be clear: `TQDM_DISABLE=1` does disable TQDM like the issue author originally requested.

But if you're calling `tqdm(..., disable=False)` or `tqdm(..., disable=some_variable_that_happens_to_be_false)`, this will override the environment variable and you _will_ get a progress bar. In that case you would need to read the environment variable yourself and rewrite something like `tqdm(..., disable=disable_progress or os.getenv("TQDM_DISABLE", default="0") == "1")`.
