### ISSUE TITLE
Support for nested progress bars + readme updates

### ISSUE THREAD

**Issue by lrq3000** [tqdm/tqdm#62]
tqdm should support displaying nested progress bars, in particular when using nested loops:

```
from tqdm import trange
from time import sleep
for i in trange(10, desc='outer loop', leave=True):
    for j in trange(100, desc='inner loop'):
        sleep(0.01)
```

This currently does not work because the outer loop is always deleted and replaced by the inner loop.

A simple fix would be to allow StatusPrinter to avoid using the `\r` replacing character when displaying the inner loop to not replace the outer loop. This is the approach taken by [ipy-progressbar](https://github.com/aplavin/ipy-progressbar).

Another way would be to update both bars independently, which is currently done for tqdm_notebook. But I'm not sure this is possible inside a terminal (is there a way to replace not only the current line but also the x previous lines? ie, the opposite of a line return).

We should then update the README to add this use case.

Also, we should add in the README that tqdm does not require any dependency, in particular curses (which is commonly required for various console utilities), this would fix https://github.com/noamraph/tqdm/issues/16.

**Comment by lrq3000** [comment]
I have implemented the idea I had (ie, the simple fix). Do you guys know of a way to implement the second way (independent updates by replacing any x previous lines)? Else we can merge :)

**Comment by lrq3000** [comment]
In fact, to make the nested bar printing perfect, we would just need to be able to go up in the console, to the overwrite the previous line. But it seems this cannot be easily done...

**Comment by lrq3000** [comment]
OK, in fact this issue of not being able to go up is the reason why lots of progress bars for console are done using curses, simply because this allows more complex positionning of the cursor.

**Comment by lrq3000** [comment]
It seems moving the cursor around in Windows console is not possible, except if either:

1. we use curses (but that would be a HUGE dependency to me).
2. we use the specific win32 functions to move the cursor in the terminal.

I vote for the second option (let me know guys if you prefer that we switch to curses), but there's not a lot of documentation about how to do that.

Luckily, there's a library that claims to do the conversion of all ANSI special characters to win32 API calls automagically: [colorama](https://github.com/tartley/colorama).

So what we can do: either link colorama as an optional dependency of tqdm to support colors and prettier nested pbars on Windows, or just extract the one function that interests us just for the moment (ie, how to move cursor one line above).

What do you think guys?

**Comment by lrq3000** [comment]
Ok I updated the code to implement the second way of displaying nested progress bars. This should work out-of-the-box on Unix/Linux terminals (and any ANSI compliant terminal), except Windows console (which is not ANSI compliant ofc...). Here's the result:

![tqdm-nested3](https://cloud.githubusercontent.com/assets/1118942/11530991/a26bfc94-98f9-11e5-99d4-4f9996fc271c.png)

For Windows support, the user just needs to install `colorama`, which has no dependency (except ctypes but it is installed in CPython since v2.5). I tried to extract the relevant code to include only the necessary stuff into tqdm._utils.py, but this would mean extracting most of colorama/win32.py and half of colorama/winterm.py, and in addition the burden on maintaining it would be now on us, so I guess it's a good idea to just propose to Windows users to install colorama (tell me if you would prefer to include the code in tqdm directly).

Anyway, for Windows users without `colorama`, the nested display will gracefully degrade to the 1st fix, so the parent bars won't be replaced in-place but it will still work.

**Comment by lrq3000** [comment]
Please guys try on Linux and tell me if this all works correctly!

```
from tqdm import trange
from time import sleep
lv = True
ns = True
for i in trange(2, desc='outer0 loop', leave=True):
    for j in trange(4, desc='inner1 loop', leave=lv, nested=ns):
        for k in trange(100, desc='inner2 loop', leave=lv, nested=ns):
            sleep(0.01)
```

**Comment by lrq3000** [comment]
Ok, I've finished all the things I wanted to implement for this PR. Please guys try it on Linux and tell me if everything's ok for you. I'm OK for the merge if you're OK guys.

PS: please note that it doesn't work in IPython (it will degrades to the first nested display, without in-place replacement of parent progress bars), so you should try in a terminal. Anyway, there is another PR with `tqdm_notebook` which supports nested progress bars in IPython.

**Comment by casperdcl** [comment]
```python
>>> from tqdm import trange
>>> from time import sleep
>>> lv = True
>>> ns = True
>>> for i in trange(2, desc='outer0 loop', leave=True):
...     for j in trange(4, desc='inner1 loop', leave=lv, nested=ns):
...         for k in trange(100, desc='inner2 loop', leave=lv, nested=ns):
...             sleep(0.01)
... 
outer0 loop: 100%|████████████████████████████████| 2/2 [00:08<00:00,  0.25it/s]
>>> r1 loop: 100%|████████████████████████████████| 4/4 [00:04<00:00,  0.98it/s]
inner2 loop: 100%|████████████████████████████| 100/100 [00:01<00:00, 98.32it/s]
```

The cursor isn't in the right place. Can't see how to solve this though... the only thing I can think of is setting `leave=False` for all nested bars.

**Comment by lrq3000** [comment]
Yes I already tried to fix it, but I didn't find an elegant way.

We would need to add a parameter to tell tqdm what nested level we're at so
that the cursor would be moved to the correct place.

And indeed, setting leave=False fix the issue, but anyway even without
fixing it I think it's still ok (we see the completed progress bars, the
user then doesn't need them anymore, the cursor position artefact is but a
tiny inconvenience to me).

2015-12-19 1:13 GMT+01:00 Casper da Costa-Luis <notifications@github.com>:

**Comment by lrq3000** [comment]
I just thought about something : we could create a dispatcher function
containing a closure variable which would memorize the total number of
iterables it was called with. The usage would then be something like this:

```
def tqdm_dispatcher(*args, **kwargs):
    bars = []
    iterables = []
    counter = []
    def dispatch(iterable):
        if not iterable in iterables:
            iterables.append(iterable)
            bar = tqdm(iterable, *args, **kwargs)
            bars.append(bar)
            counter[0] += 1
        else:
            bar = bars[iterables.find(iterable)]
        try:
            return next(bar)
        except StopIteration as exc:
            if counter == 0:
                 print "\n" * len(bars)
            else:
                 raise exc

    return dispatch

t = tqdm_dispatcher(*args)
for i in t(range(2)):
    for j in t(range(4)):
        for k in t(range(100)):
            time.sleep(0.01)
```

Of course, performance will probably suffer, particularly with pypy...

**Comment by lrq3000** [comment]
Or, instead of setting ```nested=True```, just allow the user to set
```nested=x``` where x is an integer representing the total number of
nested loops. Then, simply ```print "\n" * self.nested``` in
```tqdm.close()```. A bit less automatic than the dispatcher, but the
result would be the same without any loss of functionality (plus, the
current functionnality wouldn't be broken: nested=True is equal to nested=1
so it's OK).

2015-12-19 15:32 GMT+01:00 Stephen LARROQUE <lrq3000@gmail.com>:

> I just thought about something : we could create a dispatcher function
> containing a closure variable which would memorize the total number of
> iterables it was called with. The usage would then be something like this:
>
> ```
> def tqdm_dispatcher(*args, **kwargs):
>     bars = []
>     iterables = []
>     counter = []
>     def dispatch(iterable):
>         if not iterable in iterables:
>             iterables.append(iterable)
>             bar = tqdm(iterable, *args, **kwargs)
>             bars.append(bar)
>             counter[0] += 1
>         else:
>             bar = bars[iterables.find(iterable)]
>         try:
>             return next(bar)
>         except StopIteration as exc:
>             if counter == 0:
>                  print "\n" * len(bars)
>             else:
>                  raise exc
>
>     return dispatch
>
> t = tqdm_dispatcher(*args)
> for i in t(range(2)):
>     for j in t(range(4)):
>         for k in t(range(100)):
>             time.sleep(0.01)
> ```
>
> Of course, performance will probably suffer, particularly with pypy...

**Comment by lrq3000** [comment]
Implemented the last idea in #68. This just requires the user to set `nested=x` for the most outer loop, else it will work just like before (with a wrong completed cursor placement, but the nesting works the same).

@casperdcl : do you think I should try to implement the dispatcher or would this fix be ok?

**Comment by casperdcl** [comment]
discussion continued and

**Comment by casperdcl** [comment]
Old issue, now on #87
