### ISSUE TITLE
Drop Py 2.6 support?

### ISSUE THREAD

**Issue by altendky** [tqdm/tqdm#620]
https://www.python.org/dev/peps/pep-0361/#release-lifespan

Py 2.6 ceased to have support just shy of five years ago.  The build is presently broken.  Over a year ago in #411 it was suggested to drop support.  I'd suggest one of dropping support, fixing the build, or marking the build as allowed to fail so that PR's don't get marked as failed when they haven't introduced any issues.

I get that there's only been one broken build so it's not like this has been a long term issue.  But, I figured I'd put a ticket out here for discussion anyways.

Cheers,
-kyle

**Comment by casperdcl** [comment]
already fixed in f60feca
