### ISSUE TITLE
specify bar width format-spec

### ISSUE THREAD

**Issue by Firesphere** [tqdm/tqdm#623]
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

I can't find it, maybe I'm stupid, but I'd like to be able to set a width for the right side data (something like this)
```

Messages            : 100%|█| 99/99 [00:02<00:00, 36.14it/s]
Message             : 100%|█| 3/3 [00:00<00:00, 544.17it/s]
Channels            :  95%|█▏           | 36/38 [08:54<00:22, 11.18s/it]
Relations           : 100%|█| 99/99 [00:00<00:00, 157.06it/s]
```
It would be nice, to make it possible to align the end of the bar (channels is the awkward one here)

**Comment by casperdcl** [comment]
Not quite sure what you mean. Can you post a minimal working example?

**Comment by Firesphere** [comment]
Hi, sorry for the delayed reply. What I would like to achieve, is the data on the right side of the progress bar, to be aligned vertically, as `ljust` gives the opportunity to do it for the left side:
![image](https://user-images.githubusercontent.com/680570/46911551-e99cc700-cfbb-11e8-8c37-50d96e36e063.png)
As you can see, the progress bars don't align neatly at the far end, left, due to differences in length of the set given. I'd like to be able to make it a smooth way down.

**Comment by crogre** [comment]
I second this, right now my progress bars jump annoyingly if the it/s goes from say 90 it/s to 100 it/s. I really want a fixed width bar.

**Comment by casperdcl** [comment]
you can specify an `ncols` for a fixed bar width

**Comment by casperdcl** [comment]
you can also use `set_postfix_str()` with your own justified string representation of your dictionary

**Comment by casperdcl** [comment]
@crogre but what about `tqdm(..., ncols=20, bar_format="...")`?

**Comment by casperdcl** [comment]
right, got it

**Comment by Firesphere** [comment]
Thanks for explaining the wished outcome clearer than I could @crogre :)

Yeah, having a fixed with for both left and right, or a fixed with for _just_ the bar, would save a lot of jumping around of the bar.

A default width of a certain amount of characters for the right part would possibly also save a lot of jumping around.

**Comment by jeking3** [comment]
What I would like to see is a fixed width for the bar itself:

1. User can easily control the width of the l_bar side (description, even across multiple positioned bars).
2. Allow the bar width to be fixed, i.e. bar_width=30
3. Using dynamic_ncols, whatever space is left is allocated to the right side of the bar, and the content is truncated to fit on the screen.

This would prevent the bar from resizing as postfix changes.

**Comment by casperdcl** [comment]
btw for now something like `bar_format='{l_bar}{bar}|{r_bar:>60}` might work
