### ISSUE TITLE
AttributeError: 'Series' object has no attribute 'progress_map'

### ISSUE THREAD

**Issue by yangjingyingGo** [tqdm/tqdm#634]
I want to preprocess Sentiment-Analysis-Dataset,  but i have a problem and i can not solve. 
my code is as follows:

- import os
- import re
- 
- import warnings
- 
- warnings.simplefilter("ignore", UserWarning)
- from matplotlib import pyplot as plt
- 
- import pandas as pd
- 
- pd.options.mode.chained_assignment = None
- import numpy as np
- from string import punctuation
- 
- from nltk.tokenize import word_tokenize
- 
- from sklearn.model_selection import train_test_split
- from sklearn.feature_extraction.text import TfidfVectorizer
- from sklearn.linear_model import LogisticRegression
- from sklearn.metrics import accuracy_score, auc, roc_auc_score
- from sklearn.externals import joblib
- 
- import scipy
- from scipy.sparse import hstack
- 
- data = pd.read_csv('./data/tweets.csv', encoding='latin1', usecols=['Sentiment',
-                                                                     'SentimentText'])
- data.columns = ['sentiment', 'text']
- data = data.sample(frac=1, random_state=42)
- print(data.shape)
- 
- for row in data.head(10).iterrows():
-     print(row[1]['sentiment'], row[1]['text'])
- 
- 
- def tokenize(tweet):
-     tweet = re.sub(r'http\S+', '', tweet)
-     tweet = re.sub(r"#(\w+)", '', tweet)
-     tweet = re.sub(r"@(\w+)", '', tweet)
-     tweet = re.sub(r'[^\w\s]', '', tweet)
-     tweet = tweet.strip().lower()
-     tokens = word_tokenize(tweet)
-     return tokens
- 
- 
- data['tokens'] = data.text.progress_map(tokenize)
- data['cleaned_text'] = data['tokens'].map(lambda tokens: ' '.join(tokens))
- data[['sentiment', 'cleaned_text']].to_csv('./data/cleaned_text.csv')
- 
- data = pd.read_csv('./data/cleaned_text.csv')
- print(data.shape)
- 
- data.head()
- 
- x_train, x_test, y_train, y_test = train_test_split(data['cleaned_text'],
-                                                     data['sentiment'],
-                                                     test_size=0.1,
-                                                     random_state=42,
-                                                     stratify=data['sentiment'])
- 
- print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)
- 
- pd.DataFrame(y_test).to_csv('./predictions/y_true.csv', index=False, encoding='utf-8')

but when I run this program, given this error:
AttributeError: 'Series' object has no attribute 'progress_map'

What can I do? Thank you.

**Comment by chengs** [comment]
I cannot read your code entirely. I think you forgot to call ``tqdm.pandas()``

**Comment by yangjingyingGo** [comment]
> I cannot read your code entirely. I think you forgot to call `tqdm.pandas()`

sorry to reply to you late. My code is as follows:
[code.docx](https://github.com/tqdm/tqdm/files/2536978/code.docx)

**Comment by yangjingyingGo** [comment]
> I cannot read your code entirely. I think you forgot to call `tqdm.pandas()`

I add the code: tqdm.pandas(), but new problem I had:

**Traceback (most recent call last):
  File "G:/PycharmProjects/TextAnalysis/preprocessing.py", line 27, in <module>
    tqdm.pandas()
AttributeError: module 'tqdm' has no attribute 'pandas'**

**Comment by shuiluoyukai** [comment]
from tqdm import tqdm
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
data['tokens'] = data.text.progress_map(tokenize)

**Comment by luolitao** [comment]
from tqdm import tqdm
tqdm.pandas(desc="progress-bar")
