### ISSUE TITLE
tqdm progress bar not showing after leave notebook(not shut down)

### ISSUE THREAD

**Issue by Jacky97s** [tqdm/tqdm#636]
Before:
![image](https://user-images.githubusercontent.com/25542146/48040216-ecea3380-e1b2-11e8-94e0-11a625677954.png)

After:
![image](https://user-images.githubusercontent.com/25542146/48040252-04c1b780-e1b3-11e8-9ca8-5e6227627e9b.png)

How to make it appear again without shuting down.

**Comment by chengs** [comment]
Actually, this is not a tqdm issue, but ipywidget's. Thus I close this issue.
Perhaps this link (https://ipywidgets.readthedocs.io/en/stable/embedding.html) can help you.
