### ISSUE TITLE
Memory optimization

### ISSUE THREAD

**Issue by lrq3000** [tqdm/tqdm#64]
We can optimize the memory usage of tqdm by defining a ```__slots__``` property in `tqdm` class (see [this link](http://tech.oyster.com/save-ram-with-python-slots/) for an impressive account! -- of course, the gain will be a lot less for us, and even maybe negligible, but I think it can also be a good practice to list all the object properties).

However, we need to test if this won't break the inheriting classes.

On the matter, there's an interesting progressbar library called [python-progressbar](https://github.com/niltonvolpato/python-progressbar), it claims to be very flexible and customizable.

**Comment by Berserker66** [comment]
From same Link:
Warning: Don’t prematurely optimize and use this everywhere! It’s not great for code maintenance, and it really only saves you when you have thousands of instances.

Considering the unlikeliness of thousands of tqdm instances, I'd close this issue.

**Comment by casperdcl** [comment]
Yes, agreed.

**Comment by lrq3000** [comment]
Yes agreed too.
