### ISSUE TITLE
pb.write and print don't work in jupyter notebook

### ISSUE THREAD

**Issue by KOLANICH** [tqdm/tqdm#644]
The version used is 350640d3171a568fb3f22d64d898e154541acc56
Neither
```python
with tqdm(...) as pb:
    pb.write("test")
```
nor

```
with tqdm(...) as pb:
     print("test")
```

work.
It turned out that the text output is buffered somehow, and flushed only if there are lot of lines. It is not flushed even on cell execution finish.

**Comment by casperdcl** [comment]
that's odd. if that's jupyter's decision then I'm not sure if we should try to forcefully `flush`...

**Comment by KOLANICH** [comment]
>that's jupyter's decision then I'm not sure if we should try to forcefully flush...

I have tried, it doesn't work.

**Comment by chengs** [comment]
let me have a look

**Comment by KOLANICH** [comment]
BTW, in jupyterlab without widgets module installed the output works. I have not tested with widgets installed, because in jupyterlab widgets are npm module, not python one.

**Comment by chengs** [comment]
Closed as the problem is fixed.
