### ISSUE TITLE
jupyter lab functionality?

### ISSUE THREAD

**Issue by michaelaye** [tqdm/tqdm#645]
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:

```python
import tqdm, sys
print(tqdm.__version__, sys.version, sys.platform)
4.28.1 3.7.1 | packaged by conda-forge | (default, Nov 13 2018, 09:50:42) 
[Clang 9.0.0 (clang-900.0.37)] darwin
  ```

Using `from tqdm import tqdm_notebook` and the following code:

```python
for i in tqdm_notebook(range(6, 13)):
    do_stuff(i)
```

I get:

```bash
HBox(children=(IntProgress(value=0, max=7), HTML(value='')))
```
as output instead of a progress bar.

**Comment by casperdcl** [comment]
see #394

**Comment by michaelaye** [comment]
```bash
$ jupyter labextension list                                                                       (py37)
JupyterLab v0.35.4
Known labextensions:
   app dir: /Users/klay6683/miniconda3/envs/py37/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v0.38.1  enabled  OK
        @jupyterlab/github v0.10.0  enabled  OK
        @pyviz/jupyterlab_pyviz v0.6.3  enabled  OK
        jupyter-matplotlib v0.3.0  enabled  OK
```

**Comment by chengs** [comment]
@michaelaye can you try updating JupyterLab?
On my env, it works well.
```
~ ᐅ jupyter labextension list
JupyterLab v0.35.4
Known labextensions:
   app dir: /Users/guchen/anaconda3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v0.38.1  enabled  OK

~ ᐅ conda list widget
# packages in environment at /Users/guchen/anaconda3:
#
# Name                    Version                   Build  Channel
ipywidgets                7.4.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
widgetsnbextension        3.4.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
```

**Comment by michaelaye** [comment]
I don't understand, I have the same version as you?

**Comment by cduguet** [comment]
was there any resolution regarding this issue?

**Comment by michaelaye** [comment]
This works for me now, with these versions:

```bash
$ jupyter labextension list                                                                       (py37)
JupyterLab v0.35.4
Known labextensions:
   app dir: /usr/local/epd/miniconda/envs/py37/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v0.38.1  enabled  OK
maye@luna2|~
$ conda list widget                                                                               (py37)
# packages in environment at /usr/local/epd/miniconda/envs/py37:
#
# Name                    Version                   Build  Channel
ipywidgets                7.4.2                      py_0    conda-forge
widgetsnbextension        3.4.2                 py37_1000    conda-forge
```

**Comment by simonm3** [comment]
Does not work for me. HBox(children=(IntProgress(value=0, max=7), HTML(value='')))

I have same ipywidgets 7.4.2, widgetsnbextension 3.4.2, jupyter lan 1.1.4

**Comment by chengs** [comment]
@simonm3 @casperdcl I would suggest using Jupyter Notebook, which has better compatibility with IpyWidgets.

**Comment by casperdcl** [comment]
btw if you save and reload (even in notebook) the idgets are replaced with `HBox(...)`

**Comment by gingeard** [comment]
I've tried to install a clean environment with Python 3.8.1 and it's work. With Python 3.7.1, but with the same versions of packages, I was seeing only "HBox..." instead of widgets.

**Comment by ValeryP** [comment]
Using

```
from tqdm.auto import tqdm, trange
```
![image](https://user-images.githubusercontent.com/3534020/81059214-52b29b00-8ed0-11ea-8151-92bf3ac65f2c.png)

instead of 

```
from tqdm import tqdm, trange
```

![image](https://user-images.githubusercontent.com/3534020/81059279-737af080-8ed0-11ea-8959-5d3fc82a29f6.png)

makes a difference for me 🙂

**Comment by ziofil** [comment]
I have tried all of the above, but things are not working. Is there a problem with python 3.8?

**Comment by ehsong** [comment]
I have the same issue with these versions:

```
(base) Eunhous-MacBook-Pro:~ eunhousong$ jupyter labextension list
JupyterLab v1.2.4
Known labextensions:
   app dir: /Users/eunhousong/anaconda3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
(base) Eunhous-MacBook-Pro:~ eunhousong$ conda list widget
# packages in environment at /Users/eunhousong/anaconda3:
#
# Name                    Version                   Build  Channel
ipywidgets                7.5.1                      py_0    conda-forge
widgetsnbextension        3.5.1                    py37_0  
```

**Comment by gloryVine** [comment]
Same issue, two years later.

**Comment by casperdcl** [comment]
https://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-the-jupyterlab-extension

**Comment by krassowski** [comment]
Just heads up: it seems that you no longer need to install a separate JupyterLab extension (just ipywidgets which can be installed with `pip` or `conda`) for JupyterLab 3.0+. :tada:

You only need to upgrade ipywidgets. See: https://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-in-jupyterlab-3-0
