### ISSUE TITLE
tqdm_notebook bar malformed when bar_format is specified.

### ISSUE THREAD

**Issue by neerajprad** [tqdm/tqdm#649]
### System Info

```sh
>>>  import tqdm, sys
>>>  print(tqdm.__version__, sys.version, sys.platform)
4.28.1 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] darwin
```

### Issue:
With the bar format below, the progress bars are correctly rendered in the terminal but incorrectly in jupyter notebook (instead of filling up the bar, another bar to the right is constructed).

<img width="945" alt="screen shot 2018-12-05 at 11 59 51 am" src="https://user-images.githubusercontent.com/1762463/49540671-8590d380-f885-11e8-8b7c-649d47e94aa2.png">

**Comment by chengs** [comment]
Yes, this is a known issue. Some good tqdm features are not implemented in tqdm_noteobook.

**Comment by neerajprad** [comment]
> Yes, this is a known issue. Some good tqdm features are not implemented in tqdm_noteobook.

Given the experimental nature of the progress bar for jupyter notebooks, not supporting custom bar format is very acceptable. It will be nice if this just raised a warning or an exception, because it takes a while to debug what might be going wrong otherwise. In our case, we changed the constructor to not use a custom format when in the notebook environment.

**Comment by chengs** [comment]
@neerajprad Totally agree.

@casperdcl IHMO, #594 (related to this issue) should be fixed, or add some warnings there.

**Comment by casperdcl** [comment]
closing as duplicate - do keep bugging me at #594 :P
