### ISSUE TITLE
'tqdm_notebook.set_description()' fails with disable=True

### ISSUE THREAD

**Issue by neerajprad** [tqdm/tqdm#650]
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
```sh
>>> import tqdm, sys
>>> print(tqdm.__version__, sys.version, sys.platform)
4.28.1 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] darwin
```

Similar to the closed issue - https://github.com/tqdm/tqdm/issues/184, but in this case tqdm throws an error when we call `.set_description` on a progress bar that is disabled. 

<img width="1129" alt="screen shot 2018-12-05 at 3 50 29 pm" src="https://user-images.githubusercontent.com/1762463/49551808-a1a46d00-f8a5-11e8-95b1-6a99f4fa90e3.png">

**Comment by itssimon** [comment]
This issue still exists. @chengs did you get a chance to look at this at all?
