### ISSUE TITLE
Interactive demo for `tqdm` code examples

### ISSUE THREAD

**Issue by martinzugnoni** [tqdm/tqdm#652]
Hello folks!

I've been using `tqdm` lately and found it really interesting. I'm even thinking about adding it in our curriculum to teach our students at https://rmotr.com/ (co-founder and teacher here). While working with CLI and Python scripts it improves the UX a lot!

While looking at the code examples in the README file I thought it would be great to provide some interactive demo that people can use to play with the library before committing to download and install it locally.

> A demo is worth a thousand words 😉

I spent a few minutes compiling all `tqdm` examples into a Jupyter Notebook file, and adapted it in a way that we can open it with a small service we have at RMOTR to launch Jupyter environments online. No signup required to use it, so it's pretty convenient for people that wants to get hands on the library with a low entrance barrier. Note that `tqdm` is already installed when the env is loaded, so people can start using it right away.

The result is what you can see in my fork of the repo (see the new "Demo" section in the table of content):
https://github.com/martinzugnoni/tqdm

Do you think that having such interactive demo would help people to know and use `tqdm`?
Let's use this issue as a kick off to start a discussion. Nothing here is written in stone and we can change everything as you wish.

I hope you like it, and I truly appreciate any feedback.

thanks.

**Comment by casperdcl** [comment]
Thanks, sounds great. Will try to look into this, but have a lot of other things to get through as well.

**Comment by martinzugnoni** [comment]
Thanks for your response, @casperdcl. No hurries at all. Let me know if there's anything I can help you with.

**Comment by casperdcl** [comment]
@martinzugnoni quick question, how is *rmotr* different from *mybinder*?

(https://notebooks.rmotr.com/demo/gh/tqdm/tqdm vs https://mybinder.org/v2/gh/tqdm/tqdm/master?filepath=DEMO.ipynb)
