### ISSUE TITLE
Access to time elapsed

### ISSUE THREAD

**Issue by EvanSchalton** [tqdm/tqdm#656]
Hey, firstly -- great tool! Thank you!

A minor feature request:
It'd be great to add a "runtime" method to the progress bar object

I've been using the following as a work around:

```
import time
def tqdm_runtime(prog_bar):
    epoch_prog.start_t
    epoch_prog.last_print_t
    return time.strftime('%H:%M:%S', time.gmtime(epoch_prog.last_print_t-epoch_prog.start_t))
```

I use it frequently to log the runtime of training neural nets, but it'd be great to see the method added

**Comment by casperdcl** [comment]
P.S. you can use `epoch_prog.format_interval(epoch_prog.last_print_t-epoch_prog.start_t)` or just `epoch_prog.format_interval(epoch_prog['elapsed'])`
