### ISSUE TITLE
Pandas progress_map for pandas.Series - non-callable argument

### ISSUE THREAD

**Issue by pszynk** [tqdm/tqdm#664]
First argument of `pandas.Series.map` can also be a `pandas.Series` or `dict`. `progress_map` doesn't work with those types. It probably makes no sense to create a wrapping function in this case. Pandas is doing some optimization so it should be faster than function (not sure about that). Still I think it should be mentioned in documentation.

4.29.1 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0] linux

**Comment by chengs** [comment]
Indeed, using wrapping function as ``progress_apply`` or ``progress_applymap`` interrupts the pandas optimization for such functionality. This is a confirmed issue. It is better to mention this in the document.

**Comment by chengs** [comment]
@casperdcl regarding this issue, I suggest we not change the code but just add some instructions in the README, what do you think?

**Comment by casperdcl** [comment]
surem happy to accept a PR

**Comment by chengs** [comment]
PR submitted. close this.
