### ISSUE TITLE
estimated time skew over long periods of time

### ISSUE THREAD

**Issue by nurettin** [tqdm/tqdm#665]
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```
```
4.29.1 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] linux
```

I have this situation where estimated time skews over long-running processes. All progressbars have `smoothing=0`.  
```
Blargs     :  36%|#################2                              | 18.0k/50.1k [21:18:02<37:57:53, 4.26s/bla]
Froobles   :  36%|##############6                          | 1.44k/4.03k [21:07:12<37:58:09, 52.8s/froob]
Frablaghs  :  36%|###############                           | 3.87k/10.8k [21:18:02<37:57:49, 19.8s/frab]
Flebreps   :  36%|#################2                              | 867k/2.41M [21:21:12<38:03:32, 11.3 fleb/s]
Booblips   :  36%|##############                         | 56.3k/157k [21:20:26<38:02:06, 1.36s/boob]
```
In the beginning, they all stabilized at about 56.5 hours, then slowly slided down. Even though the percent bar stays correct, estimated time keeps on skewing down. I think this is caused by imperfect summing of floating point ratios over time. A common problem in physics simulations. With `smoothing=0`, I think we can fix the estimated time to be equal to `elapsed_t * total / n`. That will also make tqdm faster.   

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by nurettin** [comment]
Related issue: #609

**Comment by nurettin** [comment]
Now that I looked at this line where it checks if rate exists and does what I proposed https://github.com/tqdm/tqdm/blob/master/tqdm/_tqdm.py#L334 and then this line where it doesn't set rate if smoothing is none or 0 https://github.com/tqdm/tqdm/blob/master/tqdm/_tqdm.py#L1016 I'm confused as to why this is happening.

**Comment by casperdcl** [comment]
Not sure what the issue is.

The estimated time remaining is about 38h in your examples, and time elapsed is about 21h. 21+38=59 which is close to the 56.5h initial estimate you quoted.

**Comment by nurettin** [comment]
> Not sure what the issue is.
> 
> The estimated time remaining is about 38h in your examples, and time elapsed is about 21h. 21+38=59 which is close to the 56.5h initial estimate you quoted.

That is exactly the problem, why is estimated time skewing lower and lower ? I couldn't find an answer in the code.

**Comment by nurettin** [comment]
Nevermind, I am used to seeing the total time on the right and calculating the remaining time in my head, tqdm shows the remaining time on the right and elapsed on the left.
