### ISSUE TITLE
remove entries from postfix

### ISSUE THREAD

**Issue by grill02** [tqdm/tqdm#666]
Hello,
I am trying to create a progress meter for encoding a video with ffmpeg. The parameters interesting to me are percentage (encoded), filesize, time remaining,bitrate,and speed.

Here is what my progress meter looks like now
```

encoding 1768kB:  20%|████████▊                                   | 20/100.0 [00:08<00:33,  2.41it/s, bitrate=256.7kbits/s, speed=7.45x]
```

My code is 

```
with tqdm.tqdm(total=100.,desc='encoding ') as pbar:
  #size is encoded file size
  pbar.desc='encoding '+size;
  #speed is speed of encoding, bitrate is encoded bitrate
  pbar.set_postfix(speed=speed,bitrate=bitrate, refresh=False); 
```

Note the  20/100.0 (denotes percentage) and 2.41it/s (denotes update rate). These two parameters are not needed, and unnecessarily clutter up the display. what I want is 

```
encoding 1768kB:  20%|████████▊                                   | [00:08<00:33, bitrate=256.7kbits/s, speed=7.45x]
```

How can I remove these two parameters. I tried doing

```
pbar.postfix[0]=speed
pbar.postfix[1]=bitrate
```

but I got the error 
```
Traceback (most recent call last):
  File "./myffprogress.py", line 47, in <module>
    pbar.postfix[0]=speed
TypeError: 'NoneType' object does not support item assignment
```

**Comment by casperdcl** [comment]
tweak the `bar_format` parameter. Something like:

```python
tqdm(..., bar_format="{l_bar}{bar}| [{elapsed_fmt}<{eta_fmt}{postfix}]")
```

**Comment by casperdcl** [comment]
I'd suggest using stackoverflow for these kinds of questions rather than github issues (which are meant for bugs/feature requests)

I think you might be looking for something like:

```python
tqdm(..., bar_format="{l_bar}{bar}| {n:0.1f}min [{elapsed}<{remaining}{postfix}]",unit_scale=1/60.) 
```
