### ISSUE TITLE
modify precision for unit_scale

### ISSUE THREAD

**Issue by grill02** [tqdm/tqdm#667]
Hello,

I have a progress meter that looks like 
``
encoding 288kB:   0%|                                             |  0.666666666667 min[00:34<2:45:30, bitrate=59.3kbits/s, speed=1.18x]
``

I'd like to change this to 

``
encoding 288kB:   0%|                                             |  0.6 min[00:34<2:45:30, bitrate=59.3kbits/s, speed=1.18x]
``

The code is 

```
#duration is in seconds
with tqdm.tqdm(total=int(duration),desc='encoding ', bar_format="{l_bar}{bar}|  {n_fmt} min[{elapsed}<{remaining}{postfix}]",unit_scale=1/60.,unit='min') as pbar:
          pbar.update(time_done-pbar.n); #time_done is in seconds
          pbar.desc='encoding '+size;
          pbar.set_postfix(speed=speed,bitrate=bitrate, refresh=False) ;
```

The extra precision comes from unit_scale=1/60.
I update with seconds, but I want to display minutes. 
If I do unit_scale=1/60 , this gets rounded to 0 and does'nt work.

**Comment by casperdcl** [comment]
see https://github.com/tqdm/tqdm/issues/666#issuecomment-458240858
