### ISSUE TITLE
Colors do not work if tqdm imported.

### ISSUE THREAD

**Issue by krishnachouhan** [tqdm/tqdm#678]
This code works...
```
_CRED = '\033[91m'
_CEND = '\033[0m'
print(_CRED + "Colors bre being set" + _CEND + '-all_set')
```

but after importing the same code does not work.
```
import tqdm
_CRED = '\033[91m'
_CEND = '\033[0m'

print(_CRED + "Colors bre being set" + _CEND + '-all_set')
```

Python: 
(base) C:\Users\212574384>python --version
Python 3.7.0
OS: win 10

![image](https://user-images.githubusercontent.com/9086076/53049049-35a4ce80-34bc-11e9-8152-b877fcecca5d.png)

**Comment by casperdcl** [comment]
just to confirm, if you `import colorama` instead of `import tqdm`, does it still break?

**Comment by krishnachouhan** [comment]
colorama works fine.

![image](https://user-images.githubusercontent.com/9086076/53068388-4d9d4200-34fe-11e9-8679-aa00b76e8e48.png)

**Comment by krishnachouhan** [comment]
colorama works fine.
![image](https://user-images.githubusercontent.com/9086076/53068426-758ca580-34fe-11e9-8d86-216b5b5c6e6f.png)




!sorry about closing, very new to this..

**Comment by svlandeg** [comment]
We ran into this issue as well because `spaCy` uses `tqdm` (https://github.com/explosion/spaCy/issues/4200). We found that this bug seems to happen specifically on Windows, and not on other OS's.

**Comment by casperdcl** [comment]
Found the issue - for now, please use:

```python
import tqdm  # or whatever tqdm imports you use
import colorama
colorama.deinit()
colorama.init(strip=False)
```

Will patch soon...

**Comment by casperdcl** [comment]
https://github.com/tartley/colorama/issues/79

**Comment by H4CKY54CK** [comment]
I've been experiencing this issue for a long time. I just happened across this page, but the proposed temporary fix is not working for me. Has anything changed since then? I'm on Python 3.8, I just updated `tqdm` and `colorama` via pip, and still experiencing the issue.

Actually, using this on it's own *disables* my colors entirely.
```
import colorama
colorama.deinit()
colorama.init(strip=False)
```

**Comment by casperdcl** [comment]
> I don't know if there's something that `tqdm` now doesn't have that it needs

It has everything it needs, no worries.

to be clear, are you saying: 

1. colours were working
2. `import tqdm` stops colours working
3. `import colorama; colorama.deinit()` gets colours working again

**Comment by H4CKY54CK** [comment]
All of the above.

If I do a simple

```
print("\x1b[38;2;0;255;0mHello\x1b[0m")
```

I get a green "Hello".

Once I import `tqdm`, I lose the color (it still only says "Hello"; it's not doing anything crazy like printing out the ANSI sequence or anything).

If I do

```
from tqdm import tqdm
import colorama
colorama.deinit()
print("\x1b[38;2;0;255;0mHello\x1b[0m")
```

I get green text again. But I lose it again with the following.

```
from tqdm import tqdm
import colorama
colorama.deinit()
colorama.init(strip=False)
print("\x1b[38;2;0;255;0mHello\x1b[0m")
```

Sorry if that seemed condescending. I just wanted to be explicit.

If this is all normal, then I apologize for commenting on this issue. I can work with this now that I know how to get around the issue, but I suppose you can never have too much data on possible issues.

**Comment by casperdcl** [comment]
hmm this is odd. Looks related to https://github.com/tartley/colorama/issues/79

importing `tqdm` will internally do `colorama.init(strip=False)` on Windows.

1. What's your OS and terminal? I assume OS is Windows, but is the terminal git-bash? Plain command prompt? Notebook?
2. What does your output look like if you run this in one go?

```python
print("\x1b[38;2;0;255;0mCorrectly green\x1b[0m")
import colorama
print("\x1b[38;2;0;255;0mCorrectly green\x1b[0m")
colorama.init(strip=False)
print("\x1b[38;2;0;255;0mShould be green but isn't\x1b[0m")
colorama.deinit()
print("\x1b[38;2;0;255;0mCorrectly green\x1b[0m")
colorama.init()
print("\x1b[38;2;0;255;0mShould be green but isn't\x1b[0m")
```

I get this on linux (everything correctly green in terminal as well as notebook):

![image](https://user-images.githubusercontent.com/10780059/95660263-8d270080-0b1e-11eb-8196-a3a5c0f7a96e.png)

**Comment by H4CKY54CK** [comment]
Windows 10, Python 3.8.5, good old fashioned cmd. 

![image](https://user-images.githubusercontent.com/55047705/95662075-55aa5b00-0b02-11eb-8dce-600b91bc64e2.png)

**Comment by H4CKY54CK** [comment]
I don't know if this is relevant, but it all works correctly if I use cmd to ssh into my Raspberry Pi, and do all the same things from there.

**Comment by H4CKY54CK** [comment]
It seems to only be eating the "True Color" sequences (forgive me if that's not the correct term) aka `\x1b[38;2;r;g;bm`.

But surprisingly, I can use 3/4 bit sequences (again, forgive me if not the correct term) just fine aka `\x1b[32m`.

I'm not sure what this means, if anything, but I thought you should know.

![image](https://user-images.githubusercontent.com/55047705/95664017-0409cc80-0b12-11eb-9c2e-568f7134e8bf.png)

**Comment by casperdcl** [comment]
> My legwork was for naught.

correctly diagnosing and liking an appropriate issue is not for naught!

Thanks; closing for now as it seems to be an issue with an upstream library.

For now, this may be required on some systems:

```
import tqdm  # or whatever tqdm imports you use
try:
    import colorama
except ImportError:
    pass
else:
    colorama.deinit()  # breaks some windows systems but fixes other windows systems
    # see https://github.com/tartley/colorama/issues/217
```
