### ISSUE TITLE
MPI compatibility

### ISSUE THREAD

**Issue by biochem-fan** [tqdm/tqdm#691]
- [x] I have visited the [source website], and in particular read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

```
('4.31.1', '2.7.8 (default_cci, Sep  6 2016, 11:26:30) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]', 'linux2')
```

I noticed that `mpi4py` complains if I import `tqdm` after `mpi4py`. This happens with OpenMPI 2.0.0, 2.1.6 and 3.0.3 but not with 4.0.0. OpenMPI is not happy with `fork()` system calls. However, `strace` does not indicate `tqdm` is calling `fork()` or `system()`.

Test code:
```python
from mpi4py import MPI
print 'MPI imported'
print MPI.COMM_WORLD.Get_rank()

from tqdm import tqdm
print 'tqdm imported'
```

```
$ mpirun -n 2 python ~/scripts/mpitest.py
MPI imported
0
MPI imported
1
--------------------------------------------------------------------------
A process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.

The process that invoked fork was:

  Local host:          [[3456,1],0] (PID 54613)

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------
tqdm imported
tqdm imported
```

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by jonaslb** [comment]
I found that this is caused by the following code in `util.py` (near the top), used to detect whether the system is windows or not:
```python
from platform import system as _curos
CUR_OS = _curos()  # fork apparently happens here
```
I guess it should be possible to replace the code with `sys.platform` (which doesn't give the mpi warning), instead of `platform.system()`, but I'm not sure since a bunch of OS names are hardcoded.

**Comment by casperdcl** [comment]
Hmm. `sys.platform` is a little more annoying to parse but can do. https://docs.python.org/3/library/sys.html#sys.platform

**Comment by casperdcl** [comment]
does #1046 (`pip install -U 'git+https://github.com/tqdm/tqdm@devel#egg=tqdm'`) fix your issue?

**Comment by jonaslb** [comment]
That does the trick, yes :) Thanks!

**Comment by biochem-fan** [comment]
I also confirmed this. Thank you very much.

**Comment by casperdcl** [comment]
great; should be in `tqdm>=4.50.2`. Will close when released...
