### ISSUE TITLE
Installing tqdm via conda install python1.6 

### ISSUE THREAD

**Issue by soo-zie** [tqdm/tqdm#701]
I installed tqdm
`conda install -c conda-forge tqdm`

and following package plan appeared:
`## Package Plan ##

  environment location: /home/user/anaconda3/envs/tensor_env

  added / updated specs:
    - tqdm

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2019.3.9   |       hecc5488_0         146 KB  conda-forge
    openssl-1.1.1b             |       h14c3975_1         4.0 MB  conda-forge
    python-1.6                 |                0         4.6 MB  conda-forge
    tqdm-4.31.1                |             py_0          40 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         8.7 MB

The following NEW packages will be INSTALLED:

  tqdm               conda-forge/noarch::tqdm-4.31.1-py_0

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2019.1.23-0 --> conda-forge::ca-certificates-2019.3.9-hecc5488_0
  openssl              pkgs/main::openssl-1.1.1a-h7b6447c_0 --> conda-forge::openssl-1.1.1b-h14c3975_1

The following packages will be SUPERSEDED by a higher-priority channel:

  python                 pkgs/main::python-3.6.7-h0371630_0 --> conda-forge::python-1.6-0
`

I continued with the installation and typing python actually gave me python1.6

`Python 1.6 (#1, Jul 27 2016, 01:25:22)  [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux3
Copyright (c) 1995-2000 Corporation for National Research Initiatives.
All Rights Reserved.
Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
All Rights Reserved.
`

Additional Info:
* Debian Stretch
* Conda 4.6.4

**Comment by casperdcl** [comment]
what on earth? This doesn't seem to be a `tqdm` issue but rather a serious issue with your conda installation. You might try `conda update conda` and `conda update --all`

**Comment by soo-zie** [comment]
I installed python3.6 using `conda install python=3.6` and everything seems fine. 

Raised the issue here: [https://github.com/conda-forge/conda-forge.github.io/issues/754](url)
