### ISSUE TITLE
problem with tqdm while redirecting output to .txt file

### ISSUE THREAD

**Issue by vishalthengane** [tqdm/tqdm#706]
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [ ] I have searched through the [issue tracker] for duplicates
- [ ] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by vishalthengane** [comment]
I am trying to print output on the terminal and redirect the same to '.txt' file by using the following command

`$ python file.py | tee output.txt`

But, I am getting only tqdm output for all loop (It is not printing and print() statements) after the completion of total loop Its printing output in a .txt file and in the terminal.

Please help me with this.

**Comment by casperdcl** [comment]
can you provide an example of:

1. `file.py`'s contents
2. expected console output
3. expected `output.txt` contents

**Comment by vishalthengane** [comment]
Here is code example:

`
from tqdm import tqdm

for i in range(1, 11):
	for j in tqdm(range(10000), desc="Loop [{:2d}/{:2d}]".format(i, 10)):
		pass
	print("I am in {}th loop".format(i))
		
`
Expected terminal output:
`Loop [ 1/10]: 100%|██████████████████| 10000/10000 [00:00<00:00, 3175818.88it/s]
I am in 1th loop
Loop [ 2/10]: 100%|██████████████████| 10000/10000 [00:00<00:00, 3213287.37it/s]
I am in 2th loop
Loop [ 3/10]: 100%|██████████████████| 10000/10000 [00:00<00:00, 2717222.08it/s]
I am in 3th loop
Loop [ 4/10]: 100%|██████████████████| 10000/10000 [00:00<00:00, 3163840.99it/s]
I am in 4th loop
Loop [ 5/10]: 100%|██████████████████| 10000/10000 [00:00<00:00, 3247873.63it/s]
I am in 5th loop
Loop [ 6/10]: 100%|██████████████████| 10000/10000 [00:00<00:00, 3212795.10it/s]
I am in 6th loop
Loop [ 7/10]: 100%|██████████████████| 10000/10000 [00:00<00:00, 3213533.56it/s]
I am in 7th loop
Loop [ 8/10]: 100%|██████████████████| 10000/10000 [00:00<00:00, 3302601.57it/s]
I am in 8th loop
Loop [ 9/10]: 100%|██████████████████| 10000/10000 [00:00<00:00, 3271177.66it/s]
I am in 9th loop
Loop [10/10]: 100%|██████████████████| 10000/10000 [00:00<00:00, 3285527.18it/s]
I am in 10th loop
`

Output I am getting:
`Loop [ 1/10]: 100%|██████████████████| 10000/10000 [00:00<00:00, 3235097.57it/s]
Loop [ 2/10]: 100%|██████████████████| 10000/10000 [00:00<00:00, 3276800.00it/s]
Loop [ 3/10]: 100%|██████████████████| 10000/10000 [00:00<00:00, 3308593.52it/s]
Loop [ 4/10]: 100%|██████████████████| 10000/10000 [00:00<00:00, 2814024.82it/s]
Loop [ 5/10]: 100%|██████████████████| 10000/10000 [00:00<00:00, 3368648.30it/s]
Loop [ 6/10]: 100%|██████████████████| 10000/10000 [00:00<00:00, 3316441.84it/s]
Loop [ 7/10]: 100%|██████████████████| 10000/10000 [00:00<00:00, 3287845.10it/s]
Loop [ 8/10]: 100%|██████████████████| 10000/10000 [00:00<00:00, 3148404.14it/s]
Loop [ 9/10]: 100%|██████████████████| 10000/10000 [00:00<00:00, 3034952.24it/s]
Loop [10/10]: 100%|██████████████████| 10000/10000 [00:00<00:00, 3337288.35it/s]
I am in 1th loop
I am in 2th loop
I am in 3th loop
I am in 4th loop
I am in 5th loop
I am in 6th loop
I am in 7th loop
I am in 8th loop
I am in 9th loop
I am in 10th loop
`

.txt file output:

`I am in 1th loop
I am in 2th loop
I am in 3th loop
I am in 4th loop
I am in 5th loop
I am in 6th loop
I am in 7th loop
I am in 8th loop
I am in 9th loop
I am in 10th loop`

**Comment by vishalthengane** [comment]
Sorry!

This is not a problem with the tqdm without using the tqdm I am still getting a problem. The command redirects the output to .txt file after completion of the total program. It not printing and/or redirecting output after each loop. Please let me know if anyone found the answer.

Thanks in advance!

**Comment by casperdcl** [comment]
that's great - maybe a question for stackoverflow then rather than a github issue

**Comment by f0k** [comment]
When stdout is not a terminal, the output will be buffered and not flushed immediately after each `print()` statement. If you run `python -u yourscript.py` or `PYTHONUNBUFFERED=1 ./yourscript.py`, it should work as expected. See [`PYTHONUNBUFFERED`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUNBUFFERED).

**Comment by Demirrr** [comment]
Dear @f0k and @casperdcl 

I realised that explicitly using sys.stdout solved  the problem of redirecting output to .txt file.
```python
# example.py
from tqdm import tqdm
import sys
import time
file = sys.stdout
for epoch in tqdm(range(10), file=sys.stdout):
    time.sleep(0.1)
```
```bash
 python example.py > a.log
 ``` 

  0%|          | 0/10 [00:00<?, ?it/s]
 10%|█         | 1/10 [00:00<00:00,  9.96it/s]
 20%|██        | 2/10 [00:00<00:00,  9.94it/s]
 30%|███       | 3/10 [00:00<00:00,  9.94it/s]
 40%|████      | 4/10 [00:00<00:00,  9.94it/s]
 50%|█████     | 5/10 [00:00<00:00,  9.93it/s]
 60%|██████    | 6/10 [00:00<00:00,  9.92it/s]
 70%|███████   | 7/10 [00:00<00:00,  9.91it/s]
 80%|████████  | 8/10 [00:00<00:00,  9.91it/s]
 90%|█████████ | 9/10 [00:00<00:00,  9.90it/s]
100%|██████████| 10/10 [00:01<00:00,  9.91it/s]
100%|██████████| 10/10 [00:01<00:00,  9.91it/s]

**Comment by casperdcl** [comment]
not really @Demirrr instead you need:

```python
# example.py
from tqdm import tqdm
import time
for epoch in tqdm(range(10)):
    time.sleep(0.1)
```
```bash
python example.py 2>&1 > a.log
```
