### ISSUE TITLE
Progress bar prints through eol on fedora/bpython

### ISSUE THREAD

**Issue by MrMattBusby** [tqdm/tqdm#71]
Following the gif from the readme on my distro, tqdm does not play well with bpython (Fedora 21 Linux 4.1.7, bash on xterm-256color, Python 2.7.8 on bpython 0.14.2 (via yum) running tqdm 3.4.0 (via pip)).

After:

    >>> for _ in tqdm.tqdm(xrange(10)):
    ...     time.sleep(.1)

The output writes blank characters to the end (right) of the terminal (the progress bar does not extend all the way to the end either) until the new line is reached and is then reprinted on the next line, the very last write eliminates the last 100% line, leaving this printed in the terminal:

    40%|####      | 4/10 [00:00<00:00,  9.07it/s]
    80%|########  | 8/10 [00:00<00:00,  8.37it/s]

On both ipython and regular interactive python sessions the result prints properly:

    50%|███████████████████████████████████████████████████████████████████████████████████▌                                                                                   | 5/10 [00:05<00:05,  1.00it/s]

**Comment by MrMattBusby** [comment]
It seems the culprit is likely the current version of bpython as evidenced here: https://github.com/bpython/bpython/issues/574

**Comment by casperdcl** [comment]
Hmm interesting. The version of `bpython` I used for the graphic must have predated this, but now I'm observing the same glitch. I think this is a `bpython` issue and not a `tqdm` one - let me know if you find a work-around, though.

**Comment by lrq3000** [comment]
Maybe meanwhile you can try to set `ncols` to fix the width issue with bpython?

**Comment by casperdcl** [comment]
meanwhile, I think just use `bpython-curses` instead (it comes with `bpython` anyway)

**Comment by lrq3000** [comment]
Closing this too, we can't do anything about it.
