### ISSUE TITLE
Being able to show s/it instead of "it/s"

### ISSUE THREAD

**Issue by jcea** [tqdm/tqdm#72]
I have operations that takes several seconds. Lets say, process datablocks. Lets say that each datablock takes 5 seconds.

I rather prefer to see "5s/block" than "0.2block/s".

I would like to have a flag to reverse the units displayed.  Even something automatic like a flag to request "if it/s<1 -> show s/it".

**Comment by casperdcl** [comment]
Thanks for bringing this up. I remember discussing it before but must have fogot.

**Comment by damiendr** [comment]
Would it be possible to disable this with a flag? It can be confusing — for instance, when reporting simulated time (`unit="hours"`), the meter keeps swapping between seconds per hour and hours per second.

**Comment by casperdcl** [comment]
surely if it'd constantly switching that means the rate is roughly 1 either way, so it's not confusing?

**Comment by damiendr** [comment]
If the speed varies a lot, for instance between runs, it makes it hard to tell at first glance if "3" is slow or fast.

**Comment by casperdcl** [comment]
https://github.com/tqdm/tqdm/commit/b228bc39fd86e26d7d724b811b4e9f7f1be8bc7f added `rate_noinv`, and https://github.com/tqdm/tqdm/commit/1259f684d326044ff0e3019d996e66f5b9fa2b0c just added `rate_(no)inv(_fmt)` so you can:

```python
tqdm(..., bar_format="{l_bar}{bar}| {n_fmt}/{total_fmt}" +
     " [{elapsed}<{remaining}, {rate_noinv_fmt}]")
```

**Comment by damiendr** [comment]
Thanks, I'll try that!
