### ISSUE TITLE
Drop distutils

### ISSUE THREAD

**Issue by KOLANICH** [tqdm/tqdm#721]
- distutils are superceeded by setuptools which are more feature-rich and which API is incompatible.
- `setuptools_scm` gets the version from git correctly. The currently used way to get version from git is buggy, for example it breaks on linux
- Use `setuptools` `setup.cfg` (a declarative way to provide metadata to `setup`) to store metadata and import the text files

**Comment by casperdcl** [comment]
any particular reason to do so?

**Comment by KOLANICH** [comment]
What feedback do you need?

**Comment by casperdcl** [comment]
ah none really. I think this would break compatibility with py2.6 but that's not a problem - just would like to merge a few other issues first
