### ISSUE TITLE
Restarting a progress meter without getting crazy

### ISSUE THREAD

**Issue by jcea** [tqdm/tqdm#73]
In my program I can restart a calculation. If I restart a calculation, I do something like:

```
class progress :
    def __init__(self, path, num_fragmentos) :
        self.num_fragmentos = num_fragmentos
        self._first = True
        self._progress = tqdm.tqdm(
                total = num_fragmentos,
                unit = "block",
                miniters = 1)

    def __call__(self, num_fragmento) :
        if self._first :
            self._progress.update(num_fragmento)
            self._first = False
        else :
            self._progress.update()
```
I create a regular tqdm and in the first call I "jump" to the right position. This shows the progress bar, but "it/s", ETA, etc, are unrealistic for a while.

I would like to add an initial value to tqdm constructor. I should be able to do something like "tqdm(total=100, initial=71)", and not mess with time estimations.

**Comment by lrq3000** [comment]
This will get fixed at the same time as #70 with the idea I have.
