### ISSUE TITLE
`tqdm_notebook.set_description()` ignores `refresh=False`

### ISSUE THREAD

**Issue by smallnamespace** [tqdm/tqdm#740]
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```
  >>> print(tqdm.__version__, sys.version, sys.platform)
  4.31.1 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59)
  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] darwin
  ```

`refresh=False` doesn't work because `set_description` is overridden and always updates the widget: https://github.com/chengs/tqdm/blob/01ea3170a91e4b30e8e96690b9f70e853bf4ff48/tqdm/_tqdm_notebook.py#L220

![image](https://user-images.githubusercontent.com/15881001/57577032-d7d0b480-7422-11e9-9429-f36a72758606.png)

**Comment by jacksonloper** [comment]
Right so the idea is that if `refresh=True` then it should only update the description on the same schedule as `mininterval`, right?  is that the idea?  that would be a great feature.  always blowing out my jupyter iopub socket :)

**Comment by casperdcl** [comment]
ah `refresh=True` should forcefully update the bar, whereas `refresh=False` should only update as per `mininterval` etc. This seems to be part of #790

**Comment by casperdcl** [comment]
Can you try out current `devel` (`pip install -e git+https://github.com/tqdm/tqdm.git@devel#egg=tqdm` or similar) and let me know if it fixes this issue?
