### ISSUE TITLE
IPython notebook pandas

### ISSUE THREAD

**Issue by redbeards-data** [tqdm/tqdm#742]
Just attempted to install 4.32.0 and run in a Jupyter notebook running out of a docker container. Upon the first use (whether it be calling tqdm.pandas() or if this line is commented out and another import method used, the first time it is used in a for-loop), I get the following error:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-1-ac7677003442> in <module>
      7 from tqdm import tqdm_notebook as tqdm
----> 8 tqdm().pandas()

/usr/local/lib/python3.6/dist-packages/tqdm/__init__.py in tqdm_notebook(*args, **kwargs)
     23     """See tqdm._tqdm_notebook.tqdm_notebook for full documentation"""
     24     from ._tqdm_notebook import tqdm_notebook as _tqdm_notebook
---> 25     return _tqdm_notebook(*args, **kwargs)
     26 
     27 

/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm_notebook.py in __init__(self, *args, **kwargs)
    211         unit_scale = 1 if self.unit_scale is True else self.unit_scale or 1
    212         self.sp = self.status_printer(
--> 213             self.fp, self.total * unit_scale, self.desc, self.ncols)
    214         self.desc = None  # trick to place description before the bar
    215 

TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

- [ x ] I have visited the [source website], and in particular
  read the [known issues]
- [ x ] I have searched through the [issue tracker] for duplicates
- [ x ] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

--EDIT-- 

Error is not present in same code when specifying v4.31.1 

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by casperdcl** [comment]
> `tqdm().pandas()`

should be `tqdm.pandas()`

**Comment by redbeards-data** [comment]
> > `tqdm().pandas()`
> 
> should be `tqdm.pandas()`

I don't think it should be. When running, I get this error:
```AttributeError: 'function' object has no attribute 'pandas'```

**Comment by casperdcl** [comment]
ah also

> from tqdm import tqdm_notebook as tqdm

should be

`from tqdm.auto import tqdm`

or

`from tqdm.autonotebook import tqdm`

or

`from tqdm._tqdm_notebook import tqdm_notebook as tqdm`

**Comment by redbeards-data** [comment]
Still doesn't work:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-eabbf48c5516> in <module>
----> 4     for row in tqdm({name of my csv dictionary reader}):

/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm_notebook.py in __init__(self, *args, **kwargs)
    211         unit_scale = 1 if self.unit_scale is True else self.unit_scale or 1
    212         self.sp = self.status_printer(
--> 213             self.fp, self.total * unit_scale, self.desc, self.ncols)
    214         self.desc = None  # trick to place description before the bar
    215 

TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

**Comment by casperdcl** [comment]
great, now it's a different issue.

I'll open a new one and leave this one (pandas notebook) as-is as a documentation improvement candidate.

**Comment by redbeards-data** [comment]
Thanks for the prompt replies!

**Comment by CentralLT** [comment]
@redbeards-data does this problem still exist? if not let's close the issue.
