### ISSUE TITLE
Auto-detect does not work for `jupyter` notebooks running in `vscode`

### ISSUE THREAD

**Issue by songololo** [tqdm/tqdm#747]
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:

Auto-detect does not appear to work for `jupyter` notebooks running in `vscode`, and will result in the following form of output:
```
HBox(children=(IntProgress(value=0, max=252777), HTML(value=''))
```

Perhaps vscode scenarios could be covered under autonotebook's `__init__.py`?

(Tested in the normal jupyter console, and works as intended.)

Let me know if to open an issue under [`vscode-python`](https://github.com/Microsoft/vscode-python) instead.

```
tqdm.__version__
# '4.32.1'
sys.version
# '3.7.3 (default, Mar 27 2019, 09:23:15) \n[Clang 10.0.1 (clang-1001.0.46.3)]'
sys.platform
# 'darwin'
# vscode v1.34
```

**Comment by casperdcl** [comment]
> Perhaps vscode scenarios could be covered under autonotebook's __init__.py?

Would be nice if you could suggest a way to check if the frontend is vscode. Don't have much time to do ot myself :)

**Comment by songololo** [comment]
Here are some `vscode` specific environment variables available from `jupyter` when running inside vscode:

```
'VSCODE_NODE_CACHED_DATA_DIR': '...'
'VSCODE_PREVENT_FOREIGN_INSPECT': 'true',
'VSCODE_LOGS': '...',
'VSCODE_HANDLES_UNCAUGHT_ERRORS': 'true',
'VSCODE_IPC_HOOK_EXTHOST': '...',
'VSCODE_NLS_CONFIG': '{"locale":"en-gb","availableLanguages":},"_languagePackSupport":true}',
'VSCODE_IPC_HOOK': '.../1.34.0-main.sock',
'VSCODE_PID': '94309'
```
So perhaps adding a step to check for a `VSCODE_PID` environment variable would be sufficient for detecting whether `jupyter` is running inside `vscode`?

**Comment by songololo** [comment]
A heads-up that `vscode` has made some changes so there is a chance the notebook progress bar would now work for `vscode`, but I have not had a chance to test.

**Comment by casperdcl** [comment]
much wonderful such fun. let me know if there's any more future-proof solution

**Comment by songololo** [comment]
Just checked and the `autonotebook` functionality has not yet been remedied `vscode`, so this workaround can stay in place for the time being. Will update if I noticed anything changing.

**Comment by songololo** [comment]
This is the related issue at ‘vscode’: microsoft/vscode-python/issues/6290

**Comment by Serhiy-Shekhovtsov** [comment]
That's weird. I have this variable set when running without `vscode`. Tried with `jupyter notebook` and `jupyter lab` - the variable is set every time. So `tqdm.auto` imports `tqdm.std.tqdm` version. I even made sure there is no single VSCode instance running.
