### ISSUE TITLE
result of print statement appears below progress bar even though progress bar is below print statement

### ISSUE THREAD

**Issue by johncoxon** [tqdm/tqdm#748]
I've looked through the open issues and I can't see anyone else who's asked about this, so I'm hoping it's not a dupe. I'm running tqdm 4.32.1 with Python 3.6.8 on macOS Mojave (10.14.3).

When I run the following code in a Jupyter notebook, the progress bars all appear before the results of the print statements, as in the attached screenshot. Why is this occurring?

```
for i in np.arange(5):
    print('this is loop {}'.format(i))
    for j in enumerate(tqdm.tqdm(np.arange(100))):
        pass
```

![Screenshot 2019-05-23 at 13 43 25](https://user-images.githubusercontent.com/1693743/58253623-c5c70e00-7d60-11e9-8e4d-02127f0e509b.png)

**Comment by casperdcl** [comment]
https://github.com/jupyter/help/issues/111

**Comment by casperdcl** [comment]
you can also use `from tqdm.auto import tqdm`
