### ISSUE TITLE
[Feature request] Flag for completed / interrupted generator.

### ISSUE THREAD

**Issue by LucaCappelletti94** [tqdm/tqdm#752]
Hello, I am trying to figure out a way to identify if a tqdm bar has completed, having access to just the tqdm bar object.

When a bar `b` is allowed to finish, it is simply a question of comparing `b.n` and `b.total`, but when for instance a break is present within the loop a call to `__exit__` and `close()` is made, but no flag or anything (based on what I could understand reading the source code) is set.

By extending the tqdm class `close` method I could not achieve the desired behavior (setting a flag when completed) as I don't completely understand how the system works and maybe my simple inheritance approach isn't sufficient.

How could I determine if a bar has been closed?

**Comment by casperdcl** [comment]
part of notorious #548
