### ISSUE TITLE
[question] with nested loops

### ISSUE THREAD

**Issue by wherethedevildances** [tqdm/tqdm#755]
Hi, I'm new to tqdm and I'm just trying to understand the behavior of this... It counts the files in a directory and then loops over each file. The tqdm bar fills up correctly to count the files, but then bar disappears and the counter continues iterating for each sub-loop. How can I make it create a new bar for those sub loops?
Thanks!

```python
count_files = len([name for name in os.listdir(path) if os.path.isfile(os.path.join(path, name))])
with tqdm(total=count_files) as pbar:
        for entry in os.scandir(path):
            pbar.update(10) 
            
            if entry == "records":
                loop_file(entry)
```

**Comment by casperdcl** [comment]
erm this is really a stackoverflow question.

in any case, your `total` is a number of files, whereas you're `scandir`ing over both files and dirs, and you're then doing `update(10)` rather than `1` for each. That's just so wrong it's not even possible to infer what you meant to do.
