### ISSUE TITLE
tqdm.update() does nothing when called from a Future completion callback.

### ISSUE THREAD

**Issue by sammko** [tqdm/tqdm#757]
See the following example:
```python3
import time
from concurrent.futures import ThreadPoolExecutor
from tqdm import tqdm

def worker():
    time.sleep(1)

jobs = 20
with ThreadPoolExecutor(max_workers=4) as tpe, tqdm(total=jobs) as tq:
    def cb(*args):
        tq.update(1)
    for _ in range(jobs):
        tpe.submit(worker).add_done_callback(cb)
```
The progress bar does not move at all on my system. I can't tell whether this is related to #543, is a different bug, or I am doing something wrong. Thank you.

```
4.28.1 3.7.3 (default, Mar 26 2019, 21:43:19) 
[GCC 8.2.1 20181127] linux
```

**Comment by sammko** [comment]
This is caused by the fact that if you specify multiple context managers in a single `with` statement, the latter one is the "inner" one, and as such is closed right after the code inside the statement finished. In the example above, tqdm does not block and is closed immediately after the jobs are submitted. The with statement then blocks on the `ThreadPoolExecutor`, waiting for workers to finish, however at this time, tqdm is already closed. This is fixed simply by switching the order of `tqdm` and `TPE` withinin the `with` statement and is not a bug, just an oversight.

**Comment by casperdcl** [comment]
ah nice I didn't spot that. yet another example of `tqdm` making external issues more obvious :)
