### ISSUE TITLE
Race condition with tqdm.write

### ISSUE THREAD

**Issue by orf** [tqdm/tqdm#759]
`tqdm.write()` appears to have a race condition that triggers occasionally:

```python
from tqdm import tqdm

def do_something(_):
    tqdm.write('test')

with ThreadPoolExecutor(max_workers=10) as pool:
    list(tqdm(pool.map(do_something, range(1000)))
```

This fixes it:

```python
with ThreadPoolExecutor(max_workers=10) as pool:
    progress = tqdm(pool.map(do_something, range(1000))
    progress.get_lock()
    list(progress)
```

The issue appears to be in `get_lock`:

```python
    @classmethod
    def get_lock(cls):
        """Get the global lock. Construct it if it does not exist."""
        if not hasattr(cls, '_lock'):
            cls._lock = TqdmDefaultWriteLock()
        return cls._lock
```

If two threads call this at the same time then the `cls._lock` will be overwritten, and `cls._lock.release()` at the end of `external_write_mode` will release the wrong lock.

**Comment by casperdcl** [comment]
hmm yes.

You could also:

```python
from tqdm import tqdm

def do_something(_):
    tqdm.write('test')

with ThreadPoolExecutor(max_workers=10) as pool:
    tqdm.get_lock()
    list(tqdm(pool.map(do_something, range(1000)))
```

**Comment by orf** [comment]
I’m not sure this is a question, it feels like a legitimate bug.

**Comment by orf** [comment]
I feel the solution is to set the default lock in the initializer.

**Comment by casperdcl** [comment]
> I feel the solution is to set the default lock in the initializer. Is there any reason this is not already done?

There would still be a problem if two threads initialise `tqdm` simultaneously.

`question` is the label I also use for documentation update candidates

**Comment by orf** [comment]
We could add a global tqdm lock to lock the creation of this other lock? 😂
