### ISSUE TITLE
color printing not possible in jupyter notebook after importing tqdm?

### ISSUE THREAD

**Issue by Ruler26** [tqdm/tqdm#764]
Printing colored text in jupyter notebook doesn't seem to work after importing tqdm

Example:
![tqdm](https://user-images.githubusercontent.com/17850171/60166447-824d3d00-9801-11e9-9486-bb3c90bdf763.png)

tqdm 4.23.4
python 3.6.8
ipython 7.5.0
windows server 2012R2

Any suggestions?

**Comment by casperdcl** [comment]
interesting. If your replace the tqdm import with `import colorama` do you still get this issue?

**Comment by Ruler26** [comment]
colorama seems to work fine even without init() on windows. Using init() doesn't 'reset':
![tqdm_colorama](https://user-images.githubusercontent.com/17850171/60255238-abd49a00-98cf-11e9-850d-895f67293776.png)

**Comment by chaudharyachint08** [comment]
It is not still working, also from the image  above we can see that after tqdm import, both termcolor & colorama failed to display colors
