### ISSUE TITLE
Estimate remaining time using time periods as well as samples. 

### ISSUE THREAD

**Issue by Rizhiy** [tqdm/tqdm#767]
Current method of estimating remaining time doesn't perform well when there is a lot of variation between iterations and each iteration is very small.

e.g. I have a process which has the mean speed of about 100 it/s, but std of 30 it/s.
Finding the correct smoothing value for such cases is very difficult and redundant.

To perform better in such cases, we can count how many iterations have been done in past N seconds and estimate remaining time based on that.

**Comment by almson** [comment]
#1102 should have fixed this
