### ISSUE TITLE
Last vs average iteration time

### ISSUE THREAD

**Issue by cristi-neagu** [tqdm/tqdm#769]
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and

`tqdm version 4.32.1`

Hello,

The `it\s` seems to report the time it took for the last iteration to complete. Is there any way of having it report the average iteration time instead (as in, time since iteration started divided by current number of iteration steps)?

Thank you.

**Comment by casperdcl** [comment]
`smoothin=0`
