### ISSUE TITLE
How to use tqdm with map, filter, reduce etc functions?

### ISSUE THREAD

**Issue by syllogismos** [tqdm/tqdm#78]

**Comment by casperdcl** [comment]
Never actually tried this before. Just tested it now and it seems to work fine:

```python
from tqdm import tqdm, trange
a=range(int(1e8))

"""
Create an array `b` which is the `str` equivalent of `int` array `a`,
using `tqdm` for peogress.
"""

#method 1
b=[' ']*len(a)
for n in tqdm(a):
    b[n] = str(n)

#method 2
b = [str(n) for n in tqdm(a)]

#method 3
b = map(str, tqdm(a))
```

**Comment by casperdcl** [comment]
Basically just replace `iterable` with `tqdm(iterable)` everywhere you need progress monitoring...

**Comment by casperdcl** [comment]
More examples:

```python
from tqdm import tqdm, trange

reduce(lambda x,y:x+y, trange(int(1e7), leave=True))

sum(trange(int(1e7), leave=True))

a=filter(lambda x:x%2, trange(int(1e7), leave=True))
```

**Comment by syllogismos** [comment]
Wow so cool.. Thank you.
I came from here http://blog.rtwilson.com/my-top-5-new-python-modules-of-2015/

**Comment by casperdcl** [comment]
np. thx ;)

**Comment by syllogismos** [comment]
https://raw.githubusercontent.com/tqdm/tqdm/master/tqdm.gif 

What extension enables the doc_string and function signature to be shown in the box in python prompt like in this gif in the README?

**Comment by casperdcl** [comment]
`bpython` in a linux terminal.

**Comment by VijaySaiProfessional** [comment]
Hi . Is there a way to make use of tqdm or any other function to display the progress of a user defined function execution without iterables in python?

**Comment by matanster** [comment]
Any equivalent of `trange` for use in a notebook?

**Comment by casperdcl** [comment]
`from tqdm.auto import trange`

**Comment by HaleTom** [comment]
@casperdcl Method 3 no longer seems to work. 

I get:

```
 0%|          | 0/1000 [00:00<?, ?it/s]
```
Is it the same for you?

**Comment by casperdcl** [comment]
@HaleTom assuming you're using python3, `map` returns a generator rather than a `list` so you won't get progress until you iterate:

```
python3 -c "from tqdm import tqdm; map(str, tqdm(range(1000)))"
 0%|                     | 0/1000 [00:00<?, ?it/s]
```

```
python3 -c "from tqdm import tqdm; list(map(str, tqdm(range(1000))))"
100%|████| 1000/1000 [00:00<00:00, 1450312.59it/s]
```

See https://docs.python.org/3.6/library/functions.html#map verus https://docs.python.org/2.7/library/functions.html#map
