### ISSUE TITLE
CMD line overlaps nested progress bar after execution

### ISSUE THREAD

**Issue by maximilian578** [tqdm/tqdm#784]
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
```
tqdm: 4.32.2 
sys: 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] 
sys.platform: win32
```
When executed from Powershell or cmd cmd line overlaps nested progress bars after script execution.

![image](https://user-images.githubusercontent.com/8377469/62248763-8e747d80-b3f1-11e9-9803-727272b1ae0c.png)
 
![image](https://user-images.githubusercontent.com/8377469/62249275-aef10780-b3f2-11e9-9db6-518c010f75fe.png)

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by casperdcl** [comment]
See https://github.com/tqdm/tqdm#nested-progress-bars where you need to print '\n' a few times after the nests to bring the cursor down

**Comment by maximilian578** [comment]
Thanks for the answer, closing. This seems like a thing that should be done by tqdm thou.
