### ISSUE TITLE
Too much dependecies?

### ISSUE THREAD

**Issue by raffam** [tqdm/tqdm#789]
I had a project which imported and used `tqdm`. But I had to make executable for Windows and used PyInstaller to do so. PyInstaller generated a very big .exe file (70MB) due to the fact that by importing tqdm it also imported `qt`, `matplotlib` and other graphic libraries I really didn't need.

I removed the dependency from tqdm and now only print a simple statement to the console. Are all those graphic dependencies necessary for `tqdm`?

**Comment by casperdcl** [comment]
`tqdm` doesn't have any dependencies. `matplotlib`, `pandas`, `jupyter` etc are all optional and `tqdm` will work with them if they are present. Perhaps `PyInstaller` is being too intelligent and installing things even though `tqdm` does not list them as required?

**Comment by casperdcl** [comment]
yup https://pyinstaller.readthedocs.io/en/stable/operating-mode.html#analysis-finding-the-files-your-program-needs

**Comment by casperdcl** [comment]
Seems you need to edit your `myscript.spec`. Happy to reopen if there's anything `tqdm` can do.

**Comment by raffam** [comment]
Oh okay, thanks for your feedback :)

**Comment by casperdcl** [comment]
Possibly want to open an issue with PyInstaller to blacklist fake dependencies and/or use setup.py's dependencies etc..,

**Comment by Windows81** [comment]
```
--exclude-module "tqdm.std"
--exclude-module "tqdm.gui"
--exclude-module "tqdm.notebook"
--exclude-module "tqdm._tqdm_pandas"
```

From my findings, the thing that's making your PyInstaller thing too big would either be Pandas or Matlab libraries.

I was able to reduce almost all of the additional bloat.

For more info, refer to https://github.com/pyinstaller/pyinstaller/issues/3278#issuecomment-364265118.
