### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by MissAbbie** [tqdm/tqdm#80]
Hello, I am Miss Abbie, a representative from http://socialjusticecode.org, this is a message on behalf of the organization about this repo. We've noticed that there are a few triggering things included in here that could scare some members of the gay/trans/gender-fluid community away. In your readme you have what the name of this repo means in Arabic, and it is fantastic that you are including other languages, however this is cultural appropriation. Please give credit to the arabic community if you insist on using their language in the context of a project, or arabic members of the code community may be too disgusted to use the code. It would be better not to include this at all, as you are basically stealing the language from a culture and using it for your own purposes. Also there is a lot of capital letters in your file names, including "license" (all in capital letters), "contribute", "manifest", "readme", and "release." While it is fine to have one or two of these, this many may scare off some who find this triggering.

It would be fantastic if you could clear all of these up and become SJC approved, making GitHub and the coding community a better place. (✿ -‿-)

**Comment by chraibi** [comment]
In fact, Miss Abbie, I found your trolling text *triggering*. ;-)

**Comment by casperdcl** [comment]
Closed as off-topic.
Justification:
The comments seem too vague or intended to cause unproductive aggravation and include unjustified, (without explanation) libellious accusations. There seems to be a suggestion that the multilingual, multicultural `tqdm` community volunteers should refrain from using one of their languages, and refrain from using standard file naming practice. `tqdm` volunteers remain open as always to PRs and feedback, should the OP feel the need to clarify some misundertanding.
Blessed and Happy Christmas!
`tqdm`

**Comment by MissAbbie** [comment]
Not everyone celebrates Christmas, @casperdcl. My post's aim was not to cause unjustified anger, however it appears that is your response to it. Interesting. All I did was point out an issue with the amount of cultural appropriation in this project. It's troubling that it has been met with such overwhelming resistance. Shame.

**Comment by nabijaczleweli** [comment]
This is both hilarious and depressing at the same time.

**Comment by MissAbbie** [comment]
I'm glad you find societal and cultural oppression hilarious, @nabijaczleweli. Good on you.

**Comment by nabijaczleweli** [comment]
This troll is either really bored, or has been fed lotsa propaganda.
Here's another repo for you to troll, if you'd like: [`letsgetrandy/DICSS`](https://github.com/letsgetrandy/DICSS).

**Comment by MissAbbie** [comment]
It's also interesting how you think social justice is nothing more than a "troll." Congratulations on being a truly awful human being. Your mother would be proud.

**Comment by nabijaczleweli** [comment]
Cheers for making my afternoon much better, mate

**Comment by MissAbbie** [comment]
You're going to apologize for posting messages in a topic? You truly are the epitome of a weak white little cis male.

**Comment by chraibi** [comment]
Miss Abbie you suggest that the developers of this **great** project are not Arabs. Are you being racist? How could you make such a non-rational guess?
Here another project for you: [Menge](https://github.com/MengeCrowdSim/Menge).
 The authors are Americans (I know) and the project's name is German.

**Comment by nabijaczleweli** [comment]
Addressing your (insensitive, if not *\~\~\~offensive\~\~\~*) comment towards my (possibly deceased) mother: She *is* proud of me, because I, unlike you, do something with my life, other than trolling FOSS repos for using capital letters in filenames.

Oh, and I like how you assume I am a white cis male. How... SJW-like, really. You truly have become that, which you most hated.

**Comment by MissAbbie** [comment]
@chraibi I don't believe I said that at all. I'm saying white people using the language (and therefore culture) of other races is cultural appropriation and should not be tolerated. That project is problematic in its own right.

As for the racist @nabijaczleweli, no woman could ever love her son if he was as racist, insensitive, and homophobic as you are. What if someone's (maybe your?) mother had a panic attack because of random unprecedented capital letters, causing anxiety and paranoia like so many trans/gender-fluid/gay people experience on a daily basis. I assume you are a white cis male as you exhibit all the racist, awful, bigoted qualities of one. "cheers," hun :)

**Comment by MissAbbie** [comment]
Also if you could stop referring to social justice as being a troll that'd be great sweetie. (✿ -‿-)

**Comment by MissAbbie** [comment]
You're getting awful defensive @nabijaczleweli. So many projects! WOW! Is your male git-penis rock hard right now? Glad you can still display your oppressive behavior freely.

**Comment by nabijaczleweli** [comment]
I'd also delicately like to point out, that some of the world's richest (if not *the* richest) Arabs are white, see: ![arabs](https://cloud.githubusercontent.com/assets/6709544/12004209/14f654d0-ab47-11e5-9cf5-42a4007d2688.jpg)

**Comment by MissAbbie** [comment]
They've made their fortune by oppressing others, obviously. Keep digging the hole my friend.

**Comment by lrq3000** [comment]
Stop here and right now. This kind of discussion does not belong to this place (and I'm not sure it belongs to any place at all).

**Comment by lrq3000** [comment]
This thread is now locked. Please stop and don't try to reopen an issue, or you will get reported to GitHub for inappropriate behavior.

As for the original statement, it is completely bogus. Common words are part of the public culture and as thus belong to everyone. Just like you cannot patent these words, you cannot prevent others from using them: this is public domain. Also, TQDM is an acronym, so as thus, it does not directly relate to any word.
