### ISSUE TITLE
Progess not running for iter_content

### ISSUE THREAD

**Issue by dyseo** [tqdm/tqdm#804]
- [ ] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker](https://github.com/tqdm/tqdm/issues/113) for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  4.35.0 3.7.4 (default, Jul 28 2019, 22:33:35)
  [Clang 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf6 linux
  ```

let knowing my issue, my code:
```python
def download(self):
	self.timeout = 10000
	parse = self.parse("GET", stream=True)
	size = int(parse.headers.get('Content-Length', 0))
	chunks = size if size > 0 else 16*1024*1024
	tq = tqdm(desc="Downloading",
		       total=chunks,
		       unit="KB",
		       unit_scale=True, 
		       leave=True,
		       miniters=1)
	with open(self._path, 'wb') as fp:
		for chunk in parse.iter_content(chunks):
			if chunk:
				tq.update(len(chunk))
				fp.write(chunk)
			else:
				raise
	print("Download complete")
```

this code work as well as i know, but the progress bar not update and still like this
```
Downloading:   0%|                               | 0.00/33.6M [03:02<?, ?KB/s]
```
> Nb: but if download have completely, this progress bar have fully :/ and print more progress bar

but if i change chunks to `16*1024*1024` and not use size of file from url web
progress bar working as well.

**Comment by casperdcl** [comment]
Your file size is 33.6MB. So if your chunks are bigger than this then it gets downloaded in one big step (so there's no progress).

**Comment by dyseo** [comment]
> Your file size is 33.6MB. So if your chunks are bigger than this then it gets downloaded in one big step (so there's no progress).

ah i see, i have see this. that progess update only if 50%>75% and 100% of progress
okay, thanks for your advice . i'll close it
