### ISSUE TITLE
Progress bar and upload progress are not shown in python 2.7.10

### ISSUE THREAD

**Issue by neara** [tqdm/tqdm#807]
Hi folks!

I can't get the progress bar to show when running in an environment with python 2.7.10. 
Running on Mac OS Mojave 10.14.6.
tqdm version 4.35.0

Please consider following code sample:

```
import os

from tqdm import tqdm


file_name = "/full/path/to/file/to/upload.gz"
MB = 1024 * 1024


def upload_file(filename, callback):
    """Upload file using S3 to a bucket."""
    pass

def _progress_bar_update(pbar):
    def _update_pbar(chunk_uploaded_in_bytes):
        pbar.update(chunk_uploaded_in_bytes / MB)

    return _update_pbar


with tqdm(
        total=int(os.path.getsize(file_name) / MB),
        unit="MB",
        desc="Progress: ",
        unit_scale=True,
        unit_divisor=MB,
        ncols=150,
        leave=True,
) as progress_bar:
    upload_file(
        file_name,
        callback=_progress_bar_update(progress_bar),
    )
```

Progress bar looks like this:

<img width="1055" alt="Screen Shot 2019-09-09 at 17 22 34" src="https://user-images.githubusercontent.com/1453895/64539640-86302c00-d327-11e9-9c52-0b2b5c9b7429.png">

Total size is identified properly, the rest is not working. 
Everything works as expected in python 3.7.4, same machine
Any help would be greatly appreciated.

**Comment by casperdcl** [comment]
does it work if you add `ascii=True`?

**Comment by neara** [comment]
no, looks exactly the same.

**Comment by casperdcl** [comment]
hmm in that case it's probably not a unicode issue. Does the loop actually complete in py2 though? Perhaps the file isn't actually uploading? Perhaps try to print a message after it's uploaded to check.

**Comment by neara** [comment]
Yes, it's uploading.

**Comment by casperdcl** [comment]
I think the forced "MB" unit is a little weird the way you've done it (a 1GB file would show as 1kMB) but that's not the issue here.

Could it be the py2 upload code doesn't use the callback in the same way? it might be useful to use `callback=print` just to check

**Comment by neara** [comment]
I added the print and it appears on each iteration.

**Comment by casperdcl** [comment]
what about adding `miniters=1, mininterval=0`?

**Comment by neara** [comment]
Still nothing, also time elapsed doesn't update with those settings.

**Comment by neara** [comment]
Hi guys, I had to implement a different solution. Thank you for your help trying to figure out why it's not working.

**Comment by casperdcl** [comment]
Sure. "guys" plural hah it's just me :)

Did you figure it out?

**Comment by neara** [comment]
Hehe. Thank you 🙏 I really appreciate your help debugging this 😊 
I moved to another progress bar tool.

**Comment by casperdcl** [comment]
aw that's the first i've herd pf someone moving away. Now I'm really eager to fix this. Could you send a complete minimal working example?

**Comment by neara** [comment]
Sorry, ran out of time to debug this. I will be glad to help fix this :) I will try to come up with a code already this week (or asap 🙈) , something that works in python 3.7 and fails in 2.7.

**Comment by n-wach** [comment]
In python 2, division with `/` uses integer division.  Because MB is so large, I'd guess `update` is being called with `0`.

If you're specifying `unit_division` that means you want TQDM to handle dividing to display in the correct units--you shouldn't be dividing `total` or `update` values by `MB`.

**Comment by casperdcl** [comment]
oh lol yes ofc. Simply replace `MB` with `float(MB)` in the original example...
