### ISSUE TITLE
After using try/except method, progress bar can not be refreshed in one line.

### ISSUE THREAD

**Issue by shmilydy** [tqdm/tqdm#809]
**This is my code :

 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
![图片](https://user-images.githubusercontent.com/52773927/64700490-8ff99100-d4d9-11e9-9214-8c040945f579.png)

>>>>>>>>>>>>>>>
the problem reappears

**Comment by casperdcl** [comment]
swap the lines `try:` and `with tqdm(...) as t`.

Otherwise you're accessing a nonexistent variable

**Comment by shmilydy** [comment]
You mean this?
![图片](https://user-images.githubusercontent.com/52773927/64750711-64fc5500-d54c-11e9-939e-24d1832a05a0.png)
but it also not work

**Comment by shmilydy** [comment]
![图片](https://user-images.githubusercontent.com/52773927/64751358-747c9d80-d54e-11e9-9218-32a8290e4217.png)
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
above is my result.
