### ISSUE TITLE
LICENSE for v4.28.1

### ISSUE THREAD

**Issue by Silviu-Caprar** [tqdm/tqdm#819]
Hi there,

 The information found inside LICENSE is confusing: 

`tqdm` is a product of collaborative work.
Unless otherwise stated, all authors (see commit logs) retain copyright
for their respective work, and release the work under the MIT licence
(text below).

Exceptions or notable authors are listed below
in reverse chronological order:

* files: *
  MPLv2.0 2015-2018 (c) Casper da Costa-Luis
  [casperdcl](https://github.com/casperdcl).
* files: tqdm/_tqdm.py
  MIT 2016 (c) [PR #96] on behalf of Google Inc.
* files: tqdm/_tqdm.py setup.py README.rst MANIFEST.in .gitignore
  MIT 2013 (c) Noam Yorav-Raphael, original author.

First of all it says that this work is released under MIT License then as an exception all files are put under MPLv2.0 by Caspter da Costa-Luis. 
Can you please specify which license aplies on this package ? Are all files licensed under MPL except tqdm/_tqdm.py setup.py README.rst MANIFEST.in .gitignore (MIT Licensed) or all files are under MIT Licensed as specified in the first paragraph ?

Thank you,

**Comment by casperdcl** [comment]
ah effectively it's all MPLv2.0; though happy to discuss if you'd like other terms. The whole issue was kicked off by the really scary comment in #96 but as of now there are only 2 surviving lines of code from that PR, both of which as minor, so no corporation can assert ownership of `tqdm`.

There's a post scriptum at https://github.com/tqdm/tqdm/wiki/History which offers some helpful links and amusing commentary if you're interested.

**Comment by Silviu-Caprar** [comment]
Thanks you for the clarification. No further questions. :)

**Comment by casperdcl** [comment]
feel free to reopen if any other concerns
