### ISSUE TITLE
wget example assumes None instead of -1 as unknown value

### ISSUE THREAD

**Issue by frafra** [tqdm/tqdm#826]
https://github.com/tqdm/tqdm/blob/91494ccf363e5eeb4745db7dbab70ef73c4a6eb0/examples/tqdm_wget.py#L44

> If reporthook is given, it must be a function accepting three numeric parameters: A chunk number, the maximum size chunks are read in and the total size of the download (-1 if unknown)
-- https://docs.python.org/3.8/library/urllib.request.html#urllib.request.URLopener.retrieve

**Comment by casperdcl** [comment]
though we should probably just move to `requests` rather than `urllib`...
