### ISSUE TITLE
What's the best way to use tqdm for different worker threads on different lines?

### ISSUE THREAD

**Issue by chenshuiluke** [tqdm/tqdm#83]
The threads aren't nested, so I'm wondering if there's a good way to have tqdm display each thread's progress on a different line in order to produce a reasonable-looking output.

**Comment by lrq3000** [comment]
This is not possible currently. I think this would need a central dispatcher-like object to centralize the management of multiple tqdm bars. Unless someone has a more elegant and decentralized solution.

**Comment by chenshuiluke** [comment]
Alright, thanks for taking the time to answer :)

**Comment by lrq3000** [comment]
I'll see what I can do later (there are lots of PRs and opened issues suddenly!).

**Comment by casperdcl** [comment]
I think the holidays (I.e. free coders idly browsing) plus mention in blogs, my recent stackoverflow post (regarding tqdm supporting pandas), the bpython graphic on the landing page, the fact that tqdm is currently trending on github and the star rate of about 1 per minute means we're going to get a lot more feedback, @lrq3000 ...

**Comment by lrq3000** [comment]
@casperdcl lol thank's for the explanation, I was wondering about this sudden increase of feedbacks XD

**Comment by chenshuiluke** [comment]
@lrq3000 Also, there was a recent HackerNews post featuring a guy's favourite Python modules of 2015. I believe this was on the top of the list :)
