### ISSUE TITLE
Description placement

### ISSUE THREAD

**Issue by JonhSilver** [tqdm/tqdm#830]
How to make descriptions (desc) appear on back not on bottom of line?
How to start line not on left corner, but by tab.

Now -> desc ProgressBar
Need-> -TAB-ProgressBar desc
Need-> -TAB--TAB-ProgressBar desc

**Comment by casperdcl** [comment]
See the `bar_format` parameter

**Comment by casperdcl** [comment]
`bar_format='\t{percentage:3.0f}%|{bar}{r_bar} {desc}'`
