### ISSUE TITLE
custom bar_format doesn't work in Google Colab

### ISSUE THREAD

**Issue by shun-lin** [tqdm/tqdm#832]
Hi!

I am trying to develop a custom progress bar for Tensorflow Keras and I want to customize the bar format (and let the users of my custom progress bar) to be able to change the bar format to their need. Setting bar_format does not cause any problem on Ipython Notebook or on python script, but when I run it on Colab it makes the progress bar looks very weird (screenshot below), I have seen other issue with tqdm on Colab in the Issues section and I am wondering if this is also an upstream problem? Thank you so much for your time!

<img width="1619" alt="Screen Shot 2019-10-29 at 8 52 49 PM" src="https://user-images.githubusercontent.com/16867893/67827967-ea04e480-fa8e-11e9-9254-e85a58caf149.png">

As you can see above, the first tqdm progress bar has custom bar format which rendered weirdly, but when we don't add custom bar format everything looks normal. (Even the default bar_format causes trouble).

Below screencast is the bar format I want to format to.
<img width="1414" alt="Screen Shot 2019-10-29 at 3 08 09 PM" src="https://user-images.githubusercontent.com/16867893/67828155-9a72e880-fa8f-11e9-9b0a-a24b98d44109.png">

**Comment by shun-lin** [comment]
Ops nvm for some reason on Colab the tqdm version is 4.28 instead of 4.36! Will close this issue.

**Comment by casperdcl** [comment]
`!pip install -U tqdm`
