### ISSUE TITLE
tqdm renders poorly in jupyterlab dark mode

### ISSUE THREAD

**Issue by owen-synergy** [tqdm/tqdm#842]
I'm having a visual output issue when trying to use tqdm in jupyter lab in dark mode. The font color changes to white but it still shows a near white background rendering the text illegible. See examples below.

Output from:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```
4.37.0 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 22:01:29) [MSC v.1900 64 bit (AMD64)] win32

Screenshot of jupyterlab tqdm widget in light mode:

![jupyterlab_light](https://user-images.githubusercontent.com/50761413/68723805-afee2380-05f4-11ea-9a28-a128001b8935.png)

Screenshot of jupyterlab tqdm widget in dark mode:

![jupyterlab_dark](https://user-images.githubusercontent.com/50761413/68723806-b086ba00-05f4-11ea-9db5-8e862bc5dc4d.png)

I was importing tqdm as:

from tqdm.auto import tqdm

**Comment by casperdcl** [comment]
`ipywidgets.IntProgress` is used for the display - sounds like it's an upstream issue for them to support dark mode?

**Comment by owen-synergy** [comment]
Oh, should I re-raise this ticket on the ipywidgets github?

**Comment by casperdcl** [comment]
Think so... not sure how you're enabling "dark mode" but it seems like something which the renderer should manage rather than `tqdm` (for example the successful font colour change has nothing to do with `tqdm`)

**Comment by owen-synergy** [comment]
Cheers, I assume https://github.com/jupyter-widgets/ipywidgets is the right place to raise this then.

**Comment by owen-synergy** [comment]
The ipywidgets IntProgress bar does seem to handle dark mode fine. See the answer on the linked issue. So is this really a tqdm or an ipywidget issue? I enable dark mode through the jupyter lab Settings Menu as shown in the screenshot below.

![dark_mode](https://user-images.githubusercontent.com/50761413/68819339-b8149480-06c2-11ea-8be8-742768e881ea.png)

**Comment by casperdcl** [comment]
Does this have anything to do with whether you enable dark mode before or after the imports?

**Comment by casperdcl** [comment]
We also put the `IntProgress` object into an `HBox` - maybe that's the problem?

**Comment by owen-synergy** [comment]
It seems to behave the same whether I enable dark mode before or after importing tqdm (I normally leave it in dark mode all the time). I don't know if the issue is in a wrapping widget. Can you reproduce the problem?

**Comment by casperdcl** [comment]
Can't reproduce...

**Comment by casperdcl** [comment]
Can't reproduce...

![20191114_123056](https://user-images.githubusercontent.com/10780059/68857921-d1760a80-06db-11ea-955b-748aaad576ef.jpg)

**Comment by owen-synergy** [comment]
Okay, weird. I'll try to find some time to see if I can reproduce it in a clean environment and check a different OS too.

**Comment by owen-synergy** [comment]
I made a new environment and can no longer reproduce this either.

I had quite a lot of other jupyter labextensions and widgets installed in my original environment - not sure if any of them could've interfered. Sorry for the waste of time - I think this issue can be closed.

**Comment by owen-synergy** [comment]
Good to know - thanks @casperdcl I'll know to try on a new environment before raising any issues in future.

**Comment by ValeryP** [comment]
Using

```
from tqdm.auto import tqdm, trange
```
![image](https://user-images.githubusercontent.com/3534020/81059214-52b29b00-8ed0-11ea-8151-92bf3ac65f2c.png)

instead of 

```
from tqdm import tqdm, trange
```

![image](https://user-images.githubusercontent.com/3534020/81059279-737af080-8ed0-11ea-8959-5d3fc82a29f6.png)

makes a difference for me 🙂

**Comment by michaelitvin** [comment]
The issue reproduces on my environment:

```(venv36)$ node -v
v13.14.0
(venv36)$ pip3 freeze | grep -E 'jupyter|ipy'
ipykernel==5.1.4
ipython==7.8.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jupyter==1.0.0
jupyter-client==6.0.0
jupyter-console==6.1.0
jupyter-core==4.6.3
jupyterlab==2.0.1
jupyterlab-server==1.0.7
```

![image](https://user-images.githubusercontent.com/5813969/82452329-c8655c00-9ab7-11ea-877c-9f3692ede5de.png)

**Comment by casperdcl** [comment]
@michaelitvin is that in a clean env from scratch?

**Comment by michaelitvin** [comment]
My venv was created a couple of weeks ago from scratch.
I could try and create a new one now, but even if it doesn't repro in the other env - it looks like this bug does indeed exist...

**Comment by casperdcl** [comment]
indeed; there definitely looks like some sort of bug - my point is if you can reproduce it from scratch that would be a start for maintainers to be able to debug/fix it. Though when I say "maintainers" I really mean upstream (ipywidgets/jupyterlab) people - this doesn't look like something which can be fixed here since `tqdm` just uses a couple of simple widget API calls.

**Comment by michaelitvin** [comment]
It doesn't repro in a clean environment:(
Anything I could do to help find the cause?

**Comment by flutefreak7** [comment]
This issue is definitely frustrating me at the moment. I'm wondering if instead of going nuclear on the environment I could just clean up a labextensions folder somewhere? Could Jupyter be seeing old css files in a different folder somewhere (Maybe at some point I installed an extension to the "wrong" place when choosing user/sys-prefix/system/etc)?

I feel like I should be able to drill down in developer tools in Chrome and locate the source of where widgets are getting their white background from, but I'm not savvy enough to understand all the css and js stuff I'm seeing. I see the dark mode css file in there, but obviously something else is causing the widgets to break inheritance or something.

Any other thoughts on workarounds or investigation paths besides clean environment?

**Comment by scaomath** [comment]
![](https://i.imgur.com/wadWMoX.png)

I have the same issue. This is on Kaggle kernel editor web interface with dark mode on. The font color is too dark and there is little contrast.  However on my local machine there is no such problem...

**Comment by casperdcl** [comment]
if you can reproduce this in a clean env I'm sure they'd be happy to re-open https://github.com/jupyter-widgets/ipywidgets/issues/2610

**Comment by mkolodny** [comment]
I was having this issue in Colab, and running the following code in a cell solved it for me:

```
# Set the tqdm text color to white.

from IPython.display import HTML, display

def set_css_in_cell_output():
    display(HTML('''
        <style>
            .jupyter-widgets {color: #d5d5d5 !important;}
            .widget-label {color: #d5d5d5 !important;}
        </style>
    '''))

get_ipython().events.register('pre_run_cell', set_css_in_cell_output)
```

(Inspired by [this](https://stackoverflow.com/a/60159121/1658458) StackOverflow answer)
