### ISSUE TITLE
Separate colors for complete and in progress bars

### ISSUE THREAD

**Issue by sergeysprogis** [tqdm/tqdm#846]
Is it possible to see have different colors for completed bars and bars in progress if I use PyCharm  (e.g. green for completed and red for in progress)? Right now all I see is red for everything. Below is an example of how I currently do it in PyCharm.

```
from tqdm import tqdm
from time import sleep

for _ in tqdm(range(0, 5), desc="Bar 1"):
    sleep(0.5)

for _ in tqdm(range(0, 5), desc="Bar 2"):
    sleep(1)
```

**Comment by songyuc** [comment]
Hi, @casperdcl , I saw the text color of `tqdm` is red in PyCharm.
So, can I set it into default color as the normal terminal output?

**Comment by casperdcl** [comment]
PyCharm always colours `stderr` red. There are hacks around this: https://stackoverflow.com/questions/20333674/pycharm-logging-output-colours

For example, `tqdm(..., file=sys.stdout)`.

**Comment by songyuc** [comment]
@casperdcl , thanks sincerely for you help!

**Comment by casperdcl** [comment]
related (coming soon): #1040, haven't tested in PyCharm though.
