### ISSUE TITLE
jupyterlab start new lines while setting the param leave=False

### ISSUE THREAD

**Issue by dear-catchlove** [tqdm/tqdm#848]
I use tqdm.notebook.tqdm in two loops. When I set the param leave=True in the seconde loop, it always start a new line as it run over the loop.

**Comment by dear-catchlove** [comment]
Here I paste my code:

`from tqdm import notebook
import time

for i in notebook.tqdm(range(10)):
    for j in notebook.tqdm(range(10), leave=False, desc='Second Loop',position=-1,):
        time.sleep(0.05)`

**Comment by e-dorigatti** [comment]
This is an issue with ipywidgets. I opened [an issue there](https://github.com/jupyter-widgets/ipywidgets/issues/2880)

**Comment by casperdcl** [comment]
duplicate of #433
