### ISSUE TITLE
Support imprecise `n > total` with `float` updates

### ISSUE THREAD

**Issue by QEDan** [tqdm/tqdm#849]
- [X] I have marked all applicable categories:
    + [X] exception-raising bug
    + [ ] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [X] I have visited the [source website], and in particular
  read the [known issues]
- [X] I have searched through the [issue tracker] for duplicates
- [X] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=
  [StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

The following code crashes because `total` is set to `None` in `tqdm.format_meter()` during the last iteration. When `bar_format.format()` is called, the `format_dict` has `total=None`, preventing the string from being formatted.

```python
from tqdm import tqdm

bar_format = "{l_bar}{bar}| {n:.02f}/{total:.02f}"
total = 1.0
n_chunks = 9
chunk_size = total / n_chunks
with tqdm(total=total,
          desc='Progress',
          smoothing=0.01,
          bar_format=bar_format) as pbar:
    for chunk in range(n_chunks):
	pbar.update(chunk_size)
    pbar.close()
```

The error produced is this:
```
Progress:   0% 0/1.0 [00:00<?, ?it/s]Traceback (most recent call last):
  File "tqdm_test.py", line 13, in <module>
    pbar.close()
  File "/home/dan/software/anaconda3/envs/ame/lib/python3.7/site-packages/tqdm/std.py", line 1254, in close
    self.display(pos=0)
  File "/home/dan/software/anaconda3/envs/ame/lib/python3.7/site-packages/tqdm/std.py", line 1421, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "/home/dan/software/anaconda3/envs/ame/lib/python3.7/site-packages/tqdm/std.py", line 1052, in __repr__
    return self.format_meter(**self.format_dict)
  File "/home/dan/software/anaconda3/envs/ame/lib/python3.7/site-packages/tqdm/std.py", line 489, in format_meter
    nobar = bar_format.format(bar=full_bar, **format_dict)
TypeError: unsupported format string passed to NoneType.__format__
```
The error does not occur in the above code when `n_chunks=10` or when `total` is not included in `bar_format`.

I tested with the following system details:
```
>>> print(tqdm.__version__, sys.version, sys.platform)
4.38.0 3.7.5 (default, Oct 25 2019, 15:51:11)
[GCC 7.3.0] linux
```

Thanks for all of your efforts!

**Comment by casperdcl** [comment]
ah this is related to #802 - because of imprecise floating point arithmetic,

```python
sum(1.0 / 9 for chunk in range(9)) != 1.0
```

If you're going to be doing imprecise floating point arithemetic then I'd recommend at least `pbar.n = pbar.total` before you close the bar.

```python
from tqdm import tqdm

bar_format = "{l_bar}{bar}| {n:.02f}/{total:.02f}"
total = 1.0
n_chunks = 9
chunk_size = total / n_chunks
with tqdm(total=total,
          desc='Progress',
          smoothing=0.01,
          bar_format=bar_format,
) as pbar:
    for chunk in range(n_chunks):
        pbar.update(chunk_size)
    pbar.n = pbar.total
```

Better still use integers and `unit_scale`:

```python
from tqdm import tqdm, trange

bar_format = "{l_bar}{bar}| {n:.02f}/{total:.02f}"
total = 1.0
n_chunks = 9
chunk_size = total / n_chunks
for chunk in trange(
    n_chunks,
    unit_scale=chunk_size,
    desc='Progress',
    smoothing=0.01,
    bar_format=bar_format
):
    pass
```
