### ISSUE TITLE
Support skins

### ISSUE THREAD

**Issue by KOLANICH** [tqdm/tqdm#856]
- [x] I have marked all applicable categories:
    + [x] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates

https://github.com/verigak/progress/blob/master/progress/bar.py has skins. I guess we should add them to tqdm too.

**Comment by casperdcl** [comment]
the `ascii` arg supports this already - e.g. `ascii='⡀⡄⡆⡇⣇⣧⣷⣿'`

**Comment by casperdcl** [comment]
Might need to update our gif to show all the additional features sich as this one
