### ISSUE TITLE
bash completion

### ISSUE THREAD

**Issue by casperdcl** [tqdm/tqdm#858]
There are a lot of options under

```bash
tqdm --help
```

Would be nice to have bash (and even zsh) completion.

**Comment by nishnash54** [comment]
I plan to work on the bash completion script.
Is there anything specific you have in mind? @casperdcl 
Or just a basic auto complete feature with all the CLI options?

**Comment by casperdcl** [comment]
Thanks! The only requirement I'd have is that it's automatically generated somehow (e.g. the current `README.rst` is updated automatically if docstrings in e.g. `std.py` are touched).

**Comment by casperdcl** [comment]
Was about to write more here but wound up creating a branch instead which you can work on: [tqdm/tqdm@completion](https://github.com/tqdm/tqdm/tree/completion)

In particular feel free to PR on that branch (I won't work on it; the only real file to modify would be [`.meta/mkcompletion.py`](https://github.com/tqdm/tqdm/blob/completion/.meta/mkcompletion.py))

**Comment by nishnash54** [comment]
I have create the base functionality for bash autocomplete.
I've accepted the invite, but for some reason do not have access to push changes to the `completion` branch.

**Comment by casperdcl** [comment]
ah srry; doesn't look like github allows me to grant access for a branch. Would be weird to grant access for the whole org and then try to remove permissions for various things. So...

Please create a PR into the `completion` branch. If you've forked the repo and pushed to your own fork, the link would be https://github.com/tqdm/tqdm/compare/completion...nishnash54:completion
