### ISSUE TITLE
View tqdm output file

### ISSUE THREAD

**Issue by c-j-lh** [tqdm/tqdm#865]
How can one conveniently easily view `tqdm` output that has been redirected to a file, preferably with built-in commands on linux like `less` or `vim`?

Here is an example:
tqdm_test.py
```
from tqdm import trange
for i in trange(10):
    pass
```
After running `python3 tqdm_test.py 2> tqdm_test.txt` on bash, I get this visual output when running `less tqdm_test.txt`
![visual output](https://i.imgur.com/rOKHu4c.png)

- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
    + [x] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```
  ```
  4.35.0 3.5.2 (default, Nov 12 2018, 13:43:14)
  [GCC 5.4.0 20160609] linux
  ```

``` [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=
  [StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

**Comment by casperdcl** [comment]
ah this is a duplicate - please see #506
