### ISSUE TITLE
Empty progress bar with np.arange()

### ISSUE THREAD

**Issue by clematologie** [tqdm/tqdm#868]
Hello, 

I'm using the tqdm library for a standard progression bar on a np.arange.
However, before the normal progress bar I get an empty progress bar the shows and I found no way to see where it is from.

The code has this general shape:
```python
def function_1 (parameter_A):
    list = numpy.arrange(0,20)
    for a_value in tqdm.tqdm(list):
        #do_something_with_parameter_A

def function_2(Parameter_A):
    for k in range(30):
        print('Tree', k, '/30')
        function_1 (parameter_A)
```

Is there something that should be done with the array?
Thank you! 

![image](https://user-images.githubusercontent.com/59105119/71302052-d9793800-2374-11ea-960c-04f35ce7cd5b.png)

**Comment by casperdcl** [comment]
You should use `tqdm.write(str())` instead of `print()`

**Comment by clematologie** [comment]
Thank you for your answer but I have tried that before and it didn't work.
But by further investigating the issue, I've definitely narrowed it down to that string. I was wrong by supposing that the issue came from the bumpy array.

```python
def function_1 (parameter_A):
    list = numpy.arrange(0,20)
    for a_value in tqdm.tqdm(list):
        #do_something_with_parameter_A

def function_2 (Parameter_A):
    for k in range(30):
        tqdm.tqdm.write(str('Tree', k, '/30'))
        function_1 (parameter_A)
```

![image](https://user-images.githubusercontent.com/59105119/71325051-2f54f980-24b5-11ea-848a-b3a8df2c07fb.png)

**Comment by casperdcl** [comment]
Ah `k` is mutil-line `str`... that's currently not supported neatly by `write`.

**Comment by clematologie** [comment]
Ok thanks!

**Comment by casperdcl** [comment]
duplicate of #737

**Comment by casperdcl** [comment]
Actually no, the screenshot doesn't look like you ran the code. Will have to investigate more.

**Comment by clematologie** [comment]
I omitted, for simplicity, the full print.
The other part of the came from: sklearn.metrics.confusion_matrix()

**Comment by casperdcl** [comment]
ok so #737 indeed
