### ISSUE TITLE
Bug: TqdmCallback does not work with fit_generator

### ISSUE THREAD

**Issue by CorwinTanner** [tqdm/tqdm#869]
## Problem
`fit_generator()` passes `batch_size=None` in `params` resulting in an exception:

```
~/.pyenv/versions/3.7.5/envs/ratings/lib/python3.7/site-packages/tqdm/keras.py in on_epoch_begin(self, *_, **__)
     69                 self.batch_bar = self.tqdm_class(
     70                     total=total, unit='batch', leave=True,
---> 71                     unit_scale=1.0 / params('batch_size', 1))
     72                 self.on_batch_end = self.bar2callback(
     73                     self.batch_bar,

TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'
```

### Categories
 + [x] exception-raising bug

### Version
```
4.41.0 3.7.5 (default, Dec  4 2019, 14:49:32) 
[GCC 7.3.1 20180712 (Red Hat 7.3.1-6)] linux
```
## Example
```python
model.fit_generator(
    sequence,
    epochs=5,
    callbacks=[
        TqdmCallback(verbose=2),
    ]
);
```

**Comment by CorwinTanner** [comment]
I just realized that you don't need a `TqdmCallback` with `fit_generator()` as the default verbosity is effectively the same. I had `verbosity=2` from when I was using `fit()`. At least this may be useful to someone facing a similar oversight in the future.

**Comment by casperdcl** [comment]
@CorwinTanner sounds like you found a work-around but that this is still something which needs to be fixed.
