### ISSUE TITLE
How to add callback function to __iter__ method

### ISSUE THREAD

**Issue by km23630** [tqdm/tqdm#871]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] visual output bug
    + [x] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [ ] I have searched through the [issue tracker] for duplicates
- [ ] I have mentioned version numbers, operating system and
  environment, where applicable:
  
I want to add custom data to the DB every 10 iterations.
can this problem be handled with the exception of method overriding?

Method overriding makes my code too messy and complicated.

**Comment by casperdcl** [comment]
not sure what you mean, but:

```python
from tqdm import tqdm

for i, obj in enumerate(tqdm(some_iterator)):
    some_process(obj)
    if i % 10 == 0:
        DB.add(data)
```

**Comment by casperdcl** [comment]
will re-open if something else is intended/required
