### ISSUE TITLE
more succinct traceback for missing ipywidgets ('IProgress' Name Error)

### ISSUE THREAD

**Issue by OlavRab** [tqdm/tqdm#872]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [X] I have visited the [source website], and in particular
  read the [known issues]
- [X] I have searched through the [issue tracker] for duplicates
- [X] I have mentioned version numbers, operating system and
  environment, where applicable:

When I try to import an MNIST dataset from Tensorflow_datasets, the import failes due to a Name Error in the tqdm StatusPrinter. To import, I used the following code
  ```python
     mnist_dataset, mnist_info = tfds.load(name='mnist', with_info=True, as_supervised=True)
  ```
and got the following error message:

```python
NameError Traceback (most recent call last)
~\Anaconda3\envs\py3_TF2.0\lib\site-packages\tqdm\notebook.py in status_printer(_, total, desc, ncols)
     95         try:
---> 96             if total:
     97                 pbar = IProgress(min=0, max=total)

NameError: name 'IProgress' is not defined
```

Using the Following:

Windows 10 64-bit
Python 3.7
Tensorflow 2.0.0
tqdm 4.40.2

Might be a mistake by me, I'm a starter, but thanks for your help
  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=
  [StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

**Comment by casperdcl** [comment]
Looks like you're using a notebook and missing `ipywodgets`?

**Comment by sFrenkie** [comment]
I had the same issue and it helps install `ipywidgets` - `pip install ipywidgets` and restart notebook and everything is ok :+1:

**Comment by findQin** [comment]
https://ipywidgets.readthedocs.io/en/stable/user_install.html

**Comment by casperdcl** [comment]
Closing as it seems resolved

**Comment by xrobin** [comment]
I'm getting the same error here after doing a `pip install notebook`.
If ipywidgets is required, shouldn't it be automatically installed with tqdm?

**Comment by casperdcl** [comment]
It can't be automatically installed as we can't assume people are using notebooks (`tqdm` works just as well on the CLI)

**Comment by casperdcl** [comment]
There's a case for jupyter itself to start installing ipywidgets as a dependency though...

**Comment by xrobin** [comment]
Then maybe at least it would be nice to have a clearer error message indicating the need to install ipywidgets?
At the moment one has to google the error message and browse through various github issues to find the solution...

**Comment by casperdcl** [comment]
hmm it's there but I agree somewhat buried:

```python
Traceback (most recent call last):
  File "tqdm/tqdm/notebook.py", line 98, in status_printer
    pbar = IProgress(min=0, max=1)
NameError: name 'IProgress' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tqdm/tqdm/notebook.py", line 209, in __init__
    self.fp, total, self.desc, self.ncols)
  File "tqdm/tqdm/notebook.py", line 104, in status_printer
    "FloatProgress not found. Please update jupyter and ipywidgets."
ImportError: FloatProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
Exception ignored in: <bound method tqdm.__del__ of |<bar/>| 0/? [00:10<?, ?it/s]>
Traceback (most recent call last):
  File "tqdm/tqdm/std.py", line 1086, in __del__
    self.close()
  File "tqdm/tqdm/notebook.py", line 248, in close
    self.sp(bar_style='success')
AttributeError: 'tqdm_notebook' object has no attribute 'sp'
```

Where the relevant lines are only:

```python
  File "tqdm/tqdm/notebook.py", line 104, in status_printer
    "FloatProgress not found. Please update jupyter and ipywidgets."
ImportError: FloatProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
```

**Comment by xrobin** [comment]
Right!  In my case it was buried deep down a much longer traceback so I didn't see it but it's there indeed.

**Comment by casperdcl** [comment]
related #821
