### ISSUE TITLE
Using multiple tqdm bars

### ISSUE THREAD

**Issue by DEADSEC-SECURITY** [tqdm/tqdm#876]
So I'm making a script to scrape data and I need 2 tqdm bars but when I run the script after the first loop the first bar disappears and starts making multiple seconds bars.

Here is a simple recreation of the code I have: (This is not the complete code only a simplified example)
```
from tqdm import tqdm
import time

def test():
    for x in tqdm(range(500), desc='2', position=1):
        time.sleep(0.01)

for x in tqdm(range(500), desc='1', position=0):
    for y in range(500):
        test()
        time.sleep(0.1)
```

**Comment by Evidlo** [comment]
I'm getting this too with the [nested bar example](https://github.com/tqdm/tqdm/issues/876)

```
[evan@blackbox tmp] python /tmp/test.py 
2nd loop: 100%|███████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.94it/s]
2nd loop: 100%|███████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.93it/s]
2nd loop: 100%|███████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.94it/s]
2nd loop: 100%|███████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.94it/s]
1st loop: 100%|███████████████████████████████████████████████████| 4/4 [00:10<00:00,  2.59s/it]
```

Something changed between version 4.28.1 and 4.41.1 that makes this happen.

**Comment by casperdcl** [comment]
This is due to a `leave` logic fix in `v4.34.0` (see https://tqdm.github.io/releases/).

If you want you can

- add `leave=False` to the nested (position>0) bars
- inherit from `tqdm`
  + change the default to `leave=False`
  + change the default to `leave=positon==0`

**Comment by Evidlo** [comment]
@casperdcl The README probably needs an update for the nested example.

**Comment by Evidlo** [comment]
I'm seeing a related issue when I instantiate a tqdm bar and call `update(1)` on it manually:

``` python
from tqdm import tqdm
from time import sleep

for a in tqdm(range(10), desc='foo'):

    for b in tqdm(range(10), desc='bar', leave=False):
        sleep(.1)

    bar = tqdm(total=10, desc='baz', leave=False)
    for c in range(10):
        bar.update(1)
        sleep(.1)
```

However, the equivalent code with `tqdm` wrapping `range` works fine:

``` python
from tqdm import tqdm
from time import sleep

for a in tqdm(range(10), desc='foo', leave=None):

    for b in tqdm(range(10), desc='bar', leave=None):
        sleep(.1)

    for b in tqdm(range(10), desc='baz', leave=None):
        sleep(.1)
```

**Comment by Evidlo** [comment]
``` python
for a in tqdm(range(10), leave=None):

    bar1 = tqdm(total=10, leave=None)
    bar2 = tqdm(range(10), leave=None)

```

For some reason the computed position of `bar1` is 0 while the computed position of `bar2` is 1.

**Comment by casperdcl** [comment]
@Evidlo you need `bar.close()` or (better) use the `with tqdm(...) as bar:` syntax
