### ISSUE TITLE
Update progress bar after exiting loop

### ISSUE THREAD

**Issue by ludwigwinkler** [tqdm/tqdm#878]
Hi,

thank you for the amazing tool!

I was wondering whether the following is currently possible:

```python
progress = tqdm([ 1, 2, 3, 4, 5, 6])
data = []
	for number in progress:
		number_plus_one = number + 1
		data.append(number_plus_one)
		progress.set_description(f'Number: {number}')

mean = sum(data)/len(data)
progress.set_description(f'Number: {number} Mean: {mean}') # <-- Update progress bar after exiting the loop
```
So can one somehow update the progress bar one last time after exiting the loop?
I played around with `leave=False` and `progress.close()` but it didn't help.

Thanks a lot in advance!

**Comment by casperdcl** [comment]
Appending `progress.refresh()` to the code above should work

**Comment by ludwigwinkler** [comment]
It works very nicely. Thank you for your time and answer!
