### ISSUE TITLE
Verify/fix spelling of the Arabic translation of progress

### ISSUE THREAD

**Issue by impredicative** [tqdm/tqdm#895]
The PyPI page for this project states that the Arabic word for progress is taqad**u**m. This seems to not be true according to Google Translate. The spelling there is [taqad**a**m](https://translate.google.com/#view=home&op=translate&sl=en&tl=ar&text=progress). Please fix the apparent misspelling in the readme. Thunk you.

**Comment by casperdcl** [comment]
I'd prefer a native speaker's opinion over gtranslate... @noamraph do you have any suggestions?

**Comment by jaggzh** [comment]
I'm not a native speaker, but taqaddum is the masculine form of the verb.

See Etymology 1 and 2 here: https://en.wiktionary.org/wiki/%D8%AA%D9%82%D8%AF%D9%85

If you want just the verb "to progress" (aka "to proceed", etc.), without conjugation (ie. the infinitive), it would be "taqaddama", which is the standard infinite presentation of a verb.
Note the verb has a symbol (shadda -- the little curvy W thing) over the D دّ , which indicates emphasis, or doubling, of the D, hence the 'dd'.
I believe the English (transliteration) should be fixed there, not the Arabic.  The Arabic does not have the vowel markings, ie. there is no indication of a short-a or the u vowel, which is standard practice for Arabic speakers [to leave out the vowel markings], so I'd recommend changing the transliteration to "taqaddama" unless the masculine form is desired for some reason... and I'm 99%, or maybe 95% certain this is appropriate in that case. :)

**Comment by noamraph** [comment]
Hi,

I meant tqdm to be etymology 2, a noun, which is pronounced taqaddum (this
is how it is written in wiktionary, ta.qad.dum), and means "progress"
(meaning 6 in wiktionary).

Noam

**Comment by impredicative** [comment]
I propose rewriting the initial sentence in the readme to start as the following:

``tqdm`` is derived from the Arabic word [*taqadum* (تقدّم)](https://en.wiktionary.org/wiki/%D8%AA%D9%82%D8%AF%D9%85) which can mean "progress"

**Comment by casperdcl** [comment]
Sure, looks like we should double the `d`.

**Comment by impredicative** [comment]
> Sure, looks like we should double the `d`.

Agreed. Edited the prior comment.
