### ISSUE TITLE
Container class for tqdm progress bar

### ISSUE THREAD

**Issue by jam88881** [tqdm/tqdm#904]
I want to create a container class for tqdm progress bar that I can call in various places throughout my python solution. I am a novice at python. I know how to create a tqdm progress bar inline where I need it. Is it possible and practical to create a class such that instances of this class can be used elsewhere and the tqdm progress bar can be access through this code for various other processes?

**Comment by casperdcl** [comment]
Not sure what you mean. `tqdm` *is* a `class`.

You could subclass/inherit if you need to change defaults/add config etc.

**Comment by jam88881** [comment]
Here is my code (doesn't work)
I'm trying to write a class so that I don't have to state "from tqdm import tqdm" multiple times across multiple files that are in the solution. 

[progress_bar_ii.py.txt](https://github.com/tqdm/tqdm/files/4289807/progress_bar_ii.py.txt)

**Comment by jam88881** [comment]
Figured this out, here is the class I came up with, in case it ever helps anyone else. 
[progress_bar_ii - Copy.py.txt](https://github.com/tqdm/tqdm/files/4293435/progress_bar_ii.-.Copy.py.txt)
