### ISSUE TITLE
notebook: delay initial render to different Jupyter cell

### ISSUE THREAD

**Issue by mjkvaak** [tqdm/tqdm#909]
Thank you for the tqdm-team for including the tqdm's functionalities for keras' progress bar.

I came across the following bug: the progress bar is always updated in the Jupyter cell it was first generated in. This will be problematic in case you are gathering your keras callbacks into a list somewhere else than in the cell where `fit` / `fit_generator` is being called. I attached some pictures to illustrate the behaviour (I left the `fit_generator`'s verbose on to get a better idea on where the updates should be shown).

![image](https://user-images.githubusercontent.com/37109302/76080728-3e295380-5fb0-11ea-9ff9-2327213c5057.png)

![image](https://user-images.githubusercontent.com/37109302/76081361-9b71d480-5fb1-11ea-863d-21eaefe0b334.png)

Here's some code:

```python
import numpy as np

import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K


from keras.preprocessing.image import ImageDataGenerator
from keras.datasets import mnist
from keras.utils import to_categorical
from tqdm.keras import TqdmCallback

# params
batch_size = 128
num_classes = 10
epochs = 3
img_rows, img_cols = 28, 28

# data
(x_train, y_train), _ = mnist.load_data()
x_train = x_train[...,np.newaxis]
y_train = to_categorical(y_train, num_classes)
datagen = ImageDataGenerator().flow(x_train, y_train, batch_size=32)

# model
input_shape = (img_rows, img_cols, 1)
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

# START NEW CELL
callbacks = [TqdmCallback()] # or tqdmCallback = TqdmCallback()

# START NEW CELL
# fit the model: iterations update in a wrong cell
model.fit_generator(datagen,
                    steps_per_epoch=len(datagen),
                    epochs=epochs,
                    verbose=1,
                    callbacks=callbacks) #or callbacks=[tqdmCallback])

```

**Comment by casperdcl** [comment]
This is a jupyter design.

If you had a matplotlib figure created in one cell, updating it subsequent cells won't move it to a different cell.

If you need to delay creation:


```python
callbacks = [...]
...
model.fit(..., callbacks=callbacks + [TqdmCallback()])
```

**Comment by elvinlemmens** [comment]
This line actually causes the progress bar widget from being displayed upon creation, which is not necessary. 
https://github.com/tqdm/tqdm/blob/5e8978909c639bc20f58bf877e66cc6a0b9fb5bf/tqdm/notebook.py#L129
You could in fact delay initial render and call display on the widget later on. I don't know about the keras callback part though and how you could manually display the progress bar widget.
I see that the notebook widget is available through the epoch_bar property. 
https://github.com/tqdm/tqdm/blob/5e8978909c639bc20f58bf877e66cc6a0b9fb5bf/tqdm/keras.py#L48 
You could display at the appropriate times:

`callback=TqdmCallback(display=False)`
the `display` parameter is passed through `tdqm_class` all the way down to this method:
https://github.com/tqdm/tqdm/blob/5e8978909c639bc20f58bf877e66cc6a0b9fb5bf/tqdm/notebook.py#L82

in a later cell you could display it manually:

`display(callback.epoch_bar.container)`

Making this display optional will already solve my issue as well #954.

**Comment by casperdcl** [comment]
> Making this display optional will already solve my issue as well #954.

Yes @elvinlemmens that's what I mean by marking #954 as a duplicate; it's the same issue from an implementation standpoint and have way too many issues for a one-person unfunded "team" to track otherwise :)

**Comment by casperdcl** [comment]
@mjkvaak @elvinlemmens let me know if #1059 works for you :)
