### ISSUE TITLE
multiprocessing on py>=3.7 causes threading.RLock pickling exception

### ISSUE THREAD

**Issue by KingDarBoja** [tqdm/tqdm#920]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] visual output bug
    + [x] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

The current [parallel-bars](https://github.com/tqdm/tqdm/blob/master/examples/parallel_bars.py) example doesn't work as it is raising the following exception on the anaconda prompt terminal:

```console
Multi-processing
Traceback (most recent call last):
  File "D:\Anaconda3\envs\sample-project\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda3\envs\sample-project\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Programming\personal_projects\sample-project\sample_tdqm.py", line 38, in <module>
    p = Pool(initializer=tqdm.set_lock, initargs=(tqdm.get_lock(),))
  File "D:\Anaconda3\envs\sample-project\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "D:\Anaconda3\envs\sample-project\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "D:\Anaconda3\envs\sample-project\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "D:\Anaconda3\envs\sample-project\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda3\envs\sample-project\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda3\envs\sample-project\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda3\envs\sample-project\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects
```

However, this [one](https://github.com/tqdm/tqdm/pull/329#issuecomment-332872669) from an old comment in an old PR does work.

**Environment info**
```console
4.43.0 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 22:01:29) [MSC v.1900 64 bit (AMD64)] win32
```

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=
  [StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

**Comment by cgebbe** [comment]
Can confirm the error Windows. 

- Windows 10
- Python Virtual Environment (not anaconda)
- tqdm versions 4.42, 4.48, 4.49 using python version 3.7.0

Interesting side note: It works when I downgrade python to version before 3.7 (tested 3.6.0 and even 3.5.x I believe)

**Comment by prisae** [comment]
I can confirm this error. Code works fine on Linux, but fails on Windows with Python 3.8.

No problem when simply using `concurrent.futures.ProcessPoolExecutor`, but failing with `TypeError: cannot pickle '_thread.RLock' object` when using `tqdm.contrib.concurrent.process_map`.

**Comment by casperdcl** [comment]
Ah so looks like before running multiprocessing code you need to:

```python
from multiprocessing import RLock
tqdm.set_lock(RLock())
```

That's unfortunate. In any case `tqdm.contrib.concurrent.process_map` should do this automatically; will release a fix soon...

**Comment by prisae** [comment]
Awesome, thanks @casperdcl !

**Comment by cgebbe** [comment]
Works, thanks a ton @casperdcl

**Comment by vertexclique** [comment]
This still carries on. Hasn't been fixed. Example code:

```
                from multiprocessing import RLock
                t = tqdm.tqdm(queries)
                t.set_lock(RLock())
```


and end result:
```
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7faf058ae900>'. Reason: 'TypeError("cannot pickle '_thread.RLock' object")'
```
