### ISSUE TITLE
tqdm output view

### ISSUE THREAD

**Issue by MichaelSchroter** [tqdm/tqdm#923]
Hi mate,

I am running `tqdm` on `jupyter` notebook version 4.4.0. Python 3.53. running on Debian Linux 9.
However I am getting this output which is not the one that should be getting. Would you be able to  help me in this  regard. 

Please find the images of output and versions of tqdm attached herewith.

Thanks & Best Regards

Michael

tqdm version, sys version and sys platform:
![Screenshot_2020-03-26_13-39-14](https://user-images.githubusercontent.com/31654102/77608819-60404100-6f72-11ea-8c86-fbeca1fe68dc.png)

expected output:
![Screenshot_2020-03-26_15-02-31](https://user-images.githubusercontent.com/31654102/77609019-e9f00e80-6f72-11ea-8cd5-96caefce1e69.png)

Actual output:
![Screenshot_2020-03-26_13-39-34](https://user-images.githubusercontent.com/31654102/77608823-62a29b00-6f72-11ea-96dc-f124a4947fe7.png)

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=
  [StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

**Comment by casperdcl** [comment]
Looks like a duplicate of #394... It's probably easiest if you use `from tqdm.auto import tqdm, trange` rather than `from tqdm import tqdm, trange`

**Comment by MichaelSchroter** [comment]
Hi,
Thanks for the feed back. It still happens. 
I did: `from tqdm.auto import tqdm, trange`

Please find the attached image below. It shows 3 for loops one inside of another
eg: 
        ``` for in range(3):```
        ``` ##      for in range(3):```
        ``` ####         for in range(3):```


![Screenshot_2020-04-01_13-40-09](https://user-images.githubusercontent.com/31654102/78093637-5c069e80-741e-11ea-8f56-f0451245856e.png)

Please let me know if there is any other solutions available. 

Thanks & Best Regards

Michael

**Comment by casperdcl** [comment]
Not sure what the issue is. Seems more like a question for [StackOverflow#tqdm](https://stackoverflow.com/questions/tagged/tqdm) where you'll need to post your code and explain the difference between your expected output versus the actual output.

**Comment by MichaelSchroter** [comment]
Hi @casperdcl ,

Thanks for the reply. Here is an [answer](https://stackoverflow.com/questions/60928718/python-how-to-replace-tqdm-progress-bar-by-next-one-in-nested-loop/60983082#60983082) for the question. Please refer it on [stackoverflow](https://stackoverflow.com/questions/60928718/python-how-to-replace-tqdm-progress-bar-by-next-one-in-nested-loop/60983082#60983082).
It would be great if we could have **different color** bars though. :)

**Comment by casperdcl** [comment]
Thanks @MichaelSchroter I understand now - posted an answer at https://stackoverflow.com/a/60990327/3896283, reproduced here:

```python
from time import sleep
from tqdm.auto import tqdm

# acceptable version, but could cause unacceptable flicker for fast inner loops
for i in tqdm(range(3)):
    for j in tqdm(range(3), leave=i==2):
        sleep(1)

# alternatively, re-use inner bar
with tqdm(range(3)) as outer:
    inner_total = 3
    with tqdm(total=inner_total) as inner:
        for i in outer:
            inner.reset(inner_total)  # reinitialise without clearing
            for j in range(inner_total):
                sleep(1)
                inner.update()
            inner.refresh()  # print last state without clearing
```

potentially this could be included in the documentation/examples somewhere...
