### ISSUE TITLE
ImportError: cannot import name '_environ_cols_windows'

### ISSUE THREAD

**Issue by jklynch** [tqdm/tqdm#927]
- [ ] I have marked all applicable categories:
    + [X] exception-raising bug
    + [ ] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [X] I have visited the [source website], and in particular
  read the [known issues]
- [X] I have searched through the [issue tracker] for duplicates
- [X] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=
  [StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

It appears the 4.44.0 release removed `tqdm.utils._environ_cols_windows`, but `tqdm._utils` still imports it.

tqdm version 4.44.0:
```
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tqdm, sys
>>> print(tqdm.__version__, sys.version, sys.platform)
4.44.0 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] linux
>>> import tqdm._utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jlynch/local/suitcase-tiff/venv/lib/python3.6/site-packages/tqdm/_utils.py", line 1, in <module>
    from .utils import CUR_OS, IS_WIN, IS_NIX, RE_ANSI, _range, _unich, _unicode, colorama, WeakSet, _basestring, _OrderedDict, FormatReplace, Comparable, SimpleTextIOWrapper, _is_utf, _supports_unicode, _is_ascii, _environ_cols_wrapper, _environ_cols_windows, _environ_cols_tput, _environ_cols_linux, _term_move_up  # NOQA
ImportError: cannot import name '_environ_cols_windows'
```

tqdm version 4.43.0:
```
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tqdm, sys
>>> print(tqdm.__version__, sys.version, sys.platform)
4.43.0 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] linux
>>> import tqdm._utils
>>> 
```

**Comment by casperdcl** [comment]
Thanks - this should be a `DeprecationWarning` rather than `ImportError`. Will be fixed by https://github.com/tqdm/tqdm/commit/0229cc67d051019bfe06e76f3655758385c594de soon

**Comment by casperdcl** [comment]
btw in 4.43.0 You should've had:


```
Python 3.7.6 | packaged by conda-forge | (default, Mar  4 2020, 17:06:33)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tqdm._utils
__main__:1: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.utils.*` instead of `tqdm._utils.*`
```
