### ISSUE TITLE
specify iter/s or s/iter

### ISSUE THREAD

**Issue by AljoSt** [tqdm/tqdm#931]
Not quite sure what to search for, so apologies if this feature (or an issue for it) already exists.

When `it/s` drops below 1, the reciprocal is taken and it becomes `s/it`. I find this confusing as at first large numbers mean "fast" and then large numbers mean "slow" (It is especially annoying for cases when you have something around 1 it/s and it switches around occasionally) I can see that using `1000 s/it` is easier to understand than `0.001 it/s`, but tbh I think consistency in terms of which units are used is more important.  
So it would be good to at least have this as an option, if not to make it the default.

Great library btw!

**Comment by casperdcl** [comment]
Use `bar_format`:

```python
bar_format="{l_bar}{bar}| {n_fmt}/{total_fmt} [{elapsed}<{remaining}, ' '{rate_noinv_fmt}{postfix}]"
```

**Comment by AljoSt** [comment]
Ah okay, thanks for the quick reply!
