### ISSUE TITLE
Set the block size to be the same in terminal

### ISSUE THREAD

**Issue by domsupamoe** [tqdm/tqdm#933]
Hi, I have searched through the documentations for configuring the progress bar, but maybe I am not using the correct keywords. Currently in the terminal, the progress bar displays as follow:
<pre>
6%|█▍                      | 24.9M/423M [00:09<02:26, 2.85MB/s]
</pre>
However, I do not really like the block size is showing differently. Is there any way to display the block size always the same when it is progressing? Maybe like the one below:
<pre>
6%|██                      | 24.9M/423M [00:09<02:26, 2.85MB/s]
</pre>

**Comment by casperdcl** [comment]
I think you mean `tqdm(..., ascii=" █")`

**Comment by domsupamoe** [comment]
Ahh yes, that is what I am looking for. Thank you!
