### ISSUE TITLE
Nested progressbars create newlines in Jupyterlab

### ISSUE THREAD

**Issue by tcwalther** [tqdm/tqdm#935]
When nesting progress bars in Jupyter lab where the second progress bar has `leave=False`, the second progress bar isn't fully deleted, and an empty div remains. This results in vertical space being added over time.

<img width="576" alt="Screenshot 2020-04-07 at 13 38 24" src="https://user-images.githubusercontent.com/2840901/78665744-91a3ff80-78d6-11ea-8fe1-8f3d63f1be07.png">

Here is a screenshot of the corresponding HTML. The first div in the list is the parent progress bar; the next five divs are empty leftovers for the sub-progress bar. The final div is for the `---` line I printed to illustrate the vertical space.

<img width="341" alt="Screenshot 2020-04-07 at 13 50 02" src="https://user-images.githubusercontent.com/2840901/78665869-c4e68e80-78d6-11ea-889c-b5807cdd5ea7.png">

I could reproduce this bug both in Jupyter 1.2.6 and 2.1.0. In both cases I had the current ipywidgets 7.5.1 installed. This bug is with both tqdm 4.43.0 and 4.45.0.

---

- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  >>>  import tqdm, sys
  >>>  print(tqdm.__version__, sys.version, sys.platform)
  4.45.0 3.7.3 (default, Mar 27 2019, 22:11:17)
  [GCC 7.3.0] linux
  ```

**Comment by tcwalther** [comment]
Aaaand it turns out just after filing this issue I finally found the corresponding duplicate: #433.

I hope that the text in this issue will at least help other users in their google search :).

**Comment by casperdcl** [comment]
Yes, the gist from #433 is there may be some work-arounds but ultimately this is upstream https://github.com/jupyterlab/jupyterlab/issue/7354
