### ISSUE TITLE
.update() not updating partially or at all

### ISSUE THREAD

**Issue by Mz49** [tqdm/tqdm#939]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=
  [StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

My system info is as follows:
4.45.0 3.8.1 (default, Dec 27 2019, 18:05:50)
[Clang 10.0.0 (clang-1000.11.45.5)] darwin

I'm working on a script to upload large files to Google Drive through their API and wanted to use tqdm to show progress. I came across a few issues and am not sure what the reason behind the issues are. [This is a Gist](https://gist.github.com/Mz49/e07342bc2a82760826f9272a2729974b) attempting to isolate the issue to a script. Dummy files can be found [here](https://speed.hetzner.de). 

My first issue was that the progress bar does not update at all after calling `.update()` (). Whether I'm overlooking something, I'm not sure, but my attempted solution was to call `.refresh()` after updating. This is where the "at all" part of the title is (Figure A).

After calling `.refresh()` the bar seems to update, but the info does not update exactly well. The speeds are completely wrong, but I made a comment in #490 to avoid another issue. The elapsed times and remaining time also stay at `00:00<00:00`(Figure B). I looked at #861 and #320 but it did not feel like the same issue I was having.

Figure A

    Uploading 100MB.bin:   0%|                                          | 0.00/105M [00:00<?, ?B/s]

Figure B

    Uploading 100MB.bin:  21%|██████████                                | 22.0M/105M [00:00<00:00, 43.8GB/s]

**Comment by casperdcl** [comment]
- `update()` does not always force a `refresh()` for speed purposes
- when downloading/uploading over unreliable connections, or in general when there could be expected variations in speeds, you could use `miniters=1`
- if you're not happy with time remaining estimates, play around with the `smoothing` parameter https://github.com/tqdm/tqdm/#parameters

**Comment by Mz49** [comment]
Ah. That actually makes a lot of sense. It seems that this what was I looking for. Sorry for the confusion.
