### ISSUE TITLE
Shorter description when console is not wide enough

### ISSUE THREAD

**Issue by rronan** [tqdm/tqdm#941]
Related to: https://github.com/tqdm/tqdm/issues/630

When my console width is too small compared to the description (e.g., set via ```tqdm.set_description()```), I often get a multiline output, adding many new lines to stdout. I would rather have a shorter description to display instead. For example:

```one very long description: ██████████| 10000/10000 [00:13<00:00, 737.46it/s]```

```short one:  █████████████████| 10000/10000 [00:13<00:00, 737.46it/s]```

It could be an optional argument to ```tqdm.__init__()```  and/or to ```tqdm.set_description()```. If you think it has an interest, I can do a PR.

**Comment by casperdcl** [comment]
Thanks for opening this; I've added some comments on #942...
