### ISSUE TITLE
If multiple tqdm are used then the next print line is on a wrong line

### ISSUE THREAD

**Issue by mikhail** [tqdm/tqdm#945]
For nested tqdms the printline after all loops are done is printed too high. My guess is that this is because the outer loop gets done last and sets the cursor position.

```python
In [4]: print('Starting...')
   ...: for _ in tqdm(range(10), desc="Outer"):
   ...:     for _ in tqdm(range(10), desc="Inner"):
   ...:         pass
   ...: print('Done! and this prints over the Inner tqdm')
Starting...
Outer: 100%|███████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 4798.97it/s]
Done! and this prints over the Inner tqdm██████████████████████████████████████| 10/10 [00:00<00:00, 285326.80it/s]

```

- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:

```
4.19.5 3.6.5 (default, Mar 11 2020, 18:30:05)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)] darwin
  ```

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=
  [StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

**Comment by mikhail** [comment]
Without a magical solution I could see there being something that needs to be called, like `tqdm.newline()`  or `tqdm.done()` to indicate that all loops have finished. The syntax would then be 

```python
for _ in tqdm(range(10), desc="Outer"):
    for _ in tqdm(range(10), desc="Inner"):
        pass
tqdm.done()
```

**Comment by casperdcl** [comment]
The current recommendation is:

```diff
  for _ in tqdm(range(10), desc="Outer"):
      for _ in tqdm(range(10), desc="Inner"):
          pass
- tqdm.done()
+ nests = 1
+ print("\n" * (nests - 1))
```

but for some reason it's not in the README yet. Should really be in the FAQ.

**Comment by mikhail** [comment]
I'm proposing a built-in method to do this because nesting can be unknown if loops span over various classes/methods/files etc. tqdm can keep track of that internally

**Comment by casperdcl** [comment]
> tqdm can keep track of that internally

How?

**Comment by mikhail** [comment]
It already has self._instances counter when it goes deeper. It will have to track "max instances" which will monotonically increase. During close() it will have to check if _instances is 0 (most outer is closing) and after that print "max instances" new lines

**Comment by casperdcl** [comment]
actually wait I just realised you're not doing multi-threading. You really just have plain nested bars. This is fixed.


verbose (leave all bars):

```python
from tqdm import tqdm
print('Starting...')
for _ in tqdm(range(10), desc="Outer"):
    for _ in tqdm(range(10), desc="Inner"):
        pass
print('Done! and this prints over the Inner tqdm')
```

clear away inner bars:

```python
from tqdm import tqdm
print('Starting...')
for _ in tqdm(range(10), desc="Outer"):
    for _ in tqdm(range(10), desc="Inner", leave=False):
        pass
print('Done! and this prints over the Inner tqdm')
```

You're using 4.19.5. Try upgrading `tqdm`.
