### ISSUE TITLE
[question] Is there an option to limit nested progress bar to print on the original n rows

### ISSUE THREAD

**Issue by jimmy-academia** [tqdm/tqdm#959]
with the following script, the finished progress bars will continue to accumulate on top, using up multiple lines of space in the terminal.
```
from tqdm import tqdm
from time import sleep

for i in tqdm(range(4)):
    for j in tqdm(range(5)):
        for k in tqdm(range(50)):
            sleep(0.01)
```

![螢幕快照 2020-05-02 下午4 40 03](https://user-images.githubusercontent.com/37170435/80859434-9c627200-8c93-11ea-8326-c1d28cd01ada.png)

with
```
from tqdm import tqdm
from time import sleep

for i in tqdm(range(4)):
    for j in tqdm(range(5)):
        for k in tqdm(range(50)):
            sleep(0.01)

        print("\033[A\033[A")

    print("\033[A\033[A")
```
![螢幕快照 2020-05-02 下午4 42 01](https://user-images.githubusercontent.com/37170435/80859471-e2b7d100-8c93-11ea-807c-2ae3c28d52d1.png)

The progress bars can be limited to 3 rows, but it's a pretty lousy fix in my opinion.
Is there a way to limit the whole process to 3 rows on the terminal, by deleting the progress bar except for the last round?
Thanks in advance!

- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [ ] I have visited the [source website], and in particular
  read the [known issues]
- [ ] I have searched through the [issue tracker] for duplicates
- [ ] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=
  [StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

**Comment by casperdcl** [comment]
`leave=False` for the nested bars
