### ISSUE TITLE
Progress bar executed before its call

### ISSUE THREAD

**Issue by ingdanielguerrero** [tqdm/tqdm#964]
I'm having an issue here, I can't figure out what's the problem and I hope you can help me. When I run a module from my notebook which contains a code with more or less the below structure, the output is a first line with the p_bar progress in 0% and after my "print" message, and just after that starts the count... I'm not sure why is starting the progress bar before print the "print" message.

```
        print(f'There are {len(dates)} unique images.\n')

        p_bar = tqdm(total=len(dates))
        for dateI, rows in dates.iterrows():
            start = time.perf_counter()
            p_bar.update(1)
       p_bar.close()
```

**Comment by casperdcl** [comment]
looks like you're using `tqdm.tqdm` rather than `tqdm.auto.tqdm` or `tqdm.notebook.tqdm`, which means the stderr (progressbar) is grouped differently from stdout (print). Known Jupyter "feature."

```python
from __future__ import print_function
import sys
print('first message')
print('second message', file=sys.stderr)
print('third message')
```
