### ISSUE TITLE
How to use tqdm to log progress bars in cloudwatch logs?

### ISSUE THREAD

**Issue by rklarpit** [tqdm/tqdm#966]
I want to log progress of my API in cloudwatch. Is it possible to do the same?

**Comment by austinmw** [comment]
Hey, I'm also curious how to do this. I get the following ugly printout when using cloudwatch:

![image](https://user-images.githubusercontent.com/12224358/162828840-ce78618d-7a29-4bd8-941b-02a35abac851.png)

It looks like it doesn't support carriage return?

**Comment by 0x26res** [comment]
@casperdcl I saw you recently added this feature: https://github.com/tqdm/tqdm/pull/1491

For context, when running stuff in AWS, I'm trying to have each `tqdm` statement on a different line. 
Otherwise it looks like a giant blob in aws cloudwatch, and we get warnings all over the place.

Previously I had to do something like this:
```
import os

IS_AWS_BATCH: bool = "AWS_EXECUTION_ENV" in os.environ
TQDM_POSITION: Optional[int] = -1 if IS_AWS_BATCH else None

# ....

for _ in tqdm(data, position=TQDM_POSITION):
  pass

```

It works but I need to remember to import `TQDM_POSITION` and plug the position for every `tqdm` call.

I was hopping with your recent change I could use `export TQDM_POSITION=-1`. But it doesn't work.

```shell
TQDM_POSITION='-1' python -c "
import tqdm
from time import sleep

for _ in tqdm.tqdm(range(5)):
    sleep(0.1)
"
```

Gives me:
```
  File "<string>", line 5, in <module>
  File "/lib/python3.10/site-packages/tqdm/std.py", line 1091, in __init__
    self.pos = self._get_free_pos(self) if position is None else -position
TypeError: bad operand type for unary -: 'str'
Exception ignored in: <function tqdm.__del__ at 0x104fdd090>
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/tqdm/std.py", line 1147, in __del__
    self.close()
  File "/lib/python3.10/site-packages/tqdm/std.py", line 1273, in close
    pos = abs(self.pos)
AttributeError: 'tqdm' object has no attribute 'pos'

```

Do you know what I'm doing wrong? And would you be able to suggest another way to achieve this?

**Comment by casperdcl** [comment]
thanks @0x26res - that's a bug. The `position` argument is default-`None` so type inference doesn't work (i.e. `TQDM_POSITION='-1'` results in `tqdm(position='-1')` not `tqdm(position=-1)`). Will fix shortly :)

**Comment by N-Demir** [comment]
Why doesn't 
```
from time import sleep

from tqdm import tqdm

if __name__ == "__main__":
    for i in tqdm(range(9), position=-1):
        sleep(1)
```

print each update to the progress bar on a new line? According to the earlier posts it seems like it should?

**Comment by 0x26res** [comment]
> Why doesn't
> 
> ```
> from time import sleep
> 
> from tqdm import tqdm
> 
> if __name__ == "__main__":
>     for i in tqdm(range(9), position=-1):
>         sleep(1)
> ```
> 
> print each update to the progress bar on a new line? According to the earlier posts it seems like it should?

@N-Demir it depends on where you run your python program. 

For example if I use the terminal, they all go on the same line. 

But if I run in pycharm they all go on a different line. And if I run in AWS with cloudwatch, again, they all go on a different line

**Comment by miohtama** [comment]
I have released a package called [tqdm-loggable](https://github.com/tradingstrategy-ai/tqdm-loggable) that automatically converts progress bars to time-interval logged messages.
