### ISSUE TITLE
make it work with concurrent.futures

### ISSUE THREAD

**Issue by PhillipSz** [tqdm/tqdm#97]
Would be cool if it could work with concurrent.futures

So it would be possible to add it to

https://docs.python.org/3/library/concurrent.futures.html#threadpoolexecutor-example

this example and only has one progress bar for everything.

Thank you :)

**Comment by PhillipSz** [comment]
Ahh sorry, it works!

**Comment by lrq3000** [comment]
Good to know, thank's for the feedback!

**Comment by h3ku** [comment]
Can you explain a little bit more how it works with threadpoolexecutor?

I see some examples with .submit(), but I don't know how to make it work with .map()

**Comment by pyeguy** [comment]
I second h3ku's request. 

for instance if you have something like 

```python
N = 5
chunksize = len(my_iterable) // N

with ProcessPoolExecutor(max_workers=N) as e:
  emap = e.map(functools.partial(myfunc,foo=foo,bar=bar), tqdm(my_iterable),chunksize=chunksize )
  output = list(emap) 
```
the prog bar will just fill up to 100% instantly...

any suggestion would be awesome!

**Comment by casperdcl** [comment]
@PhillipSz ?

**Comment by casperdcl** [comment]
It's likely that in your example @pyeguy you'd need to implement a callback argument, eg:

```python
t = tqdm(total=chunksize)
partial(myfunc, ..., callback=t.update)
```

**Comment by casperdcl** [comment]
Please also give us feedback on #329!

**Comment by pyeguy** [comment]
hmmm running into some pickling issues there... 
(note on windows, myfunc is defined globally, the e.map call is under `if __name__ =="main":`) 

```python
  0%|                                                                  | 0/3466 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Anaconda3\lib\multiprocessing\queues.py", line 241, in _feed
    obj = ForkingPickler.dumps(obj)
  File "C:\Anaconda3\lib\multiprocessing\reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'tqdm.status_printer.<locals>.print_status'
```

**Comment by PhillipSz** [comment]
Sorry, for not answering. Sadly I don't know know it worked, as I dropped all of tqdm from my code, because I later realized that with concurrent.futures it's so fast I do not need any progress bar. Thanks a lot.

**Comment by kcarnold** [comment]
Unfortunately, `ProcessPoolExecutor.map` consumes its iterator before starting. (`ThreadPoolExecutor` might not.) I'd call that a bug. A workaround is to put tqdm on the output:

`list(tqdm.tqdm(pool.map(fn, data, chunksize=1024), total=len(data)))`

If each chunk takes a while, the iteration rate estimate is very inaccurate though.
