### ISSUE TITLE
rclone-like progress bar

### ISSUE THREAD

**Issue by ODtian** [tqdm/tqdm#972]
I'm interested in building a progress bar that like which in rclone, I 've noticed that we can use `nrows` to scroll display the progress bar in many rows, but how do we display the  summary info at top? How to  leave a fixed space and display   
what we want?

**Comment by casperdcl** [comment]
Not sure what the question is. It seems that there exists a program with some output format you would like to imitate, but you have not provided an example. Also it seems this is more appropriate for [StackOverflow#tqdm]

[StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

Please re-open if this is not the case.
