### ISSUE TITLE
Iterate over a _io.TextIOWrapper does not displayed the progress bar

### ISSUE THREAD

**Issue by aress31** [tqdm/tqdm#974]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
```python
>>> import tqdm, sys
>>> print(tqdm.__version__, sys.version, sys.platform)
4.46.0 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] win32
  ```
I am trying to make `tqdm` iterate over an `_io.TextIOWrapper` but oddly enough the output progress bar does not get displayed properly, see the following code snippet and screenshot:
```python
   for entry in tqdm(wordlist, disable=tqdm_disable, total=len):
                word = entry.rstrip()
                result = run(token, word)
                
                if result:
                    break
```
![image](https://user-images.githubusercontent.com/11601622/82338832-3c82ff80-99e5-11ea-92e7-ffdd7ddd1b32.png)

Could anyone tell me what is wrong and how to fix that?

EDIT: I forgot to mention that when manually giving the number of lines to `tqdm` it just does not enter in the `if` condition.

```python
            num_lines = sum(1 for line in wordlist)
            logging.debug("{} contains {} candidates".format(wordlist.name, num_lines))
    
            for entry in tqdm(wordlist, disable=tqdm_disable, total=num_lines):
                word = entry.rstrip()
                result = run(token, word)
```
  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=
  [StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

**Comment by casperdcl** [comment]
If the current number of iterations exceeds `total=num_lines` then the bar disappears. Also if `num_lines` is undefined the bar never shows.

Looks more like a question for [StackOverflow#tqdm](https://stackoverflow.com/questions/tagged/tqdm)

**Comment by aress31** [comment]
@casperdcl that is worth adding to the official documentation. Also, I think that providing a working example on how to iterate over each lines of a text file (which is already an iterable) should be a must. 🤨

**Comment by casperdcl** [comment]
I'm sorry, there are multiple things wrong with the code snippets you posted to do with usage of python (exhausting generators etc). I don't have time to go into detail and really think you'd get more help from [StackOverflow#tqdm](https://stackoverflow.com/questions/tagged/tqdm).

Once you solve your problem please feel free to post feedback here about how the documentation can be improved.

**Comment by aress31** [comment]
Well I can tell you how the doc could be improved, by adding examples of the most used case, this would for example include iterating over the lines of a file. Also I appreciate that you are busy, but stackoverflow is not what it used to be and a quick code snippet could have helped me a lot.
