### ISSUE TITLE
thread_map should be min(32, cpu count), not max

### ISSUE THREAD

**Issue by maxwellmckinnon** [tqdm/tqdm#977]
tqdm.contrib.concurrent.thread_map:

[default: max(32, cpu_count() + 4)].

This should be min, not max

- [X] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] visual output bug
    + [X] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request

**Comment by casperdcl** [comment]
Indees from https://docs.python.org/3/library/concurrent.futures.html#threadpoolexecutor
