### ISSUE TITLE
AttributeError: 'TqdmCallback' object has no attribute '_implements_train_batch_hooks'

### ISSUE THREAD

**Issue by jtlz2** [tqdm/tqdm#979]
- [X] I have marked all applicable categories:
    + [X] exception-raising bug
    + [ ] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [X] I have visited the [source website], and in particular
  read the [known issues]
- [X] I have searched through the [issue tracker] for duplicates
- [X] I have mentioned version numbers, operating system and
  environment, where applicable:
  
4.42.0 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] linux

As per the traceback below, the Keras TqdmCallback no longer, as of a few days ago, works for me. The recipe I had been successfully following was at

https://stackoverflow.com/a/59432060/1021819

```
    507     histNN5=NN5_model.fit(X5_train, y5_train, epochs=nepochs, batch_size=batch_size, \
    508                         validation_data=(X5_test,y5_test), callbacks=callbacks_list, \
--> 509                         verbose=0)

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
     64   def _method_wrapper(self, *args, **kwargs):
     65     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
---> 66       return method(self, *args, **kwargs)
     67 
     68     # Running inside `run_distribute_coordinator` already.

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
    824             verbose=verbose,
    825             epochs=epochs,
--> 826             steps=data_handler.inferred_steps)
    827 
    828       self.stop_training = False

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py in __init__(self, callbacks, add_history, add_progbar, model, **params)
    229     # pylint: disable=protected-access
    230     self._should_call_train_batch_hooks = any(
--> 231         cb._implements_train_batch_hooks() for cb in self.callbacks)
    232     self._should_call_test_batch_hooks = any(
    233         cb._implements_test_batch_hooks() for cb in self.callbacks)

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py in <genexpr>(.0)
    229     # pylint: disable=protected-access
    230     self._should_call_train_batch_hooks = any(
--> 231         cb._implements_train_batch_hooks() for cb in self.callbacks)
    232     self._should_call_test_batch_hooks = any(
    233         cb._implements_test_batch_hooks() for cb in self.callbacks)

AttributeError: 'TqdmCallback' object has no attribute '_implements_train_batch_hooks'
```

**Comment by casperdcl** [comment]
What version of tensorflow and/or keras are you on?

**Comment by jtlz2** [comment]
tensorflow = 2.2.0
keras = 2.3.1

Thanks!

**Comment by eliadl** [comment]
@jtlz2 The following workaround works for me:
```python
class TqdmCallbackFix(TqdmCallback):
    def _implements_train_batch_hooks(self): return True
    def _implements_test_batch_hooks(self): return True
    def _implements_predict_batch_hooks(self): return True
```

**Comment by casperdcl** [comment]
interesting oddity - not in `keras` codebase but rather in `tensorflow==2.2.0`:

https://github.com/tensorflow/tensorflow/blob/1a71abed7102a780d5e10d8de06650fd96f355e8/tensorflow/python/keras/callbacks.py#L232-L238

They should really find a better way to do this "optimisation" such as using `hasattr`

**Comment by jtlz2** [comment]
Thank you so much @casperdcl @eliadl on all counts!

**Comment by HUANGYUEXIN** [comment]
I have the same problem, how to fix it

**Comment by kenzotan95** [comment]
Hi, could you please enlighten us on how to resolve this issue? I'm at a loss on what you guys have done to close this case.

**Comment by casperdcl** [comment]
`pip install tqdm>=4.46.1` (or `conda install tqdm>=4.46.1`, etc...)

**Comment by kenzotan95** [comment]
Thanks @casperdcl for the quick response!

I've tried `pip install tqdm>=4.46.1` and ran the code below.

`from keras_tqdm import TQDMNotebookCallback

batch_size = 32

history = model.fit_generator(
    generator=training,
    steps_per_epoch=training.samples // batch_size,
    epochs=5,
    callbacks=[TQDMNotebookCallback(leave_inner=True, leave_outer=True)],
    validation_data=validation,
    validation_steps=validation.samples // batch_size
)`

The resulting error i've received was still;
`AttributeError: 'TQDMNotebookCallback' object has no attribute '_implements_train_batch_hooks'`

**Comment by casperdcl** [comment]
keras_tqdm, tensorflow.addons and keras itself are all out of date regarding progressbars and don't implement things fully correctly (c.f. https://github.com/tqdm/tqdm/issues/894#issuecomment-595800751)

Please use `from tqdm.keras import TqdmCallback` instead of `from keras_tqdm import TQDMNotebookCallback` (and of course use `TqdmCallback` instead of `TQDMNotebookCallback` in your code)

**Comment by kenzotan95** [comment]
Hi @casperdcl once again, i greatly appreciate the swift response and help! 

But there seems to be the error regarding the changes i've made to my code below.

```from tqdm.keras import TqdmCallback

batch_size = 32

history = model.fit_generator(
    generator=training,
    steps_per_epoch=training.samples // batch_size,
    epochs=10,
    callbacks=[TqdmCallback(verbose=2)],
    validation_data=validation,
    validation_steps=validation.samples // batch_size
)```

`AttributeError: 'TqdmCallback' object has no attribute '_implements_train_batch_hooks'` is still observed

**Comment by casperdcl** [comment]
`from tqdm import __version__; print(__version__)` probably older than `4.46.1`
