### ISSUE TITLE
Unexpected keyword argument 'nrows' in tqdm.tqdm.std.format_meter()

### ISSUE THREAD

**Issue by abdo-eldesokey** [tqdm/tqdm#980]
The following line unpacks the dictionary from the property [format_dict](https://github.com/tqdm/tqdm/blob/571f0ed3dd44aa3befc3cd326648fbb4d5b3e9a4/tqdm/std.py#L1430) and pass it to the function [format_meter](https://github.com/tqdm/tqdm/blob/571f0ed3dd44aa3befc3cd326648fbb4d5b3e9a4/tqdm/std.py#L311)
https://github.com/tqdm/tqdm/blob/571f0ed3dd44aa3befc3cd326648fbb4d5b3e9a4/tqdm/std.py#L1089

However, the dictionary includes `nrows` key which is not recognized by the format_meter function and it throws a TypeError:
`TypeError: format_meter() got an unexpected keyword argument 'nrows'`

**Comment by casperdcl** [comment]
fixed in `tqdm>=4.30.0`

**Comment by abdo-eldesokey** [comment]
The issue still persist in tqdm==4.46.0

**Comment by shimhyeonwoo** [comment]
using anaconda (conda-forge) tqdm == 4.44~ 4.48 same problem happens.
however using anaconda (conda-forge) tqdm==4.30 I could solve this issue.

**Comment by casperdcl** [comment]
can you post some minimal code?

**Comment by BH4615** [comment]
Based on anaconda source, line 1080 in file 
~/anaconda3/envs/(env_name)/lib/python3.7/site-packages/tqdm/std.py
I add code print() function to show you the phenomenon. 

`    
def __repr__(self):
        print(self.format_dict)
        return self.format_meter(**self.format_dict)
`
then, it prints the self.format_dict as below,  

> {'n': 0, 'total': 432, 'elapsed': 0, 'ncols': 167, 'nrows': 57, 'prefix': 'Progress', 'ascii': True, 'unit': 'ep', 'unit_scale': False, 'rate': None, 'bar_format': '\x1b[36m==>\x1b[0m\x1b[1m {desc}:\x1b[0m {percentage:3.0f}%\x1b[2m|{bar}|\x1b[0m  {n_fmt}/{total_fmt}  {elapsed}<{remaining} {rate_inv_fmt}  \x1b[32m{postfix}\x1b[0m', 'postfix': None, 'unit_divisor': 1000}

and using tqdm==4.30(conda-forge) there's no problem but, using tqdm > 4.30 (conda-forge), it shows log as below.

> File "~/anaconda3/envs/(env_name)/lib/python3.7/site-packages/tqdm/std.py", line 1081, in __repr__
>     return self.format_meter(**self.format_dict)
> TypeError: format_meter() got an unexpected keyword argument 'nrows'

I'm not sure this is enough for you. I'm using somebody else's source code and it is quite complex. 
So, I couldn't find and post the code that produces self.format_dict.

**Comment by casperdcl** [comment]
> I add code print() function to show you the phenomenon.
> 
> ` def __repr__(self): print(self.format_dict) return self.format_meter(**self.format_dict)`


In the same file, can you check `def format_dict`? It should clearly have an `**extra_kwargs` which will accept `nrows`. I would need

- a full stack trace (not just the last 2 lines `File` & `TypeError`)
- the exact version (not just > 4.30)

**Comment by BH4615** [comment]
Based on anaconda (conda-forge) tqdm==4.48.2,

the `format_dict()` function in line 1431, in ~/anaconda3/envs/(env_name)/lib/python3.7/site-packages/tqdm/std.py file 

`    def format_dict(self):
        """Public API for read-only member access."""
        if self.dynamic_ncols:
            self.ncols, self.nrows = self.dynamic_ncols(self.fp)
        ncols, nrows = self.ncols, self.nrows
        return dict(
            n=self.n, total=self.total,
            elapsed=self._time() - self.start_t
            if hasattr(self, 'start_t') else 0,
            ncols=ncols, nrows=nrows,
            prefix=self.desc, ascii=self.ascii, unit=self.unit,
            unit_scale=self.unit_scale,
            rate=1 / self.avg_time if self.avg_time else None,
            bar_format=self.bar_format, postfix=self.postfix,
            unit_divisor=self.unit_divisor)
`
and `format_meter`.
`def format_meter(n, total, elapsed, ncols=None, prefix='', ascii=False,
                     unit='it', unit_scale=False, rate=None, bar_format=None,
                     postfix=None, unit_divisor=1000, **extra_kwargs):
`

As you pointed out def format_meter has `**extra_kwars`, so I guess it can accept `nrows`.  but the  trace tells `TypeError: format_meter() got an unexpected keyword argument 'nrows'`

`Traceback (most recent call last):
  File "../main.py", line 88, in <module>
    main()
  File "../main.py", line 85, in main
    validation_augmentation=validation_augmentation)
  File "/home/ID/irr/runtime.py", line 514, in exec_runtime
    total_progress = create_progressbar(**progressbar_args)
  File "/home/ID/irr/runtime.py", line 90, in create_progressbar
    return tools.tqdm_with_logging(**tqdm_args)
  File "/home/ID/irr/tools.py", line 398, in tqdm_with_logging
    logging_on_update=logging_on_update)
  File "/home/ID/irr/tools.py", line 344, in __init__
    postfix=postfix)
  File "/home/ID/anaconda3/envs/pytorch/lib/python3.7/site-packages/tqdm/std.py", line 1041, in __init__
    self.refresh(lock_args=self.lock_args)
  File "/home/ID/anaconda3/envs/pytorch/lib/python3.7/site-packages/tqdm/std.py", line 1330, in refresh
    self.display()
  File "/home/ID/anaconda3/envs/pytorch/lib/python3.7/site-packages/tqdm/std.py", line 1462, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "/home/ID/anaconda3/envs/pytorch/lib/python3.7/site-packages/tqdm/std.py", line 1081, in __repr__
    return self.format_meter(**self.format_dict)
TypeError: format_meter() got an unexpected keyword argument 'nrows'
Exception ignored in: <function tqdm.__del__ at 0x7fe8abeba440>
Traceback (most recent call last):
  File "/home/ID/anaconda3/envs/pytorch/lib/python3.7/site-packages/tqdm/std.py", line 1077, in __del__
    self.close()
  File "/home/ID/irr/tools.py", line 374, in close
    if self._logging_on_close and not self._closed:
AttributeError: 'TqdmToLogger' object has no attribute '_logging_on_close'
`

**Comment by BH4615** [comment]
I'm not sure you can help this problem with only those informations.
I'm trying to find the reason.

**Comment by casperdcl** [comment]
> File "/home/ID/irr/tools.py", line 398, in tqdm_with_logging

This is almost certainly a custom subclass of `tqdm` overriding `format_meter` incorrectly.

See https://github.com/tqdm/tqdm/blob/master/tqdm/notebook.py#L135 for an example of how to override
