### ISSUE TITLE
Multiline in Linux shell

### ISSUE THREAD

**Issue by GarrettGaoge** [tqdm/tqdm#985]
I run my script on linux and use "screen -S" to create a virtual screen.
But the bar is moving up each line.
While there's no problem when I directly run the script without the virtual screen.
![image](https://user-images.githubusercontent.com/44859191/83667318-c4315680-a600-11ea-800b-b90964d3e395.png)

**Comment by casperdcl** [comment]
duplicate of #877 - it's an issue with `screen`; perhaps you could try using `tmux` instead?

**Comment by GarrettGaoge** [comment]
> duplicate of #877 - it's an issue with `screen`; perhaps you could try using `tmux` instead?

Thx very much! It's very helpful. I will try it.
