### ISSUE TITLE
Order of multiple progress bars got messed up after program ended

### ISSUE THREAD

**Issue by kaimingkuang** [tqdm/tqdm#987]
I wrote a program where I use one tqdm bar to monitor the progress of each iteration of a for loop:
```python
from tqdm import tqdm

for i in range(cfg.epochs):
    progress = tqdm(total=len(dl_train))
    progress.set_description_str(f"Epoch {i + 1}/{cfg.epochs}")

    # training loop
    for j, sample in enumerate(dl_train):
        progress.update(1)
        ...

    progress.set_postfix_str(f"train - loss: {train_loss:.4f}, "
        f"val - loss: {val_loss:.4f}, kappa: {val_kappa:.4f}")
```
While the program is running, the order of the tqdm bars is normal, as how they are generated. However, once the program ends, the order of these bars gets messed up like this:
```
Epoch 9/10: 100%|█████████| 266/266 [32:50<00:00,  7.41s/it, train - loss: 0.2779, val - loss: 0.3150, kappa: 0.7317]
Epoch 8/10: 100%|█████████| 266/266 [49:18<00:00, 11.12s/it, train - loss: 0.2873, val - loss: 0.3136, kappa: 0.7682]
Epoch 7/10: 100%|█████████| 266/266 [1:10:07<00:00, 15.82s/it, train - loss: 0.3117, val - loss: 0.3218, kappa: 0.7482]
Epoch 6/10: 100%|█████████| 266/266 [1:27:11<00:00, 19.67s/it, train - loss: 0.3320, val - loss: 0.3244, kappa: 0.7400]
Epoch 4/10: 100%|█████████| 266/266 [2:00:01<00:00, 27.07s/it, train - loss: 0.3585, val - loss: 0.3525, kappa: 0.6994]
Epoch 5/10: 100%|█████████| 266/266 [1:43:36<00:00, 23.37s/it, train - loss: 0.3399, val - loss: 0.3375, kappa: 0.7438]
Epoch 2/10: 100%|█████████| 266/266 [2:32:49<00:00, 34.47s/it, train - loss: 0.4649, val - loss: 0.4055, kappa: 0.6892]
Epoch 3/10: 100%|█████████| 266/266 [2:16:27<00:00, 30.78s/it, train - loss: 0.3806, val - loss: 0.3937, kappa: 0.6695]
Epoch 1/10: 100%|█████████| 266/266 [2:49:12<00:00, 38.17s/it, train - loss: 0.5978, val - loss: 0.4916, kappa: 0.6779]                                                                                                  
Epoch 10/10: 100%|█████████| 266/266 [16:24<00:00,  3.70s/it, train - loss: 0.2586, val - loss: 0.3100, kappa: 0.7595]
```
Any thoughts?

**Comment by casperdcl** [comment]
You should use `with tqdm(...) as progress:` instead (or manually call `progress.close()`)

**Comment by 0b11001111** [comment]
> You should use `with tqdm(...) as progress:` instead (or manually call `progress.close()`)

Just checked the source of `tqdm`'s context manager interface (`__enter__`, `__exit__`) and it does nothing but call into `close`.
Thus, OP's code cannot be that far off.

Apparently, I ran in a similar issue. I have multiple progress bars, updated in parallel from different async functions. The bars jump in lines and have weird artefacts at the end of the line. I tried locking using the `tqdm`'s global lock with no success :/

**Comment by VishalDhayalan** [comment]
Same problem here... Seems like the end result is in order of whichever bar completes first but this messed up the update for other bars since the line positions have now changed. I suspect it is to do with twdm not following the position argument for the terminal iteration of the bar.
