### ISSUE TITLE
Use tqdm with rm -fr folder/

### ISSUE THREAD

**Issue by orena1** [tqdm/tqdm#991]
Is it possible to add support for using tqdm with `rm`?
Sometimes a folder can have a huge amount of files and doing `rm -fr folder/` might take a few minutes, it would be great if one could use tqdm to show the progress of `rm -fr folder/`

See discussion on StackOverflow:
https://unix.stackexchange.com/questions/255190/is-it-possible-to-determine-the-progress-of-an-rm-command

- [x] I have marked all applicable categories:
    + [x] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates

**Comment by casperdcl** [comment]
based on one of the answers:

```bash
rm -rfv DIR_OR_FILE_NAME | tqdm --total $(du -a DIR_OR_FILE_NAME | wc -l) > /dev/null
```
