### ISSUE TITLE
Update pbar description without updating its progress

### ISSUE THREAD

**Issue by ingdanielguerrero** [tqdm/tqdm#992]
- [X] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [X] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [X] I have mentioned version numbers, operating system and
  environment, where applicable:

The following code is running in a Jupyter Notebook but I am not sure why the pbar description is not being updated when I change its description in the while loop, I tried to set "pbar.update(0)" just after setting the description but the bar remains with the last description. I would like to know if there is a way to update the pbar description without update its progress.

The following code is removing the numbers from the list in two rounds, first, removes the even numbers, and then add +1 to each number to remove them in the second round.

  ```python
  from tqdm.auto import tqdm
  from time import sleep
  
  def remove_even(number):
      number += 1
      if number%2 == 0:
          pbar.desc = f'Removing even {number}'
          pbar.update(1)
          sleep(1)
          return False
      else:
          return True
      
  list_of_numbers = [1,2,3,4,5,6,7,8,9,10]
  
  pbar = tqdm(total = len(list_of_numbers), desc="Starting...", bar_format="{l_bar}{bar}{r_bar}")
  round_ = 0
  while list_of_numbers:
      pbar.desc = f'This is the round {round_}...'
      sleep(5)    
      list_of_numbers = list(filter(remove_even, list_of_numbers))
      list_of_numbers = [number+1 for number in list_of_numbers]
      round_+=1
  
  pbar.close()
  ```

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=
  [StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

**Comment by casperdcl** [comment]
`pbar.set_description(...)` and `pbar.set_description_str(...)`
