### ISSUE TITLE
tqdm_gui not updating in Jupyter notebook

### ISSUE THREAD

**Issue by jonnyhtw** [tqdm/tqdm#997]
Hi there

I am using `tqdm` in a Jupyter notebook and it all works perfectly with the exception of the `tqdm_gui`.

The screenshot shows the behaviour, i.e. it displays the GUI but doesn't update with each iteration, even at the end of the loop.

I note that this is a feature in development but thought that it would be best to raise it here just in case?

Thanks!

![image](https://user-images.githubusercontent.com/12940715/85969651-697ef500-ba1c-11ea-924f-efa958e2792c.png)

- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:

  ```
  In [1]: import tqdm, sys
  ...: print(tqdm.__version__, sys.version, sys.platform)
  4.46.1 3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:43:00)
  [GCC 7.5.0] linux
 
  python --version
  Python 3.8.3

  > jupyter --version
  jupyter core     : 4.6.3
  jupyter-notebook : 6.0.3
  qtconsole        : 4.7.4
  ipython          : 7.15.0
  ipykernel        : 5.3.0
  jupyter client   : 6.1.3
  jupyter lab      : 2.1.5
  nbconvert        : 5.6.1
  ipywidgets       : 7.5.1
  nbformat         : 5.0.6
  traitlets        : 4.3.3


  ```
  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=
  [StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

**Comment by mmagnuski** [comment]
I think you should be in matplotlib's interactive mode for it to work:
```
%matplotlib
```

**Comment by jonnyhtw** [comment]
> I think you should be in matplotlib's interactive mode for it to work:
> 
> ```
> %matplotlib
> ```

Hey there. Thanks for the suggestion. Sadly doing that causes my Jupyter notebook kernel to die!

I seem to remember that this was a beta feature anyway (in notebooks).

Thsi does work however and is fine for now...

```
for i in tqdm_notebook(range(3)):
    print(foo)
```

All the best

Jonny

**Comment by mmagnuski** [comment]
Yes, I started using `tqdm_gui` lately and in my experience in real use cases it often updates only at the end. However the simple example you posted works for me in the interactive mode. Make sure you start the interactive mode (`%matplotlib`) in a separate cell. I remember there was a notebook/matplotlib bug when running that command in the same cell where plotting takes place that caused notebook to hang (with new versions of notebook it should be fine, but its better to be on the safe side).

**Comment by jonnyhtw** [comment]
> Yes, I started using `tqdm_gui` lately and in my experience in real use cases it often updates only at the end. However the simple example you posted works for me in the interactive mode. Make sure you start the interactive mode (`%matplotlib`) in a separate cell. I remember there was a notebook/matplotlib bug when running that command in the same cell where plotting takes place that caused notebook to hang (with new versions of notebook it should be fine, but its better to be on the safe side).

Thanks for your further input. I'll have a look at this as soon as I have time.

Jonny

**Comment by jonnyhtw** [comment]
Closing since it hasn't been affecting me in my use of the software. May reopen in the future. Cheers for your input @mmagnuski!
